### ISSUE TITLE
values-sr-el: Error: Invalid resource directory name

### ISSUE THREAD

**Issue by divadsn** [commons-app/apps-android-commons#1059]
The recent localisation update (29e667e8fe004ddb963e927fef78d9740735b137) from @translatewiki has broken Travis-CI builds for new PRs.

Local builds are also not working when applying the commit to the master branch on my fork.

```
Caused by: com.android.build.gradle.tasks.ResourceException: /home/travis/build/commons-app/apps-android-commons/app/src/main/res/values-sr-el: Error: Invalid resource directory name
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:269)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more
Caused by: /home/travis/build/commons-app/apps-android-commons/app/src/main/res/values-sr-el: Error: Invalid resource directory name
	at com.android.ide.common.res2.MergingException.throwIfNonEmpty(MergingException.java:152)
	at com.android.ide.common.res2.DataSet.loadFromFiles(DataSet.java:259)
	at com.android.ide.common.res2.ResourceSet.loadFromFiles(ResourceSet.java:52)
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:240)
	... 39 more
```

**Comment by nicolas-raoul** [comment]
Thanks for noticing!
I guess we should try this: https://stackoverflow.com/a/31329977
This probably involves modifying the Translatewiki configuration, something like https://phabricator.wikimedia.org/diffusion/GTWN/browse/master/groups/Wikimedia/CommonsAndroid.yaml;7a0afccf2836795f7ad2c24787a00935a2a51058$18

**Comment by divadsn** [comment]
This should definitely work, was looking on how Crowdin imports translations for sr-el, will test later!

**Comment by nicolas-raoul** [comment]
Submitted for review: https://gerrit.wikimedia.org/r/#/c/403889/1

**Comment by misaochan** [comment]
Thanks for reporting this @divadsn ! @nicolas-raoul Is there a way to push these changes to our project easily, or should we just wait for the next round of translatewiki commits before doing a release?

**Comment by nicolas-raoul** [comment]
Yes Translatewiki has a UI to download a particular localization file, so the file could be manually downloaded and copied to our source code.

**Comment by misaochan** [comment]
It seems like Travis is still failing despite the translatewiki commits having come in 20+ hours ago. The error is the same.

@nicolas-raoul @Nikerabbit Any idea why? Is it okay to just carry on with the release regardless?

**Comment by nicolas-raoul** [comment]
I checked the logs of a few of the latest Travis builds, and I don't see anything about `sr-el`. Could you please link to the latest build log that talks about `sr-el`? Thanks!

**Comment by misaochan** [comment]
Oh, sorry, I was looking at the build logs for the wrong branch! Looks like this issue has been fixed. :)

The master build is still failing though, just with a different error. I will create a new issue for it.

**Comment by misaochan** [comment]
Oh, seems @whym beat me to it - see #1068
