### ISSUE TITLE
App crashes after cloning to Android Studio from GitHub

### ISSUE THREAD

**Issue by mithlesh4257** [commons-app/apps-android-commons#1076]
App crashes after cloning to Android Studio from GitHub.

![image](https://user-images.githubusercontent.com/22450186/35048295-943e5dd2-fbc2-11e7-9027-98ee3e76f5f2.png)

**Comment by maskaravivek** [comment]
@mithlesh4257 Can you please share the stack trace.

**Comment by mithlesh4257** [comment]
Sure @maskaravivek

01-17 22:01:49.584 4205-4205/? I/art: Not late-enabling -Xcheck:jni (already on)
01-17 22:01:49.584 4205-4205/? W/art: Unexpected CPU variant for X86 using defaults: x86
01-17 22:01:50.094 4205-4205/fr.free.nrw.commons.debug I/InstantRun: starting instant run server: is main process
01-17 22:01:50.107 4205-4205/fr.free.nrw.commons.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
01-17 22:01:50.218 4205-4227/fr.free.nrw.commons.debug I/stetho: Listening on @stetho_fr.free.nrw.commons.debug_devtools_remote
01-17 22:01:50.243 4205-4205/fr.free.nrw.commons.debug W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-17 22:01:50.455 4205-4228/fr.free.nrw.commons.debug I/OpenGLRenderer: Initialized EGL, version 1.4
01-17 22:01:50.456 4205-4228/fr.free.nrw.commons.debug D/OpenGLRenderer: Swap behavior 1
01-17 22:01:50.456 4205-4228/fr.free.nrw.commons.debug W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
01-17 22:01:50.456 4205-4228/fr.free.nrw.commons.debug D/OpenGLRenderer: Swap behavior 0
01-17 22:01:50.475 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglCreateContext: 0xa4383000: maj 2 min 0 rcv 2
01-17 22:01:50.551 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:01:50.578 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:01:58.684 4205-4205/fr.free.nrw.commons.debug W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-17 22:02:06.750 4205-4205/fr.free.nrw.commons.debug D/LoginActivity: Login to start!
01-17 22:02:06.875 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:06.935 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:06.969 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.037 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.136 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.152 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.158 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.169 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.186 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.203 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.220 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.226 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.236 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.241 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.253 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.258 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.269 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.273 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.286 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.291 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.303 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.309 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.320 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.325 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.336 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.341 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.344 4205-4239/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                         Process: fr.free.nrw.commons.debug, PID: 4205
                                                                         java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                             at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:761)
                                                                          Caused by: java.io.IOError: org.xml.sax.SAXParseException: expected: /meta read: head (position:END_TAG </head>@98:158 in java.io.InputStreamReader@8418a9b) 
                                                                             at org.mediawiki.api.ApiResult.fromRequestBuilder(ApiResult.java:58)
                                                                             at org.mediawiki.api.MWApi.makeRequest(MWApi.java:186)
                                                                             at org.mediawiki.api.MWApi.access$000(MWApi.java:30)
                                                                             at org.mediawiki.api.MWApi$RequestBuilder.post(MWApi.java:50)
                                                                             at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.getLoginToken(ApacheHttpClientMediaWikiApi.java:110)
                                                                             at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.login(ApacheHttpClientMediaWikiApi.java:82)
                                                                             at fr.free.nrw.commons.auth.LoginTask.doInBackground(LoginTask.java:55)
                                                                             at fr.free.nrw.commons.auth.LoginTask.doInBackground(LoginTask.java:20)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                             at java.lang.Thread.run(Thread.java:761) 
                                                                          Caused by: org.xml.sax.SAXParseException: expected: /meta read: head (position:END_TAG </head>@98:158 in java.io.InputStreamReader@8418a9b) 
                                                                             at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
                                                                             at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
                                                                             at org.mediawiki.api.ApiResult.fromRequestBuilder(ApiResult.java:44)
                                                                             at org.mediawiki.api.MWApi.makeRequest(MWApi.java:186) 
                                                                             at org.mediawiki.api.MWApi.access$000(MWApi.java:30) 
                                                                             at org.mediawiki.api.MWApi$RequestBuilder.post(MWApi.java:50) 
                                                                             at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.getLoginToken(ApacheHttpClientMediaWikiApi.java:110) 
                                                                             at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.login(ApacheHttpClientMediaWikiApi.java:82) 
                                                                             at fr.free.nrw.commons.auth.LoginTask.doInBackground(LoginTask.java:55) 
                                                                             at fr.free.nrw.commons.auth.LoginTask.doInBackground(LoginTask.java:20) 
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                             at java.lang.Thread.run(Thread.java:761) 
01-17 22:02:07.371 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.376 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.386 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.396 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
                                                                        
                                                                        [ 01-17 22:02:07.404  1683: 1978 D/         ]
                                                                        HostConnection::get() New Host Connection established 0x97a69500, tid 1978
01-17 22:02:07.416 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.455 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.497 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.540 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.604 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.612 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.655 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.694 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.705 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.788 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.833 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.854 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.889 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)
01-17 22:02:07.937 4205-4228/fr.free.nrw.commons.debug D/EGL_emulation: eglMakeCurrent: 0xa4383000: ver 2 0 (tinfo 0xa43f2260)

**Comment by mithlesh4257** [comment]
@nicolas-raoul, @maskaravivek Please help.

**Comment by maskaravivek** [comment]
@mithlesh4257 Is it still happening?

**Comment by mithlesh4257** [comment]
I used another emulaor, but now new problem is with Login Credential. The same id is registered with Commons app is not working for Commons beta app.

@maskaravivek

**Comment by mithlesh4257** [comment]
Thanks @maskaravivek Issue solved.
