### ISSUE TITLE
Login Crash: Cannot log in anymore "attr value delimiter missing"

### ISSUE THREAD

**Issue by hismaeel** [commons-app/apps-android-commons#1173]
Everything was working fine. Today I deleted the beta app, then started debugging from Android studio. I can no longer login; app crashes on "logging in" waiting screen. Same behavior with 2.6.7-release branch. Not sure how to proceed. 

```
FATAL EXCEPTION: main
                  Process: fr.free.nrw.commons.debug, PID: 32761
                  io.reactivex.exceptions.OnErrorNotImplementedException: org.xml.sax.SAXParseException: attr value delimiter missing! (position:START_TAG <html lang='null'>@2:12 in java.io.InputStreamReader@97a2566) 
                      at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                      at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                      at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                      at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.io.IOError: org.xml.sax.SAXParseException: attr value delimiter missing! (position:START_TAG <html lang='null'>@2:12 in java.io.InputStreamReader@97a2566) 
                      at org.mediawiki.api.ApiResult.fromRequestBuilder(ApiResult.java:58)
                      at org.mediawiki.api.MWApi.makeRequest(MWApi.java:186)
                      at org.mediawiki.api.MWApi.access$000(MWApi.java:30)
                      at org.mediawiki.api.MWApi$RequestBuilder.post(MWApi.java:50)
                      at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.getLoginToken(ApacheHttpClientMediaWikiApi.java:134)
                      at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.login(ApacheHttpClientMediaWikiApi.java:98)
                      at fr.free.nrw.commons.auth.LoginActivity.login(LoginActivity.java:153)
                      at fr.free.nrw.commons.auth.LoginActivity.lambda$performLogin$2$LoginActivity(LoginActivity.java:144)
                      at fr.free.nrw.commons.auth.LoginActivity$$Lambda$2.call(Unknown Source)
                      at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
                      at io.reactivex.Observable.subscribe(Observable.java:10901)
                      at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                      at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                      at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                      at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: org.xml.sax.SAXParseException: attr value delimiter missing! (position:START_TAG <html lang='null'>@2:12 in java.io.InputStreamReader@97a2566) 
                      at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
                      at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
                      at org.mediawiki.api.ApiResult.fromRequestBuilder(ApiResult.java:44)
                      at org.mediawiki.api.MWApi.makeRequest(MWApi.java:186) 
                      at org.mediawiki.api.MWApi.access$000(MWApi.java:30) 
                      at org.mediawiki.api.MWApi$RequestBuilder.post(MWApi.java:50) 
                      at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.getLoginToken(ApacheHttpClientMediaWikiApi.java:134) 
                      at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.login(ApacheHttpClientMediaWikiApi.java:98) 
                      at fr.free.nrw.commons.auth.LoginActivity.login(LoginActivity.java:153) 
                      at fr.free.nrw.commons.auth.LoginActivity.lambda$performLogin$2$LoginActivity(LoginActivity.java:144) 
                      at fr.free.nrw.commons.auth.LoginActivity$$Lambda$2.call(Unknown Source) 
                      at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42) 
                      at io.reactivex.Observable.subscribe(Observable.java:10901) 
                      at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) 
                      at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452) 
                      at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61) 
                      at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                      at java.lang.Thread.run(Thread.java:818) 
```

**Comment by neslihanturan** [comment]
Are you able to login and upload via browser @hismaeel ? Apart from this, are you unable to login with beta and product together? Can you please test both credentials as beta debug and product debug?

**Comment by misaochan** [comment]
I'm getting the same issue on the beta server. Wonder if it might be caused by #1048 (which AFAIK is the last PR that modified the relevant code)?

**Comment by maskaravivek** [comment]
Am able to login even with a fresh install. Is anyone still facing this issue?

@neslihanturan @misaochan

**Comment by misaochan** [comment]
Interesting, I can indeed log in to my beta account in the latest version of master even after fresh install. @neslihanturan can you confirm this works for you too?
