### ISSUE TITLE
Orientation Change in NearybyActivity during Map mode crashes the app.

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1181]
**Summary:** 

Where there occurs a orientation change in NearbyActivity during Map mode, it crashes the app.

**Steps to reproduce:** 

1. Go Nearby Places activity from navigation drawer.
2. Load the list of nearby places as shown below:

![nearby_places_list_map](https://user-images.githubusercontent.com/20313518/36596802-ee3dd28c-18cc-11e8-860e-236768dc4e67.jpg)

3. Change the orientation of phone.

**System logs:**
02-23 18:55:05.588 28920-28920/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: fr.free.nrw.commons.debug, PID: 28920
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.addAnnotationIcon(java.lang.String, int, int, float, byte[])' on a null object reference
                                                                               at com.mapbox.mapboxsdk.maps.IconManager.loadIcon(IconManager.java:115)
                                                                               at com.mapbox.mapboxsdk.maps.IconManager.<init>(IconManager.java:37)
                                                                               at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:174)
                                                                               at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:70)
                                                                               at com.mapbox.mapboxsdk.maps.MapView$6$1.run(MapView.java:326)
                                                                               at android.os.Handler.handleCallback(Handler.java:754)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:163)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6237)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Expected behavior:** 

Gracefully handle orientation change and should not crashes.

**Observed behavior:** 

During orientation change in NearbyActivity in Map mode, it crashes the app.

![crash 2](https://user-images.githubusercontent.com/20313518/36596757-c4a3dd7c-18cc-11e8-92dd-b9c8ef55d91c.jpg)

**I am working on the issue.**

**Comment by nicolas-raoul** [comment]
I just tried, I don't get a crash (Android 7.1.2)

**Comment by knight-shade** [comment]
I am getting a crash (Android 7.0, MIUI V9.0).

**Comment by tobias47n9e** [comment]
Confirming the crash for Android 7.0 on orientation change.

**Comment by maskaravivek** [comment]
Yes the error also happens on an Android 5.1 Samsung device. I am getting the same stack trace.

**Comment by maskaravivek** [comment]
Added a fix for the same. Should be included in our next release. Thanks for reporting @knight-shade

**Comment by misaochan** [comment]
Thanks for spotting and fixing this, guys! :)
