### ISSUE TITLE
Unable to start the app on pre-lollipop devices

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1225]
**Summary:** 
On pre-lollipop devices (tested with physical device and emulator) the app never starts. Crashes immediately.

**Steps to reproduce:** 
Just start the app on a pre-lollipop device

**Add System logs:**
```
02-28 12:29:37.486 2502-2502/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: fr.free.nrw.commons.debug, PID: 2502
                                                 java.lang.RuntimeException: Unable to get provider fr.free.nrw.commons.modifications.ModificationsContentProvider: java.lang.ClassNotFoundException: Didn't find class "fr.free.nrw.commons.modifications.ModificationsContentProvider" on path: DexPathList[[zip file "/data/app/fr.free.nrw.commons.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/fr.free.nrw.commons.debug-1, /system/lib]]
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "fr.free.nrw.commons.modifications.ModificationsContentProvider" on path: DexPathList[[zip file "/data/app/fr.free.nrw.commons.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/fr.free.nrw.commons.debug-1, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325) 
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
```

**Device and Android version:** 
4.4

**Comment by neslihanturan** [comment]
Up. This has high priority since we can't release before fixing this.

**Comment by knight-shade** [comment]
Yup, the app is crashing on pre-lollipop devices. I have made a fix, very soon will be creating PR, @neslihanturan Can you verify the fix?

**Comment by knight-shade** [comment]
Yup, the app is crashing on pre-lollipop devices, I got a fix working for pre-lollipop devices, but then the app crashes on above lollipop devices with entirely different exception.

**Comment by neslihanturan** [comment]
@knight-shade great! I will be checking your fix in 3 hours.
