### ISSUE TITLE
Nearby Activity crashes when orientation of the Phone is changed

### ISSUE THREAD

**Issue by Jatin0312** [commons-app/apps-android-commons#1266]
**Summary:** 

When trying to change orientation from portrait to landscape in Nearby Activity the app crashes.
This bug occurs in the directNearbyUplaodsNew branch.

**Steps to reproduce:** 

Just change the orientation from portrait to landscape in Near by Activity. 

**Add System logs:** 
```
FATAL EXCEPTION: main
Process: fr.free.nrw.commons.debug, PID: 19965
 java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons.debug/fr.free.nrw.commons.nearby.NearbyActivity}: java.lang.IllegalStateException: Required view 'swipe_container' with ID 2131689649 for field 'swipeLayout' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
 at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4524)
 at android.app.ActivityThread.-wrap19(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6123)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
 Caused by: java.lang.IllegalStateException: Required view 'swipe_container' with ID 2131689649 for   field 'swipeLayout' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
 at butterknife.internal.Utils.findRequiredView(Utils.java:92)
 at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:104)
 at fr.free.nrw.commons.nearby.NearbyActivity_ViewBinding.<init>(NearbyActivity_ViewBinding.java:33)
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
 at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
 at butterknife.ButterKnife.bind(ButterKnife.java:124)
 at fr.free.nrw.commons.nearby.NearbyActivity.onCreate(NearbyActivity.java:78)
 at android.app.Activity.performCreate(Activity.java:6672)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
 at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4524) 
 at android.app.ActivityThread.-wrap19(ActivityThread.java) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:154) 
 at android.app.ActivityThread.main(ActivityThread.java:6123) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 

```

**Expected behavior:** 

The app should not crash.

**Observed behavior:** 

![20180307_012309_edited](https://user-images.githubusercontent.com/17095817/37055196-19dd4430-21a7-11e8-9b38-01b42d894067.gif)

**Device and Android version:** 
Phone: Moto G4 Plus
Android version: 7.0.0
 
 **Commons app version:** 
2.6.7

Just need to add code for swipeRefreshLayout in activity_nearby.xml (land)
I already fixed it only creating PR is left.
Thanks.

**Comment by maskaravivek** [comment]
@Jatin0312 Is this also happening on master?

**Comment by Jatin0312** [comment]
I will check and confirm it.

**Comment by Jatin0312** [comment]
No this is not happening in Master.

**Comment by maskaravivek** [comment]
Closing the issue then. :)
