### ISSUE TITLE
App crash on uploading image 

### ISSUE THREAD

**Issue by 97balakrishnan** [commons-app/apps-android-commons#1344]
**Summary:** 

After i upload images, and select the categories, the app crashes after 3 seconds.
This happens on the featuredImages branch
After relaunching the app, the number of uploads is not correct.

**Steps to reproduce:** 
Upload images, set title,desc and select the category. After saving, the app crashes.

**Add System logs:**

03-21 13:17:08.418 32126-4172/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-2
                                                                          Process: fr.free.nrw.commons.debug, PID: 32126
                                                                          java.lang.SecurityException: The authority of the uri content://fr.free.nrw.commons.modifications.contentprovider/modifications/1 does not match the one of the contentProvider: fr.free.nrw.commons.contributions.contentprovider
                                                                              at android.content.ContentProvider.validateIncomingUri(ContentProvider.java:1805)
                                                                              at android.content.ContentProvider.access$000(ContentProvider.java:91)
                                                                              at android.content.ContentProvider$Transport.delete(ContentProvider.java:305)
                                                                              at android.content.ContentProviderClient.delete(ContentProviderClient.java:235)
                                                                              at fr.free.nrw.commons.modifications.ModifierSequenceDao.delete(ModifierSequenceDao.java:50)
                                                                              at fr.free.nrw.commons.modifications.ModificationsSyncAdapter.onPerformSync(ModificationsSyncAdapter.java:125)
                                                                              at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

**Device and Android version:** 

Android 5.1

 **Commons app version:** 

2.6.5-debug-featuredImages

**Screen-shots:** 

https://drive.google.com/file/d/0B24cyklS0PONLWRPSGxOTWUzQ3piaTItcWtlbkNISTdhb3I4/view?usp=sharing

**Would you like to work on the issue?**
yes

**Comment by neslihanturan** [comment]
Does this happens on master @97balakrishnan ? Since featured images branch is not stable yet, we can say some crashes are normal.

**Comment by 97balakrishnan** [comment]
Ok

**Comment by neslihanturan** [comment]
Does this happens on master then?

**Comment by 97balakrishnan** [comment]
No I didn't encounter this crash in master.
