### ISSUE TITLE
Nearby Places never loads on API level 19

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1435]
**Summary:** 

Nearby progress bar turns to the eternity. I didn't understand why it gives illegal argument exception and I am not sure how we should handle it etiher.

**Steps to reproduce:** 
- Use an API 19 device
- Start Nearby Activity

**Add System logs:**

`E/LocationServiceManager: Illegal argument exception
                                                                                 java.lang.IllegalArgumentException: provider doesn't exist: network
                                                                                     at android.os.Parcel.readException(Parcel.java:1469)
                                                                                     at android.os.Parcel.readException(Parcel.java:1419)
                                                                                     at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:540)
                                                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:860)
                                                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:454)
                                                                                     at fr.free.nrw.commons.location.LocationServiceManager.requestLocationUpdatesFromProvider(LocationServiceManager.java:106)
                                                                                     at fr.free.nrw.commons.location.LocationServiceManager.registerLocationManager(LocationServiceManager.java:94)
                                                                                     at fr.free.nrw.commons.nearby.NearbyActivity.refreshView(NearbyActivity.java:342)
                                                                                     at fr.free.nrw.commons.nearby.NearbyActivity.access$000(NearbyActivity.java:52)
                                                                                     at fr.free.nrw.commons.nearby.NearbyActivity$2.onReceive(NearbyActivity.java:315)
                                                                                     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
                                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                     at dalvik.system.NativeStart.main(Native Method)
`

**Expected behavior:** 
To see nearby places

**Observed behavior:** 

What did you see instead?  Describe your issue in detail here.

**Device and Android version:** 

API 19
 
 **Commons app version:** 

2.7.x-release branch

**Would you like to work on the issue?**

Help to verify to issue would be nice, but I can work to fix. Related work at #1421 
- (is this only happens on my emulator or is there someone else experience same issue?)

**Comment by domdomegg** [comment]
**Summary:** 

Nearby fails as it just keeps switching screens between "GPS is disabled in your device. Would you like to enable it?" and "Nearby places cannot be displayed without location permissions".

**Steps to reproduce:** 

How can we reproduce the issue?
1. Build and run master (I used `2.8.5-debug-master~3ccd690c`) on an API 15 level device (I used `Galaxy Nexus (simulator)`)
2. Go to the nearby tab

What did you expect the app to do, and what did you see instead?
1. Suggest to enable GPS only if disabled
2. Not ask for location permissions on API levels that don't support permissions
3. Show nearby screen very similar to API level 28

**System logs:**

```
11-02 11:26:16.953 1269-1279/system_process I/ActivityManager: START {flg=0x20000 cmp=fr.free.nrw.commons.beta/fr.free.nrw.commons.nearby.NearbyActivity} from pid 9014
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:16.953 1269-1279/system_process W/WindowManager: Failure taking screenshot for (240x394) to layer 21015
11-02 11:26:17.013 9014-9014/fr.free.nrw.commons.beta I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
11-02 11:26:17.093 9014-9016/fr.free.nrw.commons.beta D/dalvikvm: GC_CONCURRENT freed 1186K, 10% free 16775K/18439K, paused 0ms+0ms
11-02 11:26:17.123 9014-9014/fr.free.nrw.commons.beta E/LocationServiceManager: Illegal argument exception
    java.lang.IllegalArgumentException: provider=network
        at android.os.Parcel.readException(Parcel.java:1331)
        at android.os.Parcel.readException(Parcel.java:1281)
        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:646)
        at android.location.LocationManager._requestLocationUpdates(LocationManager.java:589)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:453)
        at fr.free.nrw.commons.location.LocationServiceManager.requestLocationUpdatesFromProvider(LocationServiceManager.java:143)
        at fr.free.nrw.commons.location.LocationServiceManager.registerLocationManager(LocationServiceManager.java:130)
        at fr.free.nrw.commons.nearby.NearbyActivity.registerLocationUpdates(NearbyActivity.java:487)
        at fr.free.nrw.commons.nearby.NearbyActivity.onStart(NearbyActivity.java:329)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1133)
        at android.app.Activity.performStart(Activity.java:4476)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1929)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
        at android.app.ActivityThread.access$600(ActivityThread.java:123)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4424)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
11-02 11:26:17.123 9014-9014/fr.free.nrw.commons.beta D/NearbyActivity: GPS is not enabled
11-02 11:26:17.143 1269-1280/system_process D/dalvikvm: GC_EXPLICIT freed 366K, 37% free 16129K/25223K, paused 0ms+1ms
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.223 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta W/ResourceType: Skipping entry 0x109003a in package table 0 because it is not complex!
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta E/LocationServiceManager: Illegal argument exception
    java.lang.IllegalArgumentException: provider=network
        at android.os.Parcel.readException(Parcel.java:1331)
        at android.os.Parcel.readException(Parcel.java:1281)
        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:646)
        at android.location.LocationManager._requestLocationUpdates(LocationManager.java:589)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:453)
        at fr.free.nrw.commons.location.LocationServiceManager.requestLocationUpdatesFromProvider(LocationServiceManager.java:143)
        at fr.free.nrw.commons.location.LocationServiceManager.registerLocationManager(LocationServiceManager.java:130)
        at fr.free.nrw.commons.nearby.NearbyActivity.registerLocationUpdates(NearbyActivity.java:487)
        at fr.free.nrw.commons.nearby.NearbyActivity.refreshView(NearbyActivity.java:406)
        at fr.free.nrw.commons.nearby.NearbyActivity.access$000(NearbyActivity.java:59)
        at fr.free.nrw.commons.nearby.NearbyActivity$3.onReceive(NearbyActivity.java:380)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:728)
        at android.os.Handler.handleCallback(Handler.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4424)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
11-02 11:26:17.233 9014-9014/fr.free.nrw.commons.beta D/NearbyActivity: Skipping update of nearby places as location is unavailable
11-02 11:26:17.263 1269-1336/system_process I/ActivityManager: Displayed fr.free.nrw.commons.beta/fr.free.nrw.commons.nearby.NearbyActivity: +302ms
11-02 11:26:31.153 1689-1728/com.google.android.gms.persistent W/SQLiteDatabase: database lock has not been available for 30 sec. Current Owner of the lock is 361. Continuing to wait in thread: 71
```

**Device and Android version:** 

`2.8.3-debug-pr-1925~fe558b62` on Galaxy Nexus (simulated) with API level

**Screen-shots:** 

![screenshot_1541157093](https://user-images.githubusercontent.com/4953590/47913001-5952f300-de92-11e8-9633-40d1c0fbcc5e.png)
![screenshot_1541157821](https://user-images.githubusercontent.com/4953590/47913002-5952f300-de92-11e8-8c95-9caaf38991e1.png)
![screenshot_1541157868](https://user-images.githubusercontent.com/4953590/47913004-5952f300-de92-11e8-9252-dee350cd3d56.png)

**Comment by neslihanturan** [comment]
For me, it loads on API 19 device
