### ISSUE TITLE
Add new licenses

### ISSUE THREAD

**Issue by florian-184-de** [commons-app/apps-android-commons#144]
- CC-BY-SA 4.0 
- CC-BY 4.0

**Comment by nicolas-raoul** [comment]
good idea!
we should use the same default license as the Upload Wizard, if that has
changed.

**Comment by misaochan** [comment]
Oh, I made another thread without realizing that this one existed. :/ I will copy stuff over from there and keep this one open.

Similar suggestion by A. L. on Google Play:

> More permissions choice needed The software only allows cc-0, cc-by-3.0 and cc-by-sa-3.0 yet there's no option to choose cc 4.0. It needs to be updated to include this option

Steps to completing this task:

- [ ]  Modify SettingsActivity.java and Prefs.java to add new license options
- [ ]  Modify licenseTemplateFor() and related methods in Utils.java
- [ ]  Add link to appropriate license on title/desc page (SingleUploadFragment.java)

The current options on the Upload Wizard are:

- Creative Commons Attribution ShareAlike 4.0 (legal code)
- Creative Commons Attribution ShareAlike 3.0 (legal code)
- Creative Commons Attribution 4.0 (legal code)
- Creative Commons Attribution 3.0 (legal code)
- Creative Commons CC0 Waiver (release all rights, like public domain: legal code)

**Comment by misaochan** [comment]
Also requested by Pokefan95 on https://phabricator.wikimedia.org/T151664

**Comment by misaochan** [comment]
Got a crash when I was testing the latest build:

```
ANDROID_VERSION=7.0
APP_VERSION_NAME=1.44
BRAND=samsung
PHONE_MODEL=SM-G930F
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unrecognized license value
at fr.free.nrw.commons.Utils.licenseNameFor(Utils.java:226)
at fr.free.nrw.commons.upload.SingleUploadFragment.onCreateView(SingleUploadFragment.java:120)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6688)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by misaochan** [comment]
With more testing, I can't seem to reproduce the crash. But I think we might need to consider how we want to handle errors in that block (and other similar ones). Do we really want to throw an exception, or do we want to send the user back to the main screen with a "Sorry, license selection failed" message or such rather than just crashing the app?

**Comment by maskaravivek** [comment]
@misaochan I was getting this error while working on this feature but i didn't get it once i was done with my changes. It could be upgrade issue. Am taking a note of it and will try to reproduce it with some upgrade testing. 

It seems to be a better option to give some error feedback to the user rather than crashing the app. As suggested by you we could handle the error with a "Sorry, license selection failed" toast.

**Comment by misaochan** [comment]
Sounds good @maskaravivek , please feel free to implement if you can. :)

**Comment by theel0ja** [comment]
CC-BY-SA 3.0 seems to being default license, why it isn't CC-BY-SA 4.0?

**Comment by neslihanturan** [comment]
This issue seems like done, please reopen if you feel in oposite way
