### ISSUE TITLE
Nearby crashes after logging out and in

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1480]
**Summary:** 

Nearby crashes after logging out and in.

**Steps to reproduce:** 

Open app, open nearby, log out, log in, open nearby again

**Add System logs:**
```
E/LocationServiceManager: Security exception
                                                                                 java.lang.SecurityException: "network" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.
                                                                                     at android.os.Parcel.readException(Parcel.java:1599)
                                                                                     at android.os.Parcel.readException(Parcel.java:1552)
                                                                                     at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
                                                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
                                                                                     at android.location.LocationManager.requestLocationUpdates(LocationManager.java:464)
                                                                                     at fr.free.nrw.commons.location.LocationServiceManager.requestLocationUpdatesFromProvider(LocationServiceManager.java:123)
                                                                                     at fr.free.nrw.commons.location.LocationServiceManager.registerLocationManager(LocationServiceManager.java:111)
                                                                                     at fr.free.nrw.commons.nearby.NearbyActivity.onStart(NearbyActivity.java:299)
                                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                                     at android.app.Activity.performStart(Activity.java:6253)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Device and Android version:** 

API level 19
 
 **Commons app version:** 

current master

**Comment by neslihanturan** [comment]
Can be related with #1413

**Comment by misaochan** [comment]
I get a Nearby crash after logging out and in, too. However, mine has a different error log:

5-05 02:57:38.175 7683-7683/fr.free.nrw.commons.debug W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
        at org.jacoco.agent.rt.internal_773e439.Offline.getProbes(Offline.java:51)
        at fr.free.nrw.commons.CommonsApplication.$jacocoInit(CommonsApplication.java)
        at fr.free.nrw.commons.CommonsApplication.<init>(CommonsApplication.java)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)

**Comment by nicolas-raoul** [comment]
@albendz Vivek has submitted a pull request, would you mind testing it and saying whether the problem is fixed or not? https://github.com/commons-app/apps-android-commons/pull/1498 Thanks! :-)

**Comment by albendz** [comment]
@nicolas-raoul Can do!

**Comment by misaochan** [comment]
Reopening as #1498 solves a separate issue, but not this one.

**Comment by neslihanturan** [comment]
I was digging the root cause, it seems like same issue: https://github.com/mapbox/mapbox-gl-native/issues/10417

**Comment by neslihanturan** [comment]
And this one: https://github.com/mapbox/mapbox-gl-native/issues/11461

**Comment by misaochan** [comment]
We have been using mapbox for a long time, though. If the issue lies in the mapbox SDK, why is the issue only happening recently? I relog very often and always check Nearby, it has not occurred for me before the last release.

**Comment by neslihanturan** [comment]
Did you check logs recently? I just get exactly same stack trace and nothing else for all of my recent tests. I am not saying the error is about mapbox code, what I am saying is somehow we can't see native crash.

**Comment by neslihanturan** [comment]
Here what I get with these steps:

```
Failed to read the storage key: 
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
                                                                         at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:69)
                                                                         at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:48)
                                                                         at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:346)
                                                                         at fr.free.nrw.commons.nearby.NearbyMapFragment.onStart(NearbyMapFragment.java:831)
                                                                         at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-11 19:14:07.400 2430-2544/fr.free.nrw.commons.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa1486380
```

**Comment by neslihanturan** [comment]
All I could find about this bug is at here: https://github.com/mapbox/mapbox-gl-native/issues/11461 and I asked a question on thread. Maybe we get an answer.

**Comment by NitinKumar26** [comment]
can i work on this?

**Comment by neslihanturan** [comment]
Hi @NitinKumar26 , thanks for your interest. Since we refactor nearby activity to nearby fragment on 2.9-release branch, this change may not be required anymore.

**Comment by NitinKumar26** [comment]
Thank you for your response, Sir. Can you please guide me to open issues so
that I can work  on them as soon as possible.
Nitin Kumar

**Comment by neslihanturan** [comment]
seems like solved.
