### ISSUE TITLE
java.io.FileNotFoundException: /jacoco.exec (Read-only file system)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1483]
**Summary:** 

If I log out and log back in again, opening Nearby will reliably cause this crash for me the first time I do that.

**Add System logs:**

```
04-30 18:13:55.897 7145-7145/fr.free.nrw.commons.debug W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
        at org.jacoco.agent.rt.internal_773e439.Offline.getProbes(Offline.java:51)
        at fr.free.nrw.commons.CommonsApplication.$jacocoInit(CommonsApplication.java)
        at fr.free.nrw.commons.CommonsApplication.<init>(CommonsApplication.java)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1007)
04-30 18:13:55.898 7145-7145/fr.free.nrw.commons.debug W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Device and Android version:** 

Nexus S API 25
 
 **Commons app version:** 

2.7.1 prod debug build 

**Would you like to work on the issue?**

Preferably not

**Comment by nicolas-raoul** [comment]
I get this on the explore branch:
```
06-22 22:39:15.421   786   811 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
06-22 22:39:15.450 30936 30936 D libcrashlytics: Initializing libcrashlytics version 2.0.2
06-22 22:39:15.450 30936 30936 D libcrashlytics: Initializing native crash handling successful.
06-22 22:39:15.458   786 10761 I ActivityManager: Start proc 31032:com.android.exchange/u0a56 for service com.android.exchange/.service.EasService
06-22 22:39:15.569   786  1120 D ConnectivityService: Returning blocked NetworkInfo to uid=10143
06-22 22:39:15.585 31055 31055 I art     : Late-enabling -Xcheck:jni
06-22 22:39:15.615   786 32097 I ActivityManager: Start proc 31055:fr.free.nrw.commons.debug/u0a196 for activity fr.free.nrw.commons.debug/fr.free.nrw.commons.contributions.ContributionsActivity
06-22 22:39:15.618   786 32097 W ActivityManager: Slow operation: 87ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
06-22 22:39:15.637 30997 31042 D ActivityThread: Loading provider com.android.email.provider;com.android.email.notifier: com.android.email.provider.EmailProvider
06-22 22:39:15.686 31032 31032 I art     : Starting a blocking GC AddRemoveAppImageSpace
06-22 22:39:15.687 31032 31032 W System  : ClassLoader referenced unknown path: /system/app/Exchange2/lib/arm
06-22 22:39:15.832 31055 31055 W System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
06-22 22:39:15.836 31055 31055 W System.err:    at java.io.FileOutputStream.open(Native Method)
06-22 22:39:15.836 31055 31055 W System.err:    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
06-22 22:39:15.836 31055 31055 W System.err:    at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
06-22 22:39:15.836 31055 31055 W System.err:    at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
06-22 22:39:15.836 31055 31055 W System.err:    at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
06-22 22:39:15.836 31055 31055 W System.err:    at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
06-22 22:39:15.836 31055 31055 W System.err:    at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
06-22 22:39:15.836 31055 31055 W System.err:    at org.jacoco.agent.rt.internal_773e439.Offline.getProbes(Offline.java:51)
06-22 22:39:15.836 31055 31055 W System.err:    at fr.free.nrw.commons.CommonsApplication.$jacocoInit(CommonsApplication.java)
06-22 22:39:15.836 31055 31055 W System.err:    at fr.free.nrw.commons.CommonsApplication.<init>(CommonsApplication.java)
06-22 22:39:15.836 31055 31055 W System.err:    at java.lang.Class.newInstance(Native Method)
06-22 22:39:15.836 31055 31055 W System.err:    at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
06-22 22:39:15.836 31055 31055 W System.err:    at android.app.Instrumentation.newApplication(Instrumentation.java:993)
06-22 22:39:15.836 31055 31055 W System.err:    at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
06-22 22:39:15.836 30936 30948 W art     : Suspending all threads took: 61.008ms
06-22 22:39:15.836 31055 31055 W System.err:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5422)
06-22 22:39:15.837 31055 31055 W System.err:    at android.app.ActivityThread.-wrap2(ActivityThread.java)
06-22 22:39:15.837 31055 31055 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
06-22 22:39:15.837 31055 31055 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
06-22 22:39:15.837 31055 31055 W System.err:    at android.os.Looper.loop(Looper.java:154)
06-22 22:39:15.837 31055 31055 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6186)
06-22 22:39:15.837 31055 31055 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
06-22 22:39:15.837 31055 31055 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-22 22:39:15.837 31055 31055 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by nicolas-raoul** [comment]
I guess it only happens with debug APKs.
I believe it is OK as long as code coverage code does not get included in the production APK.

**Comment by domdomegg** [comment]
Don't think this is reproducable any more - reopen if it is.
