### ISSUE TITLE
App crashes when retry upload menu icon is clicked.

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#1492]
**Summary:** 

The app crashes when retry upload is clicked in contributions activity while viewing media details of image for which the upload has failed.

**Steps to reproduce:** 

1. Open the app
2. Go to home
3. Try to upload an image (some how make the upload fail)
4. Click on the image for which the upload fails.
5. Click on retry icon on the top

**Add System logs:**
`  --------- beginning of crash
05-04 06:40:26.508 31912-31946/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: UploadService
    Process: fr.free.nrw.commons, PID: 31912
    java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{358e635 31912:fr.free.nrw.commons/u0a95} (pid=31912, uid=10095) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.os.Parcel.readException(Parcel.java:1950)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4758)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:5836)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2526)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1780)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1394)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
        at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:188)
        at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:127)
        at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:35)
        at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:25)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

Add logcat files here (if possible).

**Expected behavior:** 

The expected behaviour was to retry image upload

**Observed behavior:** 

The app crashed.

**Device and Android version:** 

Android 8.1.0 Pixel Emulator (Android emulator built for x86)
 
 **Commons app version:** 

2.4.2

**Screen-shots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Would you like to work on the issue?**

Yes
![screenshot_1525415356](https://user-images.githubusercontent.com/17375274/39615578-9c185866-4f94-11e8-8743-91c9f069522a.png)
![screenshot_1525415371](https://user-images.githubusercontent.com/17375274/39615579-9c487dc0-4f94-11e8-9e82-567ad2425c4d.png)
![screenshot_1525415387](https://user-images.githubusercontent.com/17375274/39615580-9c71faec-4f94-11e8-93a1-d526c81798bf.png)

**Comment by neslihanturan** [comment]
This should be solved now
