### ISSUE TITLE
App crashes when opening *Nearby* in a particular scenario

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1504]
**Summary:** 
*Nearby* crashes when the phone is connected to a network that is disconnected from the ISP's network. To be more detailed, I use a Wi-Fi enabled data modem with the ability to disconnect the data service. So, when I disconnect the data service and connect the phone to the Wi-Fi network (which isn't connected to the ISP's network) and visit *Nearby*, the app crashes.

**Steps to reproduce:** 
1. Connect to a network that isn't connected to the ISP's network in some way (one way is described in the summary)
1. Open the app
1. Open *Nearby*

**Add System logs:**
*Will update with logs within this weekend when I get time to get hands.*

BTW, if there an easy way to get the logs without *Android studio* let me know. That's because I'm fed with waiting for the Gradle build to complete :imp: (it's taking much longer as it's been too long since the last successful Gradle build for the app).

**Expected behavior:** 
Warn about the inability to connect to the network.

**Observed behavior:** 
The app crashes.

**Device and Android version:** 
*Device*: Samsung Galaxy J2
*Android*: 5.1.1

 **Commons app version:** 
2.7.1

**Would you like to work on the issue?**
No.

**Comment by sivaraam** [comment]
> Is it Android Studio that isn't working for you, or manual builds? ? AFAIK you can get logs via Android Studio's logcat without building ...

Actually Android studio required the Gradle build for the modified source (not the apk generation) to be completed before the dubug console could be used to debug the hooked up to the device.

**Comment by ashishkumar468** [comment]
@sivaraam You can also get logs by using [ADB](https://stackoverflow.com/questions/31374085/installing-adb-on-mac-os-x),  It would let you have the logs instantly. Make sure you filter the logs for this application by using `./adb logcat | grep fr.free.nrw.commons`

**Comment by ashishkumar468** [comment]
I tried to reproduce the issue and made the app crash with the following logs 
`io.reactivex.exceptions.OnErrorNotImplementedException: Callable returned null
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Callable returned null
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:10901)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)`

**Comment by maskaravivek** [comment]
Looks like null isn't handled properly while loading data in nearby. @ashishkumar468 will you be able to take care of this issue?

**Comment by ashishkumar468** [comment]
@maskaravivek I have most probably made the fix, creating a pull request for the same

**Comment by sivaraam** [comment]
Thanks @ashishkumar468 for your thoughts. 

> Actually Android studio required the Gradle build for the modified source (not the apk generation) to be completed before the dubug console could be used to debug the hooked up to the device.

Sorry, that seems to be a misleading comment. I actually was overlooked and mistook the "debug build" icon for the "attach debugger" icon :disappointed:

Regardless, I wasn't able to able to attach the debugger to a production release.

**Comment by ashishkumar468** [comment]
@sivaraam This seems to be a different issue, anybody else if facing such issues ?

**Comment by sivaraam** [comment]
@ashishkumar468 Yep. It does seem to be different issue. I forgot to mention that:

> I just wanted to be sure I'm not the only one facing this.

So, am I missing something?

**Comment by ashishkumar468** [comment]
@sivaraam You are trying to login into betaDebug build variant I suppose, make sure that you signed up on the same variant or try to login with the same credentials in prodDebug or prodRelease build variant

**Comment by sivaraam** [comment]
@ashishkumar468 Thanks for the pointer! 

Regardless of that, I guess the error message could be made more helpful/useful as it mentioned only about checking my password and **not my username**.

**Comment by ashishkumar468** [comment]
@sivaraam Sure, Thanks for the suggestion, you can create a new issue for that and someone can pick that up as an enhancement, coming back to this issue, were you able to login ?

**Comment by sivaraam** [comment]
Yeah, I was able to log-in and the app seems to crash as noticed before. And the log output seems to be the same as the one you posted in [your comment](1504#issuecomment-388007087).

**Comment by ashishkumar468** [comment]
@sivaraam The changes have not yet been merged to master, you will have to take a take a pull from branch ashishkumar468:feature/bug_fix_#1504 to verify

**Comment by sivaraam** [comment]
> Regardless of that, I guess the error message could be made more helpful/useful as it mentioned only about checking my password and not my username!

Just for sake of note, the error about an incorrect password was correct as there incidentally was an account with my username in the beta website. So, it was my mistake, again!

**Comment by maskaravivek** [comment]
@sivaraam Please refrain from posting about other issues on a thread that is totally unrelated. It adds to the confusion. :)
