### ISSUE TITLE
Nearby Places Crash

### ISSUE THREAD

**Issue by gupta1anubhav** [commons-app/apps-android-commons#1560]
### Summary:
If I cancel request to enable GPS as well as cancel the request for location permission, then the app crashes first going back to home page quickly and then crashes.

### Add System logs:
```
05-28 01:05:01.697 8612-10425/fr.free.nrw.commons.debug W/System.err: io.reactivex.exceptions.UndeliverableException: java.io.InterruptedIOException: thread interrupted
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:48)
        at io.reactivex.Observable.subscribe(Observable.java:10901)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
    Caused by: java.io.InterruptedIOException: thread interrupted
        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
        at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
05-28 01:05:01.698 8612-10425/fr.free.nrw.commons.debug W/System.err:     at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
        at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
        at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:783)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
        at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:84)
        at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:48)
        at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocation(NearbyController.java:56)
        at fr.free.nrw.commons.nearby.NearbyActivity.lambda$refreshView$7$NearbyActivity(NearbyActivity.java:433)
        at fr.free.nrw.commons.nearby.NearbyActivity$$Lambda$7.call(Unknown Source)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
    	... 10 more
05-28 01:05:01.799 8612-10425/fr.free.nrw.commons.debug I/Process: Sending signal. PID: 8612 SIG: 9
```

### Device and Android version:

Redmi Note 4 (API 24)

### Commons app version:

2.7.1 prod debug build, beta debug build

### Would you like to work on the issue?

Yes, I want to work on this issue.

**Comment by neoliteconsultant** [comment]
I start working on this

**Comment by maskaravivek** [comment]
@gupta1anubhav Can you pick this up and fix it. :)

**Comment by neslihanturan** [comment]
It seems like solved.
