### ISSUE TITLE
Crash after installing previous version of app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1589]
When we add a new feature, there will always be 0.1% of people who hate the new feature so much that they switch back to the previous version of the app. I think that has happened to many of us too, and if they prefer that version well why not.

Problem: After switching to a previous version, any attempt to start the app is met with this crash:

![screenshot_20180605-172011](https://user-images.githubusercontent.com/99590/40963991-ee9ca786-68e4-11e8-8673-6cde7f529d4a.png)

Unknown to most users, the logcat below offers an explanation.
Rather than crashing, we should probably explain how to fix the problem ("please uninstall then reinstall"), or even remove the database (we don't store vital information in there right?) then start normally.

```
06-05 17:02:38.802 2360-2360/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.debug, PID: 2360
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons.debug/fr.free.nrw.commons.contributions.ContributionsActivity}: android.database.sqlite.SQLiteException: Can't downgrade database from version 7 to 6
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 7 to 6
        at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
        at fr.free.nrw.commons.contributions.ContributionsContentProvider.query(ContributionsContentProvider.java:52)
        at android.content.ContentProvider.query(ContentProvider.java:1020)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:145)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:127)
        at fr.free.nrw.commons.contributions.ContributionDao.loadAllContributions(ContributionDao.java:50)
        at fr.free.nrw.commons.contributions.ContributionsActivity.onAuthCookieAcquired(ContributionsActivity.java:116)
        at fr.free.nrw.commons.auth.AuthenticatedActivity.requestAuthToken(AuthenticatedActivity.java:26)
        at fr.free.nrw.commons.contributions.ContributionsActivity.onCreate(ContributionsActivity.java:140)
        at android.app.Activity.performCreate(Activity.java:6684)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
```

**Comment by whym** [comment]
Going forward, it seems like we can use https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#onDowngrade(android.database.sqlite.SQLiteDatabase,%20int,%20int) . Or if not, can we offer to delete the (too new) database when the old app is started?

For the versions that are already released, a section or a page in the documentation would be better than nothing. (on the wiki or store page?)

**Comment by ashishkumar468** [comment]
A DB migration unhandled exception, handled in the latest commits, seems to very very old, closing this one
