### ISSUE TITLE
Notifications Activity crashes

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1600]
**Summary:** 

Notifications activity crashes.

**Steps to reproduce:** 

Just opening activity

**Add System logs:**

```
FATAL EXCEPTION: main
                                                 Process: fr.free.nrw.commons, PID: 7654
                                                 java.util.regex.PatternSyntaxException: Unrecognized backslash escape sequence in pattern near index 4:
                                                 (^\h*)|(\h*$)
                                                     ^
                                                     at java.util.regex.Pattern.compileImpl(Native Method)
                                                     at java.util.regex.Pattern.compile(Pattern.java:411)
                                                     at java.util.regex.Pattern.<init>(Pattern.java:394)
                                                     at java.util.regex.Pattern.compile(Pattern.java:381)
                                                     at java.lang.String.replaceAll(String.java:1785)
                                                     at fr.free.nrw.commons.notification.NotificationRenderer.setTitle(NotificationRenderer.java:73)
                                                     at fr.free.nrw.commons.notification.NotificationRenderer.render(NotificationRenderer.java:62)
                                                     at com.pedrogomez.renderers.RVRendererAdapter.onBindViewHolder(RVRendererAdapter.java:121)
                                                     at com.pedrogomez.renderers.RVRendererAdapter.onBindViewHolder(RVRendererAdapter.java:41)
                                                     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
```

**Device and Android version:** 
Android 4.2.2
 
 **Commons app version:** 

master / productionRelease built variant

**Comment by neslihanturan** [comment]
Still happens on master for me.

**Comment by neslihanturan** [comment]
Also happens on 2.8-release branch too

**Comment by maskaravivek** [comment]
@neslihanturan It is not crashing for me when I open notifications. It seems you have some notification that is causing the issue. Can you put breakpoints and check which notification is the culprit. I will pick up this issue and fix it.

**Comment by neslihanturan** [comment]
Fixed.
