### ISSUE TITLE
Expected adapter item count: 25, found: 0

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1602]
```
06-08 21:26:23.172 28003 28003 E AndroidRuntime: FATAL EXCEPTION: main
06-08 21:26:23.172 28003 28003 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 28003
06-08 21:26:23.172 28003 28003 E AndroidRuntime: java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 25, found: 0 Pager id: fr.free.nrw.commons.debug:id/mediaDetailsPager Pager class: class android.support.v4.view.ViewPager Problematic adapter: class fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.support.v4.view.ViewPager.populate(ViewPager.java:1137)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1059)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:692)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.View.measure(View.java:19861)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:621)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-08 21:26:23.172 28003 28003 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-08 21:26:23.289   786  1191 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.explore.SearchActivity
```

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul How can you tell the steps to reproduce this.

**Comment by nicolas-raoul** [comment]
Easy: I just tapped everywhere like crazy ;-)
Unfortunately I don't know how to reproduce the problem. It might even be a race condition.
