### ISSUE TITLE
ConcurrentModificationException at fr.free.nrw.commons.Media.setDescriptions

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1648]
explore branch with category_search merged in.
When scrolling featured images then looking at their properties.
Reproducible, two examples of crash:
```
06-21 22:12:07.171 29126 29126 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:12:07.251 29126 29126 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:12:07.254 29126 29126 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:12:07.600 29126 29245 D MediaDataExtractor: Nominated for deletion: false
06-21 22:12:07.661 29126 29270 D MediaDataExtractor: Nominated for deletion: false
06-21 22:12:07.998 29126 29269 D MediaDataExtractor: Nominated for deletion: false
06-21 22:12:08.117 29126 29245 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:12:08.118 29126 29245 D MediaDataExtractor: MediaDataExtractor found self-license cc-by-sa-4.0
06-21 22:12:08.122 29126 29126 D MediaDetailFragment: Media license is: cc-by-sa-4.0
06-21 22:12:08.451 29126 29270 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:12:08.478 29126 29126 D MediaDetailFragment: Media license is: cc-by-sa-4.0
06-21 22:12:08.544 29126 29269 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:12:08.545 29126 29269 D MediaDataExtractor: MediaDataExtractor found non-self license cc-by-sa-4.0
06-21 22:12:08.571 29126 29126 D AndroidRuntime: Shutting down VM
06-21 22:12:08.578 29126 29126 E AndroidRuntime: FATAL EXCEPTION: main
06-21 22:12:08.578 29126 29126 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 29126
06-21 22:12:08.578 29126 29126 E AndroidRuntime: java.util.ConcurrentModificationException
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at fr.free.nrw.commons.Media.setDescriptions(Media.java:359)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.fill(MediaDataExtractor.java:303)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:268)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:241)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:667)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-21 22:12:08.578 29126 29126 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-21 22:12:08.591   790 15308 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity
```

```
06-21 22:13:59.022 29968 29968 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:13:59.101 29968 29968 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:13:59.104 29968 29968 D MediaDetailFragment: MediaDetailFragment ready to display details
06-21 22:13:59.568 29968 30013 D MediaDataExtractor: Nominated for deletion: false
06-21 22:13:59.568 29968 30044 D MediaDataExtractor: Nominated for deletion: false
06-21 22:14:00.059  1824  1824 I Watcher_AppUti: Sending:android.appwidget.action.APPWIDGET_UPDATE
06-21 22:14:00.100 29968 30043 D MediaDataExtractor: Nominated for deletion: false
06-21 22:14:00.115 29968 30013 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:14:00.116 29968 30013 D MediaDataExtractor: MediaDataExtractor found self-license cc-by-sa-4.0
06-21 22:14:00.123 29968 29968 D MediaDetailFragment: Media license is: cc-by-sa-4.0
06-21 22:14:00.425  1824  1824 W Service_Wear: isRunning
06-21 22:14:00.518 29968 30044 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:14:00.522 29968 30044 D MediaDataExtractor: MediaDataExtractor found non-self license cc-by-sa-4.0
06-21 22:14:00.527 29968 29968 D MediaDetailFragment: Media license is: cc-by-sa-4.0
06-21 22:14:00.600 29968 30043 D MediaDataExtractor: MediaDataExtractor searching for license
06-21 22:14:00.601 29968 30043 D MediaDataExtractor: MediaDataExtractor found self-license cc-by-sa-4.0
06-21 22:14:00.603 29968 29968 D AndroidRuntime: Shutting down VM
06-21 22:14:00.606 29968 29968 E AndroidRuntime: FATAL EXCEPTION: main
06-21 22:14:00.606 29968 29968 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 29968
06-21 22:14:00.606 29968 29968 E AndroidRuntime: java.util.ConcurrentModificationException
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at fr.free.nrw.commons.Media.setDescriptions(Media.java:359)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.fill(MediaDataExtractor.java:303)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:268)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:241)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:667)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-21 22:14:00.606 29968 29968 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-21 22:14:00.608   790  1817 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity
06-21 22:14:00.618   790   805 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{4f5e05c 29734:com.airbnb.android/u0a138} (pid=29734, uid=10138) requires android.permission.READ_LOGS due to sender android (uid 1000)
```

**Comment by ujjwalagrawal17** [comment]
This is also fixed now.

**Comment by nicolas-raoul** [comment]
```
07-05 22:28:44.096   640  3104 D MediaDataExtractor: MediaDataExtractor searching for license
07-05 22:28:44.097   640  3104 D MediaDataExtractor: MediaDataExtractor found non-self license cc-by-sa-4.0
07-05 22:28:44.111   640   640 D AndroidRuntime: Shutting down VM
07-05 22:28:44.116   640   640 E AndroidRuntime: FATAL EXCEPTION: main
07-05 22:28:44.116   640   640 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 640
07-05 22:28:44.116   640   640 E AndroidRuntime: java.util.ConcurrentModificationException
07-05 22:28:44.116   640   640 E AndroidRuntime:        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at fr.free.nrw.commons.Media.setDescriptions(Media.java:359)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.fill(MediaDataExtractor.java:303)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:266)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:239)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:667)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-05 22:28:44.116   640   640 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-05 22:28:44.124   789   418 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity
```

**Comment by nicolas-raoul** [comment]
Duplicate of #1665
