### ISSUE TITLE
[browse-commons-via-app] Crash on deleting categories.

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1655]
**Summary:** 

It crashes on deleting recent categories

**Steps to reproduce:** 
Played with app first, couldn't recognize steps at beginning. After some playing, search several categories first, then click to x, then click to delete icon.

**Add System logs:**

```
FATAL EXCEPTION: main
                                                                           Process: fr.free.nrw.commons.debug, PID: 30135
                                                                           java.lang.IllegalStateException: Already released
                                                                               at android.content.ContentProviderClient.release(ContentProviderClient.java:456)
                                                                               at fr.free.nrw.commons.explore.recentsearches.RecentSearchesDao.deleteAll(RecentSearchesDao.java:61)
                                                                               at fr.free.nrw.commons.explore.recentsearches.RecentSearchesFragment.lambda$null$0$RecentSearchesFragment(RecentSearchesFragment.java:45)
                                                                               at fr.free.nrw.commons.explore.recentsearches.RecentSearchesFragment$$Lambda$2.onClick(Unknown Source)
                                                                               at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ujjwalagrawal17** [comment]
I think this issue is fixed now. I couldn't reproduce this.

**Comment by neslihanturan** [comment]
Yes, solved:)
