### ISSUE TITLE
Wild rabbit crashes app (NumberFormatException: For input string: "1=42.344335")

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1660]
Steps to reproduce (explore branch):

1. Open Explore
2. Search for "rabbit"
3. Scroll a dozen images until you find the image `File:Wild rabbit, cut.jpg` (don't worry, the rabbit is entire and healthy, only the picture was cut)
4. Crash:
```
06-23 23:08:38.841  2122  2122 D MediaDetailFragment: MediaDetailFragment ready to display details                                                                                              
06-23 23:08:38.906  2122  2122 D MediaDetailFragment: MediaDetailFragment ready to display details                                                                                                                                                           06-23 23:08:38.908  2122  2122 D MediaDetailFragment: MediaDetailFragment ready to display details                                                                                                                                            
06-23 23:08:38.924   938   938 I GoogleInputMethod: onFinishInput() : Dummy InputConnection bound                                                                                                                                                            
06-23 23:08:38.924   938   938 I GoogleInputMethod: onStartInput() : Dummy InputConnection bound                                                                                                                                                             
06-23 23:08:38.924   938   938 I ShortcutsDataManager: startImportContentTask()                       
06-23 23:08:38.924   938   938 I ShortcutsDataManager: onImportAborted()                                                                                                                                              
06-23 23:08:39.548  2122 13550 D MediaDataExtractor: Nominated for deletion: false                                                                    
06-23 23:08:39.554  2122 13547 D MediaDataExtractor: Nominated for deletion: false                                                                        
06-23 23:08:39.977  2122 13551 D MediaDataExtractor: Nominated for deletion: false                                                                            
06-23 23:08:40.038  2122 13550 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #22                                                                                                   
06-23 23:08:40.038  2122 13550 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 2122                                                                                                                                                               
06-23 23:08:40.038  2122 13550 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)                         
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)                  
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)                                              
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)                                        
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)          
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)                                                     
06-23 23:08:40.038  2122 13550 E AndroidRuntime: Caused by: java.lang.NumberFormatException: For input string: "1=42.344335"                              
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.lang.Double.parseDouble(Double.java:547)                           
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.getCoordinates(MediaDataExtractor.java:254)
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.processWikiParseTree(MediaDataExtractor.java:117)                                                                                                          
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.fetch(MediaDataExtractor.java:77)       
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:252)
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:241)                                                                                                     
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)      
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)                                                     
06-23 23:08:40.038  2122 13550 E AndroidRuntime:        ... 3 more                                                                     
06-23 23:08:40.065   786  1364 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.explore.SearchActivity
```
A strange thing is that searching for "Wild rabbit cut" and touching the same image does not trigger the crash.
https://commons.wikimedia.org/wiki/File:Wild_rabbit,_cut.jpg

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul Umm, I can't reproduce this issue.

**Comment by nicolas-raoul** [comment]
Does not crash anymore, indeed.
