### ISSUE TITLE
Crash when swiping in featured pictures

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1665]
- Go to featured pictures
- touch a picture
- swipe right a few times
- crash:

```
06-27 19:42:41.050 13318 15939 D MediaDataExtractor: Nominated for deletion: false
06-27 19:42:41.332 13318 13318 D MediaDetailFragment: MediaDetailFragment ready to display details
06-27 19:42:41.478 13318 15939 D MediaDataExtractor: MediaDataExtractor searching for license
06-27 19:42:41.482 13318 13318 D AndroidRuntime: Shutting down VM
06-27 19:42:41.492 13318 13318 E AndroidRuntime: FATAL EXCEPTION: main
06-27 19:42:41.492 13318 13318 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 13318
06-27 19:42:41.492 13318 13318 E AndroidRuntime: java.util.ConcurrentModificationException
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at fr.free.nrw.commons.Media.setDescriptions(Media.java:359)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at fr.free.nrw.commons.MediaDataExtractor.fill(MediaDataExtractor.java:303)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:268)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailFragment$3.onPostExecute(MediaDetailFragment.java:241)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:667)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-27 19:42:41.492 13318 13318 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-27 19:42:41.499   790  1817 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity
```

**Comment by nicolas-raoul** [comment]
This also happens on the master branch.

**Comment by nicolas-raoul** [comment]
Also got this when scrolling down the details of a featured picture.

**Comment by nicolas-raoul** [comment]
Probably this has been happening since ever before, but the browsing feature makes it more important because it makes us look at pictures much more than before.

**Comment by VaishSiddharth** [comment]
@nicolas-raoul I am not able to see any images in Featured Images it shows No images found! Please help.

**Comment by ujjwalagrawal17** [comment]
@VaishSiddharth  can you post the screenshots of explore activity here.

**Comment by VaishSiddharth** [comment]
@ujjwalagrawal17 
![screenshot_20180714-004959](https://user-images.githubusercontent.com/36266597/42709959-e482e042-86ff-11e8-9ac4-00d76c6e319b.png)

**Comment by ujjwalagrawal17** [comment]
I think you are in wrong branch or your branch is not updated. can you pull the code from browse branch.

**Comment by VaishSiddharth** [comment]
Ok i am in wrong branch. Please can you tell how to identify that which branch to work on for a particular issue. Thanks

**Comment by ujjwalagrawal17** [comment]
Every issue has a many labels most of them have a label for branch. Like this issue has browse-commons-via-app-branch. Also you can check your local branch using git branch.
