### ISSUE TITLE
Error when scrolling down in category details

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1667]
When reaching end of results, it seems.
```
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm: Error occurred while loading featured images
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.w3c.dom.Element.getAttribute(java.lang.String)' on a null object reference
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at fr.free.nrw.commons.utils.ContinueUtils.getQueryContinue(ContinueUtils.java:12)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.getCategoryImages(ApacheHttpClientMediaWikiApi.java:618)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at fr.free.nrw.commons.category.CategoryImageController.getCategoryImages(CategoryImageController.java:27)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at fr.free.nrw.commons.category.CategoryImagesListFragment.lambda$fetchMoreImages$1$CategoryImagesListFragment(CategoryImagesListFragment.java:194)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at fr.free.nrw.commons.category.CategoryImagesListFragment$$Lambda$3.call(Unknown Source)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at io.reactivex.Observable.subscribe(Observable.java:10901)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-27 20:55:49.683  3326  3326 E CategoryImagesListFragm:       at java.lang.Thread.run(Thread.java:761)
```

**Comment by nicolas-raoul** [comment]
Presumably fixed.
