### ISSUE TITLE
App crashes when uploadin image via share without logging in

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#1669]
**Summary:** 
The app crashes when trying to upload (via Share) without logging into the app for the first time.

**Steps to reproduce:** 
1. Install the app
1. _Do not sign-in into the app_
1. Try to upload an image via Share (without logging in)
1. Give a title and description for the image and start the upload

**Add System logs:**
```
06-27 18:50:12.156 22035-22035/fr.free.nrw.commons.debug D/AndroidRuntime: Shutting down VM
06-27 18:50:12.156 22035-22035/fr.free.nrw.commons.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: fr.free.nrw.commons.debug, PID: 22035
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons.debug/fr.free.nrw.commons.upload.ShareActivity}: java.lang.ClassCastException: fr.free.nrw.commons.upload.ShareActivity cannot be cast to fr.free.nrw.commons.upload.SimilarImageDialogFragment$onResponse
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
                                                                               at android.app.ActivityThread.access$1000(ActivityThread.java:218)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:145)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6934)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                            Caused by: java.lang.ClassCastException: fr.free.nrw.commons.upload.ShareActivity cannot be cast to fr.free.nrw.commons.upload.SimilarImageDialogFragment$onResponse
                                                                               at fr.free.nrw.commons.upload.SimilarImageDialogFragment.onCreate(SimilarImageDialogFragment.java:86)
                                                                               at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
                                                                               at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                               at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                                                                               at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                                                                               at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                                                                               at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                                                                               at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
                                                                               at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
                                                                               at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
                                                                               at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
                                                                               at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                               at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1264)
                                                                               at android.app.Activity.performStart(Activity.java:6647)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3113)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260) 
                                                                               at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:145) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6934) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
06-27 18:50:14.739 22035-22035/fr.free.nrw.commons.debug I/Process: Sending signal. PID: 22035 SIG: 9
```

**Expected behavior:** 
The app should prompt the user to loign while communicating clearly that it's required to login to upload images.

**Observed behavior:** 
The app crashes.

**Device and Android version:** 
Samsung Galaxy j1 ace (Android 5.1.1) 
 
**Commons app version:** 
2.7.2 (beta flavour)

**Would you like to work on the issue?**
No.

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by nicolas-raoul** [comment]
@ShridharGoel It is yours :-)

**Comment by Mansi449** [comment]
@nicolas-raoul Since the issue is still open, is there anything left to be done in it? If yes, I would like to give it a try.
