### ISSUE TITLE
SecurityException: Permission Denial: reading com.google.android.apps.photos.contentprovider.MediaContentProvider requires the provider be exported, or grantUriPermission()

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#167]
Posted by andrea as on 9 Jul:

```
USER_COMMENT=stavo caricando 3 immagini  (Google translate: I was uploading 3 pictures)
ANDROID_VERSION=6.0.1
APP_VERSION_NAME=1.17
BRAND=google
PHONE_MODEL=Nexus 6
CUSTOM_DATA=
STACK_TRACE=java.lang.SecurityException: Permission Denial: reading com.google.android.apps.photos.contentprovider.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F19181/ORIGINAL/NONE/443149508 from pid=18891, uid=10128 requires the provider be exported, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1620)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:176)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:114)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:27)
at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:19)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by misaochan** [comment]
This is a tricky one, can't seem to use the standard runtime permission requesting with it. Asked at http://stackoverflow.com/questions/38301605/reading-com-google-android-apps-photos-contentprovider-mediacontentprovider-requ .

**Comment by ashishkumar468** [comment]
Solved in latest commits, closing this one, feel free to reopen if some one is facing this again

**Comment by HOODZCHRIS** [comment]
Rootless installer error:

 java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/5328 from pid=1208, uid=10495 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
	at android.os.Parcel.createException(Parcel.java:1966)
	at android.os.Parcel.readException(Parcel.java:1934)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1465)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1302)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1022)
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.open(ContentUriFileDescriptor.java:47)
	at com.aefyr.sai.model.apksource.ZipApkSource.nextApk(ZipApkSource.java:38)
	at com.aefyr.sai.installer.rootless.RootlessSAIPackageInstaller.installApkFiles(RootlessSAIPackageInstaller.java:88)
	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$JoIX5zHO8wAlRUBL4_c01BL_9V0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
