### ISSUE TITLE
NPE in ContinueUtils

### ISSUE THREAD

**Issue by ninad458** [commons-app/apps-android-commons#1718]
There is a NullPointerException in ContinueUtils.
continueElement.getAttribute("continue") returns null

`label:featured`

Clicked Featured from the drawer.

`07-14 23:42:26.767 4030-4030/fr.free.nrw.commons.debug E/CategoryImagesListFragm: Error occurred while loading featured images
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.w3c.dom.Element.getAttribute(java.lang.String)' on a null object reference
        at fr.free.nrw.commons.utils.ContinueUtils.getQueryContinue(ContinueUtils.java:12)
        at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.getCategoryImages(ApacheHttpClientMediaWikiApi.java:618)
        at fr.free.nrw.commons.category.CategoryImageController.getCategoryImages(CategoryImageController.java:27)
        at fr.free.nrw.commons.category.CategoryImagesListFragment.lambda$initList$0$CategoryImagesListFragment(CategoryImagesListFragment.java:110)
        at fr.free.nrw.commons.category.CategoryImagesListFragment$$Lambda$0.call(Unknown Source)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:10901)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)`

Add logcat files here (if possible).

Asus Zenphone, android version 6.0, location Nagpur, India

App cloned from github and run on the device. betaDebug

I would like to work on this issue and similar other beginner-friendly issues. Please let me know how I can proceed(NOT asking for this particular issue).

**Comment by ujjwalagrawal17** [comment]
@ninad458 this issue is already fixed in browse branch so I think it will be fixed when we merge browse branch with master. You may work on some other issue.

**Comment by ujjwalagrawal17** [comment]
You can look in the open issues and comment I start working on this before starting the work.

**Comment by nicolas-raoul** [comment]
Thanks! :-)
