### ISSUE TITLE
Parent categories loading icon keeps spinning forever, even after coming back to stable network

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1721]
I kept pressing random subcategories and random parent categories on my way from outside.
When the phone connected to my home WiFi (I guess but maybe it is irrelevant), the tab I was on did not leave the state where the waiting icon spins. It has been spinning for 10 minutes now. Below is a part of the logcat that seems to match that timing. Note the CalledFromWrongThreadException at the end.
```
07-17 14:27:50.787   790   894 D ConnectivityService: NetworkAgentInfo [VPN () - 134] EVENT_NETWORK_INFO_CHANGED, going from CONNECTING to CONNECTED
07-17 14:27:50.787   790   894 D ConnectivityService: Adding iface tun0 to network 134
07-17 14:27:50.807  9622 11861 E ApacheHttpClientMediaWi: Failed to obtain parent Categories
07-17 14:27:50.807  9622 11863 E ApacheHttpClientMediaWi: Failed to obtain searchCategories
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment: Error occurred while loading queried parentcategories
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment: java.util.concurrent.TimeoutException
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment:       at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutTimedObserver$TimeoutTask.run(ObservableTimeoutTimed.java:290)
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment:       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment:       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment:       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-17 14:27:50.811  9622 11800 E SubCategoryListFragment:       at java.lang.Thread.run(Thread.java:761)
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm: Error occurred while loading images inside a category
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm: java.util.concurrent.TimeoutException
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm:       at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutTimedObserver$TimeoutTask.run(ObservableTimeoutTimed.java:290)
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm:       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm:       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm:       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-17 14:27:50.811  9622 11803 E CategoryImagesListFragm:       at java.lang.Thread.run(Thread.java:761)
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment: Error occurred while loading queried subcategories
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment: java.util.concurrent.TimeoutException
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment:       at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutTimedObserver$TimeoutTask.run(ObservableTimeoutTimed.java:290)
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment:       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment:       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment:       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-17 14:27:50.811  9622 11798 E SubCategoryListFragment:       at java.lang.Thread.run(Thread.java:761)
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm: Error occurred while loading images inside a category
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm: java.util.concurrent.TimeoutException
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm:       at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutTimedObserver$TimeoutTask.run(ObservableTimeoutTimed.java:290)
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm:       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm:       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm:       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-17 14:27:50.811  9622 11797 E CategoryImagesListFragm:       at java.lang.Thread.run(Thread.java:761)
07-17 14:27:50.853   790   814 D LuxLevels: bright hysteresis constant= 0.1, threshold=183.79442, lux=167.08583
07-17 14:27:50.853   790   814 D LuxLevels: dark hysteresis constant= 0.2, threshold=133.66867, lux=167.08583
07-17 14:27:50.871   790   894 D ConnectivityService: Setting DNS servers for network 134 to []
07-17 14:27:50.928   790   801 I art     : Background sticky concurrent mark sweep GC freed 90488(4MB) AllocSpace objects, 75(7MB) LOS objects, 25% free, 31MB/41MB, paused 10.029ms total 107.107ms
07-17 14:27:51.039  7146  7176 D NccWifiManager: ProcWifiCheck in
07-17 14:27:51.039  7146  7176 D NccWifiManager: last connect ssid is  "aegis"
07-17 14:27:51.039  7146  7176 D NccWifiManager: ProcWifiCheck out
07-17 14:27:51.050  9622 11797 W System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6898)
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1048)
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.068  9622 11797 W System.err:    at android.support.v4.widget.DrawerLayout.requestLayout(DrawerLayout.java:1243)
07-17 14:27:51.068  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.068  9622 11797 W System.err:    at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
07-17 14:27:51.069  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.069  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.069  9622 11797 W System.err:    at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
07-17 14:27:51.069  9622 11797 W System.err:    at android.view.View.requestLayout(View.java:19785)
07-17 14:27:51.069  9622 11797 W System.err:    at android.view.View.setFlags(View.java:11482)
07-17 14:27:51.069  9622 11797 W System.err:    at android.view.View.setVisibility(View.java:8069)
07-17 14:27:51.069  9622 11797 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.initErrorView(CategoryImagesListFragment.java:152)
07-17 14:27:51.069  9622 11797 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.handleError(CategoryImagesListFragment.java:139)
07-17 14:27:51.069  9622 11797 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment.bridge$lambda$1$CategoryImagesListFragment(CategoryImagesListFragment.java)
07-17 14:27:51.069  9622 11797 W System.err:    at fr.free.nrw.commons.category.CategoryImagesListFragment$$Lambda$2.accept(Unknown Source)
07-17 14:27:51.069  9622 11797 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
07-17 14:27:51.069  9622 11797 W System.err:    at io.reactivex.observers.SerializedObserver.onError(SerializedObserver.java:155)
07-17 14:27:51.069  9622 11797 W System.err:    at io.reactivex.internal.operators.observable.ObservableTimeoutTimed$TimeoutTimedObserver$TimeoutTask.run(ObservableTimeoutTimed.java:290)
07-17 14:27:51.069  9622 11797 W System.err:    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
07-17 14:27:51.069  9622 11797 W System.err:    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
07-17 14:27:51.070  9622 11797 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-17 14:27:51.070  9622 11797 W System.err:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-17 14:27:51.070  9622 11797 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-17 14:27:51.070  9622 11797 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-17 14:27:51.070  9622 11797 W System.err:    at java.lang.Thread.run(Thread.java:761)
```
It happened to me with the parent categories tab, but the problem might exist with other tabs too.

**Comment by ujjwalagrawal17** [comment]
We don't have a network broadcast receiver in the fragment now. currently, it will load images if we have internet at the time of clicking tabs. We should call APIs again when we receive a callback of internet connection establishment. I will try to do it.

**Comment by nicolas-raoul** [comment]
If it is too difficult, how about just displaying "Internet connection failed" when that happens?

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul I think I have already added that. I will try to reproduce the same.

**Comment by ujjwalagrawal17** [comment]
@nicolas-raoul It seems to be fixed. Please tell me if you are still facing this.

**Comment by neslihanturan** [comment]
I couldn't reproduce it either, this one might be solved but not sure yet.
