### ISSUE TITLE
Multiple Uploads crashes if user try to upload without title

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1734]
**Summary:** 

Try to multiple upload and click upload button without title, it crashes.

**Add System logs:**

```
E/AndroidRuntime: FATAL EXCEPTION: UploadService
                                                                         Process: fr.free.nrw.commons.debug, PID: 9875
                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                                             at java.util.regex.Matcher.reset(Matcher.java:177)
                                                                             at java.util.regex.Matcher.<init>(Matcher.java:90)
                                                                             at java.util.regex.Pattern.matcher(Pattern.java:297)
                                                                             at fr.free.nrw.commons.Utils.fixExtension(Utils.java:120)
                                                                             at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:219)
                                                                             at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:130)
                                                                             at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:40)
                                                                             at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:26)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
07-22 17:27:18.382 1266-1266/? E/EGL_emulation: tid 1266: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
07-22 17:27:18.594 9875-9926/fr.free.nrw.commons.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa0612140
07-22 17:27:21.864 9875-9926/fr.free.nrw.commons.debug E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa0613220
```

**Device and Android version:** 
It happens on almost all devices. One is emulator API 24

 **Commons app version:** 
current master

**Would you like to work on the issue?**

No, if possible:)

**Comment by albendz** [comment]
I will take a look at this

**Comment by neslihanturan** [comment]
I tagged as assigned @albendz , it is yours

**Comment by Aschroet** [comment]
Same one my phone. After such a crash i even cannot start the app again and need to re-install it.

**Comment by maskaravivek** [comment]
@albendz Are you working on this? :)

We are very close to a release. It would be great to have this crash fix as part of this release itself.

**Comment by albendz** [comment]
I was on vacation last week when it was assigned to me and can get started next week. When is your release? I can let you know if I can get it done by the release.

**Comment by albendz** [comment]
Question: how do you want this to behave when a user inputs a blank title? Do you want this to save with an empty name (I would not recommend this) or fail with a message of invalid title?

**Comment by albendz** [comment]
I'll have a PR today with a toast that indicates a title for the set is missing.

**Comment by albendz** [comment]
PR is up! https://github.com/commons-app/apps-android-commons/pull/1769

**Comment by maskaravivek** [comment]
Closing this as it was fixed by @albendz's PR.
