### ISSUE TITLE
Nearby crash when LatLng is null

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1735]
**Summary:** 

I am able to get this crash on some first runs. Then it gets solved.

**Steps to reproduce:** 

Not very stable, sometimes, it happens. Ie, once I turned off wireless connection and it happened.
**Add System logs:**
```
                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                             at fr.free.nrw.commons.location.LatLng.from(LatLng.java:45)
                                                                             at fr.free.nrw.commons.location.LocationServiceManager.getLKL(LocationServiceManager.java:109)
                                                                             at fr.free.nrw.commons.nearby.NearbyActivity.onRequestPermissionsResult(NearbyActivity.java:224)
                                                                             at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6553)
                                                                             at android.app.Activity.dispatchActivityResult(Activity.java:6432)
```

**Comment by ashishkumar468** [comment]
Hi @neslihanturan @maskaravivek  I seem to have found the issue
`if (lastKL == null) {
                lastKL = locationManager.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);
            }
            return LatLng.from(lastKL);`

The function LatLng.from(lastKL) crashes when lastKL is null, we have a null check for location from GPS_PROVIDER but not for NETWORK_PROVIDER, 
Can I take this up?

**Comment by maskaravivek** [comment]
Yup sure it’s yours @ashishkumar468

**Comment by ashishkumar468** [comment]
Thanks @maskaravivek Have raised the pull request for the same
