### ISSUE TITLE
Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.setCurrentItem(int)' on a null object reference

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1741]
In current master branch, press on Explore, then press on any picture. Crash:
```
07-24 21:18:32.424  5863  5863 D AndroidRuntime: Shutting down VM
07-24 21:18:32.439  5863  5863 E AndroidRuntime: FATAL EXCEPTION: main
07-24 21:18:32.439  5863  5863 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 5863
07-24 21:18:32.439  5863  5863 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.setCurrentItem(int)' on a null object reference
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailPagerFragment.showImage(MediaDetailPagerFragment.java:270)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at fr.free.nrw.commons.category.CategoryImagesActivity.onItemClick(CategoryImagesActivity.java:126)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:4054)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-24 21:18:32.439  5863  5863 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-24 21:18:32.477   790  5378 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity
07-24 21:18:32.638   790 16326 I OpenGLRenderer: Initialized EGL, version 1.4
07-24 21:18:32.638   790 16326 D OpenGLRenderer: Swap behavior 1
07-24 21:18:32.981   790   804 W ActivityManager: Activity pause timeout for ActivityRecord{1a72cd0 u0 fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity t11777 f}
```

Android 7.1.2

**Comment by nicolas-raoul** [comment]
```
07-25 10:46:19.660 31058 31408 D DownloadManager: [5375] Finished with status SUCCESS                                                                                                                                                                                  
07-25 10:46:19.802  3787  3787 I TTS     : Broadcast received, download complete                                                                                                                                                                                       
07-25 10:46:19.802  3787  3787 I TTS     : Schedule processing voice download                                                                                                                                
07-25 10:46:19.818  3787  3787 I TTS     : Start processing voice download 5375                                                                                                                                                                                                               
07-25 10:46:20.867  6528  6569 I NetGuard.Service: Capabilities changed generation=null                                                                                                                                                           
07-25 10:46:20.867  6528  6569 I NetGuard.Service: New network generation=null                                                                                                                                                                                                                                       
07-25 10:46:20.868  6528  6569 I NetGuard.Monitor: New capabilities network 104 [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "aegis", failover: false, available: true, roaming: false, metered: false]                     
07-25 10:46:20.869  6528  6569 I NetGuard.Monitor: Capabilities=[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&FOREGROUND LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -61]               
07-25 10:46:21.011  3787 31881 I TTS     : Signature verification Success file:///storage/emulated/0/Android/data/com.google.android.tts/files/download_cache/fr-fr_4.zip                                                                                              
07-25 10:46:22.082 31058 31499 D DownloadManager: [5374] Finished with status SUCCESS                                                                                                                                                         
07-25 10:46:22.136  3787  3787 I TTS     : Broadcast received, download complete                                                                                                                                                                                                                       
07-25 10:46:22.136  3787  3787 I TTS     : Schedule processing voice download                                                                                                                                                                                          
07-25 10:46:22.153  3787  3787 I TTS     : Start processing voice download 5374                                                                                                                                               
07-25 10:46:22.409   956   956 I SlideTouchEvent: vel=0.0, MinimumFlingVelocity=150                                                                                                                                                                                                                                 
07-25 10:46:22.528 30412 30412 E InputEventReceiver: Exception dispatching input event.                                                                                                                                                                                                                              
07-25 10:46:22.528 30412 30412 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback                                                                                                                                                                                                         
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.setCurrentItem(int)' on a null object reference                                                                                           
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at fr.free.nrw.commons.media.MediaDetailPagerFragment.showImage(MediaDetailPagerFragment.java:270)                                                                                                      
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at fr.free.nrw.commons.category.CategoryImagesActivity.onItemClick(CategoryImagesActivity.java:126)                                                                                                                                              
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.widget.AdapterView.performItemClick(AdapterView.java:310)                                                                                                                                                                                         
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.widget.AbsListView.performItemClick(AbsListView.java:1164)                                                                                                                             
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)                                                                                                                
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.widget.AbsListView.onTouchUp(AbsListView.java:4066)                                                                                                                    
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.widget.AbsListView.onTouchEvent(AbsListView.java:3825)                                                                                                                                  
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.View.dispatchTouchEvent(View.java:10024)                                                                                                                      
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)                                                                                                         
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)                                                                                                                     
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                        
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                                          
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                                
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                                               
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                                        
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                                               
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                                   
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                                                              
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                                                                                                
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                                                                                                            
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                                                   
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                                    
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                                          
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                                                  
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                       
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                                    
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)                                                                                                                    
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)                                                                                                          
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)                                                                                                                                                                        
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.app.Activity.dispatchTouchEvent(Activity.java:3065)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.View.dispatchPointerEvent(View.java:10244)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
07-25 10:46:22.554 30412 30412 E MessageQueue-JNI:      at android.view.ViewRootImpl$WindowIn
07-25 10:46:22.555 30412 30412 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-25 10:46:22.556 30412 30412 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                                                                                                                                                     [974/5832]
07-25 10:46:22.556 30412 30412 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 30412
07-25 10:46:22.556 30412 30412 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.setCurrentItem(int)' on a null object reference
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailPagerFragment.showImage(MediaDetailPagerFragment.java:270)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at fr.free.nrw.commons.category.CategoryImagesActivity.onItemClick(CategoryImagesActivity.java:126)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.widget.AbsListView.onTouchUp(AbsListView.java:4066)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3825)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.View.dispatchTouchEvent(View.java:10024)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.app.Activity.dispatchTouchEvent(Activity.java:3065)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.View.dispatchPointerEvent(View.java:10244)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
07-25 10:46:22.556 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6356)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:323)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:136)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-25 10:46:22.557 30412 30412 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-25 10:46:22.663   785  7976 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity
07-25 10:46:23.168   785   803 W ActivityManager: Activity pause timeout for ActivityRecord{207cd44 u0 fr.free.nrw.commons.debug/fr.free.nrw.commons.category.CategoryImagesActivity t11792 f}
07-25 10:46:23.278   785 31897 I chatty  : uid=1000(system) RenderThread expire 2 lines
07-25 10:46:23.521  3787 31641 I TTS     : Signature verification Success file:///storage/emulated/0/Android/data/com.google.android.tts/files/download_cache/ja-jp_2.zip
07-25 10:46:23.885  6528  6569 I NetGuard.Service: Capabilities changed generation=null
07-25 10:46:23.885  6528  6569 I NetGuard.Service: New network generation=null
07-25 10:46:23.885  6528  6569 I NetGuard.Monitor: New capabilities network 104 [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "aegis", failover: false, available: true, roaming: false, metered: false]
07-25 10:46:23.885  6528  6569 I NetGuard.Monitor: Capabilities=[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&FOREGROUND LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -78]
07-25 10:46:24.034 30412 30444 I art     : Starting a blocking GC Explicit
```
