### ISSUE TITLE
Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1747]
Crash in current master:
```
07-26 22:47:58.194   789   803 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.
launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10028)                                                                                                                                                           
07-26 22:47:58.226 26844 26844 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.                                                                                                                             
07-26 22:47:58.492   931   931 I GoogleInputMethod: onFinishInput() : Dummy InputConnection bound                                                                                                                                                            
07-26 22:47:58.493   789   810 I ActivityManager: Displayed fr.free.nrw.commons.debug/fr.free.nrw.commons.explore.SearchActivity: +311ms                                                                                                                     
07-26 22:47:58.493   931   931 I ShortcutsDataManager: startImportContentTask()                                                                                                                                                                              
07-26 22:47:58.493   931   931 I ShortcutsDataManager: onImportAborted()                                                                                                                                                                                     
07-26 22:47:58.514   931   931 I EmptyEmojiDataEx: onActivate()                                                                                                                                                                                              
07-26 22:47:58.525   931   931 I EmptyEmojiDataEx: onDeactivate()                                                                                                                                                                                            
07-26 22:47:58.526   931   931 I ShortcutsDataManager: startImportContentTask()                                                                                                                                                                              
07-26 22:47:58.526   931   931 I ShortcutsDataManager: onImportAborted()                                                                                                                                                                                     
07-26 22:47:58.537   931   931 I EmptyEmojiDataEx: onActivate()                                                                                                                                                                                              
07-26 22:47:58.849 26844 26844 W System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference                                                 
07-26 22:47:58.849 26844 26844 W System.err:    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)                                                                                                               
07-26 22:47:58.849 26844 26844 W System.err:    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)                                                                                                               
07-26 22:47:58.849 26844 26844 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)                                                                                                                            
07-26 22:47:58.849 26844 26844 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)                                                                                                                             
07-26 22:47:58.849 26844 26844 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)                                                                                
07-26 22:47:58.849 26844 26844 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)                                                                                        
07-26 22:47:58.850 26844 26844 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)                                                                                                         
07-26 22:47:58.850 26844 26844 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)                                                                                                                                                       
07-26 22:47:58.850 26844 26844 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)                                                                                                                                                       
07-26 22:47:58.850 26844 26844 W System.err:    at android.os.Looper.loop(Looper.java:154)                                                                                                                                                                   
07-26 22:47:58.850 26844 26844 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6186)                                                                                                                                                 
07-26 22:47:58.850 26844 26844 W System.err:    at java.lang.reflect.Method.invoke(Native Method)                                                                                                                                                            
07-26 22:47:58.850 26844 26844 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)                                                                                                                           
07-26 22:47:58.850 26844 26844 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)                                                                                                                                              
07-26 22:47:58.854 26844 26844 W System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference                                                              
07-26 22:47:58.854 26844 26844 W System.err:    at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList(SearchImageFragment.java:124)                                                                                                      
07-26 22:47:58.855 26844 26844 W System.err:    at fr.free.nrw.commons.explore.SearchActivity.lambda$setTabs$1$SearchActivity(SearchActivity.java:111)                                                                                                       
07-26 22:47:58.855 26844 26844 W System.err:    at fr.free.nrw.commons.explore.SearchActivity$$Lambda$1.accept(Unknown Source)                                                                                                                               
07-26 22:47:58.855 26844 26844 W System.err:    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)                                                                                                                             
07-26 22:47:58.855 26844 26844 W System.err:    ... 10 more                                                                                                                                                                                                  
--------- beginning of crash                                                                                                                                                                    
07-26 22:47:58.858 26844 26844 E AndroidRuntime: FATAL EXCEPTION: main                                                                         
07-26 22:47:58.858 26844 26844 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 26844                                                                                                      
07-26 22:47:58.858 26844 26844 E AndroidRuntime: io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)                  
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)                                                 
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)    
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)                                                                           
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)                                                                                                             
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)                                                                                                                 
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)                                                                        
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)                                                        
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)                
07-26 22:47:58.858 26844 26844 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference 
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at fr.free.nrw.commons.explore.images.SearchImageFragment.updateImageList(SearchImageFragment.java:124)
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at fr.free.nrw.commons.explore.SearchActivity.lambda$setTabs$1$SearchActivity(SearchActivity.java:111)
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at fr.free.nrw.commons.explore.SearchActivity$$Lambda$1.accept(Unknown Source)                
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
07-26 22:47:58.858 26844 26844 E AndroidRuntime:        ... 10 more                                                                                                                                                                     
07-26 22:47:58.895   789 27994 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.explore.SearchActivity                                 
07-26 22:47:59.032   789 10621 I OpenGLRenderer: Initialized EGL, version 1.4                                                                                                                                         
07-26 22:47:59.032   789 10621 D OpenGLRenderer: Swap behavior 1                                                                                                                                       
07-26 22:47:59.399   789   803 W ActivityManager: Activity pause timeout for ActivityRecord{42b383e u0 fr.free.nrw.commons.debug/fr.free.nrw.commons.explore.SearchActivity t11866 f}  
```

**Comment by nicolas-raoul** [comment]
Duplicate of #1753
