### ISSUE TITLE
Notification-related crashes on Android 8.1 (API 27)

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#1834]
**Summary:** 

I consistently get crashes on upload attempts on Android 8.1.

**Steps to reproduce:** 

Tap the camera icon and proceed to upload.

Logcat says:

    08-17 21:31:19.706 17044-17044/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 17044
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x52 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Device and Android version:** 

Android 8.1.
 
 **Commons app version:** 

master (3cee4bbe3b305d58)

**Would you like to work on the issue?**

yes

**Comment by misaochan** [comment]
Thanks @whym ! We'll test your PR ASAP.
