### ISSUE TITLE
Nearby crashes when Home [From the Nav Drawer] is pressed while nearby is still loading data

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#1846]
**Summary:** 
If we press home while nearby is still loading data, nearby crashes.

**Steps to reproduce:** 

Click on Nearby and while its loading data, click on home from the nav drawer, nearby crashes with InterruptedIOException

**Add System logs:**

Add logcat files here (if possible).

```
Caused by: java.io.InterruptedIOException: thread interrupted
        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
        at com.android.okhttp.okio.Okio$1.write(Okio.java:78)
        at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
        at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
        at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:60)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1154)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:976)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:509)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:438)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:247)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
        at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:84)
        at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:48)
        at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocation(NearbyController.java:56)
        at fr.free.nrw.commons.nearby.NearbyActivity.lambda$refreshView$7$NearbyActivity(NearbyActivity.java:438)
        at fr.free.nrw.commons.nearby.NearbyActivity$$Lambda$7.call(Unknown Source)
```

**Device and Android version:** 

Samsung s7 api 27

 **Commons app version:** 
2.8.1-debug-master~4ea72298

**Screen-shots:** 
NA

**Would you like to work on the issue?**
Yes

**Comment by ashishkumar468** [comment]
Can someone please review this ?

**Comment by maskaravivek** [comment]
Please go ahead and fix it if you can. :)

**Comment by maskaravivek** [comment]
Does it also happen on latest master?

**Comment by VojtechDostal** [comment]
Cannot reproduce this bug in 2.8.2.

Anyone?

**Comment by ashishkumar468** [comment]
Actually my version is 2.8.1

**Comment by maskaravivek** [comment]
@ashishkumar468 If this is not happening in the latest version of the app, then we can probably close it. Let us know if you are still facing an issue.

**Comment by maskaravivek** [comment]
IMO, it might not be reproducible every time especially on faster networks. If it is still happening on the latest master, you can go ahead and add handling for `InterruptedIOException`. 

Anyways will try to test if it happens for me as well.

**Comment by ashishkumar468** [comment]
@maskaravivek Yes, might be the case that I will not be easily reproducible in fast networks. Still the issue persists and can be easily realised from the code. Have added a fix for the same. It would be great if you could review https://github.com/commons-app/apps-android-commons/pull/1847

**Comment by maskaravivek** [comment]
The corresponding PR has been merged. Closing this issue. Thanks @ashishkumar468

**Comment by nicolas-raoul** [comment]
I just had something vaguely similar with 2.8.6:
```
11-01 10:01:54.611   786   812 I ActivityManager: Displayed fr.free.nrw.commons/.contributions.ContributionsActivity: +436ms                                                                                                                                 
11-01 10:01:54.626 31756 31756 I MultiDex: VM with version 2.1.0 has multidex support                                                                                                                                                                        
11-01 10:01:54.626 31756 31756 I MultiDex: Installing application                                                                                                                                                                                            
11-01 10:01:54.626 31756 31756 I MultiDex: VM has multidex support, MultiDex support library is disabled.                                                                                                                                                    
11-01 10:01:54.660 25179 25179 I GoogleInputMethod: onFinishInput() : Dummy InputConnection bound                                                                                                                                                            
11-01 10:01:54.660 25179 25179 I GoogleInputMethod: onStartInput() : Dummy InputConnection bound                                                                                                                                                             
11-01 10:01:54.660 25179 25179 I ShortcutsDataManager: startImportContentTask()                                                                                                                                                                              
11-01 10:01:54.660 25179 25179 I ShortcutsDataManager: onImportAborted()                                                                                                                                                                                     
11-01 10:01:54.673 31210 31797 D ContributionsSyncAdapte: Max number of uploads set to 500                                                                                                                                                                   
11-01 10:01:54.914 25179 25179 I GoogleInputMethod: onFinishInput() : Dummy InputConnection bound                                                                                                                                                            
11-01 10:01:54.914 25179 25179 I GoogleInputMethod: onStartInput() : Dummy InputConnection bound                                                                                                                                                             
11-01 10:01:54.914 25179 25179 I ShortcutsDataManager: startImportContentTask()                                                                                                                                                                              
11-01 10:01:54.914 25179 25179 I ShortcutsDataManager: onImportAborted()                                                                                                                                                                                     
11-01 10:01:54.915 31210 31277 W OpenGLRenderer: Points are too far apart 4.000001                                                                                                                                                                           
11-01 10:01:55.207   786   801 I ActivityManager: Waited long enough for: ServiceRecord{b18ef41 u0 com.whatsapp/.messaging.MessageService}                                                                                                                   
11-01 10:01:55.285 31210 31656 D NearbyPlaces: Reading from query result...                                                                                                                                                                                  
11-01 10:01:55.286 31210 31656 V NearbyPlaces: ?location        ?item   ?label  ?class  ?class_label    ?icon   ?emoji  ?wikipediaArticle       ?commonsArticle ?Commons_category                                                                            
11-01 10:01:55.304 31210 31656 W System.err: io.reactivex.exceptions.UndeliverableException: java.io.InterruptedIOException: thread interrupted                                                                                                              
11-01 10:01:55.315 31210 31656 W System.err:    at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)                                                                                                                                        
11-01 10:01:55.315 31210 31656 W System.err:    at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:48)                                                                                         
11-01 10:01:55.315 31210 31656 W System.err:    at io.reactivex.Observable.subscribe(Observable.java:10901)                                                                                                                                                  
11-01 10:01:55.315 31210 31656 W System.err:    at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)                                                                                         
11-01 10:01:55.315 31210 31656 W System.err:    at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)                                                                                                                                                
11-01 10:01:55.315 31210 31656 W System.err:    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)                                                                                                                         
11-01 10:01:55.315 31210 31656 W System.err:    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)                                                                                                                        
11-01 10:01:55.315 31210 31656 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)                                                                                                                                                  
11-01 10:01:55.315 31210 31656 W System.err:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)                                                                                            
11-01 10:01:55.315 31210 31656 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)                                                                                                                           
11-01 10:01:55.315 31210 31656 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)                                                                                                                           
11-01 10:01:55.315 31210 31656 W System.err:    at java.lang.Thread.run(Thread.java:761)                                                                                                                                                                     
11-01 10:01:55.328 31210 31656 W System.err: Caused by: java.io.InterruptedIOException: thread interrupted                                                                                                                                                   
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)                                                                                                                                          
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.Okio$2.read(Okio.java:133)                                                                                                                                                        
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)                                                                                                                                        
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)                                                                                                                               
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:464)                                                                                                               
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)                                                                                                                               
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)                                                                                                                          
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.InflaterSource.refill(InflaterSource.java:101)                                                                                                                                    
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.InflaterSource.read(InflaterSource.java:62)                                                                                                                                       
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.GzipSource.read(GzipSource.java:80)                                                                                                                                               
11-01 10:01:55.328 31210 31656 W System.err:    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)                                                                                                                            
11-01 10:01:55.328 31210 31656 W System.err:    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
11-01 10:01:55.328 31210 31656 W System.err:    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)                                                                                                                                       [244/8122]
11-01 10:01:55.328 31210 31656 W System.err:    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)                                                         
11-01 10:01:55.329 31210 31656 W System.err:    at java.io.InputStreamReader.read(InputStreamReader.java:184)                                                                                                                                                
11-01 10:01:55.329 31210 31656 W System.err:    at java.io.BufferedReader.fill(BufferedReader.java:172)                                                             
11-01 10:01:55.329 31210 31656 W System.err:    at java.io.BufferedReader.readLine(BufferedReader.java:335)                                                                                                                                                  
11-01 10:01:55.329 31210 31656 W System.err:    at java.io.BufferedReader.readLine(BufferedReader.java:400)                     
11-01 10:01:55.329 31210 31656 W System.err:    at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:88)
11-01 10:01:55.329 31210 31656 W System.err:    at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:48)
11-01 10:01:55.329 31210 31656 W System.err:    at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocation(NearbyController.java:56)
11-01 10:01:55.329 31210 31656 W System.err:    at fr.free.nrw.commons.nearby.NearbyActivity.lambda$refreshView$7$NearbyActivity(NearbyActivity.java:437)
11-01 10:01:55.329 31210 31656 W System.err:    at fr.free.nrw.commons.nearby.NearbyActivity$$Lambda$7.call(Unknown Source)        
11-01 10:01:55.329 31210 31656 W System.err:    at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)                                                                                         
11-01 10:01:55.329 31210 31656 W System.err:    ... 10 more                                                                                          
11-01 10:01:55.330 31210 31656 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1                                                               
11-01 10:01:55.330 31210 31656 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 31210                                                                                                                                                                    
11-01 10:01:55.330 31210 31656 E AndroidRuntime: io.reactivex.exceptions.UndeliverableException: java.io.InterruptedIOException: thread interrupted
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)                            
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:48)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at io.reactivex.Observable.subscribe(Observable.java:10901)                                                              
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)                                                                                 
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)                  
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)                                                                                                                                          
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)                                                                                    
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)                                                                                                                   
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)                                                            
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)                                                                                                       
11-01 10:01:55.330 31210 31656 E AndroidRuntime: Caused by: java.io.InterruptedIOException: thread interrupted                         
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.Okio$2.read(Okio.java:133)                                                                                                                                           
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)   
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)           
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:464)   
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)                                                               
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)                                                                           
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.InflaterSource.refill(InflaterSource.java:101)                                                                                                                            
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.InflaterSource.read(InflaterSource.java:62)                                          
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.GzipSource.read(GzipSource.java:80)                                                                                                                                       
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)                                        
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)                          
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)                                                                                                                                      
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)                                                                                                                                             
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.io.InputStreamReader.read(InputStreamReader.java:184)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.io.BufferedReader.fill(BufferedReader.java:172)                                                                                                       
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.io.BufferedReader.readLine(BufferedReader.java:335)          
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at java.io.BufferedReader.readLine(BufferedReader.java:400)                 
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:88)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyPlaces.getFromWikidataQuery(NearbyPlaces.java:48)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocation(NearbyController.java:56)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyActivity.lambda$refreshView$7$NearbyActivity(NearbyActivity.java:437)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyActivity$$Lambda$7.call(Unknown Source)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
11-01 10:01:55.330 31210 31656 E AndroidRuntime:        ... 10 more
```

**Comment by ashishkumar468** [comment]
Fixed and Not reproducible in latest builds, marking this as closed
