### ISSUE TITLE
App crashing when selecting some specific images

### ISSUE THREAD

**Issue by Divyanshu2132** [commons-app/apps-android-commons#1942]
**Summary:**

App is crashing whenever I am selecting specific image from gallery 

**Add System logs:**

java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.ShareActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.close()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.close()' on a null object reference
        at fr.free.nrw.commons.utils.FileUtils.saveFileFromURI(FileUtils.java:48)
        at fr.free.nrw.commons.utils.ContributionUtils.saveFileBeingUploadedTemporarily(ContributionUtils.java:34)
        at fr.free.nrw.commons.upload.ShareActivity.receiveImageIntent(ShareActivity.java:358)
        at fr.free.nrw.commons.upload.ShareActivity.onCreate(ShareActivity.java:299)
        at android.app.Activity.performCreate(Activity.java:7013)
        at android.app.Activity.performCreate(Activity.java:7004)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

**Device and Android version:** 

Asus Zenfone Max Pro M1  Android 8.1.0
 
 **Commons app version:** 

master and betaDebug/prodDebug

**Would you like to work on the issue?**

Preferably no

**Comment by konohakesh** [comment]
Is anyone working on it?  I would like to look into it.

**Comment by misaochan** [comment]
@Divyanshu2132 are you working on this at the moment?

**Comment by Divyanshu2132** [comment]
No anyone take up tuis issue I am working on different issue

**Comment by misaochan** [comment]
@konohakesh It is yours. :)

**Comment by konohakesh** [comment]
I looked into it. Looks like it is failing when ShareActivity is getting rendered which happens once you select a picture from gallery and then this activity actually brings in the Title\Desc screen.

While this activity is getting loaded, under the covers it tries to save the picture to temp location in order to use that URI for upload process later. 

But when it is inFileUtils.saveFileFromURI() method while closing output stream it throws NPE as the object is null at that point. 

Now this can avoided by having  a null check for both input stream and output stream objects in finally block but what I am not able to understand why they would be null in the first place.

The whole stack trace will go away post null check but it does not show the core problem.

One theory is that something happened either during fetching inputStream or outputStream.
Some exception which occurred beyond what catch block is hoping for, would also explain this stack trace.

So in this case how should I go about fixing it? Should I change the catch block to accept All exceptions so that in future we will have complete stack trace for fixing this problem?

**Comment by konohakesh** [comment]
Its been a while. Now I see that post this [#1918](https://github.com/commons-app/apps-android-commons/pull/1918#issue-221159306) PR, null check is done but that can be improved upon by having   separate catch block for both input and output stream. I will do that change.

Also make the earlier catch block handle all exceptions as I talked about it in the above post so that we know what really caused the null streams.
