### ISSUE TITLE
App crashes due to NPE in bookmarks

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#1967]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

Proddebug installs on a fresh install when a media item is clicked. 

**Add System logs:**

```
2018-10-31 23:58:04.528 18194-18194/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 18194
    java.lang.NullPointerException: Cannot return null from a non-@Nullable @Provides method
        at dagger.internal.Preconditions.checkNotNull(Preconditions.java:48)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideBookmarkContentProviderClientFactory.get(CommonsApplicationModule_ProvideBookmarkContentProviderClientFactory.java:24)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideBookmarkContentProviderClientFactory.get(CommonsApplicationModule_ProvideBookmarkContentProviderClientFactory.java:10)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.findBookmark(BookmarkPicturesDao.java:123)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.updateBookmarkState(MediaDetailPagerFragment.java:310)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateOptionsMenu(MediaDetailPagerFragment.java:277)
        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2450)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3296)
        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:322)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:365)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:332)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:55)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:766)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6649)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

```

**Device and Android version:** 

Android 8.1

**Comment by domdomegg** [comment]
Was able to reproduce with `2.8.5-debug-master~ef73204c` on `Samsung Galaxy S6` with API level `25`

```
2018-11-03 13:04:38.706 3881-3881/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 3881
    java.lang.SecurityException: Permission Denial: opening provider fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesContentProvider from ProcessRecord{214d0bb 3881:fr.free.nrw.commons/u0a107} (pid=3881, uid=10107) that is not exported from uid 10106
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4199)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:5534)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2220)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:1504)
        at android.content.ContentResolver.acquireContentProviderClient(ContentResolver.java:1569)
        at fr.free.nrw.commons.di.CommonsApplicationModule.provideBookmarkContentProviderClient(CommonsApplicationModule.java:79)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideBookmarkContentProviderClientFactory.get(CommonsApplicationModule_ProvideBookmarkContentProviderClientFactory.java:25)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideBookmarkContentProviderClientFactory.get(CommonsApplicationModule_ProvideBookmarkContentProviderClientFactory.java:10)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.findBookmark(BookmarkPicturesDao.java:123)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.updateBookmarkState(MediaDetailPagerFragment.java:310)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateOptionsMenu(MediaDetailPagerFragment.java:277)
        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2450)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3296)
        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:322)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:365)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:332)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:55)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by maskaravivek** [comment]
@domdomegg The issue is no longer happening for me.
