### ISSUE TITLE
Crash on opening media details activity

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2026]
**Summary:** 

Opening media details activity crashes the app

**Steps to reproduce:** 

Click on any uploaded image to open media details. 

**System logs:**

```
2018-11-25 23:52:08.022 11454-11924/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #9
    Process: fr.free.nrw.commons.beta, PID: 11454
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOError: org.xml.sax.SAXParseException: attr value delimiter missing! (position:START_TAG <img src='https://www.wikimedia.org/static/images/wmf.png' srcset='https://www.wikimedia.org/static/images/wmf-2x.png 2x' alt='null'>@20:163 in java.io.InputStreamReader@a90d559) 
        at fr.free.nrw.commons.mwapi.CustomApiResult.fromRequestBuilder(CustomApiResult.java:58)
        at fr.free.nrw.commons.mwapi.CustomMwApi.makeRequest(CustomMwApi.java:177)
        at fr.free.nrw.commons.mwapi.CustomMwApi.access$000(CustomMwApi.java:18)
        at fr.free.nrw.commons.mwapi.CustomMwApi$RequestBuilder.get(CustomMwApi.java:34)
        at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.fetchMediaByFilename(ApacheHttpClientMediaWikiApi.java:340)
        at fr.free.nrw.commons.MediaDataExtractor.fetch(MediaDataExtractor.java:72)
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:263)
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:248)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: org.xml.sax.SAXParseException: attr value delimiter missing! (position:START_TAG <img src='https://www.wikimedia.org/static/images/wmf.png' srcset='https://www.wikimedia.org/static/images/wmf-2x.png 2x' alt='null'>@20:163 in java.io.InputStreamReader@a90d559) 
        at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:147)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
        at fr.free.nrw.commons.mwapi.CustomApiResult.fromRequestBuilder(CustomApiResult.java:43)
        at fr.free.nrw.commons.mwapi.CustomMwApi.makeRequest(CustomMwApi.java:177) 
        at fr.free.nrw.commons.mwapi.CustomMwApi.access$000(CustomMwApi.java:18) 
        at fr.free.nrw.commons.mwapi.CustomMwApi$RequestBuilder.get(CustomMwApi.java:34) 
        at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.fetchMediaByFilename(ApacheHttpClientMediaWikiApi.java:340) 
        at fr.free.nrw.commons.MediaDataExtractor.fetch(MediaDataExtractor.java:72) 
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:263) 
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:248) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2018-11-25 23:52:08.022 11454-11923/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #8
    Process: fr.free.nrw.commons.beta, PID: 11454
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOError: org.xml.sax.SAXParseException: attr value delimiter missing! (position:START_TAG <img src='https://www.wikimedia.org/static/images/wmf.png' srcset='https://www.wikimedia.org/static/images/wmf-2x.png 2x' alt='null'>@20:163 in java.io.InputStreamReader@c82251e) 
        at fr.free.nrw.commons.mwapi.CustomApiResult.fromRequestBuilder(CustomApiResult.java:58)
        at fr.free.nrw.commons.mwapi.CustomMwApi.makeRequest(CustomMwApi.java:177)
        at fr.free.nrw.commons.mwapi.CustomMwApi.access$000(CustomMwApi.java:18)
        at fr.free.nrw.commons.mwapi.CustomMwApi$RequestBuilder.get(CustomMwApi.java:34)
        at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.fetchMediaByFilename(ApacheHttpClientMediaWikiApi.java:340)
        at fr.free.nrw.commons.MediaDataExtractor.fetch(MediaDataExtractor.java:72)
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:263)
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:248)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: org.xml.sax.SAXParseException: attr value delimiter missing! (position:START_TAG <img src='https://www.wikimedia.org/static/images/wmf.png' srcset='https://www.wikimedia.org/static/images/wmf-2x.png 2x' alt='null'>@20:163 in java.io.InputStreamReader@c82251e) 
        at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:147)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
        at fr.free.nrw.commons.mwapi.CustomApiResult.fromRequestBuilder(CustomApiResult.java:43)
        at fr.free.nrw.commons.mwapi.CustomMwApi.makeRequest(CustomMwApi.java:177) 
        at fr.free.nrw.commons.mwapi.CustomMwApi.access$000(CustomMwApi.java:18) 
        at fr.free.nrw.commons.mwapi.CustomMwApi$RequestBuilder.get(CustomMwApi.java:34) 
        at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.fetchMediaByFilename(ApacheHttpClientMediaWikiApi.java:340) 
        at fr.free.nrw.commons.MediaDataExtractor.fetch(MediaDataExtractor.java:72) 
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:263) 
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:248) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Device and Android version:** 

Nexus 5. API 27. 
 
**Commons app version:** 

`2.9-release` branch. Beta variant

**Would you like to work on the issue?**

Preferably not.

**Comment by Divyanshu2132** [comment]
I want to take up this issue

**Comment by maskaravivek** [comment]
Sure @Divyanshu2132, take this up. Also, check if this happens just on `beta` variant or also happens on `prod`

**Comment by Divyanshu2132** [comment]
Yes I have checked on beta version also same thing is happening

**Comment by maskaravivek** [comment]
Please check on `prod` version as well. I got this issue on `beta` version and I couldn't check `prod`

**Comment by misaochan** [comment]
Works in prod for me on API 27 Nexus S. No harm in fixing it for beta, but not a high priority IMO.

**Comment by Divyanshu2132** [comment]
Sure I will look into it

**Comment by namrata-jha** [comment]
Can I take the issue up?

**Comment by maskaravivek** [comment]
Sure take this up @namrata-jha. The first step would be to reproduce the issue. It is possible that this might already be fixed.

**Comment by ashishkumar468** [comment]
Seems to ve very old, also I can confirm from the logs that this has been fixed. Closing this issue
