### ISSUE TITLE
NPE after tapping image in Explore

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2029]
**Summary:** 

App crashes after tapping an image in Explore to view the media details

**Steps to reproduce:** 

Open Explore. Tap on a picture.

**System logs:**

```
11-26 20:31:51.818 4699-4740/fr.free.nrw.commons D/CustomApiResult: API response is
     <?xml version="1.0" encoding="UTF-8"?><api batchcomplete=""><query><pages><page _idx="71497799" pageid="71497799" ns="6" title="File:Dehnbare Helmling Mycena epipterygia.jpg" imagerepository="local"><imageinfo><ii thumburl="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Dehnbare_Helmling_Mycena_epipterygia.jpg/640px-Dehnbare_Helmling_Mycena_epipterygia.jpg" thumbwidth="640" thumbheight="448" url="https://upload.wikimedia.org/wikipedia/commons/1/1e/Dehnbare_Helmling_Mycena_epipterygia.jpg" descriptionurl="https://commons.wikimedia.org/wiki/File:Dehnbare_Helmling_Mycena_epipterygia.jpg" descriptionshorturl="https://commons.wikimedia.org/w/index.php?curid=71497799"/></imageinfo></page></pages></query></api>
11-26 20:31:52.098 4699-4699/fr.free.nrw.commons D/AndroidRuntime: Shutting down VM
11-26 20:31:52.098 4699-4699/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 4699
    java.lang.NullPointerException: Attempt to invoke interface method 'int fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailProvider.getTotalMediaCount()' on a null object reference
        at fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter.getCount(MediaDetailPagerFragment.java:398)
        at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:526)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateView(MediaDetailPagerFragment.java:110)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Device and Android version:** 

Nexus S API 27
 
**Commons app version:** 

2.9-release prodRelease build

**Would you like to work on the issue?**

Pref not

**Comment by misaochan** [comment]
Actually, no, this seems to happen all the time now (on prodRelease anyway), not just after Skip Login. :/
