### ISSUE TITLE
2.9.0: Unable to exit app after going to notifications activity

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2044]
**Summary:**
I am unable to exit the app using the back button just after I go to the notifications activity. Hitting the back button cycles through the notification and main screen infinitely.

**Steps to reproduce:** 
1. Open the app
2. Tap on the notification icon (left end of the top bar)
3. Hit back (should have come to the main screen)
4. Hit back to exit the app
5. Hit back agian

**Observation**
When I hit back in steps 4 I am taken back to the notification activity. In step  5, I'm taken back to home screen. This goes on infinitely and I'm unable to exit the app. This seems very odd.

**Device and Android version:** 
Galaxy J1 ace running Android 5.1.1 (stock)

**Commons app version:** 
2.9.0

**Would you like to work on the issue?**
No

**Comment by nicolas-raoul** [comment]
I can reproduce on latest alpha.
Additionally, the jpp crashes after I do it many many times:
```
USER_COMMENT=
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=2.9.0.109
BRAND=google
PHONE_MODEL=Nexus 5
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.ContextWrapper.getSharedPreferences(java.lang.String, int)' on a null object reference
at fr.free.nrw.commons.notification.UnreadNotificationsCheckAsync.onPostExecute(UnreadNotificationsCheckAsync.java:51)
at fr.free.nrw.commons.notification.UnreadNotificationsCheckAsync.onPostExecute(UnreadNotificationsCheckAsync.java:18)
at android.os.AsyncTask.finish(AsyncTask.java:667)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by misaochan** [comment]
I think @domdomegg submitted a PR for this. Let us try again after his PR is merged :)
