### ISSUE TITLE
Error loading achievements due to SSL handshake error

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2061]
As reported by a user. 

**Summary:** 

Achievements activity doesn't load

**System logs:**
Added from the logs received:

```
javax.net.ssl.SSLHandshakeException: Connection closed by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:302)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:270)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:162)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.lambda$getAchievements$4$ApacheHttpClientMediaWikiApi(ApacheHttpClientMediaWikiApi.java:985)
	at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi$$Lambda$8.call(Unknown Source)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```
 
**Commons app version:** 

2.9.0

**Would you like to work on the issue?**

No.

**Comment by misaochan** [comment]
Does it never load for that user, or did this only happen once?

**Comment by maskaravivek** [comment]
The logs sent by the user had 3 instances of this error. And I didn't see any success logs either. 

Username: Jompol0000

**Comment by Divyanshu2132** [comment]
Same is happening with my achievement activity also 
I would like to work on this issue

**Comment by Divyanshu2132** [comment]
Response.body() is getting this data from server side 
"Content-type:application/json "
That is why it is unable to convert to gson datatype giving IllegalStateException

**Comment by misaochan** [comment]
@Divyanshu2132 please feel free, thanks! :)

**Comment by maskaravivek** [comment]
@Divyanshu2132 The error you are talking seems to be different from this issue. 

"Content-type:application/json" is issue #2154 

Also, it has a PR #2087 which is working well and is waiting just for a review.

**Comment by domdomegg** [comment]
There have been no further instances of this error so am closing.
