### ISSUE TITLE
Crash when clicking bookmark icon inside BookmarksActivity

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2166]
**Summary:** 

Crashes on clicking the bookmark icon in the action bar when viewing media through BookmarksActivity.

**Steps to reproduce:** 

How can we reproduce the issue?
1. Log in
2. Open media from Home
3. Click bookmark icon
4. Go to bookmarks tab
5. Click media
6. Click bookmark icon
7. Crashes

What did you expect the app to do, and what did you see instead?
- Should show bookmarked icon as 'filled in' to represent it is bookmarked
- Should not crash when bookmark icon clicked
- Should unbookmark the item

**Demonstration:**

Video:
https://giant.gfycat.com/WellinformedCheeryBeagle.webm

In video above I:
1. Open bookmarks, show empty
2. Add a bookmark on an image from Home (notice unfilled goes to filled icon)
3. Open bookmarks, show it's now there
4. Open image in bookmarks (notice unfilled star icon)
5. Try to unbookmark, crashes
6. Try steps 3-5 again, crashes
7. Unbookmark the image in the Home tab (notice filled star icon)
8. Show bookmarks now empty

<details>
<summary><b>System logs (click to expand)</b></summary>
<pre><code>2018-12-18 23:34:21.916 16027-16027/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 16027
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String fr.free.nrw.commons.bookmarks.Bookmark.getMediaName()' on a null object reference
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.findBookmark(BookmarkPicturesDao.java:129)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.updateBookmark(BookmarkPicturesDao.java:70)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onOptionsItemSelected(MediaDetailPagerFragment.java:161)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2476)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3343)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:347)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:413)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-12-18 23:34:21.917 16027-16027/fr.free.nrw.commons E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String fr.free.nrw.commons.bookmarks.Bookmark.getMediaName()' on a null object reference
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.findBookmark(BookmarkPicturesDao.java:129)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.updateBookmark(BookmarkPicturesDao.java:70)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onOptionsItemSelected(MediaDetailPagerFragment.java:161)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2476)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3343)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:347)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:413)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
</code></pre>

<pre><code>2018-12-18 23:34:47.721 16144-16144/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 16144
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String fr.free.nrw.commons.bookmarks.Bookmark.getMediaName()' on a null object reference
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.findBookmark(BookmarkPicturesDao.java:129)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.updateBookmark(BookmarkPicturesDao.java:70)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onOptionsItemSelected(MediaDetailPagerFragment.java:161)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2476)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3343)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:347)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:413)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-12-18 23:34:47.723 16144-16144/fr.free.nrw.commons E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String fr.free.nrw.commons.bookmarks.Bookmark.getMediaName()' on a null object reference
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.findBookmark(BookmarkPicturesDao.java:129)
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.updateBookmark(BookmarkPicturesDao.java:70)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onOptionsItemSelected(MediaDetailPagerFragment.java:161)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2476)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3343)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:347)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:413)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
</code></pre>
</details><br/>

**Device and Android version:** 

`2.9.0-debug-master~46db38b8 (prodDebug)` on `Galaxy Nexus (emulator)` at API level `28`
`2.9.0-debug-master~46db38b8 (prodDebug)` on `Samsung Galaxy` at API level `25`

**Comment by briancollins-92** [comment]
Hi @domdomegg, just having  look and I am afraid I am not able to replicate this using my emulators (Nexus, one at 27 and one at 25)

I am wondering which branch you might be using, I tried it on master and on 2.9-release and could not replicate, thanks

**Comment by domdomegg** [comment]
Hi @briancollins-92, thanks for looking into this.

I was using master @ 46db38b.

I've just tried again and can't reproduce it now on the current master (784ee8b) but can in the version that was failing (46db38b)

I think it may have been fixed by #2047 which was merged 5 hours ago in f3b450e. Going to close this for now, will reopen if bug reappears.
