### ISSUE TITLE
Crash in nearby

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2167]
**Summary:** 

Sometimes nearby crashes. Based off error messages, think is to do with #591 / #2051.

**Steps to reproduce:** 

How can we reproduce the issue?
Not quite sure, but seems to happen if you log in/out a few times and then open the nearby tab. Very inconsistent. Given the method names might also need to be moving/be in the process of being located by GPS?

**System logs:**

```
2018-12-18 23:43:12.661 18186-18186/fr.free.nrw.commons E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons
    java.lang.NullPointerException: Attempt to read from field 'boolean fr.free.nrw.commons.nearby.NearbyMapFragment.searchThisAreaModeOn' on a null object reference
        at fr.free.nrw.commons.nearby.NearbyFragment.updateMapFragment(NearbyFragment.java:432)
        at fr.free.nrw.commons.nearby.NearbyFragment.refreshView(NearbyFragment.java:319)
        at fr.free.nrw.commons.nearby.NearbyFragment.onLocationChangedSlightly(NearbyFragment.java:226)
        at fr.free.nrw.commons.location.LocationServiceManager.onLocationChanged(LocationServiceManager.java:277)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
        at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Device and Android version:** 

`2.9.0-debug-master~46db38b8 (prodDebug)` on `Samsung Galaxy S6` at API level `25`

Unfortunately I haven't been able to reproduce on emulator.

**Comment by domdomegg** [comment]
Another log

```
2018-12-19 00:06:33.103 22588-22588/fr.free.nrw.commons E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons
    java.lang.NullPointerException: Attempt to read from field 'boolean fr.free.nrw.commons.nearby.NearbyMapFragment.searchThisAreaModeOn' on a null object reference
        at fr.free.nrw.commons.nearby.NearbyFragment.updateMapFragment(NearbyFragment.java:432)
        at fr.free.nrw.commons.nearby.NearbyFragment.refreshView(NearbyFragment.java:319)
        at fr.free.nrw.commons.nearby.NearbyFragment.onLocationChangedSlightly(NearbyFragment.java:226)
        at fr.free.nrw.commons.location.LocationServiceManager.onLocationChanged(LocationServiceManager.java:277)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
        at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by domdomegg** [comment]
Another log. Still no closer to finding out the circumstances needed to trigger crash.

It's not flaky internet though, because I had an extremely strong connection when this happened. Makes me suspect flaky GPS sensor data?

```
2018-12-19 19:06:58.973 30364-30364/fr.free.nrw.commons E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons
    java.lang.NullPointerException: Attempt to read from field 'boolean fr.free.nrw.commons.nearby.NearbyMapFragment.searchThisAreaModeOn' on a null object reference
        at fr.free.nrw.commons.nearby.NearbyFragment.updateMapFragment(NearbyFragment.java:449)
        at fr.free.nrw.commons.nearby.NearbyFragment.refreshView(NearbyFragment.java:321)
        at fr.free.nrw.commons.nearby.NearbyFragment.onLocationChangedSlightly(NearbyFragment.java:228)
        at fr.free.nrw.commons.location.LocationServiceManager.onLocationChanged(LocationServiceManager.java:277)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
        at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
