### ISSUE TITLE
Nearby map does not load and throws error

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#2168]
**Summary:** 

Nearby map doesn't load (just appears grey)

**Steps to reproduce:** 

How can we reproduce the issue?
- Seems to pretty consistently happen for me whenever I open nearby tab

What did you expect the app to do, and what did you see instead?
Expected: Show me a map
Actual: Shows grey screen (but location loads as list works)

**System logs:**

Able to recreate in `2.9.0-debug-master~46db38b8` on `Galaxy Nexus (emulator)` at API levels `23`, `25` and `28`.

Similar logs seem to have happened before, see https://github.com/commons-app/apps-android-commons/issues/1480#issuecomment-396300543 and https://github.com/commons-app/apps-android-commons/issues/1480#issuecomment-408604591

API level 23:

```
12-19 00:12:00.540 20614-20614/fr.free.nrw.commons E/FileSource: Failed to read the storage key: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
        at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:69)
        at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:48)
        at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:349)
        at fr.free.nrw.commons.nearby.NearbyMapFragment.onStart(NearbyMapFragment.java:990)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

API level 25:

```
2018-12-18 23:54:00.833 4000-4000/fr.free.nrw.commons E/FileSource: Failed to read the storage key: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.BaseBundle.getBoolean(java.lang.String, boolean)' on a null object reference
        at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:69)
        at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:48)
        at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:349)
        at fr.free.nrw.commons.nearby.NearbyMapFragment.onStart(NearbyMapFragment.java:990)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

```
2018-12-18 23:56:17.810 6686-6686/fr.free.nrw.commons E/FileSource: Failed to read the storage key: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.BaseBundle.getBoolean(java.lang.String, boolean)' on a null object reference
        at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:69)
        at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:48)
        at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:349)
        at fr.free.nrw.commons.nearby.NearbyMapFragment.onStart(NearbyMapFragment.java:990)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

API level 28:

```
2018-12-18 23:56:50.742 17126-17126/fr.free.nrw.commons E/FileSource: Failed to read the storage key: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
        at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:69)
        at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:48)
        at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:349)
        at fr.free.nrw.commons.nearby.NearbyMapFragment.onStart(NearbyMapFragment.java:990)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
2018-12-18 23:57:42.131 17284-17284/fr.free.nrw.commons E/FileSource: Failed to read the storage key: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
        at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:69)
        at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:48)
        at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:349)
        at fr.free.nrw.commons.nearby.NearbyMapFragment.onStart(NearbyMapFragment.java:990)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**GIF:** 

![blankmap](https://user-images.githubusercontent.com/4953590/50190604-caa31400-0321-11e9-8e13-b5da4516677c.gif)

**Comment by nicolas-raoul** [comment]
Strange, the map shows normally for me with 2.9.0.114

**Comment by misaochan** [comment]
I get the same issue with my emulator, too. To the best of my knowledge, this is an issue for some emulators, and no one has reproduced it with a real device.
