### ISSUE TITLE
Crash on retry

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2256]
```
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=2.9.0.140
BRAND=google
PHONE_MODEL=Nexus 5
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'void fr.free.nrw.commons.upload.UploadService.queue(int, fr.free.nrw.commons.contributions.Contribution)' on a null object reference
at fr.free.nrw.commons.contributions.ContributionsListAdapter.retryUpload(ContributionsListAdapter.java:116)
at fr.free.nrw.commons.contributions.ContributionsListAdapter$1.onClick(ContributionsListAdapter.java:92)
at android.view.View.performClick(View.java:5637)
at android.view.View$PerformClick.run(View.java:22433)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by sp2710** [comment]
I would like to work on this

**Comment by nicolas-raoul** [comment]
```
USER_COMMENT=retry
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=2.9.0.155
BRAND=google
PHONE_MODEL=Nexus 5
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'void fr.free.nrw.commons.upload.UploadService.queue(int, fr.free.nrw.commons.contributions.Contribution)' on a null object reference
at fr.free.nrw.commons.contributions.ContributionsListAdapter.retryUpload(ContributionsListAdapter.java:116)
at fr.free.nrw.commons.contributions.ContributionsListAdapter$1.onClick(ContributionsListAdapter.java:92)
at android.view.View.performClick(View.java:5637)
at android.view.View$PerformClick.run(View.java:22433)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by nicolas-raoul** [comment]
I did not try sp2710's code, but I just wanted to mention that the issue reproduces always.

**Comment by maskaravivek** [comment]
Yes its reproducible for me as well. Just a note for anyone picking this issue, ensure that the `Contribution` is not `null` at any point in time. Before retrying `Contribution` is again fetched from the DAO and the retry is attempted. 

Also, it seems some refactoring needs to be done for the `Adapter` layer and too many interactions with the DAO layer should be avoided. If we move to `RecyclerView` and `ViewHolder` pattern, we can avoid a lot of unnecessary complexity in the lists.

`CategoryImagesActivity` can be reused to some extent for writing the `ContributionsListFragment` as both deal with the same `Media` object and just a few things happen differently.
