### ISSUE TITLE
Hide details of failed upload? Or fix them?

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2311]
A failed upload happens when for instance Internet cuts in the middle of an upload.
In such cases, the image appears as a "failed" item in the home activity.

Unlike other images, tapping on this failed upload does not show the image's details activity. I guess this is intended?
Problem: If you tap the next unfailed image and swipe left, you can reach the failed image's details.

# Solution 1

Fix the details activity so that it shows correct information for a failed upload (for instance I believe the categories are stored so that they can be used when retrying?), and make it accessible by tap in the home activity, like all other images. Also, remove its download/share/date/copy/delete fields and all other fields that are not relevant.

# Solution 2

Make the the details of the failed image not accessible via swipe or any other mean.

**Comment by sp2710** [comment]
Is anyone working on this issue?

**Comment by nicolas-raoul** [comment]
@ShridharGoel Let's go with solution 1. Are you still motivated to work on it? :-)

**Comment by ShridharGoel** [comment]
Yes, definitely! :)

**Comment by nicolas-raoul** [comment]
@ShridharGoel  Assigned to you :-)

**Comment by vanshikaarora** [comment]
@ShridharGoel  Are you still working on this Issue or Shall I take this up?

**Comment by ShridharGoel** [comment]
@vanshikaarora Feel free to work on this.

**Comment by vanshikaarora** [comment]
Thanks @ShridharGoel :)

**Comment by ShridharGoel** [comment]
You're welcome @vanshikaarora :)

**Comment by domdomegg** [comment]
Reopening as not fully solved, still doesn't display all the details we could.

**Comment by vanshikaarora** [comment]
>Reopening as not fully solved, still doesn't display all the details we could.

Sorry for not seeing this before. I just checked issue with failed images is here (probably incorrect parsing of API response)

```
java.io.IOException: org.xml.sax.SAXParseException: Unexpected end of document
        at fr.free.nrw.commons.MediaDataExtractor.processWikiParseTree(MediaDataExtractor.java:119)
        at fr.free.nrw.commons.MediaDataExtractor.fetch(MediaDataExtractor.java:84)
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:290)
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:275)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: org.xml.sax.SAXParseException: Unexpected end of document
        at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
        at fr.free.nrw.commons.MediaDataExtractor.processWikiParseTree(MediaDataExtractor.java:115)
        at fr.free.nrw.commons.MediaDataExtractor.fetch(MediaDataExtractor.java:84) 
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:290) 
        at fr.free.nrw.commons.media.MediaDetailFragment$3.doInBackground(MediaDetailFragment.java:275) 
        at android.os.AsyncTask$2.call(AsyncTask.java:304) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762) 
```

Since the previous PR is already merged shall I work on a different PR for this?

**Comment by neslihanturan** [comment]
Please open another PR @vanshikaarora :)
