### ISSUE TITLE
App crashes when trying to upload or download media without internet connectivity

### ISSUE THREAD

**Issue by ShridharGoel** [commons-app/apps-android-commons#2312]
**Summary:** 

App crashes after Step 1 of upload if internet is not connected. It also crashes when trying to download from media details fragment. 

**Steps to reproduce:** 

1. Turn off the internet connection.
2. Try uploading a picture.
3. App will crash when "Next" is pressed on Step 1.
4. Try downloading a picture without connecting to the internet.
5. App will crash.

**System logs:**

```
2019-01-17 17:11:18.981 13703-13741/fr.free.nrw.commons.beta W/System.err: java.net.UnknownHostException: Unable to resolve host "commons.wikimedia.beta.wmflabs.org": No address associated with hostname
2019-01-17 17:11:18.981 13703-13703/fr.free.nrw.commons.beta D/AccessibilityManager: current package=fr.free.nrw.commons.beta, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:752)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:361)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at in.yuvi.http.fluent.Http$HttpRequestBuilder.asResponse(Http.java:470)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.CustomApiResult.fromRequestBuilder(CustomApiResult.java:43)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.CustomMwApi.makeRequest(CustomMwApi.java:177)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.CustomMwApi.access$000(CustomMwApi.java:18)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.CustomMwApi$RequestBuilder.get(CustomMwApi.java:34)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.isUserBlockedFromCommons(ApacheHttpClientMediaWikiApi.java:959)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.auth.AuthenticatedActivity.lambda$showBlockStatus$0$AuthenticatedActivity(AuthenticatedActivity.java:63)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.auth.AuthenticatedActivity$$Lambda$0.call(Unknown Source)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
2019-01-17 17:11:18.982 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at com.tspoon.traceur.ObservableOnAssemblyCallable.subscribeActual(ObservableOnAssemblyCallable.java:42)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12030)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-01-17 17:11:18.983 13703-13741/fr.free.nrw.commons.beta W/System.err:     at java.lang.Thread.run(Thread.java:760)
```

**Device and Android version:** 

Android version 7.1.2 (API 25) 

**Would you like to work on the issue?**

Yes

**Comment by maskaravivek** [comment]
When the app is not connected to internet some other features make the app crash too. You might consider add graceful handling for other features as well. For eg. download button in media details crashes the app when offline

**Comment by ShridharGoel** [comment]
So, should I look for the same problem in other places too and fix them together in a single PR?

**Comment by maskaravivek** [comment]
Yes, you can submit a single PR if you are simply handling the corner cases and not adding any new functionality. The issue can be renamed to include more such cases.
