### ISSUE TITLE
Crash if Japanese locale

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2330]
**Steps to reproduce:** 

1. Change Android's locale to Japanese
2. Open app
3. Immediate crash

**System logs:**

```
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=2.9.0.173
BRAND=google
PHONE_MODEL=Nexus 5
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:325)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.util.UnknownFormatConversionException: Conversion = 'さ'
at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2730)
at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2759)
at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2591)
at java.util.Formatter.parse(Formatter.java:2524)
at java.util.Formatter.format(Formatter.java:2472)
at java.util.Formatter.format(Formatter.java:2426)
at java.lang.String.format(String.java:2626)
at fr.free.nrw.commons.notification.NotificationUtils.getMentionMessage(NotificationUtils.java:216)
at fr.free.nrw.commons.notification.NotificationUtils.getNotificationFromApiResult(NotificationUtils.java:150)
at fr.free.nrw.commons.notification.NotificationUtils.getNotificationsFromList(NotificationUtils.java:100)
at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.getNotifications(ApacheHttpClientMediaWikiApi.java:607)
at fr.free.nrw.commons.notification.NotificationController.getNotifications(NotificationController.java:30)
at fr.free.nrw.commons.notification.UnreadNotificationsCheckAsync.doInBackground(UnreadNotificationsCheckAsync.java:34)
at fr.free.nrw.commons.notification.UnreadNotificationsCheckAsync.doInBackground(UnreadNotificationsCheckAsync.java:18)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
java.util.UnknownFormatConversionException: Conversion = 'さ'
at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2730)
at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2759)
at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2591)
at java.util.Formatter.parse(Formatter.java:2524)
at java.util.Formatter.format(Formatter.java:2472)
at java.util.Formatter.format(Formatter.java:2426)
at java.lang.String.format(String.java:2626)
at fr.free.nrw.commons.notification.NotificationUtils.getMentionMessage(NotificationUtils.java:216)
at fr.free.nrw.commons.notification.NotificationUtils.getNotificationFromApiResult(NotificationUtils.java:150)
at fr.free.nrw.commons.notification.NotificationUtils.getNotificationsFromList(NotificationUtils.java:100)
at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.getNotifications(ApacheHttpClientMediaWikiApi.java:607)
at fr.free.nrw.commons.notification.NotificationController.getNotifications(NotificationController.java:30)
at fr.free.nrw.commons.notification.UnreadNotificationsCheckAsync.doInBackground(UnreadNotificationsCheckAsync.java:34)
at fr.free.nrw.commons.notification.UnreadNotificationsCheckAsync.doInBackground(UnreadNotificationsCheckAsync.java:18)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by whym** [comment]
It looks like it was an error in the localized message. Hopefully this will fix it: https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-notifications_mention/ja&diff=8603506&oldid=8078028

By the way, did it happen in the released app?

**Comment by nicolas-raoul** [comment]
@whym Thanks for the investigation and fix!
Wow that's a long time ago! Hopefully it only happened to the minority(?) of users who get mentioned in discussions.

**Comment by nicolas-raoul** [comment]
Closing for now, in that happens again after the translatewiki update I will reopen.
