### ISSUE TITLE
On changing orientation on nearby map is not able to load

### ISSUE THREAD

**Issue by sp2710** [commons-app/apps-android-commons#2368]
**Steps to reproduce:** 

Change orientation on nearby

**What was expected**
Map should be visible in different orientation

**What happened instead**
Map is not visible and loading never finishes

**System logs:**

>2019-01-29 04:06:57.450 4881-4881/fr.free.nrw.commons.beta E/ActivityThread: Activity fr.free.nrw.commons.contributions.MainActivity has leaked ServiceConnection fr.free.nrw.commons.contributions.ContributionsFragment$1@a1b3798 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity fr.free.nrw.commons.contributions.MainActivity has leaked ServiceConnection fr.free.nrw.commons.contributions.ContributionsFragment$1@a1b3798 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
        at android.app.ContextImpl.bindService(ContextImpl.java:1422)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
        at fr.free.nrw.commons.contributions.ContributionsFragment.onAuthCookieAcquired(ContributionsFragment.java:360)
        at fr.free.nrw.commons.contributions.ContributionsFragment.onAttach(ContributionsFragment.java:224)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1372)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:19759)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19759)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19759)
        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1059)
        at android.view.View.measure(View.java:19759)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:19759)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19759)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19759)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19759)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
        at android.view.View.measure(View.java:19759)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2283)
    	at android.view.ViewRootImpl.measureH

**Device and Android version:** 

Motorola Moto G5 plus on Api 24
 
**Commons app version:** 

Latest master

**Would you like to work on the issue?**

Yes

**Comment by nicolas-raoul** [comment]
In "Steps to reproduce" please add:

- What was expected
- What happened instead

Thanks!

**Comment by sp2710** [comment]
Done :)

**Comment by nicolas-raoul** [comment]
I can reproduce the problem. Thanks for handling it @sp2710 :-)

**Comment by sp2710** [comment]
@nicolas-raoul I found out that the logs that i had posted are indicating memory leaks issue.
On changing orientation not loading of nearby map is a different issue which i had resolved.

**Comment by sp2710** [comment]
Should I send a PR for this issue and make new issue for this memory leak issue?

**Comment by nicolas-raoul** [comment]
Yes thanks 🙂

Shubham Pinjwani <notifications@github.com> 於 2019年1月29日 週二 21:49寫道：

**Comment by sp2710** [comment]
@nicolas-raoul I have submitted the PR for this and have also opened the new issue for memory leak:)
