### ISSUE TITLE
Crash while uploading images

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2459]
**Summary:** 

We have received a lot of crash reports for 2.10.0. 

**System logs:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.Date.toString()' on a null object reference
at fr.free.nrw.commons.mwapi.UploadResult.toString(UploadResult.java:42)
at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:251)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:134)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:42)
at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:26)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:198)
at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Commons app version:** 

2.10.0

**Would you like to work on the issue?**

Yes

**Comment by aniketnath** [comment]
I have solved the issue
