### ISSUE TITLE
Crash due to contribution dao in 2.10

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2476]
**Summary:** 

We have received a couple of crash reports pointing to some issue with the `ContributionDao`. 
**Steps to reproduce:** 

How can we reproduce the issue? 

Upgrading the app from previous release versions might help in reproducing the issue. 

**System logs:**

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.sqlite.SQLiteException: no such column: wikidataEntityID (code 1): , while compiling: SELECT _id, filename, local_uri, image_url, timestamp, state, length, uploaded, transferred, source, description, creator, multiple, width, height, license, wikidataEntityID FROM contributions ORDER BY state DESC, uploaded DESC , (timestamp * state)LIMIT 100
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
(no such column: wikidataEntityID (code 1): , while compiling: SELECT _id, filename, local_uri, image_url, timestamp, state, length, uploaded, transferred, source, description, creator, multiple, width, height, license, wikidataEntityID FROM contributions ORDER BY state DESC, uploaded DESC , (timestamp * state)LIMIT 100)
#################################################################
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1095)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:660)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1739)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:399)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
at fr.free.nrw.commons.contributions.ContributionsContentProvider.query(ContributionsContentProvider.java:57)
at android.content.ContentProvider.query(ContentProvider.java:1063)
at android.content.ContentProvider.query(ContentProvider.java:1155)
at android.content.ContentProvider$Transport.query(ContentProvider.java:244)
at android.content.ContentResolver.query(ContentResolver.java:760)
at android.content.ContentResolver.query(ContentResolver.java:710)
at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:61)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:39)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 3 more
android.database.sqlite.SQLiteException: no such column: wikidataEntityID (code 1): , while compiling: SELECT _id, filename, local_uri, image_url, timestamp, state, length, uploaded, transferred, source, description, creator, multiple, width, height, license, wikidataEntityID FROM contributions ORDER BY state DESC, uploaded DESC , (timestamp * state)LIMIT 100
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
(no such column: wikidataEntityID (code 1): , while compiling: SELECT _id, filename, local_uri, image_url, timestamp, state, length, uploaded, transferred, source, description, creator, multiple, width, height, license, wikidataEntityID FROM contributions ORDER BY state DESC, uploaded DESC , (timestamp * state)LIMIT 100)
#################################################################
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1095)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:660)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1739)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:399)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
at fr.free.nrw.commons.contributions.ContributionsContentProvider.query(ContributionsContentProvider.java:57)
at android.content.ContentProvider.query(ContentProvider.java:1063)
at android.content.ContentProvider.query(ContentProvider.java:1155)
at android.content.ContentProvider$Transport.query(ContentProvider.java:244)
at android.content.ContentResolver.query(ContentResolver.java:760)
at android.content.ContentResolver.query(ContentResolver.java:710)
at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:61)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:39)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)```

**Commons app version:** 

2.10.0

**Comment by misaochan** [comment]
USER_COMMENT=just tried opening the app
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=2.10.1
BRAND=google
PHONE_MODEL=Nexus 5
CUSTOM_DATA=
```
STACK_TRACE=java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: android.database.sqlite.SQLiteException: no such column: wikidataEntityID (code 1): , while compiling: SELECT _id, filename, local_uri, image_url, timestamp, state, length, uploaded, transferred, source, description, creator, multiple, width, height, license, wikidataEntityID FROM contributions ORDER BY state DESC, uploaded DESC , (timestamp * state)LIMIT 100
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:419)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:296)
at fr.free.nrw.commons.contributions.ContributionsContentProvider.query(ContributionsContentProvider.java:57)
at android.content.ContentProvider.query(ContentProvider.java:1022)
at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
at android.content.ContentResolver.query(ContentResolver.java:534)
at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:61)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:39)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
android.database.sqlite.SQLiteException: no such column: wikidataEntityID (code 1): , while compiling: SELECT _id, filename, local_uri, image_url, timestamp, state, length, uploaded, transferred, source, description, creator, multiple, width, height, license, wikidataEntityID FROM contributions ORDER BY state DESC, uploaded DESC , (timestamp * state)LIMIT 100
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:419)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:296)
at fr.free.nrw.commons.contributions.ContributionsContentProvider.query(ContributionsContentProvider.java:57)
at android.content.ContentProvider.query(ContentProvider.java:1022)
at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
at android.content.ContentResolver.query(ContentResolver.java:534)
at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:61)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:39)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```
