### ISSUE TITLE
Fix NullPointerException when uploading file failed

### ISSUE THREAD

**Issue by zhao-gang** [commons-app/apps-android-commons#2480]
**Summary:** 

The related PR fixes a NullPointerException when uploading file failed.

**Steps to reproduce:** 

When uploading a file failed due to server is in readonly mode, the response does not contain property dateUploaded and this causes class UploadResult.toString() throws NullPointerException.

**System logs:**

```
2019-02-17 10:28:39.271 12764-12801/fr.free.nrw.commons.beta D/CustomApiResult: API response for method uploadFile is
     <?xml version="1.0" encoding="UTF-8"?><api servedby="deployment-mediawiki-09"><error code="readonly" info="The wiki is currently in read-only mode." readonlyreason="The database has been automatically locked while the replica database servers catch up to the master." xml:space="preserve">See https://commons.wikimedia.beta.wmflabs.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &amp;lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&amp;gt; for notice of API deprecations and breaking changes.</error></api>
2019-02-17 10:28:39.273 12764-12801/fr.free.nrw.commons.beta D/ApacheHttpClientMediaWikiApi: Result: fr.free.nrw.commons.mwapi.CustomApiResult@6fb4331
2019-02-17 10:28:39.284 12764-12801/fr.free.nrw.commons.beta E/ApacheHttpClientMediaWikiApi: readonly
2019-02-17 10:28:39.286 12764-12801/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: UploadService
    Process: fr.free.nrw.commons.beta, PID: 12764
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.Date.toString()' on a null object reference
        at fr.free.nrw.commons.mwapi.UploadResult.toString(UploadResult.java:42)
        at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:251)
        at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:134)
        at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:42)
        at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:26)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-02-17 10:28:39.288 12764-12801/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.Date.toString()' on a null object reference
        at fr.free.nrw.commons.mwapi.UploadResult.toString(UploadResult.java:42)
        at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:251)
        at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:134)
        at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:42)
        at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:26)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Device and Android version:** 

Unrelated
 
**Commons app version:** 

master betaDebug

**Screen-shots:** 

Not needed

**Would you like to work on the issue?**

Yes

**Comment by zhao-gang** [comment]
Oh. I just found it's already fixed in 2.10 branch. But not in master yet. So I'd better Close this issue.
