### ISSUE TITLE
NPE at UploadResult.toString (v2.10.0)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2486]
USER_COMMENT=Stavo caricando un'immagine (translation: "I was uploading an image")
ANDROID_VERSION=8.1.0
APP_VERSION_NAME=2.10.0
BRAND=samsung
PHONE_MODEL=SM-J710F
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.Date.toString()' on a null object reference
at fr.free.nrw.commons.mwapi.UploadResult.toString(UploadResult.java:42)
at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:251)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:134)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:42)
at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:26)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by maskaravivek** [comment]
This is already fixed. #2480
