### ISSUE TITLE
Newly uploaded picture replacing some of the other pics (in My Uploads page)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#25]
After uploading a new picture, occasionally the new pic replaces some of the other pics in the list. Scrolling up and down past the replaced pic sometimes changes it back to the original, but sometimes not. Clicking on the replaced pic to go to the details still takes you to the correct page with the original pic. 

Issue is found from version 17 of the app onwards (release version), however I haven't tried the previous versions.

I've uploaded screenshots of the problem. It's a bit hard to see, but the first screenshot is of the new upload (French onion soup), and the second is of the pic further down the list (Hobbiton) that gets replaced by french onion soup.

![screenshot_2015-10-29-01-22-36](https://cloud.githubusercontent.com/assets/3611199/10788485/c2152f44-7ddc-11e5-9ae3-a293885f856e.png)
![screenshot_2015-10-29-01-30-00](https://cloud.githubusercontent.com/assets/3611199/10788487/c41b5066-7ddc-11e5-8db6-b192b7485612.png)

**Comment by misaochan** [comment]
Not sure if relevant to this bug, but when I scroll through the pics I get these errors on logcat:

```
06-18 19:03:26.769: E/ImageLoader(2725): Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A55 from pid=2725, uid=10058 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
06-18 19:03:26.769: E/ImageLoader(2725): java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A55 from pid=2725, uid=10058 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.os.Parcel.readException(Parcel.java:1599)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromContent(BaseImageDownloader.java:156)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(BaseImageDecoder.java:84)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:70)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:290)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:250)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:131)
06-18 19:03:26.769: E/ImageLoader(2725): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-18 19:03:26.769: E/ImageLoader(2725): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-18 19:03:26.769: E/ImageLoader(2725): 	at java.lang.Thread.run(Thread.java:818)
06-18 19:03:26.769: E/DatabaseUtils(2032): Writing exception to parcel
06-18 19:03:26.769: E/DatabaseUtils(2032): java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A53 from pid=2725, uid=10058 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
06-18 19:03:26.769: E/DatabaseUtils(2032): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
06-18 19:03:26.769: E/DatabaseUtils(2032): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
06-18 19:03:26.769: E/DatabaseUtils(2032): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:471)
06-18 19:03:26.769: E/DatabaseUtils(2032): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:416)
06-18 19:03:26.769: E/DatabaseUtils(2032): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:313)
06-18 19:03:26.769: E/DatabaseUtils(2032): 	at android.os.Binder.execTransact(Binder.java:453)
06-18 19:03:26.769: E/ImageLoader(2725): Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A53 from pid=2725, uid=10058 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
06-18 19:03:26.769: E/ImageLoader(2725): java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A53 from pid=2725, uid=10058 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.os.Parcel.readException(Parcel.java:1599)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
06-18 19:03:26.769: E/ImageLoader(2725): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStreamFromContent(BaseImageDownloader.java:156)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.download.BaseImageDownloader.getStream(BaseImageDownloader.java:88)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.getImageStream(BaseImageDecoder.java:84)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:70)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:290)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:250)
06-18 19:03:26.769: E/ImageLoader(2725): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:131)
06-18 19:03:26.769: E/ImageLoader(2725): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-18 19:03:26.769: E/ImageLoader(2725): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-18 19:03:26.769: E/ImageLoader(2725): 	at java.lang.Thread.run(Thread.java:818)
```

And so on and so forth for each image scrolled through. I suppose I'll try and fix those errors first and see if this bug clears up.

**Comment by misaochan** [comment]
Well, fixed the error message, but that doesn't solve this problem. :/

**Comment by nicolas-raoul** [comment]
Just happened to me too.
Two pictures I uploaded a few weeks ago have their miniature replaced with the miniature of a picture I took an hour ago.

**Comment by misaochan** [comment]
Yeah, I haven't had any luck fixing this, spent quite many hours on it already and had to move on. :(

**Comment by lekseys** [comment]
Waiting for fix

**Comment by misaochan** [comment]
Interesting. With the new fixes, the picture now changes constantly during the final phase of the progress bar, lol. @veyndan , do you think this could be related to #355 ? Not saying your patch was at fault, this issue already existed previously, just made more obvious now. I'm asking so that we can try and drill down to figure out what is causing the issue.

**Comment by veyndan** [comment]
It shouldn't have anything to do with that commit. Most of that PR was removing unused code, and the only change is that `@style/AppTheme` now extends `Theme.AppCompat`. As this is a stylistic change, there should be no difference in the logic of the app. Even if it could some how change it, my PR still shouldn't have affected the images screen as in the `AndroidManifest.xml` the theme has always extended from `Theme.AppCompat` directly. So to conclude, the changes in #355 are only stylistic and only affects `LoginActivity` and `WelcomeActivity` (as is evident from the manifest file).

**Comment by misaochan** [comment]
Thanks for clarifying, @veyndan . Will keep looking.

**Comment by misaochan** [comment]
This appears to have been fixed as a nice side effect of one of @dbrant 's PRs. :) Feel free to reopen if anyone is still experiencing this.
