### ISSUE TITLE
NPE on bookmark while pic from explore still loading (slow internet)

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2652]
**Summary:** 
From crash report of @nicolas-raoul , seems like an easy one.
```
USER_COMMENT=bookmark while pic from explore still loading (slow internet)
ANDROID_VERSION=7.1.2
APP_VERSION_NAME=2.10.1.306
BRAND=google
PHONE_MODEL=Nexus 5
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String fr.free.nrw.commons.bookmarks.Bookmark.getMediaName()' on a null object reference
at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.findBookmark(BookmarkPicturesDao.java:131)
at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesDao.updateBookmark(BookmarkPicturesDao.java:72)
at fr.free.nrw.commons.media.MediaDetailPagerFragment.onOptionsItemSelected(MediaDetailPagerFragment.java:157)
at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2588)
at androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManagerImpl.java:2704)
at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:400)
at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:377)
at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:197)
at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204)
at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
at android.view.View.performClick(View.java:5637)
at android.view.View$PerformClick.run(View.java:22433)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by oluwadara-abijo** [comment]
@neslihanturan Can I take this?

**Comment by neslihanturan** [comment]
Yes, feel free @oluwadara-abijo

**Comment by oluwadara-abijo** [comment]
Hi @neslihanturan 
I could not reproduce the issue

**Comment by neslihanturan** [comment]
This issue is taken from user reports, I also didn't experience this issue. @nicolas-raoul did. Maybe it can be good to ping him to get some help to reproduce.

**Comment by oluwadara-abijo** [comment]
> This issue is taken from user reports, I also didn't experience this issue. @nicolas-raoul did. Maybe it can be good to ping him to get some help to reproduce.

Alright then.
@nicolas-raoul can you help here?

**Comment by ashishkumar468** [comment]
@oluwadara-abijo The issue might not reproduce on your device, but is a simple case of NPE, ie. if the bookmark object itself is null, for example in MediaDetailPagerFragment where it is initialised separately and say the method findBookmark() is called before it is initialised. IMO having a look in the function could help you fix the bug

**Comment by nicolas-raoul** [comment]
I can't add more details than what my bug report already says, but if it happens again I will let you know.
As Ashish says, reading the stack trace and source code is the best way to find the problem :-)

**Comment by ashishkumar468** [comment]
As @oluwadara-abijo was away and the fix was really small, I have raised a PR for the same (so that it could go in 2.10 hotfix release).

**Comment by oluwadara-abijo** [comment]
> As @oluwadara-abijo was away and the fix was really small, I have raised a PR for the same (so that it could go in 2.10 hotfix release).

Okay then.
