### ISSUE TITLE
RuntimeException while uploading image if the license if invalid

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#2720]
**Summary:** 
While uploading a media, if the license is somehow invalid we throw a RuntimeException and as it is not handled, the app crashes

**Steps to reproduce:** 

How can we reproduce the issue? 
Provide invalid license while uploading image.

**System logs:**

```
java.lang.RuntimeException: Unable to resume activity {fr.free.nrw.commons/fr.free.nrw.commons.upload.UploadActivity}: java.lang.RuntimeException: Unrecognized license value: CC BY-SA
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3421)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3461)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.RuntimeException: Unrecognized license value: CC BY-SA
at fr.free.nrw.commons.Utils.licenseUrlFor(Utils.java:135)
at fr.free.nrw.commons.upload.UploadActivity.updateLicenseSummary(UploadActivity.java:275)
at fr.free.nrw.commons.upload.UploadPresenter.updateLicenses(UploadPresenter.java:335)
at fr.free.nrw.commons.upload.UploadPresenter.addView(UploadPresenter.java:312)
at fr.free.nrw.commons.upload.UploadActivity.lambda$checkStoragePermissions$2$UploadActivity(UploadActivity.java:204)
at fr.free.nrw.commons.upload.UploadActivity$$Lambda$4.run(Unknown Source)
at fr.free.nrw.commons.utils.PermissionUtils$1.onPermissionGranted(PermissionUtils.java:77)
at com.karumi.dexter.MultiplePermissionsListenerToPermissionListenerAdapter.onPermissionsChecked(Unknown Source)
at com.karumi.dexter.DexterInstance$1.run(Unknown Source)
at com.karumi.dexter.MainThread.execute(Unknown Source)
at com.karumi.dexter.DexterInstance.checkMultiplePermissions(Unknown Source)
at com.karumi.dexter.DexterInstance.checkPermissions(Unknown Source)
at com.karumi.dexter.Dexter.check(Unknown Source)
at fr.free.nrw.commons.utils.PermissionUtils.checkPermissionsAndPerformAction(PermissionUtils.java:103)
at fr.free.nrw.commons.upload.UploadActivity.checkStoragePermissions(UploadActivity.java:202)
at fr.free.nrw.commons.upload.UploadActivity.onResume(UploadActivity.java:190)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
at android.app.Activity.performResume(Activity.java:6776)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3398)
... 10 more
java.lang.RuntimeException: Unrecognized license value: CC BY-SA
at fr.free.nrw.commons.Utils.licenseUrlFor(Utils.java:135)
at fr.free.nrw.commons.upload.UploadActivity.updateLicenseSummary(UploadActivity.java:275)
at fr.free.nrw.commons.upload.UploadPresenter.updateLicenses(UploadPresenter.java:335)
at fr.free.nrw.commons.upload.UploadPresenter.addView(UploadPresenter.java:312)
at fr.free.nrw.commons.upload.UploadActivity.lambda$checkStoragePermissions$2$UploadActivity(UploadActivity.java:204)
at fr.free.nrw.commons.upload.UploadActivity$$Lambda$4.run(Unknown Source)
at fr.free.nrw.commons.utils.PermissionUtils$1.onPermissionGranted(PermissionUtils.java:77)
at com.karumi.dexter.MultiplePermissionsListenerToPermissionListenerAdapter.onPermissionsChecked(Unknown Source)
at com.karumi.dexter.DexterInstance$1.run(Unknown Source)
at com.karumi.dexter.MainThread.execute(Unknown Source)
at com.karumi.dexter.DexterInstance.checkMultiplePermissions(Unknown Source)
at com.karumi.dexter.DexterInstance.checkPermissions(Unknown Source)
at com.karumi.dexter.Dexter.check(Unknown Source)
at fr.free.nrw.commons.utils.PermissionUtils.checkPermissionsAndPerformAction(PermissionUtils.java:103)
at fr.free.nrw.commons.upload.UploadActivity.checkStoragePermissions(UploadActivity.java:202)
at fr.free.nrw.commons.upload.UploadActivity.onResume(UploadActivity.java:190)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
at android.app.Activity.performResume(Activity.java:6776)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3398)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3461)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Device and Android version:** 

WUSER_COMMENT=
ANDROID_VERSION=7.0
BRAND=motorola
PHONE_MODEL=Moto G (4)
**Commons app version:** 
APP_VERSION_NAME=2.10.2

**Would you like to work on the issue?**
Yes

**Comment by ashishkumar468** [comment]
@maskaravivek @misaochan @neslihanturan @nicolas-raoul, The crash is because, license urls for "CC BY" & "CC BY-SA" is not handled. Does any one knows what url's need to be returned for these license names?

**Comment by misaochan** [comment]
The Upload Wizard uses https://creativecommons.org/licenses/by-sa/4.0/deed.en for CC BY SA 4.0, and https://creativecommons.org/licenses/by/4.0/deed.en for CC BY 4.0, so I think we can go with that. For 3.0 just replace the corresponding string in the URL.

**Comment by ashishkumar468** [comment]
@misaochan Thanks JO,  but the app already had the same for CC BY SA 4.0 and CC BY 4.0, the ones matching exactly "CC BY" & "CC BY-SA" are not there. Seems like they are deprecated. I was wondering if it will be okay to use the ones for CC BY SA 4.0, and CC BY 4.0 respectively ?

**Comment by misaochan** [comment]
I don't think there is a need for a "CC BY" & "CC BY-SA" license without any version number. The Upload Wizard only has 3.0 and 4.0 for these corresponding licenses, and CC0 (so 5 licenses in total). In fact I don't think there is even a legal definition for "CC BY" without a version? Let's ask @nicolas-raoul to confirm.

**Comment by nicolas-raoul** [comment]
"CC BY" & "CC BY-SA" are not valid license, they must not be applied to any of our uploads.

Was the image that triggered the RuntimeException uploaded from the app? Or from another tool?

**Comment by ashishkumar468** [comment]
> Was the image that triggered the RuntimeException uploaded from the app? Or from another tool?

I am not sure about that, the logs are not sufficient to conclude that, if they are not valid licenses, can we remove it from the list of valid license names from the license drop down shown in the upload?

**Comment by misaochan** [comment]
If the image is triggering the exception via UploadActivity, it would be uploaded via the app, right?

> if they are not valid licenses, can we remove it from the list of valid license names from the license drop down shown in the upload?

@ashishkumar468 I am not seeing "CC BY" or "CC BY SA" in the license drop down shown in step 3 of the upload at all. Do you see it? I only see the 5 options that are similar to upload wizard.

**Comment by ashishkumar468** [comment]
@misaochan We do not show it in the drop down, but the old images which are already licensed by them , the app needs to recognise with their license as well. Are we supposed to update the license of one of the defaults from the app or is there a better way to handle this ?

**Comment by ashishkumar468** [comment]
@misaochan  @nicolas-raoul I have probably found the root cause for the issue. For some of the users who have been using the app since a long time, the older licenses ("CC BY" & "CC BY-SA"), were most probably stored by the BasicKvStore which when being applied while upload used to throw a RuntimeException. I have added a PR for the same to remove the deprecated licenses and use the default one (CC_BY_SA_4 (the one used by the commons web app)). Please let me know if this needs to be improved.

**Comment by misaochan** [comment]
Makes sense. Thanks @ashishkumar468 . :) I'll close this issue now that your PR is merged.
