### ISSUE TITLE
App Crashes with IllegalStateException in ViewUtils

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#2789]
**Summary:** 

App Crashes with IllegalStateException in ViewUtils
**System logs:**

```
java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
at android.support.design.widget.Snackbar.make(Snackbar.java:137)
at android.support.design.widget.Snackbar.make(Snackbar.java:170)
at fr.free.nrw.commons.utils.ViewUtil.lambda$showShortSnackbar$0$ViewUtil(ViewUtil.java:28)
at fr.free.nrw.commons.utils.ViewUtil$$Lambda$0.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:152)
at android.app.ActivityThread.main(ActivityThread.java:5136)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
```

**Device and Android version:** 

ANDROID_VERSION=4.3
BRAND=ZTE
PHONE_MODEL=Z797C
CUSTOM_DATA=
 
**Commons app version:** 

APP_VERSION_NAME=2.10.2

**Comment by ashishkumar468** [comment]
No more reproducible, closing this one :)
