### ISSUE TITLE
Crash when back button pressed if NearbyList has not finished loading

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#283]
```
USER_COMMENT=gallery button then back
ANDROID_VERSION=6.0.1
APP_VERSION_NAME=1.30


BRAND=google
PHONE_MODEL=Nexus 5
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
at android.view.LayoutInflater.from(LayoutInflater.java:229)
at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:178)
at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:163)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAdapter.<init>(NearbyListFragment.java:178)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAsyncTask.onPostExecute(NearbyListFragment.java:143)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAsyncTask.onPostExecute(NearbyListFragment.java:112)

at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

```
USER_COMMENT=trying to post a picture of the weather in Nigeria
ANDROID_VERSION=5.1
APP_VERSION_NAME=1.31
BRAND=itel
PHONE_MODEL=itel it1506
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at fr.free.nrw.commons.nearby.NearbyListFragment.loadAttractionsFromLocation(NearbyListFragment.java:308)
at fr.free.nrw.commons.nearby.NearbyListFragment.access$300(NearbyListFragment.java:27)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAsyncTask.doInBackground(NearbyListFragment.java:134)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAsyncTask.doInBackground(NearbyListFragment.java:112)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at fr.free.nrw.commons.nearby.NearbyListFragment.loadAttractionsFromLocation(NearbyListFragment.java:308)
at fr.free.nrw.commons.nearby.NearbyListFragment.access$300(NearbyListFragment.java:27)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAsyncTask.doInBackground(NearbyListFragment.java:134)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAsyncTask.doInBackground(NearbyListFragment.java:112)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by misaochan** [comment]
@tobias47n9e , just checking - did you press back before NearbyList had finished loading, in the minute or so prior to the crash? I'm still trying to ascertain the cause of these.

```
USER_COMMENT=?


ANDROID_VERSION=6.0
APP_VERSION_NAME=1.31
BRAND=HUAWEI
PHONE_MODEL=HUAWEI VNS-L31
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
at android.view.LayoutInflater.from(LayoutInflater.java:234)

at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:178)
at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:163)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAdapter.<init>(NearbyListFragment.java:178)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAsyncTask.onPostExecute(NearbyListFragment.java:143)
at fr.free.nrw.commons.nearby.NearbyListFragment$NearbyAsyncTask.onPostExecute(NearbyListFragment.java:112)
at android.os.AsyncTask.finish(AsyncTask.java:679)
at android.os.AsyncTask.access$500(AsyncTask.java:180)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:696)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5639)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
```

**Comment by tobias47n9e** [comment]
You probably got.a few emails from me. As I was trying to pinpoint the crash. It doesn't happen every time but it happens as you said when pressing the back-button while the nearby list loads.

**Comment by misaochan** [comment]
Ah, okay, thanks. Yeah, I've been trying to fix this issue, but it hasn't been a straightforward fix.

**Comment by VojtechDostal** [comment]
In my case the app crashes everytime I am not connected to the Internet and click on Nearby.

**Comment by misaochan** [comment]
Hi @VojtechDostal ,

Could you submit a crash report the next time that happens, please? I've been looking through the recent crash reports but can't seem to find yours.

**Comment by misaochan** [comment]
I can have the app check for network connectivity status before running NearbyPlaces, but that appears to require an additional permission (see http://stackoverflow.com/questions/2326767/how-do-you-check-the-internet-connection-in-android ). Do you guys think it would be worth it?

**Comment by nicolas-raoul** [comment]
How about just catching network-related exceptions?

**Comment by misaochan** [comment]
Oh, good idea! Do you think IOException will suffice to cover that?

**Comment by nicolas-raoul** [comment]
The best is to disable network them try, and see what exception comes.

**Comment by VojtechDostal** [comment]
Done. Did you receive the crash report?

**Comment by misaochan** [comment]
@nicolas-raoul Ah, good point, thanks.

@VojtechDostal I think so, thanks! Oddly it was sent via MMS though (and doesn't have your username on it), but I think it's yours. :)

**Comment by misaochan** [comment]
v1.33 has been released and should solve this problem, please do let me know if it doesn't fix it for you.

**Comment by VojtechDostal** [comment]
This prevents the crash. 

It keeps "loading" for eternity. Even if I reenable the network it does not find nearby places any more. 
![screenshot_2016-10-07-08-57-40](https://cloud.githubusercontent.com/assets/21329813/19182686/6b2751e0-8c6c-11e6-8a1e-ed33fb683317.png)

**Comment by misaochan** [comment]
@VojtechDostal The way the app works currently, it downloads the list of nearby places only the first time the list is opened (unless you close the app or it becomes inactive). When the list is opened for the second time, it just displays the places that have already been downloaded - this saves time for the users. I don't think it's possible for the app to reattempt the download when network connectivity is detected without requesting an extra permission to check network status. 

So I guess the question is, do you think granting the app the extra permission would be worth it? Do you often disable and re-enable your network connection while using the app?

**Comment by nicolas-raoul** [comment]
@VojtechDostal what happens if you perform the procedure below?
1. Disable network
2. Open Nearby
3. Go back to the main screen
4. Enable network
5. Open Nearby again
6. (Success or failure?)

**Comment by nicolas-raoul** [comment]
I just tested. No crash, but I can reproduce the problem reported by @VojtechDostal. It is different from the present issue, in such cases better create a new issue: #291

**Comment by VojtechDostal** [comment]
This is not a serious issue.

To me, the thing that really makes this thing difficult to use is the time it takes for the Nearby list to load. I have a quick connection here and it just takes several minutes!

**Comment by misaochan** [comment]
@VojtechDostal I agree that the file takes a long time to load. :( We are tentatively planning to switch to a WikiData API query in the future though (see #289 ), which would hopefully speed things up.

**Comment by VojtechDostal** [comment]
Let's meet and work on all these issues! :-) As I already mentioned, I think that the Vienna Hackathon (or any of the planned pre-hackathon events early next year) is a perfect opportunity.

**Comment by misaochan** [comment]
That sounds great. :) I don't know how the hackathons work, but would be more than happy to support it (and maybe try to show up if the date/venue/cost works out for me).

**Comment by VojtechDostal** [comment]
Well you are one of the most important people who should be there :-), without you it makes little sense. We can organize one of the pre-hackathon events in Prague for example - the city is cheap and we can provide scholarships for a small team. This would both speed up the improvements of this cool app and also build a community of open source programmers around it who would then hopefully continue working on it :)

**Comment by misaochan** [comment]
Is [this](http://www.gossamer-threads.com/lists/wiki/wikitech/691707) the  Vienna Hackathon that you mentioned? What's the difference between a pre-hackathon and a hackathon?

**Comment by VojtechDostal** [comment]
Yes that's it. I think @tobias47n9e should also be interested (he is a local!) but I am sure we can discuss this further somewhere else (I'll put together a place where we can start planning the event). 

This year's Wikimedia Hackathon will take place in May in Vienna but other countries are encouraged by the organizers to prepare small pre-events which would take place before the main event. Basically, you would be able to set up a team during the pre-hackathon, get to know each other and discuss things properly - and then we could meet again in Vienna and start proper work.

**Comment by misaochan** [comment]
Yes, please do. :) I have no idea what the protocol is for submitting our project for inclusion in the hackathon, but would love for it to happen.

I will see if there are scholarships available for me to attend - getting to Europe will be difficult/expensive for me as I'm based in NZ.
