### ISSUE TITLE
Achivements says you have no contributions while I have

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2975]
**Summary:** 
This happened on beta flavor, so if this is an expected behavior for achievements on beta please close this issue. Along with the wrong message an error exists on logs too.

**System logs:**

```
2019-06-01 15:41:18.197 1065-1065/fr.free.nrw.commons E/QuizChecker: Fetching feedback failed
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
        at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at fr.free.nrw.commons.mwapi.OkHttpJsonApiClient.lambda$getAchievements$2(OkHttpJsonApiClient.java:146)
        at fr.free.nrw.commons.mwapi.-$$Lambda$OkHttpJsonApiClient$e1yuTHfYTkBd47P3BZbbQnvFIto.call(Unknown Source:6)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

**Device and Android version:** 

API 26 emulator, 2.10.2-debug-refactorNearbyClassesMVP~008e1f632 which was my local work branch, it happens also on current master
 
**Commons app version:** 

betaDebug, currentMaster

**Screen-shots:** 
![image](https://user-images.githubusercontent.com/3127881/58748643-a6c52c00-8484-11e9-8dac-bf71e58c0be4.png)

**Comment by maskaravivek** [comment]
Even on beta flavour achievements are fetched for prod. If your beta and prod username is same then it should ideally show you prod statistics. 

From the logs it seems the API timed out. Was the username valid for prod?

**Comment by neslihanturan** [comment]
No it is not same user name. So th,is is not a bug anymore, but why even on beta we have achievements fro prod? Changing this would be easier for testing future issues on beta.

**Comment by maskaravivek** [comment]
Have opened an upstream issue.

**Comment by maskaravivek** [comment]
@urbanecm Has updated the APIs to make it work for the beta cluster as well. Am taking up the changes to start using the updated API for the beta cluster.
