### ISSUE TITLE
Crash everytime I try to start the app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2985]
After a multiple upload that failed on slow network.
```
APP_VERSION_CODE=243
APP_VERSION_NAME=2.10.2-debug-upload_caption_depict
ANDROID_VERSION=9
PHONE_MODEL=SM-G970F
STACK_TRACE=java.lang.NullPointerException: key == null
at androidx.collection.LruCache.get(LruCache.java:84)
at fr.free.nrw.commons.contributions.ContributionViewHolder.fetchAndDisplayThumbnail(ContributionViewHolder.java:107)
at fr.free.nrw.commons.contributions.ContributionViewHolder.bindModel(ContributionViewHolder.java:60)
at fr.free.nrw.commons.contributions.ContributionsListAdapter.bindView(ContributionsListAdapter.java:72)
at androidx.cursoradapter.widget.CursorAdapter.getView(CursorAdapter.java:274)
at android.widget.AbsListView.obtainView(AbsListView.java:3219)
at android.widget.GridView.makeAndAddView(GridView.java:1636)
at android.widget.GridView.makeRow(GridView.java:404)
at android.widget.GridView.fillDown(GridView.java:345)
at android.widget.GridView.fillFromTop(GridView.java:480)
at android.widget.GridView.layoutChildren(GridView.java:1463)
at android.widget.AbsListView.onLayout(AbsListView.java:2991)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)
at android.view.View.layout(View.java:22420)
at android.view.ViewGroup.layout(ViewGroup.java:6579)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3343)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2807)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1853)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8476)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
at android.view.Choreographer.doCallbacks(Choreographer.java:761)
at android.view.Choreographer.doFrame(Choreographer.java:696)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7032)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

IS_SILENT=false
USER_EMAIL=
USER_CRASH_DATE=2019-06-03T14:24:06.176+09:00
REPORT_ID=784e8694-45ac-47df-bf5d-766a1ff72c12
```

Not sure if due to gsoc2019 branch or not.

Workaround: Remove the app's data, in Android settings.

**Comment by ashishkumar468** [comment]
@nicolas-raoul Must have been reproduce due to some thing on the gsoc branch, but the class is somewhere un related to gsoc changes, I will anyways raise a PR on master for the fix of the same

**Comment by nicolas-raoul** [comment]
Fixed
