### ISSUE TITLE
[GSOC 2019] App crash while uploading the image

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#3022]
**Summary:** 

App crash on navigating to a different app while uploading an image. Don't now that it appears other times or not. But I'll go through it

```
E/ACRA: ACRA caught a IllegalStateException for fr.free.nrw.commons.beta
    java.lang.IllegalStateException: Failure saving state: active UploadMediaDetailFragment{49afb6e (a30d76d9-c80c-4da5-8418-952c2c6f0b74) id=0x7f09025c} was removed from the FragmentManager
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2315)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at android.app.Activity.performSaveInstanceState(Activity.java:1420)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1306)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4710)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4007)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4072)
        at android.app.ActivityThread.-wrap25(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1076)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
I/Process: Sending signal. PID: 21465 SIG: 9
Application terminated.

```

**Would you like to work on the issue?**

Yes

**Comment by ashishkumar468** [comment]
Is this happening on master as well ?

**Comment by vanshikaarora** [comment]
No it happened for me in branch `upload_caption_depict`

**Comment by ashishkumar468** [comment]
Ohh, please sync your branch with master, master already has a fix for this :-)
