### ISSUE TITLE
App Crashes while selecting depicts

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3033]
**Summary:** 

App crashes while selecting depicts

**System logs:**

```
    
    --------- beginning of crash
2019-06-23 11:10:05.336 14136-14136/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 14136
    java.lang.NullPointerException: Cannot return null from a non-@Nullable @Provides method
        at dagger.internal.Preconditions.checkNotNull(Preconditions.java:48)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.proxyProvideDepictsContentProviderClient(CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.java:35)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.get(CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.java:24)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.get(CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.java:10)
        at fr.free.nrw.commons.upload.structure.depicts.DepictDao.find(DepictDao.java:53)
        at fr.free.nrw.commons.upload.structure.depicts.DepictModel.updateDepictCount(DepictModel.java:125)
        at fr.free.nrw.commons.upload.structure.depicts.DepictModel.onDepictItemClicked(DepictModel.java:115)
        at fr.free.nrw.commons.repository.UploadRemoteDataSource.onDepictedItemClicked(UploadRemoteDataSource.java:193)
        at fr.free.nrw.commons.repository.UploadRepository.onDepictItemClicked(UploadRepository.java:270)
        at fr.free.nrw.commons.upload.depicts.DepictsPresenter.onDepictItemClicked(DepictsPresenter.java:52)
        at fr.free.nrw.commons.upload.depicts.DepictsFragment.depictsClicked(DepictsFragment.java:151)
        at fr.free.nrw.commons.upload.UploadDepictsRenderer.lambda$hookListeners$0$UploadDepictsRenderer(UploadDepictsRenderer.java:44)
        at fr.free.nrw.commons.upload.-$$Lambda$UploadDepictsRenderer$K3eBLW7UfOGyapHxVB_gzqCv74c.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-06-23 11:10:05.338 14136-14136/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Cannot return null from a non-@Nullable @Provides method
        at dagger.internal.Preconditions.checkNotNull(Preconditions.java:48)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.proxyProvideDepictsContentProviderClient(CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.java:35)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.get(CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.java:24)
        at fr.free.nrw.commons.di.CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.get(CommonsApplicationModule_ProvideDepictsContentProviderClientFactory.java:10)
        at fr.free.nrw.commons.upload.structure.depicts.DepictDao.find(DepictDao.java:53)
        at fr.free.nrw.commons.upload.structure.depicts.DepictModel.updateDepictCount(DepictModel.java:125)
        at fr.free.nrw.commons.upload.structure.depicts.DepictModel.onDepictItemClicked(DepictModel.java:115)
        at fr.free.nrw.commons.repository.UploadRemoteDataSource.onDepictedItemClicked(UploadRemoteDataSource.java:193)
        at fr.free.nrw.commons.repository.UploadRepository.onDepictItemClicked(UploadRepository.java:270)
        at fr.free.nrw.commons.upload.depicts.DepictsPresenter.onDepictItemClicked(DepictsPresenter.java:52)
        at fr.free.nrw.commons.upload.depicts.DepictsFragment.depictsClicked(DepictsFragment.java:151)
        at fr.free.nrw.commons.upload.UploadDepictsRenderer.lambda$hookListeners$0$UploadDepictsRenderer(UploadDepictsRenderer.java:44)
        at fr.free.nrw.commons.upload.-$$Lambda$UploadDepictsRenderer$K3eBLW7UfOGyapHxVB_gzqCv74c.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by vanshikaarora** [comment]
Fixed the issue in the latest [commit](https://github.com/commons-app/apps-android-commons/pull/2970/commits/4a6bb78a9d0339fa4764a53a8f85e59db1b552a4)
