### ISSUE TITLE
Achivements doesn't work 

### ISSUE THREAD

**Issue by PavelAplevich** [commons-app/apps-android-commons#3058]
I can't open achivements in my phone Redmi4x API 25 and emulator Nexus One API 22. 
I see this..
![Screenshot_1562567325](https://user-images.githubusercontent.com/52326878/60787699-5e73ea80-a163-11e9-8c82-a9270ff46aac.png)

Then this..
![Screenshot_1562567288](https://user-images.githubusercontent.com/52326878/60787724-6c297000-a163-11e9-8a79-b4dd76323127.png)

On my phone the situation is similar. Version 2.10.2

"Run" in android studio writes:

```
E/ComplexColorCompat: Failed to inflate ComplexColor.
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.Resources.getValue(Resources.java:1266)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2649)
        at android.content.res.Resources.getXml(Resources.java:1131)
        at androidx.core.content.res.ComplexColorCompat.createFromXml(ComplexColorCompat.java:152)
        at androidx.core.content.res.ComplexColorCompat.inflate(ComplexColorCompat.java:140)
        at androidx.core.content.res.TypedArrayUtils.getNamedComplexColor(TypedArrayUtils.java:150)
        at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VFullPath.updateStateFromTypedArray(VectorDrawableCompat.java:1921)
        at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat$VFullPath.inflate(VectorDrawableCompat.java:1887)
        at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflateInternal(VectorDrawableCompat.java:836)
        at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:723)
        at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:682)
        at androidx.appcompat.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:777)
        at androidx.appcompat.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:368)
        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
        at androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:59)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:187)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:107)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141)
        at fr.free.nrw.commons.achievements.AchievementsActivity.onCreate(AchievementsActivity.java:123)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCal
```

**Comment by nicolas-raoul** [comment]
I believe this was fixed a few hours ago :-)
Could you please:
1. [Install the alpha version](https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21#how-to-install-the-alpha)
2. Let us know whether that solve the issue
Thanks for your feedback!

**Comment by PavelAplevich** [comment]
I fork repo and run it in my AndroidStudio. I run 2.11 rep and master rep. I have error in this rep. 

I understand that achievements work on earlier versions? Or I did not understand you correctly?(

**Comment by nicolas-raoul** [comment]
It used to work, then broke, then the latest commit in master is supposed to fix this, if I understand correctly.
Could you please post a screenshot of your About screen? :-)

**Comment by PavelAplevich** [comment]
![Screenshot_1562575157](https://user-images.githubusercontent.com/52326878/60795809-0ba32e80-a175-11e9-9d51-878f9305c535.png)

This my about on emulator Nexus One. On real phone Redmi4x analogically

**Comment by nicolas-raoul** [comment]
If you were using the latest commit of the master repository, the number at the end of the version string should be fe540eb

Also, at https://github.com/PavelAplevich/apps-android-commons I see "This branch is 15 commits ahead, 4 commits behind commons-app:master"

So I guess you need to "git rebase" from the master repository.

Would you mind trying? Thanks! :-)

**Comment by PavelAplevich** [comment]
I do this steps:
1. Delete my repo and delete project in Android Studio and Git.
2. Fork commons-app and pull in Git. 
3. Run Android Studio
4. Run emulator Nexus One API 22 and see this  <1 second.
![Screenshot_1562583515](https://user-images.githubusercontent.com/52326878/60805483-e4565c80-a188-11e9-9cf0-ebfccc2365cb.png)
5. Then i see this
![Screenshot_1562583480](https://user-images.githubusercontent.com/52326878/60805503-f801c300-a188-11e9-93a6-6453d190e296.png)
6. If i trying go to achivements i see error too..


**Tell me what I'm doing wrong :(**

**Comment by nicolas-raoul** [comment]
You have the correct version now, and it seems that you have discovered a new bug haha :-)
To be sure, please go to the Android settings, delete all data of the Commons app, then try opening it again. If it crashes, please create a new issue.
Thanks a lot!

**Comment by neslihanturan** [comment]
Hi @PavelAplevich , I think your previous reported error can be related with previous version of the app as @nicolas-raoul reported. And by checking the log it seemed to me lke a API<19 related error, should be about using vector drawables on old versions.

But according to your latest screenshoot you discovered a new bug too. Can you please paste new logs of your latest build here? The about page should include fe540eb as you shared screenshoots.

**Comment by neslihanturan** [comment]
Please make sure you cleaned logcat before test, just to make sure we get log of up to date version, thanks for discovering though @PavelAplevich !

**Comment by PavelAplevich** [comment]
**And problem still here. I have this About menu**
![Screenshot_1562583496](https://user-images.githubusercontent.com/52326878/60808123-364eb080-a190-11e9-99dd-2cdae63467b9.png)
**But after a second i see this**
![Screenshot_1562583480](https://user-images.githubusercontent.com/52326878/60808209-5ed6aa80-a190-11e9-899b-6e0afe8fe440.png)

**I run app on emulator Nexus One API 22 and real phone Redmi4x API 25. And situation analogical..
In emulator after clicking About LogCat write this:**

07-08 15:03:04.864 10897-10897/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri fr.free.nrw.commons.contributions.Contribution.getContentUri()' on a null object reference
        at fr.free.nrw.commons.contributions.ContributionsListFragment.findIdOfItemWithPosition(ContributionsListFragment.java:220)
        at fr.free.nrw.commons.contributions.ContributionsListFragment.onSaveInstanceState(ContributionsListFragment.java:202)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2627)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2629)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at fr.free.nrw.commons.auth.AuthenticatedActivity.onSaveInstanceState(AuthenticatedActivity.java:49)
        at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:102)
        at android.app.Activity.performSaveInstanceState(Activity.java:1298)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1288)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:3958)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3369)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3425)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by PavelAplevich** [comment]
**UPD**

Issue #2940 still here, but Review activity send error before ~1sec, too
![Screenshot_1562589206](https://user-images.githubusercontent.com/52326878/60810509-fdb1d580-a195-11e9-8fc4-fc5a82726e55.png)

**Comment by neslihanturan** [comment]
Hi @PavelAplevich , separate issues for each different issue would be a better for all to follow. I think the one about Peer review is a different issue. 

I will share what I understand, can you please verify if correct. When you click to achievements activity on current master, you see this error right?
```
07-08 15:03:04.864 10897-10897/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri fr.free.nrw.commons.contributions.Contribution.getContentUri()' on a null object reference
        at fr.free.nrw.commons.contributions.ContributionsListFragment.findIdOfItemWithPosition(ContributionsListFragment.java:220)
        at fr.free.nrw.commons.contributions.ContributionsListFragment.onSaveInstanceState(ContributionsListFragment.java:202)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2627)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2629)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at fr.free.nrw.commons.auth.AuthenticatedActivity.onSaveInstanceState(AuthenticatedActivity.java:49)
        at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:102)
        at android.app.Activity.performSaveInstanceState(Activity.java:1298)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1288)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:3958)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3369)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3425)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I wanted to make sure and asking this because this log seems like related with **contributions fragment** instead of **achievements**.

And for the peer review error, can you please edit issue description with screenshots and logs here: https://github.com/commons-app/apps-android-commons/issues/3060 and we can continue peer review related discussion there.

**Comment by PavelAplevich** [comment]
**@neslihanturan I think this problem has one reason for all Activity. And I just noticed that i lot out from my profile, app doesn't crash anytime and working correctly.
I can give you logs of all Activity which you want**

**Comment by neslihanturan** [comment]
Can you try login again and see if it works for you @PavelAplevich ?

**Comment by PavelAplevich** [comment]
**I try and my logcat if i go to About write this:**

 --------- beginning of system
07-09 11:20:28.458 17708-17708/fr.free.nrw.commons.beta I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-09 11:20:29.386 17708-17708/fr.free.nrw.commons.beta D/AndroidRuntime: Shutting down VM
07-09 11:20:29.387 17708-17708/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri fr.free.nrw.commons.contributions.Contribution.getContentUri()' on a null object reference
        at fr.free.nrw.commons.contributions.ContributionsListFragment.findIdOfItemWithPosition(ContributionsListFragment.java:220)
        at fr.free.nrw.commons.contributions.ContributionsListFragment.onSaveInstanceState(ContributionsListFragment.java:202)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2627)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2629)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at fr.free.nrw.commons.auth.AuthenticatedActivity.onSaveInstanceState(AuthenticatedActivity.java:49)
        at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:102)
        at android.app.Activity.performSaveInstanceState(Activity.java:1298)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1288)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:3958)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3369)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3425)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-09 11:20:29.432 17708-17708/? I/Process: Sending signal. PID: 17708 SIG: 9

**Comment by neslihanturan** [comment]
Maybe leaving the contributions fragment causes this, because it is not expected to have a very obvious bug on each activities. What do you say @ashishkumar468 ? Can this be related with latest contributions changes?

**Comment by PavelAplevich** [comment]
**I give you another logcat from real device. I hope this help you**

--------- beginning of crash
2019-07-09 11:25:17.416 13854-13854/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 13854
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri fr.free.nrw.commons.contributions.Contribution.getContentUri()' on a null object reference
        at fr.free.nrw.commons.contributions.ContributionsListFragment.findIdOfItemWithPosition(ContributionsListFragment.java:220)
        at fr.free.nrw.commons.contributions.ContributionsListFragment.onSaveInstanceState(ContributionsListFragment.java:202)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2627)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2629)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at fr.free.nrw.commons.auth.AuthenticatedActivity.onSaveInstanceState(AuthenticatedActivity.java:49)
        at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:102)
        at android.app.Activity.performSaveInstanceState(Activity.java:1477)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1301)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4631)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3934)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3999)
        at android.app.ActivityThread.-wrap25(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1559)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
2019-07-09 11:25:17.431 13854-13854/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri fr.free.nrw.commons.contributions.Contribution.getContentUri()' on a null object reference
        at fr.free.nrw.commons.contributions.ContributionsListFragment.findIdOfItemWithPosition(ContributionsListFragment.java:220)
        at fr.free.nrw.commons.contributions.ContributionsListFragment.onSaveInstanceState(ContributionsListFragment.java:202)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2627)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2629)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2267)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2326)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at fr.free.nrw.commons.auth.AuthenticatedActivity.onSaveInstanceState(AuthenticatedActivity.java:49)
        at fr.free.nrw.commons.contributions.MainActivity.onSaveInstanceState(MainActivity.java:102)
        at android.app.Activity.performSaveInstanceState(Activity.java:1477)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1301)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4631)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3934)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3999)
        at android.app.ActivityThread.-wrap25(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1559)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by neslihanturan** [comment]
Hi @PavelAplevich , how did yo produce the latest logcat, what were you doing with the app?

**Comment by PavelAplevich** [comment]
Analogical. I go to About and app crash

**Comment by PavelAplevich** [comment]
UPD! 
If I minimize application app crash instantly. Maybe problem with life cycle? In onPause or onStop?

**Comment by neslihanturan** [comment]
Yes, I thought the same. Lets see what @ashishkumar468 will say, he recently worked on related area.

**Comment by PavelAplevich** [comment]
I reset down to commit #3046 and app works correctly. As I undestand, problem in this commit #3046

**Comment by PavelAplevich** [comment]
#3062 solved this issue
