### ISSUE TITLE
App crashes 5 sec after start 

### ISSUE THREAD

**Issue by AtaZh** [commons-app/apps-android-commons#307]
No difference whether I had time to open upload dialog or not.
I'm logged in from 2 devices with Android 4.0.4 and 4.4.2. The same on both.
Where the problem can be, what do you think?

**Comment by nicolas-raoul** [comment]
Strange!

What version of the app?

Thanks for the feedback!
Nicolas Raoul

**Comment by misaochan** [comment]
@AtaZh are you using the Ukranian language for the app? If so, could you please try changing to English just to see if the same thing happens?

Thanks, and sorry for the inconvenience!

**Comment by AtaZh** [comment]
Btw, I don't see menu button. 
![14825738_1308909752476678_1723201960_n](https://cloud.githubusercontent.com/assets/10130813/19721253/27cc34fc-9b7a-11e6-9455-2e59b6378e1f.jpg)

After changing device language to English I managed to upload an image.
Could it be that I left an issue in uk localisation?
![image](https://cloud.githubusercontent.com/assets/10130813/19721612/af9df4aa-9b7b-11e6-98e3-154e5a8234f5.png)

**Comment by misaochan** [comment]
@AtaZh Yeah, the localization issue would be my best guess. The next time it crashes, could you please submit a crash report? That'll help us pinpoint the line of code causing trouble.

The lack of menu button is odd though. Has it been that way the entire time or just in the latest version?

**Comment by AtaZh** [comment]
I must have sent a report before opening this issue.
Crash happened only in last version.
I changed language back from English (US) to Ukrainian and now app works ok, I uploaded an image.
Menu button is not in the app but the menu can be opened by menu button of device.
Maybe in the end it's something about my phone. Hm.

**Comment by misaochan** [comment]
Odd, I looked up your crash report and it doesn't point to localization errors, just an OutOfMemoryError that I mentioned at #308 . Just to clarify, the crash happened after you started the app, before you tried to upload anything?

```
USER_COMMENT=
ANDROID_VERSION=4.0.4
APP_VERSION_NAME=1.36
BRAND=Sony
PHONE_MODEL=ST21i
CUSTOM_DATA=
STACK_TRACE=java.lang.OutOfMemoryError
at com.android.volley.toolbox.ByteArrayPool.getBuf(ByteArrayPool.java:101)
at com.android.volley.toolbox.PoolingByteArrayOutputStream.<init>(PoolingByteArrayOutputStream.java:53)
at com.android.volley.toolbox.BasicNetwork.entityToBytes(BasicNetwork.java:228)
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:123)
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

```

**Comment by AtaZh** [comment]
I guess, both reports mentioned here and in #308 are mine. Comments there made me think.
I assume that the first crash happened after tapping on a file in gallery in order to upload it. And then when app was opened again it crashes right away. If smth happens to any app I always go end processes in task manager. So I ended this one and a bunch of others, opened app again and it crashed on choosing a file.

**Comment by neslihanturan** [comment]
@AtaZh did you eperience this issue recently? Or anyone else? Because Out Of Memory errors should be solved recently.

**Comment by domdomegg** [comment]
Closing due to inactivity. Please reopen if still an issue.
