### ISSUE TITLE
IndexOutOfBoundsException when scrolling on Explore items, after a night of not using the app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3140]
Yesterday on the emulator I was scrolling items in the Explore activity, and let the app like this.
This morning I came back to my computer, scrolled a bit again, and got this crash:
```
APP_VERSION_CODE=243
APP_VERSION_NAME=2.10.2-debug-upload_caption_depict
ANDROID_VERSION=9
PHONE_MODEL=Android SDK built for x86
STACK_TRACE=java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{fa892 position=105 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{12c493a VFED.V... ........ 0,11-1080,1458 #7f090124 app:id/imagesListBox}, adapter:com.pedrogomez.renderers.RVRendererAdapter@b0709eb, layout:androidx.recyclerview.widget.LinearLayoutManager@dc70348, context:fr.free.nrw.commons.explore.SearchActivity@4f736b
at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5815)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5998)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by vanshikaarora** [comment]
@nicolas-raoul Where have you observed this Issue, Explore or Items?

**Comment by nicolas-raoul** [comment]
Explore

**Comment by vanshikaarora** [comment]
okay

**Comment by erlandvr** [comment]
I have the same error when coming back from a backgrounded app into a recyclerView. Do you have any updates on this issue? 
`Android: 9
Android Build: PKQ1.180716.001
Manufacturer: OnePlus
Model: ONEPLUS A5000
CrashReporter Key: 3a3cce06-0988-40c4-af2d-ed889612f39e
Start Date: 2019-12-05T08:32:27.372Z
Date: 2019-12-05T09:07:21.574Z

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{9c10b65 position=42 id=-1, oldPos=-1, pLpos:-1 no parent} android.support.v7.widget.RecyclerView{5570386 VFED..... ........ 0,0-1080,1710 #7f0800be app:id/RecyclerViewArticleList}, adapter:md5623915d2b8a458722d135bd864d9eab4.PageOverviewRecyclerAdapter@98a8c6b, layout:md5d2bdfca8c8b0ba87f97a6daeec554f14.DisableScrollLinearLayoutManager@780e6e5, context:md592f4888a4b76d4195bf84c4122bcce9a.ChannelHomepageActivity@e64d034
  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline
  at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline
  at android.support.v7.widget.GapWorker.flushTaskWithDeadline
  at android.support.v7.widget.GapWorker.flushTasksWithDeadline
  at android.support.v7.widget.GapWorker.prefetch
  at android.support.v7.widget.GapWorker.run
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6863)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `

**Comment by nicolas-raoul** [comment]
Similar issue on latest master:
```
03-21 16:02:53.645 10576 10576 E AndroidRuntime: FATAL EXCEPTION: main
03-21 16:02:53.645 10576 10576 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 10576
03-21 16:02:53.645 10576 10576 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{87418aa position=8 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{b82884e VFED.V... ........ 0,12-1080,1707 #7f090127 app:id/imagesListBox}, adapter:com.pedrogomez.renderers.RVRendererAdapter@66ffd6f, layout:androidx.recyclerview.widget.LinearLayoutManager@fc0ea7c, context:fr.free.nrw.commons.explore.SearchActivity@197b1f7
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5815)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5998)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7032)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
03-21 16:02:53.645 10576 10576 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
03-21 16:02:53.647 10576 10576 E ACRA    : ACRA caught a IndexOutOfBoundsException for fr.free.nrw.commons
```

**Comment by nicolas-raoul** [comment]
I just got this error using the latest `structured-data`.
The app was running and on the front on my smartphone, but I had not touched my phone for a while (like 20 minutes). When I took my phone and just started scrolling (I think I was on an Explore item search), it crashed immediately with this logcat:
```
04-11 21:28:20.543 11838 11838 D ViewRootImpl@ebc6a4f[SearchActivity]: ViewPostIme pointer 0
04-11 21:28:20.623 11838 11838 D AndroidRuntime: Shutting down VM
04-11 21:28:20.624 11838 11838 E AndroidRuntime: FATAL EXCEPTION: main
04-11 21:28:20.624 11838 11838 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 11838
04-11 21:28:20.624 11838 11838 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{26f0724 position=8 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{ffc0456 VFED.V... ........ 0,12-1080,1707 #7f090126 app:id/imagesListBox}, adapter:com.pedrogomez.renderers.RVRendererAdapter@d7b3486, layout:androidx.recyclerview.widget.LinearLayoutManager@d1a6147, context:fr.free.nrw.commons.explore.SearchActivity@f1511f0
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5815)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5998)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7032)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-11 21:28:20.624 11838 11838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
04-11 21:28:20.626 11838 11838 E ACRA    : ACRA caught a IndexOutOfBoundsException for fr.free.nrw.commons
04-11 21:28:20.626 11838 11838 E ACRA    : java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{26f0724 position=8 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{ffc0456 VFED.V... ........ 0,12-1080,1707 #7f090126 app:id/imagesListBox}, adapter:com.pedrogomez.renderers.RVRendererAdapter@d7b3486, layout:androidx.recyclerview.widget.LinearLayoutManager@d1a6147, context:fr.free.nrw.commons.explore.SearchActivity@f1511f0
04-11 21:28:20.626 11838 11838 E ACRA    : 	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5815)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5998)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:873)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at android.os.Looper.loop(Looper.java:214)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7032)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-11 21:28:20.626 11838 11838 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/79223065-8dd12980-7e50-11ea-8c16-57e8a94faf38.png)

There are 5 possible culprits but there are only 3 of these fragments used from SearchActivity so that narrows it down a bit.

I'd propose 3 tickets out of this to tackle #3462 because this is an error of a structural nature

**Comment by macgills** [comment]
This also requires #3468 because the Renderers library used for adapters does not support PagedList
