### ISSUE TITLE
Upload of file with all-Japanese caption fails

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3143]
I am trying to upload a file with the Japanese caption `贅沢そうめん`.
It failed, and every retry fails immediately too:
```
2019-08-26 12:57:47,719     [DEBUG] [file-logging-thread-1] [ContributionsFragment] : Restarting for fr.free.nrw.commons.contributions.model.DisplayableContribution@f097b1
2019-08-26 12:57:47,730     [WARN ] [file-logging-thread-1] [UploadService] : Exception during upload
java.lang.IllegalArgumentException: Unexpected char 0x8d05 at 47 in Content-Disposition value: form-data; name="file"; filename="Temp_15767473贅沢そうめん"
	at okhttp3.Headers.checkValue(Headers.java:272)
	at okhttp3.Headers.of(Headers.java:224)
	at okhttp3.MultipartBody$Part.createFormData(MultipartBody.java:259)
	at fr.free.nrw.commons.upload.UploadClient.uploadFileToStash(UploadClient.java:38)
	at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$1$UploadService(UploadService.java:239)
	at fr.free.nrw.commons.upload.-$$Lambda$UploadService$t65Il4uRfVsV80fLOIW6RgLISAc.apply(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:70)
	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
	at io.reactivex.Observable.subscribe(Observable.java:12090)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```
Strcutured Data branch, not tried with master.

**Comment by PavelAplevich** [comment]
@nicolas-raoul 
https://commons.wikimedia.beta.wmflabs.org/wiki/File%3A%E8%B4%85%E6%B2%A2%E3%81%9D%E3%81%86%E3%82%81%E3%82%93.jpg

Can't reproduce

**Comment by nicolas-raoul** [comment]
Can't reproduce either :-)
