### ISSUE TITLE
 Error occurred while loading notifications

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3214]
**Summary:** 

When you suspend the app and resume, error occurred while loading notifications log will appear.

**Steps to reproduce:** 

Suspend the app then resume

**System logs:**

```
2019-11-21 16:54:10.789 8540-8540/fr.free.nrw.commons.beta E/MainActivity: Error occurred while loading notifications
    org.wikipedia.dataclient.mwapi.MwException: You must be logged in.
        at org.wikipedia.dataclient.mwapi.MwResponse.postProcess(MwResponse.java:20)
        at org.wikipedia.json.PostProcessingTypeAdapter$1.read(PostProcessingTypeAdapter.java:28)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Device and Android version:** 

Nexus 6 APı 26 Emulator
 
**Commons app version:** 
betaDebug

**Would you like to work on the issue?**
Ideally no

**Comment by maskaravivek** [comment]
It seems to be working fine for me. I also tried suspending and resuming the app. 

![device-2019-11-23-161252](https://user-images.githubusercontent.com/3069373/69477418-2ddbd700-0e0c-11ea-9b24-f7e559f528a1.png)

From the logs, it looks like there's some login issue. 

```
You must be logged in
```

Were you logged in properly when this occurred?

**Comment by neslihanturan** [comment]
Hey @maskaravivek , can you also check logs? I was checking the logs for another issue but recognized that I am seeing this possibly improper logs that I shared. Do you also see them?

**Comment by maskaravivek** [comment]
Yes, I checked it. I don't see these logs.

**Comment by ashishkumar468** [comment]
Not seeing this issue on the latest master, closing this issue for now
