### ISSUE TITLE
Resources$NotFoundException - issues with Korean translation?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#326]
Received this crash report from Teemeah (from the Community Wishlist survey):

```
USER_COMMENT=right after logging in it stopped
ANDROID_VERSION=6.0
APP_VERSION_NAME=1.38
BRAND=HONOR
PHONE_MODEL=PLK-L01
CUSTOM_DATA=
STACK_TRACE=android.content.res.Resources$NotFoundException: Plural resource ID #0x7f070000 quantity=0 item=other
at android.content.res.Resources.getQuantityText(Resources.java:381)
at android.content.res.Resources.getQuantityString(Resources.java:493)
at fr.free.nrw.commons.contributions.ContributionsActivity.onLoadFinished(ContributionsActivity.java:217)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
at android.support.v4.content.Loader.deliverResult(Loader.java:126)
at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:252)
at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)
at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5546)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

She sent me an accompanying screenshot. It seems the issue might be with the Korean translations? How do we fix the issue if we can't read/write Korean? (The stack trace doesn't seem to point to the exact string causing the issues)

![screenshot_2016-11-17-12-01-19](https://cloud.githubusercontent.com/assets/3611199/20387266/293edcc0-ad24-11e6-94bf-67eaa03dcfab.png)

**Comment by misaochan** [comment]
I looked around and the issue is probably with one of these?

```
  <plurals name="contributions_subtitle"/>
  <plurals name="starting_multiple_uploads">
    <item quantity="one">한 장 업로드 시작</item>
    <item quantity="other">%d 장 업로드 시작</item>
  </plurals>
  <plurals name="multiple_uploads_title">
    <item quantity="one">한 장 업로드</item>
    <item quantity="other">%d 장 업로드</item>
  </plurals>
```

**Comment by nicolas-raoul** [comment]
Are these plurals similar in XML structure to the English ones?

**Comment by misaochan** [comment]
No, the English one has

```
    <plurals name="contributions_subtitle">
        <item quantity="zero">No uploads yet</item>
        <item quantity="one">1 upload</item>
        <item quantity="other">%d uploads</item>
```

Maybe I will ask her to help translate that part for us?

**Comment by nicolas-raoul** [comment]
That's most probably the reason.
Would you mind removing such broken translations from all language files?
Asking her for translation is a good idea too.

**Comment by misaochan** [comment]
Haha, it will probably take a while to go through all of them, but I'll do what I can. If the translation is broken, can I remove the field entirely with no adverse effects?

**Comment by nicolas-raoul** [comment]
From the localization files, yes, remove the whole thing.
