### ISSUE TITLE
Nearby Crashes when LatLng object is null

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3302]
**Summary:** 

Nearby Crashes when LatLng object is null

**System logs:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double fr.free.nrw.commons.location.LatLng.getLatitude()' on a null object reference
at fr.free.nrw.commons.nearby.fragments.NearbyMapFragment.addCurrentLocationMarker(NearbyMapFragment.java:324)
at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.recenterMap(NearbyParentFragment.java:845)
at fr.free.nrw.commons.nearby.presenter.NearbyParentFragmentPresenter.lambda$setActionListeners$1$NearbyParentFragmentPresenter(NearbyParentFragmentPresenter.java:165)
at fr.free.nrw.commons.nearby.presenter.-$$Lambda$NearbyParentFragmentPresenter$SsMTyquU_-0wTkhYYQ8nWV2foSc.onClick(lambda)
at android.view.View.performClick(View.java:6199)
at android.view.View$PerformClick.run(View.java:23647)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

```

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Is it the stock version from the manufacturer or a custom ROM ?
 
**Commons app version:** 
2.12.0

**Would you like to work on the issue?**

Yes

**Comment by ashishkumar468** [comment]
This seems to be already fixed on the current version, closing this issue
