### ISSUE TITLE
App Crashes in GridViewAdapter$setAuthorView

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3307]
**Summary:** 
App crashes with invalid string formatter in GridViewAdapter

**System logs:**

```
java.util.IllegalFormatConversionException: a != java.lang.String
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4402)
at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2897)
at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
at java.util.Formatter.format(Formatter.java:2529)
at java.util.Formatter.format(Formatter.java:2458)
at java.lang.String.format(String.java:2814)
at fr.free.nrw.commons.category.GridViewAdapter.setAuthorView(GridViewAdapter.java:104)
at fr.free.nrw.commons.category.GridViewAdapter.getView(GridViewAdapter.java:90)
at android.widget.AbsListView.obtainView(AbsListView.java:2400)
at android.widget.GridView.onMeasure(GridView.java:1065)
at android.view.View.measure(View.java:22524)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
at android.view.View.measure(View.java:22524)
at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
at android.view.View.measure(View.java:22524)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
at android.view.View.measure(View.java:22524)
at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
at android.view.View.measure(View.java:22524)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6794)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
at android.view.View.measure(View.java:22524)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6794)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
at android.view.View.measure(View.java:22524)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6794)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:22524)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6794)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
at android.view.View.measure(View.java:22524)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6794)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:792)
at android.view.View.measure(View.java:22524)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2833)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1762)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2034)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1650)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
at android.view.Choreographer.doCallbacks(Choreographer.java:732)
at android.view.Choreographer.doFrame(Choreographer.java:664)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:202)
at android.app.ActivityThread.main(ActivityThread.java:6962)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
```

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
IAPP_VERSION_CODE=508
APP_VERSION_NAME=2.12.0
ANDROID_VERSION=8.1.0
PHONE_MODEL=CPH1909
**Would you like to work on the issue?**
Yes

**Comment by maskaravivek** [comment]
@ashishkumar468 does this crash happen for some particular language?

**Comment by ashishkumar468** [comment]
Yes, @maskaravivek, it was because of the invalid argument in strings file
