### ISSUE TITLE
Error shown when there are no more images to load

### ISSUE THREAD

**Issue by chinmoy12c** [commons-app/apps-android-commons#3314]
**Summary:** 
When the featured or uploaded by mobile list comes to end, i.e there are no more images to load an error is shown instead of suitable information.

**Steps to reproduce:** 
Reach the last image of featured or mobile uploads.

**System logs:**

```
2020-01-02 03:04:50.601 23152-23152/fr.free.nrw.commons.beta E/CategoryImagesListFragment: Error occurred while loading images inside a category
    java.lang.NullPointerException: The mapper function returned a null value.
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:437)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:326)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onSubscribe(ObservableFlatMap.java:546)
        at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableCollectSingle.subscribeActual(ObservableCollectSingle.java:49)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

**Device and Android version:** 
 Redmi note 7s , Android version 9 (Pie)

**Commons app version:** 

version 2.12.0

**Screen-shots:** 
![Screenshot_2020-01-02-02-59-22-015_fr free nrw commons beta](https://user-images.githubusercontent.com/57670338/71646337-ea2e9400-2d0c-11ea-901c-e5afa34ea5ce.jpg)

**Would you like to work on the issue?**
Yes, I would like to work on the issue. I have found the root cause of this issue. The recent update of Rxjava does not allow **_Single_**  to return null value which is the case when there are no more images left and leads to NullPointerException. By checking the error for empty list a suitable information could be provided to the user.

**Comment by chinmoy12c** [comment]
This is the pull request with the fix.
https://github.com/commons-app/apps-android-commons/pull/3325#issue-362757440
