### ISSUE TITLE
CategoryImagesListFragment.handleError never succeeds

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3448]
**Summary:** 

While getting timeouts from the beta endpoint I did not see an error view.

The problem is the usage of `timeout` after `observeOn`, timeout by default operates on the Computation Scheduler switching the downstream operator to this thread

**Steps to reproduce:** 

Change the timeout to be 1ms and see that the error view is not shown.

**System logs:**

```
2020-03-02 14:49:53.375 3727-3792/fr.free.nrw.commons.beta W/System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
2020-03-02 14:49:53.376 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7313)
2020-03-02 14:49:53.376 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1161)
2020-03-02 14:49:53.376 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.View.requestLayout(View.java:21995)
2020-03-02 14:49:53.377 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.View.requestLayout(View.java:21995)
2020-03-02 14:49:53.377 3727-3792/fr.free.nrw.commons.beta W/System.err:     at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1303)
2020-03-02 14:49:53.377 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.View.requestLayout(View.java:21995)
2020-03-02 14:49:53.377 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
2020-03-02 14:49:53.377 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.View.requestLayout(View.java:21995)
2020-03-02 14:49:53.377 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.View.requestLayout(View.java:21995)
2020-03-02 14:49:53.377 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
2020-03-02 14:49:53.378 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.View.requestLayout(View.java:21995)
2020-03-02 14:49:53.378 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.View.setFlags(View.java:13343)
2020-03-02 14:49:53.378 3727-3792/fr.free.nrw.commons.beta W/System.err:     at android.view.View.setVisibility(View.java:9420)
2020-03-02 14:49:53.378 3727-3792/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.category.CategoryImagesListFragment.initErrorView(CategoryImagesListFragment.java:163)
2020-03-02 14:49:53.378 3727-3792/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.category.CategoryImagesListFragment.handleError(CategoryImagesListFragment.java:152)
2020-03-02 14:49:53.378 3727-3792/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.category.CategoryImagesListFragment.lambda$T3p9-uu_pOMeRRzxWL12UOxUmzM(Unknown Source:0)
2020-03-02 14:49:53.378 3727-3792/fr.free.nrw.commons.beta W/System.err:     at fr.free.nrw.commons.category.-$$Lambda$CategoryImagesListFragment$T3p9-uu_pOMeRRzxWL12UOxUmzM.accept(Unknown Source:4)
2020-03-02 14:49:53.379 3727-3792/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
2020-03-02 14:49:53.379 3727-3792/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.run(SingleTimeout.java:123)
2020-03-02 14:49:53.379 3727-3792/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
2020-03-02 14:49:53.379 3727-3792/fr.free.nrw.commons.beta W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
2020-03-02 14:49:53.379 3727-3792/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-03-02 14:49:53.379 3727-3792/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020-03-02 14:49:53.379 3727-3792/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2020-03-02 14:49:53.379 3727-3792/fr.free.nrw.commons.beta W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-03-02 14:49:53.380 3727-3792/fr.free.nrw.commons.beta W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Commons app version:** 

master & betaDebug

**Would you like to work on the issue?**

Happy to.

**Comment by macgills** [comment]
The problem and anti pattern of wrapping view access in a try catch is much more widespread.
All usage of `.timeout` should be addressed
