### ISSUE TITLE
App Crashes in MediaDetailsFragment with ClassCastException

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3507]
**Summary:** 

Open MediaDetails from the MainActivity and Swipe the ViewPager till it reaches it's end, the app crashes

**Steps to reproduce:** 
Open MediaDetails from the MainActivity and Swipe the ViewPager till it reaches it's end

**System logs:**

```
 java.lang.ClassCastException: fr.free.nrw.commons.contributions.MainActivity cannot be cast to fr.free.nrw.commons.category.CategoryImagesCallback
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onPageScrolled(MediaDetailPagerFragment.java:333)
        at androidx.viewpager.widget.ViewPager.dispatchOnPageScrolled(ViewPager.java:1930)
        at androidx.viewpager.widget.ViewPager.onPageScrolled(ViewPager.java:1904)
        at androidx.viewpager.widget.ViewPager.pageScrolled(ViewPager.java:1842)
        at androidx.viewpager.widget.ViewPager.computeScroll(ViewPager.java:1802)
        at android.view.View.updateDisplayListIfDirty(View.java:17289)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
        at android.view.View.updateDisplayListIfDirty(View.java:17265)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
        at android.view.View.updateDisplayListIfDirty(View.java:17265)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
        at android.view.View.updateDisplayListIfDirty(View.java:17265)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
        at android.view.View.updateDisplayListIfDirty(View.java:17265)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.draw(View.java:18327)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.draw(View.java:18327)
        at com.android.internal.policy.DecorView.draw(DecorView.java:923)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:698)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:806)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3135)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2931)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2523)
```

**Device and Android version:** 

Samsung S6
 
**Commons app version:** 

Current master

**Would you like to work on the issue?**
Preferably not

**Comment by kbhardwaj123** [comment]
@ashishkumar468 I recently made major changes to the media detail files can I work on this

**Comment by macgills** [comment]
Go ahead @kbhardwaj123 !

**Comment by kbhardwaj123** [comment]
@ashishkumar468 i got it it was because MainActivity did not implement the CategoryImagesCallback interface due to which the context of MainActivity couldn't be cast to CategoryImagesCallback
