### ISSUE TITLE
Application crashes when nomination for deletion is pressed

### ISSUE THREAD

**Issue by gouri-panda** [commons-app/apps-android-commons#3520]
**Steps to reproduce:** 
1. Install the Application.
2. Skip the Login or Signup section
3. Go to the Explore section and select one image
4. Tap the button Nominate for deletion

**System logs:**
`2020-03-15 20:11:48.076 12723-12723/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 12723
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at fr.free.nrw.commons.media.MediaDetailFragment.onDeleteButtonClicked(MediaDetailFragment.java:351)
        at fr.free.nrw.commons.media.MediaDetailFragment_ViewBinding$5.doClick(MediaDetailFragment_ViewBinding.java:90)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-03-15 20:11:48.077 12723-12723/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at fr.free.nrw.commons.media.MediaDetailFragment.onDeleteButtonClicked(MediaDetailFragment.java:351)
        at fr.free.nrw.commons.media.MediaDetailFragment_ViewBinding$5.doClick(MediaDetailFragment_ViewBinding.java:90)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

**Device and Android version:** 
Device name - Pixel 3a XL
Android version - Android 10
API level - 29

**Would you like to work on the issue?**
Yes

**Comment by madhurgupta10** [comment]
@gouri-panda Could you please add logs?

**Comment by gouri-panda** [comment]
@nicolas-raoul  , @maskaravivek  Can I Start work on this issue?

**Comment by madhurgupta10** [comment]
@gouri-panda I am unable to reproduce this issue. Can you share the flavor and app version you faced this issue on?

**Comment by gouri-panda** [comment]
> @gouri-panda I am unable to reproduce this issue. Can you share the flavor and app version you faced this issue on?

@madhurgupta10 The app version is 2.12.3 and the  flavor is Beta

**Comment by gouri-panda** [comment]
@madhurgupta10  Did you find it?

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/76737568-ee414e00-6760-11ea-80b6-5208c5c17484.png)
@madhurgupta10 try not being logged in, the warning on that `equals`  is unsurprisingly `may produce NPE`

**Comment by madhurgupta10** [comment]
I can see the issue now. @gouri-panda Do mention it (skip login) in your description.
