### ISSUE TITLE
Application crashes when clicking the GridView adapter of Bookmarks.

### ISSUE THREAD

**Issue by gouri-panda** [commons-app/apps-android-commons#3531]
**Summary:** 
Application crashes when clicking the grid view after changing the theme in Bookmarks.

**Steps to reproduce:** 

- Go to the bookmarks section
- Change the theme by going to the navigation drawer
- Go back to the Bookmarks section
- Select one image view in the Grid view

**System logs:**

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ListAdapter android.widget.GridView.getAdapter()' on a null object reference
        at fr.free.nrw.commons.bookmarks.pictures.BookmarkPicturesFragment.getAdapter(BookmarkPicturesFragment.java:228)
        at fr.free.nrw.commons.bookmarks.BookmarksPagerAdapter.getMediaAdapter(BookmarksPagerAdapter.java:57)
        at fr.free.nrw.commons.bookmarks.BookmarksActivity.getTotalMediaCount(BookmarksActivity.java:137)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter.getCount(MediaDetailPagerFragment.java:384)
        at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:532)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateView(MediaDetailPagerFragment.java:100)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2440)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:885)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:686)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2057)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1847)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1802)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1709)
        at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java:229)
        at fr.free.nrw.commons.bookmarks.BookmarksActivity.onItemClick(BookmarksActivity.java:96)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
        at android.widget.AbsListView$3.run(AbsListView.java:4116)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Device and Android version:** 

Device name - Pixel 3a XL
Android version - Android 10
API level - 29
 
**Commons app version:** 
2.12.3

**Would you like to work on the issue?**
yes

**Comment by nicolas-raoul** [comment]
I confirm that this crash still happens in latest master.
