### ISSUE TITLE
Get rid of HandlerService

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3555]
**Summary:** 

We have RxJava if we need to simulate a queue of work, by binding we can just pass acquire a service reference and directly invoke methods instead of using message passing.

**Comment by VitalyVPinchuk** [comment]
Hello @macgills @nicolas-raoul  
Can I try to work on this?

**Comment by nicolas-raoul** [comment]
@VitalyVPinchuk I guess, yes, thanks! :-)

**Comment by VitalyVPinchuk** [comment]
Hello @macgills @nicolas-raoul !
Could you please have a look at [changes](https://github.com/commons-app/apps-android-commons/compare/master...VitalyVPinchuk:fix-3555)

Is it what I was supposed to do?

**Comment by macgills** [comment]
@VitalyVPinchuk yes that is what I was hoping would be achieved. The class can be slimmed down further as we don't need to pass this `what` and have switch statements with 1 clause. simply `uploadService.upload(contribution)` is what I would like to be invoking

**Comment by macgills** [comment]
Or perhaps even a queue implemented using a PublishProcessor of Contributions, and the api is just `uploadService.queue(contribution)`

**Comment by VitalyVPinchuk** [comment]
Got it. Thanks.

**Comment by VitalyVPinchuk** [comment]
> Or perhaps even a queue implemented using a PublishProcessor of Contributions, and the api is just `uploadService.queue(contribution)`

Hello @macgills 
I'm new to RxJava and need some help.
Why would we need to use `PublishProcessor` here? Do we need to implement multiple subscribers? Or back pressure? I can't figure out how to apply it here. Could you give me an example?

**Comment by macgills** [comment]
A PublishProcessor is for ease of implementing a queue so we can call something like `contributionsToUpload.offer(contribution)`

And then the service manages this with maybe something as simple as `contributionsToUpload.subscribe(contribution->uploadContribution(contribution))`

We can Rx this up a bit more in the future, for now it would be quite complicated I think

**Comment by VitalyVPinchuk** [comment]
Hello @macgills 
I've made a [commit](https://github.com/commons-app/apps-android-commons/compare/master...VitalyVPinchuk:fix-3555)  with `PublishProcessor` but not sure if it is right.

**Comment by macgills** [comment]
@VitalyVPinchuk looks fine to me, have you tested it with uploading multiple images at once?

**Comment by VitalyVPinchuk** [comment]
@macgills Yes I have and they upload fine. 
Though app gives me an error about incorrect date format, just as the master branch.
Probably I've got a problem with localisation in my emulator.

```
W/UploadService: Exception during upload
    java.text.ParseException: Unparseable date: "2020-04-17T10:16:56Z"
        at java.text.DateFormat.parse(DateFormat.java:362)
        at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$5$UploadService(UploadService.java:289)
        at fr.free.nrw.commons.upload.-$$Lambda$UploadService$z4mESqjWAHg0tpHdfefQt3ojNaw.accept(Unknown Source:8)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:265)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:562)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)


```

**Comment by macgills** [comment]
You need to sync with the upstream master, this bug was fixed on the 8th

**Comment by VitalyVPinchuk** [comment]
Thanks. Merged with master. The error has gone.

Here is [PR](https://github.com/commons-app/apps-android-commons/pull/3671)
