### ISSUE TITLE
After tapping "+", new language caption+description pair difficult to access

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3561]
When the "+" button is tapped, a new language (caption+description fields couple) is added at the bottom, but somehow it does not seem to always appear immediately, especially from the third language pair, I have to tap around a bit before being able to see it, not sure why.
![Screenshot_20200316-231105_Commons](https://user-images.githubusercontent.com/99590/76766756-d5c24980-67db-11ea-83a9-25b5a8a24acd.jpg)

**Comment by chao19991005** [comment]
Can I work on this issue?

**Comment by nicolas-raoul** [comment]
@chao19991005 Have you managed to reproduce the issue? Please send a screenshot showing these fields in several languages, thanks :-)

**Comment by chao19991005** [comment]
@nicolas-raoul Sorry, I found that there is no such bug appears in my device

**Comment by AntSYau** [comment]
it happens after i have added several languages. besides i found it impossible to delete the languages i don't want, there's only a + button. 
![Screenshot_20200321-202514](https://user-images.githubusercontent.com/10476297/77226316-5a351380-6bb2-11ea-99b4-40b453045584.jpg)

**Comment by AntSYau** [comment]
Oh and after adding another several blank languages, I directly suspended my phone, and when I turned it back on, the app crashed and asked me to send error messages...

**Comment by nicolas-raoul** [comment]
@chao19991005 @AntSYau Oh sorry I did not realize the Structured Data branch had not been merged yet.
Would you mind temporarily switching to this branch? https://github.com/commons-app/apps-android-commons/commits/structured-data Thanks!

**Comment by AntSYau** [comment]
sure i'll see what i can do

**Comment by AntSYau** [comment]
the "+" button now don't work at all @nicolas-raoul

**Comment by AntSYau** [comment]
```
I/SessionManager: dispatchVolumeKeyEvent:fr.free.nrw.commons.beta true KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=339612010, downTime=339612010, deviceId=6, source=0x101 } -2147483648 false java.lang.Throwable
        at android.media.session.MediaSessionManager.dispatchVolumeKeyEventInternal(MediaSessionManager.java:365)
        at android.media.session.MediaSessionManager.dispatchVolumeKeyEventAsSystemService(MediaSessionManager.java:358)
        at com.android.internal.policy.PhoneWindow.onKeyDown(PhoneWindow.java:1899)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:350)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5557)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5425)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5068)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5125)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5101)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5262)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2590)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2100)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2091)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2567)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/SessionManager: dispatchVolumeKeyEvent:fr.free.nrw.commons.beta true KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x28, repeatCount=0, eventTime=339612712, downTime=339612010, deviceId=6, source=0x101 } -2147483648 false java.lang.Throwable
        at android.media.session.MediaSessionManager.dispatchVolumeKeyEventInternal(MediaSessionManager.java:365)
        at android.media.session.MediaSessionManager.dispatchVolumeKeyEventAsSystemService(MediaSessionManager.java:358)
        at com.android.internal.policy.PhoneWindow.onKeyUp(PhoneWindow.java:2000)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:351)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5557)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5425)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5068)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5125)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5101)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5262)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2590)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2100)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2091)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2567)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/SessionManager: dispatchVolumeKeyEvent:fr.free.nrw.commons.beta true KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=339612130, downTime=339612010, deviceId=6, source=0x101 } -2147483648 false java.lang.Throwable
        at android.media.session.MediaSessionManager.dispatchVolumeKeyEventInternal(MediaSessionManager.java:365)
        at android.media.session.MediaSessionManager.dispatchVolumeKeyEventAsSystemService(MediaSessionManager.java:358)
        at com.android.internal.policy.PhoneWindow.onKeyUp(PhoneWindow.java:2000)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:351)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5557)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5425)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5068)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5125)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4936)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4962)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4928)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5101)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5262)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2590)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2100)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2091)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2567)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by AntSYau** [comment]
Here are logs after I wake up my phone. It looks like the app is trying to drag something from server or something, but it never made it and got trapped
```
W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/UploadMediaDetailAdapter$ViewHolder: descItemEditText:androidx.appcompat.widget.AppCompatEditText{ce862b2 VFED..CL. ......I. 0,0-0,0 #7f0900d4 app:id/description_item_edit_text}
D/UploadMediaDetailAdapter$ViewHolder: UploadMediaDetail is fr.free.nrw.commons.upload.UploadMediaDetail@4b07203
D/OnePlusJankManager:  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadActivity--- jank level = 2
D/UploadMediaDetailAdapter$ViewHolder: Description language code is: ccp
E/Choreographer: skip doframe for fr.free.nrw.commons.beta
D/OkHttp: --> GET https://commons.wikimedia.beta.wmflabs.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=query&meta=userinfo&uiprop=blockinfo
D/CookieManager: Domain:commons.wikimedia.beta.wmflabs.org
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/UploadMediaDetailAdapter$ViewHolder: descItemEditText:androidx.appcompat.widget.AppCompatEditText{6e2d2be VFED..CL. ......I. 0,0-0,0 #7f0900d4 app:id/description_item_edit_text}
D/UploadMediaDetailAdapter$ViewHolder: UploadMediaDetail is fr.free.nrw.commons.upload.UploadMediaDetail@7bdcf1f
D/UploadMediaDetailAdapter$ViewHolder: Description language code is: ccp
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/UploadMediaDetailAdapter$ViewHolder: descItemEditText:androidx.appcompat.widget.AppCompatEditText{8e0f646 VFED..CL. ......I. 0,0-0,0 #7f0900d4 app:id/description_item_edit_text}
D/UploadMediaDetailAdapter$ViewHolder: UploadMediaDetail is fr.free.nrw.commons.upload.UploadMediaDetail@2f66007
D/UploadMediaDetailAdapter$ViewHolder: Description language code is: ccp
D/OkHttp: <-- 200 https://commons.wikimedia.beta.wmflabs.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=query&meta=userinfo&uiprop=blockinfo (2511ms, unknown-length body)
W/System: A resource failed to call close. 
E/Choreographer: skip doframe for fr.free.nrw.commons.beta
```

**Comment by AntSYau** [comment]
And if I straightly go back to sleep from here, the app will crash.
```
D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
E/Choreographer: skip doframe for fr.free.nrw.commons.beta
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 25189
    java.lang.RuntimeException: Unable to resume activity {fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { act=fr.free.nrw.commons.upload.upload cmp=fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadService }: app is in background uid UidRecord{9e79b1a u0a115 TPSL bg:+4m0s113ms idle change:cached procs:1 seq(0,0,0)}
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3961)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3993)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=fr.free.nrw.commons.upload.upload cmp=fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadService }: app is in background uid UidRecord{9e79b1a u0a115 TPSL bg:+4m0s113ms idle change:cached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1595)
        at android.app.ContextImpl.startService(ContextImpl.java:1550)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at fr.free.nrw.commons.upload.UploadController.prepareService(UploadController.java:81)
        at fr.free.nrw.commons.repository.UploadRemoteDataSource.prepareService(UploadRemoteDataSource.java:82)
        at fr.free.nrw.commons.repository.UploadRepository.prepareService(UploadRepository.java:67)
        at fr.free.nrw.commons.upload.UploadPresenter.onAttachView(UploadPresenter.java:130)
        at fr.free.nrw.commons.upload.UploadPresenter.onAttachView(UploadPresenter.java:25)
        at fr.free.nrw.commons.upload.UploadActivity.onResume(UploadActivity.java:192)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1514)
        at android.app.Activity.performResume(Activity.java:7311)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3953)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3993) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6940) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
E/ACRA: ACRA caught a RuntimeException for fr.free.nrw.commons.beta
    java.lang.RuntimeException: Unable to resume activity {fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { act=fr.free.nrw.commons.upload.upload cmp=fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadService }: app is in background uid UidRecord{9e79b1a u0a115 TPSL bg:+4m0s113ms idle change:cached procs:1 seq(0,0,0)}
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3961)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3993)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=fr.free.nrw.commons.upload.upload cmp=fr.free.nrw.commons.beta/fr.free.nrw.commons.upload.UploadService }: app is in background uid UidRecord{9e79b1a u0a115 TPSL bg:+4m0s113ms idle change:cached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1595)
        at android.app.ContextImpl.startService(ContextImpl.java:1550)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at fr.free.nrw.commons.upload.UploadController.prepareService(UploadController.java:81)
        at fr.free.nrw.commons.repository.UploadRemoteDataSource.prepareService(UploadRemoteDataSource.java:82)
        at fr.free.nrw.commons.repository.UploadRepository.prepareService(UploadRepository.java:67)
        at fr.free.nrw.commons.upload.UploadPresenter.onAttachView(UploadPresenter.java:130)
        at fr.free.nrw.commons.upload.UploadPresenter.onAttachView(UploadPresenter.java:25)
        at fr.free.nrw.commons.upload.UploadActivity.onResume(UploadActivity.java:192)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1514)
        at android.app.Activity.performResume(Activity.java:7311)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3953)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3993) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1934) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6940) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
W/ACRA: Warning: Acra may behave differently with a debugger attached
```

**Comment by nicolas-raoul** [comment]
Please rebuild with the "prodDebug" flavor, it is better to always use that flavor. Thanks!

I tried the following:

- Select an image to upload
- Enter caption/description in the first language
- Tap '+'
- Nothing happens, even if waiting for a long time
- Switch the focus to the other fields
- Still nothing happens, even if waiting for a long time
- Add another character to the description field of the first language
- Now the second language has appeared.

Do you observe the same?

@AntSYau Could you please create new bugs for each crash? (after searching to see whether a bug report already exists for that crash) Thanks! :-)

**Comment by AntSYau** [comment]
Yes, that happens on my build!
Sorry I had little experience in tracking issues. I will look through history reports about the other crash.

**Comment by nicolas-raoul** [comment]
@chao19991005 Are you able to reproduce the issue I described above? On the structured-data branch.

**Comment by Rajahn** [comment]
Hi，i've reproduced that issue on structured-data branch. if @chao### doesn't feel like fixing it, i could try it

**Comment by chao19991005** [comment]
@nicolas-raoul I have reproduce that issue but I am not sure how to solve that.

**Comment by hyonisss** [comment]
What version is  your android studio ?

**Comment by AntSYau** [comment]
I'm using AS 3.6.1 @hyonisss

**Comment by sivaraam** [comment]
@macgills would like to take a look at this, I believe.

**Comment by nicolas-raoul** [comment]
@chao19991005 Please `git pull` as this screen has changed in the structured-data branch.

Actually it is much easier to use than before, thanks to the bigger space.

So now it only feels weird when you try to enter a third language pair.

**Comment by macgills** [comment]
The feature is pretty unusable for many languages, the data is not persisted so if you start scrolling it just deletes your text. That might be a separate issue but it would probably take entirely rewriting the adapters and data flow to actually sort out cleanly.

There is also the lingering question of the #3508 @nicolas-raoul could you check out my comments on the associated PR and see if I am on the right track as regards the UX?

**Comment by SaumiaSinghal** [comment]
Hi @nicolas-raoul! I noticed the time lag issue on pressing '+' button. Can I work on it?

**Comment by nicolas-raoul** [comment]
@SaumiaSinghal Actually I just tried again (using the app as compiled from the latest master) and I can not see any lag anymore haha... could you please try again with the latest master? (About should show commit version 96cf57711)

**Comment by SaumiaSinghal** [comment]
Hi @nicolas-raoul! I tried after merging from the latest master. The problem that I see now is there is no lag on pressing '+' button but, I have to scroll to make the new content appear.

**Comment by nicolas-raoul** [comment]
Having to scroll is not such a big problem, but could you please send a pull request, so that we can check the code? Thanks!
Thanks also for the screencast, it makes it easy to see the result. And it looks like an improvement indeed!

**Comment by SaumiaSinghal** [comment]
No problem! I'll open a PR.
