### ISSUE TITLE
[2.13-release] Crash when trying to upload images

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#3639]
**Summary:** 
I face the following crash whenever I try to upload a picture using the app build from the `2.13-release` branch pointing at c961099013a19b91c46763216331795c36957b5d

**Steps to reproduce:**
*Pre-requisite*: Ensure that 'Don't keep activities' is turned on in the device's developer options.
1. Build an app from the `2.13-release` branch
2. Open the app
3. Tap on the + button
4. Choose the 'Gallery' or 'Camera' option
5. Complete the action for the corresponding action
6. Observe the crash

**System logs:**

```
04-10 22:43:56.314 32368-32368/? E/MotionRecognitionManager: motionService = null
04-10 22:43:56.394 189-189/? E/BufferQueueCore: [Starting fr.free.nrw.commons] setDefaultMaxBufferCount: setting count to 3, previous is 2 
04-10 22:43:56.955 32107-32107/? E/ACRA: ACRA caught a RuntimeException for fr.free.nrw.commons
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@3e9300bc: Unmarshalling unknown type code 2131296410 at offset 7596
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
        at android.app.ActivityThread.access$1000(ActivityThread.java:218)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6934)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@3e9300bc: Unmarshalling unknown type code 2131296410 at offset 7596
        at android.os.Parcel.readValue(Parcel.java:2228)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:2546)
        at android.os.Parcel.readSparseArray(Parcel.java:1874)
        at android.os.Parcel.readValue(Parcel.java:2209)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:822)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:772)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
        at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:27)
        at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:6609)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6934) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Device and Android version:** 
Samsung SM-J111F; Android 5.1.1

**Commons app version:** 
2.13-reelase branch @ c961099013a19b91c46763216331795c36957b5d
prodDebug variant

**Comment by misaochan** [comment]
Odd, the unmarshalling exception was supposed to have been fixed. :/ We should look into this prior to releasing.

**Comment by maskaravivek** [comment]
@misaochan  I tried testing on the commit ID(`c961099013a19b91c46763216331795c36957b5d`) mentioned in this issue and didn't observe a crash. 

I had a freshly installed APK of the app.

**Comment by macgills** [comment]
I reproduced.
Just turn on "don't keep activities"

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 11397
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@7e2a331: Unmarshalling unknown type code 2131296410 at offset 13192
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@7e2a331: Unmarshalling unknown type code 2131296410 at offset 13192
        at android.os.Parcel.readValue(Parcel.java:2833)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3204)
        at android.os.Parcel.readSparseArray(Parcel.java:2416)
        at android.os.Parcel.readValue(Parcel.java:2811)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3123)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
        at android.os.BaseBundle.unparcel(BaseBundle.java:226)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:1009)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:772)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
        at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:27)
        at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
E/ACRA: ACRA caught a RuntimeException for fr.free.nrw.commons
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@7e2a331: Unmarshalling unknown type code 2131296410 at offset 13192
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@7e2a331: Unmarshalling unknown type code 2131296410 at offset 13192
        at android.os.Parcel.readValue(Parcel.java:2833)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:3204)
        at android.os.Parcel.readSparseArray(Parcel.java:2416)
        at android.os.Parcel.readValue(Parcel.java:2811)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3123)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
        at android.os.BaseBundle.unparcel(BaseBundle.java:226)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:1009)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:772)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
        at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:27)
        at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

I'd write an automated test where you write a Contribution to a parcel and then read a contribution from a parcel as that is what is failing.

It would be best if we weren't writing any code though and we could just use the `Parcelize` annotation from kotlin

**Comment by maskaravivek** [comment]
Awesome, thanks @macgills. 

Fixing the issue.

**Comment by misaochan** [comment]
Thanks @macgills and @maskaravivek . Is there a PR up for this?

**Comment by maskaravivek** [comment]
@misaochan I haven't been able to fix the issue yet. I am able to reproduce it consistently when `do not keep activities` setting is on but I am not sure about the fix. 

The crash happens even without initiating the upload so it is just related to we are saving the state of the activities. 

When `do not keep activities` setting is on, open the contributions list page(main page) and then take the app in the background. Resume the app again to observe the crash. 

This suggests that we have not implemented the `onSaveInstanceState` properly in the main activity/contributions fragment. It won't affect most of the users as the crash happens only in `unexpected situations`. 

Ref: https://stackoverflow.com/questions/21227623/whats-the-main-advantage-and-disadvantage-of-do-not-keep-activities-in-android

@ashishkumar468 @macgills Do you guys have any insights about how to fix this?

**Comment by macgills** [comment]
It is the parcelable implementation of Contribution/Media that causes this

>I'd write an automated test where you write a Contribution to a parcel and then read a contribution from a parcel as that is what is failing.

I recommend this as acceptance criteria

**Comment by ashishkumar468** [comment]
I think the crash is in Nearby Fragment, I tried removing the nearby fragment from the ViewPager in the MainActivity, the app did not crash with the said steps( although It did crash when it was there), also I have already tested sending contribution via intent packaged as bundle without any crash. I am yet to figure out the exact thing in NearbyFragment, which is causing this
