### ISSUE TITLE
Login timeout error in betaDebug

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#3646]
**Summary:** 
Getting login timeout error in betaDebug

**Steps to reproduce:** 
Perform Login in betaDebug

**System logs:**
```
2020-04-12 17:13:11.451 7910-8000/fr.free.nrw.commons.beta D/OkHttp: <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
2020-04-12 17:13:11.456 7910-7910/fr.free.nrw.commons.beta E/LoginActivity: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:662)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:671)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:142)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:99)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at fr.free.nrw.commons.OkHttpConnectionFactory$CommonHeaderRequestInterceptor.intercept(OkHttpConnectionFactory.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:215)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-04-12 17:13:11.460 7910-7958/fr.free.nrw.commons.beta D/EGL_emulation: eglMakeCurrent: 0xd31a8660: ver 3 0 (tinfo 0xbed83f60)
2020-04-12 17:13:11.475 7910-7958/fr.free.nrw.commons.beta D/EGL_emulation: eglMakeCurrent: 0xd31a8660: ver 3 0 (tinfo 0xbed83f60)
2020-04-12 17:13:11.483 2049-2850/? E/InputDispatcher: Window handle Window{857f938 u0 Logging in} has no registered input channel
2020-04-12 17:13:11.834 1792-2473/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
```

**Device and Android version:** 
Google Pixel 2 Android 10 API Level 29
 
**Commons app version:** 
2.12.3-debug-master~241b54d00

**Screen-shots:** 
![Screenshot_1586704343](https://user-images.githubusercontent.com/30932899/79072331-cbaf4000-7ce0-11ea-8760-9311395a7546.png)

**Comment by sivaraam** [comment]
Do you get this error whenever you try to log-in? I get a `timeout` at times but successive attempts would result in a successful log-in.

Also, I'm doubtful about whether there's anything to be done in the app's side. This would generally happen when the network is not good or when there's a delay in the server's response both of which are out of our control. We could increase the timeout, if possible. But AFAIK it's not a major issue reported by users using the production version of the app, so I think it's not worth doing that.

**Comment by madhurgupta10** [comment]
> Do you get this error whenever you try to log-in? I get a `timeout` at times but successive attempts would result in a successful log-in.

Yes during login, I tried multiple times but didn't worked.



> Also, I'm doubtful about whether there's anything to be done in the app's side. This would generally happen when the network is not good or when there's a delay in the server's response both of which are out of our control. We could increase the timeout, if possible. But AFAIK it's not a major issue reported by users using the production version of the app, so I think it's not worth doing that.

Maybe there is some ongoing issue with beta API, I don't think we need to increase the timeout.

**Comment by sivaraam** [comment]
> > Do you get this error whenever you try to log-in? I get a `timeout` at times but successive attempts would result in a successful log-in.
> 
> Yes during login, I tried multiple times but didn't worked.

I just tried building `betaDebug` from `master` (2.12.3-debug-HEAD~241b54d00) and I was able to successfully log-in to the beta server.

![Screenshot_2020-04-13-00-23-40](https://user-images.githubusercontent.com/12448084/79077231-95dc7c80-7d1d-11ea-92b8-c72e43714c50.png)

If you're sure there's no issue with your network, just check after a day or so to see if this changes.

**Comment by macgills** [comment]
Beta is just a bit unstable at the best of times, use prod when at all possible and beta for only uploading many images, closing
