### ISSUE TITLE
StreamTimeout.newTimeoutException when depicting Sandbox

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3654]
I think I reproduced the error that Vivek is seeing, on a super-fast super-stable Internet connection:
```
04-15 13:33:19.398 30877  5330 W UploadService: Exception during upload
04-15 13:33:19.398 30877  5330 W UploadService: java.net.SocketTimeoutException: timeout
04-15 13:33:19.398 30877  5330 W UploadService:         at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:662)
04-15 13:33:19.398 30877  5330 W UploadService:         at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:671)
04-15 13:33:19.398 30877  5330 W UploadService:         at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.kt:547)
04-15 13:33:19.398 30877  5330 W UploadService:         at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.kt:526)
04-15 13:33:19.398 30877  5330 W UploadService:         at okio.ForwardingSink.write(ForwardingSink.kt:29)
04-15 13:33:19.398 30877  5330 W UploadService:         at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:222)
04-15 13:33:19.398 30877  5330 W UploadService:         at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:181)
04-15 13:33:19.398 30877  5330 W UploadService:         at okio.RealBufferedSink.write(RealBufferedSink.kt:39)
04-15 13:33:19.398 30877  5330 W UploadService:         at okio.ForwardingSink.write(ForwardingSink.kt:29)
04-15 13:33:19.398 30877  5330 W UploadService:         at fr.free.nrw.commons.upload.CountingRequestBody$CountingSink.write(CountingRequestBody.kt:42)
04-15 13:33:19.398 30877  5330 W UploadService:         at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:181)
04-15 13:33:19.398 30877  5330 W UploadService:         at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:108)
04-15 13:33:19.398 30877  5330 W UploadService:         at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:162)
04-15 13:33:19.398 30877  5330 W UploadService:         at fr.free.nrw.commons.upload.CountingRequestBody.writeTo(CountingRequestBody.kt:34)
04-15 13:33:19.398 30877  5330 W UploadService:         at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
04-15 13:33:19.399 30877  5330 W UploadService:         at fr.free.nrw.commons.OkHttpConnectionFactory$CommonHeaderRequestInterceptor.intercept(OkHttpConnectionFactory.java:57)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
04-15 13:33:19.399 30877  5330 W UploadService:         at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:63)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:215)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
04-15 13:33:19.399 30877  5330 W UploadService:         at okhttp3.RealCall.execute(RealCall.kt:66)
04-15 13:33:19.399 30877  5330 W UploadService:         at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
04-15 13:33:19.399 30877  5330 W UploadService:         at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.Observable.subscribe(Observable.java:12267)
04-15 13:33:19.399 30877  5330 W UploadService:         at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.Observable.subscribe(Observable.java:12267)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.Observable.subscribe(Observable.java:12267)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:96)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.Observable.subscribe(Observable.java:12267)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
04-15 13:33:19.399 30877  5330 W UploadService:         at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
04-15 13:33:19.399 30877  5330 W UploadService:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-15 13:33:19.399 30877  5330 W UploadService:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-15 13:33:19.399 30877  5330 W UploadService:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-15 13:33:19.399 30877  5330 W UploadService:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-15 13:33:19.399 30877  5330 W UploadService:         at java.lang.Thread.run(Thread.java:764)
```
https://www.wikidata.org/wiki/Q4115189
Might be totally random, will try again later.

**Comment by nicolas-raoul** [comment]
Probably a false alert, I was able to upload a picture depicting Sandbox, and a retry on the failed pic worked.
