### ISSUE TITLE
App crashes due to network issue

### ISSUE THREAD

**Issue by chihuazhang** [commons-app/apps-android-commons#3663]
Studies have shown that mobile apps are prone to crashes due to a network issue, mainly because successful network calls return unexpected or no data. And we found that when the field of the app(version 243)'s network return data (JSON format) is null or the network request fails (status code is 404), the app has crashed. the specific crash information is as follows:

1. 

> java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
      at fr.free.nrw.commons.contributions.ContributionsFragment.setUploadCount(ContributionsFragment.java:455)
      at fr.free.nrw.commons.contributions.ContributionsFragment.onCreateView(ContributionsFragment.java:173)

2. 

> java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
	at android.support.design.widget.Snackbar.make(Snackbar.java:137)
	at android.support.design.widget.Snackbar.make(Snackbar.java:170)
	at fr.free.nrw.commons.utils.ViewUtil.lambda$showShortSnackbar$0$ViewUtil(ViewUtil.java:28)

3. 

> io.reactivex.exceptions.OnErrorNotImplementedException: org.xml.sax.SAXParseException: Unexpected token (position:TEXT error@1:6 in java.io.InputStreamReader@c82005a) 
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.io.IOError: org.xml.sax.SAXParseException: Unexpected token (position:TEXT error@1:6 in java.io.InputStreamReader@c82005a) 
	at fr.free.nrw.commons.mwapi.CustomApiResult.fromRequestBuilder(CustomApiResult.java:60)
	at fr.free.nrw.commons.mwapi.CustomMwApi.makeRequest(CustomMwApi.java:177)
	at fr.free.nrw.commons.mwapi.CustomMwApi.access$000(CustomMwApi.java:18)
	at fr.free.nrw.commons.mwapi.CustomMwApi$RequestBuilder.post(CustomMwApi.java:38)
	at fr.free.nrw.commons.mwapi.ApacheHttpClientMediaWikiApi.login(ApacheHttpClientMediaWikiApi.java:121)
	at fr.free.nrw.commons.auth.LoginActivity.login(LoginActivity.java:237)
	at fr.free.nrw.commons.auth.LoginActivity.lambda$performLogin$8$LoginActivity(LoginActivity.java:228)
	at fr.free.nrw.commons.auth.LoginActivity$$Lambda$6.call(dalvik_source_frfreenrwcommons_243.apk)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:12030)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.xml.sax.SAXParseException: Unexpected token (position:TEXT error@1:6 in java.io.InputStreamReader@c82005a) 
	at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
	at fr.free.nrw.commons.mwapi.CustomApiResult.fromRequestBuilder(CustomApiResult.java:42)
	... 18 more

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is not relevant any more so we can close this
