### ISSUE TITLE
NullPointerException when you click on image in MediaDetailFragment

### ISSUE THREAD

**Issue by gvaibhav1734** [commons-app/apps-android-commons#3730]
**Summary:** 

App crashes when you click on the image in MediaDetailFragment.

**Steps to reproduce:** 

1. Click on one of the images in Contributions tab
2. When MediaDetailFragment loads the particular media click on the image again. Do it immediately before the other fields such as license, description, depictions are loaded.

**System logs:**

```
USER_COMMENT=
APP_VERSION_CODE=561
APP_VERSION_NAME=2.12.3-debug-master
ANDROID_VERSION=9
PHONE_MODEL=AOSP on IA Emulator
STACK_TRACE=java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:490)
	at android.net.Uri$StringUri.<init>(Uri.java:480)
	at android.net.Uri.parse(Uri.java:452)
	at fr.free.nrw.commons.media.MediaDetailFragment.launchZoomActivity(MediaDetailFragment.java:231)
	at fr.free.nrw.commons.media.MediaDetailFragment_ViewBinding$1.doClick(MediaDetailFragment_ViewBinding.java:48)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25885)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

IS_SILENT=false
USER_EMAIL=
USER_CRASH_DATE=2020-05-05T10:12:02.219+05:30
REPORT_ID=c543b132-25f8-4e69-ba28-5168cb41e410
```

**Device and Android version:** 

PHONE_MODEL=AOSP on IA Emulator (Pixel 2 emulator)
ANDROID_VERSION=9
 
**Commons app version:** 

APP_VERSION_NAME=2.12.3-debug-master
FLAVOUR=betaDebug

**Would you like to work on the issue?**

I would like to work on this issue.

**Comment by misaochan** [comment]
Assigned to you, go for it @gvaibhav1734 . :)

I suggest you start by verifying that the problem also exists on prodDebug.

**Comment by gvaibhav1734** [comment]
Problem occurs on prodDebug as well.

The line of code in _onClickListener_ for the _ImageView_ causing the issue:
``` java
startActivity(Intent(ctx,ZoomableActivity.class).setData(Uri.parse(media.getImageUrl())))
```

`media.getImageUrl()` depends on an a network call to be populated. Would a simple null check be sufficient?

**Comment by ashishkumar468** [comment]
A null check should be fine, what do you say @misaochan ?

**Comment by misaochan** [comment]
If we just don't do anything when `media.getImageUri()` returns null, will it still be able to display the image after the network call succeeds?

**Comment by ashishkumar468** [comment]
We can, but that might not be a good thing,
User could be interested in browsing other  things once he realises image has not loaded yet and we not knowing his intention would take him to the zoom activity even though he might not be interested in that at that moment

**Comment by misaochan** [comment]
Good point. Let us go with the simple null check for now, and see how it goes. :)
