### ISSUE TITLE
App crashes when scrolling ITEMS in search activity

### ISSUE THREAD

**Issue by VitalyVPinchuk** [commons-app/apps-android-commons#3748]
**Summary:** 
App crashes when scrolling ITEMS in search activity.

**Steps to reproduce:** 
1. Go to Explore
2. Search for "rabbit" then tap ITEMS
3. Tap an item from recycler view
4. Go back
5. Try to scroll any direction

**Device and Android version:** 
Emulator API 29
 
**Commons app version:** 
Latest master prodDebug

**Would you like to work on the issue?**
Yes

**Comment by nicolas-raoul** [comment]
Thanks for reporting!
Indeed I can reproduce this at first try on latest master:
```
USER_COMMENT=issue 3748
APP_VERSION_CODE=561
APP_VERSION_NAME=2.12.3-debug-master
ANDROID_VERSION=9
PHONE_MODEL=SM-G970F
STACK_TRACE=java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 8(offset:8).state:25 androidx.recyclerview.widget.RecyclerView{aa21709 VFED.V... ........ 0,12-1080,1707 #7f090126 app:id/imagesListBox}, adapter:com.pedrogomez.renderers.RVRendererAdapter@3febd0e, layout:androidx.recyclerview.widget.LinearLayoutManager@7e4f32f, context:fr.free.nrw.commons.explore.SearchActivity@9c76cfc
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6023)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7032)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

IS_SILENT=false
USER_EMAIL=
USER_CRASH_DATE=2020-05-22T12:08:34.433+09:00
REPORT_ID=e3324eff-e954-4190-8dad-12ed364f0bbb
```

**Comment by misaochan** [comment]
@macgills Has this been solved?

**Comment by macgills** [comment]
When my final pagination PR for this trio of fragments is merged I would be surprised if this crash could be possible

**Comment by macgills** [comment]
The 3 Explore fragments have been converted to pagination and I can not reproduce with the given steps, closing
