### ISSUE TITLE
Switch to WorkManagers

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3790]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)
App crashes when upload is somehow initiated from the background.

**Steps to reproduce:** 
Yet to figure out, reported by email

**System logs:**

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { act=fr.free.nrw.commons.upload.upload cmp=fr.free.nrw.commons/.upload.UploadService }: app is in background uid UidRecord{a10f242 u0a101 LAST bg:+10h50m21s78ms idle change:cached procs:1 seq(0,0,0)}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4823)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4732)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4782)
	at android.app.ActivityThread.access$3200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1826)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=fr.free.nrw.commons.upload.upload cmp=fr.free.nrw.commons/.upload.UploadService }: app is in background uid UidRecord{a10f242 u0a101 LAST bg:+10h50m21s78ms idle change:cached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
	at android.app.ContextImpl.startService(ContextImpl.java:1532)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at fr.free.nrw.commons.contributions.MainActivity.initMain(MainActivity.java:118)
	at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:90)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 16 more
```

**Device and Android version:** 
ANDROID_VERSION=9
PHONE_MODEL=Redmi 3S
**Commons app version:** 
APP_VERSION_CODE=709
APP_VERSION_NAME=2.13

**Would you like to work on the issue?**
Yes

**Comment by ashishkumar468** [comment]
The UploadService is either missing to call startForeground in some cases, we can probably think of including a combination of WorkManager and Foreground service to handle the same

**Comment by misaochan** [comment]
We can add this to the stability tasks in the upcoming grant probably, as it only happens intermittently and the workload for the fix will be pretty significant.

**Comment by misaochan** [comment]
From conversation with @ashishkumar468 : This will happen when the user presses the home button/app goes in background immediately after initiating upload before the app gets time to attach the service with the progress update notification. And only in Android O+.

**Comment by nicolas-raoul** [comment]
I just got this by starting the upload process, and switching off the screen of my phone while on the depictions (or was it categories?) screen, then switching my phone's screen back on like 20 minutes later.

**Comment by nicolas-raoul** [comment]
With the latest master, this happens anytime I try to upload an image (via either gallery or camera, from either home or nearby).
Happens even after uninstalling and reinstalling the app.

**Comment by ashishkumar468** [comment]
@nicolas-raoul  Can you send the logs for this, please?

**Comment by nicolas-raoul** [comment]
@ashishkumar0207 30 minutes ago I wrongly posted a comment here, but then realized that it was a different error, so I filed a new issue: https://github.com/commons-app/apps-android-commons/issues/3997
Sorry for the noise!

**Comment by ashishkumar468** [comment]
No problem @nicolas-raoul
