### ISSUE TITLE
Prod debug app crashes on startup

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3791]
**Summary:** 

App crashes on startup while using it on an emulator. 

**Steps to reproduce:** 

Install and run prod debug on x86 emulator. 

**System logs:**

```
2020-05-31 18:57:04.430 3670-3670/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 3670
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
        at fr.free.nrw.commons.CommonsApplication.onCreate(CommonsApplication.java:127)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Device and Android version:** 

Android 9
 
**Commons app version:** 

`prodDebug` on latest master while using an emulator. 

**Would you like to work on the issue?**

No.

**Comment by maskaravivek** [comment]
Ref: https://github.com/mapbox/mapbox-gl-native/issues/14428
https://github.com/mapbox/mapbox-gl-native/issues/15331

**Comment by maskaravivek** [comment]
This is no longer reproducible on master.
