### ISSUE TITLE
App crashes when Upload Media Details fragment is clicked ad there is no compound drawable [2]

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3827]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)
App crashes when Upload Media Details fragment is clicked ad there is no compound drawable [2]
**Steps to reproduce:** 

How can we reproduce the issue? 
Click on the EditText title in UploadMediaDetailFragment

**System logs:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect android.graphics.drawable.Drawable.getBounds()' on a null object reference
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.lambda$addEtTitleTouchListener$1$UploadMediaDetailFragment(UploadMediaDetailFragment.java:178)
at fr.free.nrw.commons.upload.mediaDetails.-$$Lambda$UploadMediaDetailFragment$b9r0xnPBA0dlhVOVH_D0-KQrnHs.onTouch(Unknown Source:2)
at android.view.View.dispatchTouchEvent(View.java:14372)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:730)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
at android.app.Activity.dispatchTouchEvent(Activity.java:4051)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:688)
at android.view.View.dispatchPointerEvent(View.java:14644)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6508)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6295)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5733)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5786)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5752)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5908)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5760)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5965)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5733)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5786)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5752)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5760)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5733)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8892)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8753)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8706)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9028)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:197)
at android.app.ActivityThread.main(ActivityThread.java:7857)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Device and Android version:** 

ANDROID_VERSION=10
PHONE_MODEL=SM-G960F
 
**Commons app version:** 

2.12.3 PROD

**Would you like to work on the issue?**

Yes

**Comment by ashishkumar468** [comment]
Fixed in #3828
