### ISSUE TITLE
App Crashes in UploadMediaDetailFragment when trying to upload a very large image in lower end devices

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3829]
**Summary:** 

App Crashes in UploadMediaDetailFragment when trying to upload a very large image in lower-end devices

**Steps to reproduce:** 

Upload a  very high-quality image.

**System logs:**

```
java.lang.RuntimeException: Canvas: trying to draw too large(219189248bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at android.widget.ImageView.onDraw(ImageView.java:1434)
	at android.view.View.draw(View.java:21473)
	at android.view.View.updateDisplayListIfDirty(View.java:20350)
	at android.view.View.draw(View.java:21205)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4412)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4171)
	at android.view.View.updateDisplayListIfDirty(View.java:20341)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4396)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4369)
	at android.view.View.updateDisplayListIfDirty(View.java:20310)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3685)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3480)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2817)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7751)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Device and Android version:** 

 Mi 9 SE Android Version:10
 
**Commons app version:** 

2.13

**Would you like to work on the issue?**

Yes

**Comment by ashishkumar468** [comment]
Fixed in #3830
