### ISSUE TITLE
Uploaded picture corrupt (part is grey)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3903]
I uploaded a picture of a building, but unfortunately the bottom of the uploaded picture is grey: https://commons.wikimedia.org/wiki/File:%E6%9D%B1%E4%BA%AC%E5%A1%97%E6%96%99%E4%BC%9A%E9%A4%A8.jpg

I suspect that only the beginning of the file is uploaded, and then the upload gets considered as finished even though it is not. Depictions/categories/etc are set correctly.

The same actually happened twice last week too:

![tempFileForShare_20200817-233115](https://user-images.githubusercontent.com/99590/90407908-08050980-e0e2-11ea-8cb2-ec49d0acb192.jpg)

Using the Commons website I overwrote these two but the original upload can be seen in their history pages: https://commons.wikimedia.org/wiki/File:Restaurant_%E6%B3%89%E8%8F%AF%E8%8D%98_2.jpg https://commons.wikimedia.org/wiki/File:Phasme_%C3%A0_Tokyo.jpg

App version: 2.12.3-debug-temp-filteere~796f1f07d (very close to current master, only leaderboard addition that does not change anything to the upload part)

**Comment by ashishkumar468** [comment]
@maskaravivek Could this be related with the chunk uploads?

**Comment by nicolas-raoul** [comment]
50% of my 14 latest uploaded pictures are corrupt in the same way.
I can try any branch you want, to help debug the problem :-)

**Comment by misaochan** [comment]
@nicolas-raoul Have you tried master recently? If it still happens, logs would be great. :)

**Comment by nicolas-raoul** [comment]
I just uploaded 5 pictures and it worked (latest master) :-)
I close for now and will only reopen if it happens again.

**Comment by nicolas-raoul** [comment]
Unfortunately the problem happened again with the latest master (2.12.3-debug-master~df209e752): https://commons.wikimedia.org/wiki/File:Evening_walk_in_Shirokane_-_sushi_restaurant.jpg
My Internet connection is rather slow, that might trigger it? I expect that many people need to upload on similar connections, though.

**Comment by nicolas-raoul** [comment]
Below is the log for this corrupted upload: https://commons.wikimedia.org/wiki/File:Strange_eggplant.jpg
```
[... many identical SocketTimeoutExceptions ...]
2020-08-31 21:39:50,421     [ERROR] [file-logging-thread-1] [UploadClient] : Error occurred in uploading chunk
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
	at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.kt:557)
	at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.kt:535)
	at okio.ForwardingSink.write(ForwardingSink.kt:29)
	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:145)
	at okio.ForwardingSink.write(ForwardingSink.kt:29)
	at fr.free.nrw.commons.upload.CountingRequestBody$CountingSink.write(CountingRequestBody.kt:49)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:184)
	at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
	at fr.free.nrw.commons.upload.CountingRequestBody.writeTo(CountingRequestBody.kt:40)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
	at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at fr.free.nrw.commons.OkHttpConnectionFactory$CommonHeaderRequestInterceptor.intercept(OkHttpConnectionFactory.java:63)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.Observable.subscribe(Observable.java:12253)
	at io.reactivex.Observable.subscribe(Observable.java:12181)
	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileToStash$2$UploadClient(UploadClient.java:106)
	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$o9957uEjSG2yFmKju6TjCB8UUak.accept(Unknown Source:19)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:98)
	at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.Observable.subscribe(Observable.java:12253)
	at io.reactivex.Observable.subscribe(Observable.java:12155)
	at io.reactivex.Observable.forEach(Observable.java:9105)
	at fr.free.nrw.commons.upload.UploadClient.uploadFileToStash(UploadClient.java:83)
	at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$2$UploadService(UploadService.java:269)
	at fr.free.nrw.commons.upload.-$$Lambda$UploadService$Mykz4B1wymjq4LCG_9JtKi5_-pY.apply(Unknown Source:8)
	at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:70)
	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

2020-08-31 21:40:01,077     [ERROR] [file-logging-thread-1] [ContributionBoundaryCallback$fetchContributions] : Failed to fetch contributions: timeout
2020-08-31 21:40:01,564     [ERROR] [file-logging-thread-1] [ContributionBoundaryCallback$fetchContributions] : Failed to fetch contributions: timeout
2020-08-31 21:40:11,061     [ERROR] [file-logging-thread-1] [ContributionBoundaryCallback$fetchContributions] : Failed to fetch contributions: timeout
2020-08-31 21:40:11,935     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : gps's status changed to 1
2020-08-31 21:40:20,638     [ERROR] [file-logging-thread-1] [UploadClient] : Error occurred in uploading chunk
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
	at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.kt:557)
	at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.kt:535)
	at okio.ForwardingSink.write(ForwardingSink.kt:29)
	at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.kt:218)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:145)
	at okio.ForwardingSink.write(ForwardingSink.kt:29)
	at fr.free.nrw.commons.upload.CountingRequestBody$CountingSink.write(CountingRequestBody.kt:49)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:235)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:184)
	at okhttp3.RequestBody$Companion$asRequestBody$1.writeTo(RequestBody.kt:167)
	at fr.free.nrw.commons.upload.CountingRequestBody.writeTo(CountingRequestBody.kt:40)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
	at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at fr.free.nrw.commons.OkHttpConnectionFactory$CommonHeaderRequestInterceptor.intercept(OkHttpConnectionFactory.java:63)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.Observable.subscribe(Observable.java:12253)
	at io.reactivex.Observable.subscribe(Observable.java:12181)
	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileToStash$2$UploadClient(UploadClient.java:106)
	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$o9957uEjSG2yFmKju6TjCB8UUak.accept(Unknown Source:19)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableFromIterable$FromIterableDisposable.run(ObservableFromIterable.java:98)
	at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:58)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.Observable.subscribe(Observable.java:12253)
	at io.reactivex.Observable.subscribe(Observable.java:12155)
	at io.reactivex.Observable.forEach(Observable.java:9105)
	at fr.free.nrw.commons.upload.UploadClient.uploadFileToStash(UploadClient.java:83)
	at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$2$UploadService(UploadService.java:269)
	at fr.free.nrw.commons.upload.-$$Lambda$UploadService$Mykz4B1wymjq4LCG_9JtKi5_-pY.apply(Unknown Source:8)
	at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:70)
	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

2020-08-31 21:40:27,742     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : gps's status changed to 1
2020-08-31 21:40:31,244     [ERROR] [file-logging-thread-1] [ContributionBoundaryCallback$fetchContributions] : Failed to fetch contributions: timeout
2020-08-31 21:40:31,471     [ERROR] [file-logging-thread-1] [ContributionBoundaryCallback$fetchContributions] : Failed to fetch contributions: timeout
2020-08-31 21:40:31,491     [ERROR] [file-logging-thread-1] [ContributionBoundaryCallback$fetchContributions] : Failed to fetch contributions: timeout
2020-08-31 21:40:41,003     [ERROR] [file-logging-thread-1] [ContributionBoundaryCallback$fetchContributions] : Failed to fetch contributions: timeout
2020-08-31 21:40:47,924     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : gps's status changed to 1
2020-08-31 21:41:09,195     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : gps's status changed to 1
2020-08-31 21:41:31,365     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : gps's status changed to 1
2020-08-31 21:41:59,428     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : gps's status changed to 1
2020-08-31 21:42:27,676     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : on location changed
2020-08-31 21:42:27,685     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : gps's status changed to 1
2020-08-31 21:42:50,894     [DEBUG] [file-logging-thread-1] [UploadService] : Stash upload response 1 is StashUploadResult(state=SUCCESS, fileKey=17qbh2m96qi0.6nexud.27103.jpg)
2020-08-31 21:42:50,904     [DEBUG] [file-logging-thread-1] [UploadService] : making sure of uniqueness of name: strange eggplant.jpg
2020-08-31 21:42:55,402     [DEBUG] [file-logging-thread-1] [UploadService] : Stash upload response 2 is UploadResult(result=Success, filekey=null, offset=0, filename=Strange_eggplant.jpg)
2020-08-31 21:42:55,878     [DEBUG] [file-logging-thread-1] [WikidataEditService] : EntityId for image was received successfully: 93707744
2020-08-31 21:42:56,461     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : gps's status changed to 1
2020-08-31 21:42:57,327     [DEBUG] [file-logging-thread-1] [WikidataEditService] : DEPICTS property was set successfully for 93707744
2020-08-31 21:42:57,329     [DEBUG] [file-logging-thread-1] [WikidataEditService] : edit response: true
2020-08-31 21:42:58,832     [DEBUG] [file-logging-thread-1] [WikidataEditService] : Caption successfully set, revision id = org.wikipedia.dataclient.mwapi.MwPostResponse@27c5a37[success=1,errors=<null>]
2020-08-31 21:42:58,836     [DEBUG] [file-logging-thread-1] [WikidataEditService] : edit response: true
```

**Comment by maskaravivek** [comment]
Yes, this is due to my recent changes. I will try to fix it as soon as possible.

**Comment by maskaravivek** [comment]
@nicolas-raoul I have added a fix for it but I wasn't able to reproduce the issue(as I couldn't replicate flaky internet situation). It would be great if you could help in testing #3916

**Comment by ashishkumar468** [comment]
@nicolas-raoul  This seems to be fixed, although we do have a failure issue, I can't seem to produce this, do the latest commits by @maskaravivek not fix this for you?

**Comment by nicolas-raoul** [comment]
I have not gotten this for a while, thanks all! :-)
