### ISSUE TITLE
Upload fails immediately. App freshly reset, fast Internet

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3926]
2.13.1

I have sent a log with the same title.
I can reproduce if you need

Logcat
```
java.lang.IllegalArgumentException: Unexpected char 0x4e16 at 48 in Content-Disposition value: form-data; name="file"; filename="Temp_226963455世田谷公園公園管理事務所.jpg"
	at okhttp3.Headers.checkValue(Headers.java:272)
	at okhttp3.Headers.of(Headers.java:224)
	at okhttp3.MultipartBody$Part.createFormData(MultipartBody.java:259)
	at fr.free.nrw.commons.upload.UploadClient.uploadFileToStash(UploadClient.java:44)
	at fr.free.nrw.commons.upload.UploadService.lambda$uploadContribution$2$UploadService(UploadService.java:235)
	at fr.free.nrw.commons.upload.-$$Lambda$UploadService$1SCovDN7mw1DtV3vnSpT23zFZcQ.apply(Unknown Source:8)
	at io.reactivex.internal.operators.observable.ObservableScalarXMap.tryScalarXMapSubscribe(ObservableScalarXMap.java:70)
	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:51)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by misaochan** [comment]
@nicolas-raoul , do you mean that the upload failure is completely reproducible for you?

**Comment by nicolas-raoul** [comment]
Yes. It does not happen all the time but I was able to reproduce it now. I just sent a log 🙂
Sorry if it is a bug already fixed on master.

**Comment by asraman9792** [comment]
Hello is this issue available to work or has been resolved ?

**Comment by nicolas-raoul** [comment]
@asraman9792 Sorry I forgot to mark this issue as fixed! Thanks for the hint.
