### ISSUE TITLE
App doesnt run on Samsung Galaxy A50

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3944]
**Summary:** 
Current master does not run on Samsung Galaxy A50, Android 10. Shows nonsense error log:

```
2020-09-29 20:31:52.967 15325-15325/fr.free.nrw.commons E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "fr.free.nrw.commons.commons" on path: DexPathList[[zip file "/data/app/fr.free.nrw.commons-crShAtwg6Xqu2CciYymEMw==/base.apk"],nativeLibraryDirectories=[/data/app/fr.free.nrw.commons-crShAtwg6Xqu2CciYymEMw==/lib/arm64, /data/app/fr.free.nrw.commons-crShAtwg6Xqu2CciYymEMw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

```
     Caused by: java.io.FileNotFoundException: /proc/net/xt_qtaguid/stats: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at X.1EV.A00(:17)
        at X.1BT.A02(:52) 
        at X.2QH.run(:10) 
        at X.0u2.run(:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at X.250.run(:3) 
        at X.0uF.run(:12) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
```

```
2020-09-29 20:44:47.110 15896-17708/fr.free.nrw.commons E/ACRA: ACRA caught a IllegalStateException for fr.free.nrw.commons
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
        at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
```

**Comment by misaochan** [comment]
Are you building from AS, @neslihanturan ? The first log looks like a build issue, try cleaning and rebuilding?

**Comment by neslihanturan** [comment]
I tried with fresh install + cleaning the AS. It shows me the login screen but it crashes as soon as I logged in. With no meaningful error at all:/

```
java.lang.SecurityException: Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps from pid=13955, uid=10143 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()
        at android.content.ContentProvider.enforceWritePermissionInner(ContentProvider.java:824)
```

**Comment by ashishkumar468** [comment]
@neslihanturan  This seems to be a migration error, you must have switched out from one of the release branches to master. As of now, our release branches are not always up to date with master and vice-versa
