### ISSUE TITLE
Cannot GET /en.wikipedia.org/v1/page/media-list/ ; RuntimeException: fileexists-no-change at uploadFileFromStash

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3967]
I have some trouble uploading a particular file. Maybe I mistakenly paused it, and also I noticed a "Wikipedia" symbol on it in gallery, it is the first time I see that symbol, not sure if related.
```
10-18 18:19:45.914  8261  5482 I okhttp.OkHttpClient: --> GET https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=query&meta=tokens&type=csrf
10-18 18:19:45.915  8261  5482 D CookieManager: Domain:commons.wikimedia.org
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: <-- HTTP FAILED: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 404, URL: https://en.wikipedia.org/api/rest_v1/page/media-list/, title: Not found., detail: <!DOCTYPE html>
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: <html lang="en">
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: <head>
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: <meta charset="utf-8">
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: <title>Error</title>
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: </head>
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: <body>
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: <pre>Cannot GET /en.wikipedia.org/v1/page/media-list/</pre>
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: </body>
10-18 18:19:46.080  8261  5477 I okhttp.OkHttpClient: </html>
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: <-- HTTP FAILED: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 404, URL: https://en.wikipedia.org/api/rest_v1/page/media-list/, title: Not found., detail: <!DOCTYPE html>
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: <html lang="en">
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: <head>
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: <meta charset="utf-8">
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: <title>Error</title>
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: </head>
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: <body>
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: <pre>Cannot GET /en.wikipedia.org/v1/page/media-list/</pre>
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: </body>
10-18 18:19:46.081  8261  5484 I okhttp.OkHttpClient: </html>
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: <-- HTTP FAILED: org.wikipedia.dataclient.okhttp.HttpStatusException: Code: 404, URL: https://en.wikipedia.org/api/rest_v1/page/media-list/, title: Not found., detail: <!DOCTYPE html>
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: <html lang="en">
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: <head>
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: <meta charset="utf-8">
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: <title>Error</title>
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: </head>
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: <body>
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: <pre>Cannot GET /en.wikipedia.org/v1/page/media-list/</pre>
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: </body>
10-18 18:19:46.090  8261  4291 I okhttp.OkHttpClient: </html>
10-18 18:19:46.283  8261  5482 I okhttp.OkHttpClient: <-- 200 https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=query&meta=tokens&type=csrf (368ms, unknown-length body)
10-18 18:19:46.286  8261  5482 I okhttp.OkHttpClient: --> POST https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&ignorewarnings=1 (1464-byte body)
10-18 18:19:46.287  8261  5482 D CookieManager: Domain:commons.wikimedia.org
10-18 18:19:48.657  8261  5482 I okhttp.OkHttpClient: <-- 200 https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&ignorewarnings=1 (2370ms, unknown-length body)
10-18 18:19:48.665  8261  5482 E UploadService: Error occurred in uploading file from stash
10-18 18:19:48.665  8261  5482 E UploadService: java.lang.RuntimeException: fileexists-no-change
10-18 18:19:48.665  8261  5482 E UploadService: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileFromStash$3$UploadClient(UploadClient.java:230)
10-18 18:19:48.665  8261  5482 E UploadService: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$-xVSLroq3t059tyyfYuDUQukbVk.apply(Unknown Source:4)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
10-18 18:19:48.665  8261  5482 E UploadService: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
10-18 18:19:48.665  8261  5482 E UploadService: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
10-18 18:19:48.665  8261  5482 E UploadService: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-18 18:19:48.665  8261  5482 E UploadService: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
10-18 18:19:48.665  8261  5482 E UploadService: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
10-18 18:19:48.665  8261  5482 E UploadService: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-18 18:19:48.665  8261  5482 E UploadService: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-18 18:19:48.665  8261  5482 E UploadService: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-18 18:19:48.665  8261  5482 E UploadService: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-18 18:19:48.665  8261  5482 E UploadService: 	at java.lang.Thread.run(Thread.java:764)
10-18 18:19:48.672  8261  5482 W UploadService: Exception during upload
10-18 18:19:48.672  8261  5482 W UploadService: java.lang.RuntimeException: fileexists-no-change
10-18 18:19:48.672  8261  5482 W UploadService: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileFromStash$3$UploadClient(UploadClient.java:230)
10-18 18:19:48.672  8261  5482 W UploadService: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$-xVSLroq3t059tyyfYuDUQukbVk.apply(Unknown Source:4)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
10-18 18:19:48.672  8261  5482 W UploadService: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
10-18 18:19:48.672  8261  5482 W UploadService: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
10-18 18:19:48.672  8261  5482 W UploadService: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-18 18:19:48.672  8261  5482 W UploadService: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
10-18 18:19:48.672  8261  5482 W UploadService: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
10-18 18:19:48.672  8261  5482 W UploadService: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-18 18:19:48.672  8261  5482 W UploadService: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-18 18:19:48.672  8261  5482 W UploadService: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-18 18:19:48.672  8261  5482 W UploadService: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-18 18:19:48.672  8261  5482 W UploadService: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by sivaraam** [comment]
I'm not sure about why you got the "Cannot GET ..." error. I just thought of clarifying that the Wikipedia icon for the image should've come from the implementation for #872 (done in PR #3783) for which we use [`media-list`](https://en.wikipedia.org/api/rest_v1/#/Page%20content/getContent-media-list) API to get a list of images associated with the corresponding Wikipedia article. Ideally, the icon should be shown only for images which have already been uploaded.

The runtime exception appears to be related to the upload process, though.
