### ISSUE TITLE
Hitting on on My Rank in leaderboard section crashes the application

### ISSUE THREAD

**Issue by harshchinu** [commons-app/apps-android-commons#3996]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)
If you haven't made any contribution then my rank button should be disabled or tell the user use to make some contribution but it crashes the application

**Steps to reproduce:** 

How can we reproduce the issue? 
Signup with a new account or use an account with 0 contributions and go to profile and then the leaderboard 
it will display a message you haven't made any contribution then we click on okay on the dialog box then and then click on my rank in the fragment

What did you expect the app to do, and what did you see instead?
Well I was expecting a toast or message that go do some contribution but instead, the application got crashed

**System logs:**

```
Add logcat files here (if possible).
  Process: fr.free.nrw.commons.beta, PID: 731
    java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at fr.free.nrw.commons.profile.leaderboard.LeaderboardFragment.scrollToUserRank(LeaderboardFragment.java:181)
        at fr.free.nrw.commons.profile.leaderboard.LeaderboardFragment.lambda$onCreateView$0$LeaderboardFragment(LeaderboardFragment.java:159)
        at fr.free.nrw.commons.profile.leaderboard.-$$Lambda$LeaderboardFragment$inILp4O8S6TD2ALCIIkG2aFuFI4.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27340)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Need help? See https://github.com/commons-app/apps-android-commons/wiki/Getting-app-logs-from-Android-Studio
```

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Is it the stock version from the manufacturer or a custom ROM ?
 
**Commons app version:** 

You can find this information by going to the navigation drawer in the app and tapping 'About'. If you are building from our codebase instead of downloading the app, please also mention the branch and build variant (e.g. master and prodDebug).

**Screen-shots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Would you like to work on the issue?**

Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.

**Comment by harshchinu** [comment]
I have solved this bug can PR for it as well?

**Comment by misaochan** [comment]
Yes, please feel free @harshchinu , thanks!
