### ISSUE TITLE
Crash while scrolling media on contributions screen

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#4012]
**Summary:** 

Crash while scrolling media on contributions screen

**System logs:**

```
USER_COMMENT=
APP_VERSION_CODE=775
APP_VERSION_NAME=2.13.1-debug-chunkSize
ANDROID_VERSION=9
PHONE_MODEL=SM-G970F
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'fr.free.nrw.commons.Media fr.free.nrw.commons.contributions.Contribution.getMedia()' on a null object reference
	at fr.free.nrw.commons.contributions.ContributionViewHolder.init(ContributionViewHolder.java:67)
	at fr.free.nrw.commons.contributions.ContributionsListAdapter.onBindViewHolder(ContributionsListAdapter.java:49)
	at fr.free.nrw.commons.contributions.ContributionsListAdapter.onBindViewHolder(ContributionsListAdapter.java:14)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7093)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7172)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6037)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6304)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6143)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6139)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:560)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4141)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3853)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4410)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)
	at android.view.View.layout(View.java:22420)
	at android.view.ViewGroup.layout(ViewGroup.java:6579)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3343)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2807)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1853)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8476)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7032)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

IS_SILENT=false
USER_EMAIL=
USER_CRASH_DATE=2020-11-04T19:02:25.319+09:00
REPORT_ID=1a504546-ac7a-4adb-8343-8a5a00e7c77f
```

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Is it the stock version from the manufacturer or a custom ROM ?
 
**Commons app version:** 

master

**Comment by nicolas-raoul** [comment]
It was mine, there has been code changes and it has not happened again, so I will close now, and only reopen if it happens again.
