### ISSUE TITLE
App crashes when back button presses on ContributionFragment

### ISSUE THREAD

**Issue by gouri-panda** [commons-app/apps-android-commons#4084]
**Summary:** 
Application crashes when back button presses on the ContributionFragment.

**Steps to reproduce:** 
* Open App
* Press Back button
<details> 
  <summary>System Logs</summary> 

``` 
     2020-12-07 19:29:07.724 13139-13139/fr.free.nrw.commons.beta E/InputEventSender: Exception dispatching finished signal.
2020-12-07 19:29:07.724 13139-13139/fr.free.nrw.commons.beta E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2020-12-07 19:29:07.724 13139-13139/fr.free.nrw.commons.beta E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.free.nrw.commons.media.MediaDetailPagerFragment.isVisible()' on a null object reference
        at fr.free.nrw.commons.contributions.ContributionsFragment.backButtonClicked(ContributionsFragment.java:599)
        at fr.free.nrw.commons.contributions.MainActivity.onBackPressed(MainActivity.java:239)
        at android.app.Activity.onKeyUp(Activity.java:3715)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2864)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4064)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:418)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6111)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5971)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5428)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5488)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5447)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5612)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5455)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5669)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5428)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5488)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5447)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5455)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5428)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5488)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5447)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5645)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5810)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3230)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2773)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2764)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3207)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:182)
        at android.app.ActivityThread.main(ActivityThread.java:7802)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
2020-12-07 19:29:07.727 13139-13139/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
```
</details>

**Device and Android version:** 
* Branch: master
* Device: Realme
* Android version: 10

**Screen-shots:**
NA

**Would you like to work on the issue?**
yes

**Comment by Prince-kushwaha** [comment]
this issue is same as #4081

**Comment by Prince-kushwaha** [comment]
I solved this issue make PR in few day
you work on different issue
