### ISSUE TITLE
Crash when tapping on the nearbyNotification in Contributions activity

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4086]
**Summary:** 
In new UI when click on the nearbyNotification content  app crash
**Steps to reproduce:** 
**Go to Contributions 
click on the nearbyNotification** 

![Screenshot_2020-12-08-10-12-53-464_fr free nrw commons beta](https://user-images.githubusercontent.com/65972015/101441408-084e3c80-393f-11eb-97f8-94d60929eac5.jpg)

**System logs:**

Add logcat files here (if possible).
2020-12-07 21:44:02.773 20043-20043/fr.free.nrw.commons.beta E/SwipableCardView: 0
2020-12-07 21:44:02.802 20043-20043/fr.free.nrw.commons.beta E/SwipableCardView: 1
2020-12-07 21:44:02.873 20043-20043/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    **Process: fr.free.nrw.commons.beta, PID: 20043
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources androidx.fragment.app.FragmentActivity.getResources()' on a null object reference
        at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.centerMapToPlace(NearbyParentFragment.java:655)
        at fr.free.nrw.commons.contributions.MainActivity.centerMapToPlace(MainActivity.java:305)
        at fr.free.nrw.commons.nearby.NearbyNotificationCardView.lambda$setActionListeners$0$NearbyNotificationCardView(NearbyNotificationCardView.java:86)
        at fr.free.nrw.commons.nearby.-$$Lambda$NearbyNotificationCardView$VOPNkXLFp2_oU8vL3IdOKygUkxo.onClick(Unknown Source:4)**
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25919)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
**Device and Android version:**
Android device:Redmi y3 
API:29

**Commons app version:** 
2.13.1~debug

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
i fixes

**Comment by Prince-kushwaha** [comment]
assigned to me

**Comment by nicolas-raoul** [comment]
I can reproduce on latest master.
Thanks for spotting this bug!

**Comment by Prince-kushwaha** [comment]
Pull request is create

**Comment by 4D17Y4** [comment]
Hey, 
I can help here.

Let me walk through the issue,
So first when the the notification is tapped,

https://github.com/commons-app/apps-android-commons/blob/f1b40728b2a21a768428c3181f898e66829e55dd/app/src/main/java/fr/free/nrw/commons/contributions/MainActivity.java#L294-L297

is called which in turn calls the function with same name in nearby fragment

https://github.com/commons-app/apps-android-commons/blob/9e92c95d425a53f98d0b845ea0ef7605af711d24/app/src/main/java/fr/free/nrw/commons/nearby/fragments/NearbyParentFragment.java#L647-L655

now as we have called the getActivity() (line 655) from here and the fragment isnt ready (ie not atttched ) it crashes.
but as we look closely the mere task of this call was to set lastPlacetoCentre to place.

now for the solution part,
if we add 
`if(null == getActivity())
{
   return;
}`

just before checking if lastPlacetoCentre is null (or multiple condition in same if) we can restrict the function to just set the lastPlacetoCentre to place and thus fixing the issue.

For those wondering that after this the map wont be centered, I must mention that the function is also called after the fragment is attached 

https://github.com/commons-app/apps-android-commons/blob/b8ba89d077fd9b23781884a6468d634e84a4a21d/app/src/main/java/fr/free/nrw/commons/nearby/presenter/NearbyParentFragmentPresenter.java#L229-L234

and the place parameter is null this time therefore the lastPlacetoCentre doesn't change and map centers to required location (ie the place in notification) and solving the issue.

Let me know if I missed something @misaochan @neslihanturan @nicolas-raoul .

I will link PR if this is accepted, Thx.

**Comment by Prince-kushwaha** [comment]
Actually this issue is closed by my pull request #4105

**Comment by Prince-kushwaha** [comment]
Actually this issue is closed by my pull request #4105 and merged

**Comment by misaochan** [comment]
Hi @Prince-kushwaha , there are reviews on your PR #4092 requesting you to rethink the way you are handling the solution, as simply adding a fixed delay is a bandaid. What do you think about the suggestion that @4D17Y4 made instead?

**Comment by Prince-kushwaha** [comment]
Ok

**Comment by Prince-kushwaha** [comment]
@misaochan  idea suggested by @4D17Y4  is good . I also implemented the idea of //@4D17Y4//  it,s solve this issue in better way
