### ISSUE TITLE
Crash when tapping on "Nearby item" card in Contributions

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4116]
**Summary:** 

Tapping on the Nearby item card in Contributions crashes the app.

**Steps to reproduce:** 

Make sure your GPS is on and you have location permissions enabled for the app. When the card at the top of Contributions screen appears, tap it.

**System logs:**

STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources androidx.fragment.app.FragmentActivity.getResources()' on a null object reference
	at fr.free.nrw.commons.nearby.fragments.NearbyParentFragment.centerMapToPlace(NearbyParentFragment.java:655)
	at fr.free.nrw.commons.contributions.MainActivity.centerMapToPlace(MainActivity.java:296)
	at fr.free.nrw.commons.nearby.NearbyNotificationCardView.lambda$setActionListeners$0$NearbyNotificationCardView(NearbyNotificationCardView.java:86)
	at fr.free.nrw.commons.nearby.-$$Lambda$NearbyNotificationCardView$VOPNkXLFp2_oU8vL3IdOKygUkxo.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Device and Android version:** 

Samsung Galaxy S20FE, Android 10

**Commons app version:** 

ProdRelease, e454cfd98fe7537a9b95960031aa46edaf7a50ab

**Would you like to work on the issue?**

No

**Comment by Saral-code** [comment]
I would like to work on this issue. I think I can fix that.

**Comment by misaochan** [comment]
Great, please feel free to start on this once you have a PR up for #4115 @Saral-code

**Comment by Prince-kushwaha** [comment]
This issue is already create - #4086 and and solved my pull request  #4105

**Comment by misaochan** [comment]
Sorry about that, this is indeed a duplicate of #4086 , closing for redundancy.
