### ISSUE TITLE
App Crashes on logging out

### ISSUE THREAD

**Issue by Pratham2305** [commons-app/apps-android-commons#4129]
**Summary:** 
App crashes when trying to log out.

**Steps to reproduce:** 
Go to More tab on Bottom Navigation Bar.
click on log out then select yes on alert dialog.

What did you expect the app to do, and what did you see instead?
User should  log out and login screen should appear, but app crashes instead.

**System logs:**

Add logcat files here (if possible).

2020-12-25 22:37:05.305 23964-23964/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 23964
    kotlin.KotlinNullPointerException
        at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.fetchContributions(ContributionBoundaryCallback.kt:54)
        at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.onZeroItemsLoaded(ContributionBoundaryCallback.kt:30)
        at androidx.paging.PagedList$1.run(PagedList.java:476)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-12-25 22:37:05.305 23964-23964/fr.free.nrw.commons.beta E/ACRA: ACRA caught a KotlinNullPointerException for fr.free.nrw.commons.beta
    kotlin.KotlinNullPointerException
        at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.fetchContributions(ContributionBoundaryCallback.kt:54)
        at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.onZeroItemsLoaded(ContributionBoundaryCallback.kt:30)
        at androidx.paging.PagedList$1.run(PagedList.java:476)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Device and Android version:** 
Device: Motorola One Fusion+, Android 10
 
**Commons app version:** 
2.13.1-debug
Branch: Master, Build Variant: betaDebug

**Would you like to work on the issue?**
 Yes

**Comment by mrudultora** [comment]
@Pratham2305 Unable to reproduce.

**Comment by mrudultora** [comment]
@nicolas-raoul This is a valid issue. I am able to reproduce this issue randomly. @Pratham2305 If you are not working on this, would you mind if I take this up ?

**Comment by Pratham2305** [comment]
@mrudultora  Sure, you can go for it. I am currently on another issue, But It would be better if any mentor approved this one then you can start :-)

**Comment by nicolas-raoul** [comment]
Thanks @Pratham2305 for reporting the issue and for your fairness!
@mrudultora I see you currently have no assigned issue without a pending pull request, so you can take this one, thanks!

**Comment by nicolas-raoul** [comment]
I can reproduce the issue on latest master:
```
02-23 20:33:06.641  5618  5640 D RestrictionPolicy: isLocalContactStorageAllowed(0) : true
02-23 20:33:06.641 31688 31688 E AndroidRuntime: FATAL EXCEPTION: main
02-23 20:33:06.641 31688 31688 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 31688
02-23 20:33:06.641 31688 31688 E AndroidRuntime: kotlin.KotlinNullPointerException
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.fetchContributions(ContributionBoundaryCallback.kt:54)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at fr.free.nrw.commons.contributions.ContributionBoundaryCallback.onZeroItemsLoaded(ContributionBoundaryCallback.kt:30)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at androidx.paging.PagedList$1.run(PagedList.java:476)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7032)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-23 20:33:06.641 31688 31688 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
02-23 20:33:06.641 31688 31688 E ACRA    : ACRA caught a KotlinNullPointerException for fr.free.nrw.commons
```
