### ISSUE TITLE
App Crashes on viewing reviews in Review Fragment

### ISSUE THREAD

**Issue by shabar-shab** [commons-app/apps-android-commons#4132]
**Summary**:

On viewing the reviews (Peer Review)  in Review Fragment app continuously crashes.

**Steps to reproduce:** 

- In bottom Navigation Bar got to Hamburger button (three stacked parallel  line)
- click Review 
- on viewing review parameter " is this image correctly categorized "app crashes

**System logs:**

```
2020-12-26 13:07:58.620 28060-28060/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wikipedia.dataclient.mwapi.MwQueryPage$Revision.getUser()' on a null object reference
        at fr.free.nrw.commons.review.ReviewImageFragment.onCreateView(ReviewImageFragment.java:119)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1816)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:262)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
2020-12-26 13:07:58.743 28060-28060/fr.free.nrw.commons.beta I/Process: Sending signal. PID: 28060 SIG: 9

```

**Device and Android version:** 

 Samsung Galaxy j2, Version 5.0.1(Lollipop) did you encounter this on?
 Android version 5.0.1 Lollipop 
 Custom ROM 
 
**Commons app version:** 

2.13.1-debug-master

**Would you like to work on the issue?**

yes, After finishing  working on pervious issue assigned, until then any one want to work will be appreciated

**Comment by shabar-shab** [comment]
I have started working on this.
