### ISSUE TITLE
click on skip button in Peer Review after orientation change then app is crashed

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4143]
**Summary:** 

**issue :  when  click on skip button in Peer Review after  orientation change  then app is crashed** 

**Step to Reproduce the issue**

1. Open the Peer Review Activity 
2. change the orientation of screen 
3. click on the button "skip this image"
4. then App crash

**Screenshot for first issue **

![20210103_102548](https://user-images.githubusercontent.com/65972015/103472142-d4d0c780-4daf-11eb-802f-8846e991d8e4.gif)
**System logs:**
2020-12-31 18:14:01.518 26369-26369/fr.free.nrw.commons.beta E/ACRA: ACRA caught a NullPointerException for fr.free.nrw.commons.beta
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setEnabled(boolean)' on a null object reference**
        at fr.free.nrw.commons.review.ReviewImageFragment.disableButtons(ReviewImageFragment.java:199)
        at fr.free.nrw.commons.review.ReviewPagerAdapter.disableButtons(ReviewPagerAdapter.java:51)
        at fr.free.nrw.commons.review.ReviewActivity.lambda$onCreate$0$ReviewActivity(ReviewActivity.java:116)
        at fr.free.nrw.commons.review.-$$Lambda$ReviewActivity$-LATUATvQAPhlK652ow3LysvMck.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25919)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Device and Android version:** 
Android Device:Redmi y3;
API :29

**Commons app version:** 
2.13.1 or current master branch 
  
**Would you like to work on the issue?**
YES

Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
Yes

**Comment by nicolas-raoul** [comment]
On latest master even after a configuration change (theme switch) I am not able to reproduce the first issue (no crash), nor the second issue (different image appears), nor the third issue.
Would you mind posting a screencast (including the configuration change) and the full logcat, on the latest master branch? Thanks!

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul bug are in latest master i upload screershot for each bug

**Comment by nicolas-raoul** [comment]
@Prince-kushwaha Thanks for the screencasts, very helpful!
By "configuration change" I think you meant "orientation change", I understand now :-)

**Comment by neslihanturan** [comment]
I can not reproduce the issue, can you please explain the steps more briefly? You can use bullet list that composed of steps instead of a sentence.

**Comment by neslihanturan** [comment]
Also, I recognized 2 issues are listed under this same issue. This causes confusion, please make sure you created singe issue for each one. Please make sure you followed issue and PR creation documentations. These kinds of issues that prepared out of guidelines confuses reviewers and makes things harder.

**Comment by Prince-kushwaha** [comment]
@neslihanturan these  issues are present in latest master I add steps to Reproduce these two  issues

**Comment by Prince-kushwaha** [comment]
I listed 2 issue under this same issue becouse the cause of these  issues is same
