### ISSUE TITLE
App crashes while back press on the home-screen

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#4179]
**Summary:** 

App crashes while back press on the home-screen
(Reported by one of the users via email)

**Steps to reproduce:** 
1. Open the app
2. Back press

**System logs:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.free.nrw.commons.media.MediaDetailPagerFragment.isVisible()' on a null object reference
	at fr.free.nrw.commons.contributions.ContributionsFragment.backButtonClicked(ContributionsFragment.java:620)
	at fr.free.nrw.commons.contributions.MainActivity.onBackPressed(MainActivity.java:242)
	at android.app.Activity.onKeyUp(Activity.java:3645)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2825)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3969)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:393)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5511)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5379)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4886)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4939)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4905)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5045)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4913)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5102)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4886)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4939)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4905)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4913)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4886)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4939)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4905)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5078)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5239)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3064)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2607)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2598)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3041)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:343)
	at android.os.Looper.loop(Looper.java:188)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Device and Android version:** 
Android Version 10

**Commons app version:** 

3.0.0

**Would you like to work on the issue?**

Yes

**Comment by ashishkumar468** [comment]
Fix has been merged to 3-0- release
