### ISSUE TITLE
App crash in CategoryDetailsActivity when click on any media

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4196]
**Summary:** 
In the CategoryDetalis Activity click on any medai  (image or video) then App crash

**Steps to reproduce:** 
See in ScreenShot

What did you expect the app to do, and what did you see instead?
App not crash in the CategoryDetails Activity  on click on any medai (image,video)

 **System logs:**

 java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateView(MediaDetailPagerFragment.java:103)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
        at fr.free.nrw.commons.category.CategoryDetailsActivity.onMediaClicked(CategoryDetailsActivity.java:122)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2$1.invoke(PageableMediaFragment.kt:17)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2$1.invoke(PageableMediaFragment.kt:14)
        at fr.free.nrw.commons.explore.media.SearchImagesViewHolder$bind$1.onClick(PagedMediaAdapter.kt:37)

**Device and Android version:** 
 Android Device:Redmi y3

**Commons app version:** 
 Latest Master

**Screen-shots:** 

https://user-images.githubusercontent.com/65972015/105280190-3033ef80-5bcf-11eb-9d00-ee29723dbe8b.mp4

**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by Prince-kushwaha** [comment]
Can I work on this issue

**Comment by madhurgupta10** [comment]
@Prince-kushwaha Thanks for reporting the issue, feel free to work on it.

**Comment by mrudultora** [comment]
@Prince-kushwaha Are you still working on this ? If not, then please inform :-)

**Comment by Prince-kushwaha** [comment]
Yes

**Comment by Prince-kushwaha** [comment]
@mrudultora  I am work on this issue

**Comment by mrudultora** [comment]
@Prince-kushwaha Okay ;-)

**Comment by nicolas-raoul** [comment]
I am able to reproduce the crash on latest master.
