### ISSUE TITLE
App crashes when pressing back button in bookmarks fragment

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4226]
**Summary:** 

When I try to close the bookmarks fragment by pressing back button the app crashes

**Steps to reproduce:** 
Go to bookmarks tab. Press back button.

**System logs:**

> 2021-02-13 12:22:53.623 32617-32617/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
Process: fr.free.nrw.commons.beta, PID: 32617
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.free.nrw.commons.media.MediaDetailPagerFragment.isVisible()' on a null object reference
at fr.free.nrw.commons.bookmarks.BookmarkListRootFragment.backPressed(BookmarkListRootFragment.java:175)
at fr.free.nrw.commons.bookmarks.BookmarkFragment.onBackPressed(BookmarkFragment.java:77)
at fr.free.nrw.commons.contributions.MainActivity.onBackPressed(MainActivity.java:250)

**Device and Android version:** 
Device Model (Redmi Note 7S)
Android Version (Android 10)
 
**Commons app version:** 
App Version is 2.13.1-debug-master~c19858069
Build Variant is betaDebug

**Screen-shots:** 

https://user-images.githubusercontent.com/65870389/107846487-1f5f4e00-6e0a-11eb-8cba-1b3681214ae5.mp4

**Would you like to work on the issue?**
**Yes**

**Comment by mrudultora** [comment]
Can I work on this ?
