### ISSUE TITLE
App crash in WikidataItemDetailsActivity on clicking any media

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4244]
**Summary:** 

On clicking any media in **WikidataItemDetailsActivity** the app crashes ( Point to note here is I am not talking about **CategoryDetailsActivity**). A similar issue was fixed few days ago but was fixed in a wrong way.

**Steps to reproduce:** 

https://user-images.githubusercontent.com/65870389/108374564-1960d700-7227-11eb-9408-7c18d70b96ce.mp4

What did you expect the app to do, and what did you see instead?
The media must open in _**MediaDetailsFragment**_.

**System logs:**

```
2021-02-18 20:12:59.037 11542-11542/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 11542
    java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateView(MediaDetailPagerFragment.java:103)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
        at fr.free.nrw.commons.explore.depictions.WikidataItemDetailsActivity.onMediaClicked(WikidataItemDetailsActivity.java:133)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2$1.invoke(PageableMediaFragment.kt:17)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2$1.invoke(PageableMediaFragment.kt:14)
        at fr.free.nrw.commons.explore.media.SearchImagesViewHolder$bind$1.onClick(PagedMediaAdapter.kt:37)
        at android.view.View.performClick(View.java:7185)
```

**Device and Android version:** 
Redmi Note 7S (Android 10).

**Commons app version:** 
3.0.0-debug-master~850d9411a

**Would you like to work on the issue?**
**Yes**, I would like to work on this issue.

**Comment by nicolas-raoul** [comment]
I can reproduce in latest master.
