### ISSUE TITLE
App is Crash when click on  Bookmark  Bottom navigation bar icon or open Bookmark At Android API Level 25

### ISSUE THREAD

**Issue by Prince-kushwaha** [commons-app/apps-android-commons#4253]
**Summary:** 

App is Crash when click on Bookmark Bottom navigation bar icon or open Bookmark At Android API Level 25
but it is not crash on API Level 28

**Steps to reproduce:** 

1. Open the app
2. click on Bookmark Bottom navigation bar icon 
3. then App is crash

What did you expect the app to do, and what did you see instead?
App not crash 
**System logs:**

```
     --------- beginning of crash
2021-02-20 00:11:27.461 27665-27665/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 27665
    android.database.sqlite.SQLiteException: no such table: bookmarksLocations (code 1): , while compiling: SELECT location_name, location_description, location_category, location_label_text, location_label_icon, location_lat, location_long, location_image_url, location_wikipedia_link, location_wikidata_link, location_commons_link, location_pic, location_destroyed FROM bookmarksLocations
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:419)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:296)
        at fr.free.nrw.commons.bookmarks.locations.BookmarkLocationsContentProvider.query(BookmarkLocationsContentProvider.java:61)
        at android.content.ContentProvider.query(ContentProvider.java:1030)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:145)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:127)
        at fr.free.nrw.commons.bookmarks.locations.BookmarkLocationsDao.getAllBookmarksLocations(BookmarkLocationsDao.java:48)
        at fr.free.nrw.commons.bookmarks.locations.BookmarkLocationsController.loadFavoritesLocations(BookmarkLocationsController.java:24)
        at fr.free.nrw.commons.bookmarks.locations.BookmarkLocationsFragment.initList(BookmarkLocationsFragment.java:85)
        at fr.free.nrw.commons.bookmarks.locations.BookmarkLocationsFragment.onResume(BookmarkLocationsFragment.java:78)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:363)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1197)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2581)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2756)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:363)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1197)
        at androidx.fragment.app.FragmentManager.performPendingDeferredStart(FragmentManager.java:1109)
        at androidx.fragment.app.FragmentManager.startPendingDeferredFragments(FragmentManager.java:1517)
        at androidx.fragment.app.FragmentManager.doPendingDeferredStart(FragmentManager.java:2285)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1823)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:238)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:19886)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
2021-02-20 00:11:27.462 27665-27665/fr.free.nrw.commons E/AndroidRuntime:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19886)
 

```

**Device and Android version:** 
Device :Redmi 4
Android Version :25
**Commons app version:** 
Latest master (3.0.0)
**Would you like to work on the issue?**
YES
Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.
YES

**Comment by mrudultora** [comment]
@Prince-kushwaha Have a look at this #4142. This thread might help you.

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul can you confirm that  issue so that i work on this issue

**Comment by Prince-kushwaha** [comment]
@misaochan @madhurgupta10 @ashishkumar468 can you confirm that issue and assigned me

**Comment by Prince-kushwaha** [comment]
@misaochan @madhurgupta10 @ashishkumar468 can you confirm that issue and assigned me

**Comment by Prince-kushwaha** [comment]
@misaochan @madhurgupta10 @ashishkumar468 can you confirm that issue and assigned me

**Comment by Prince-kushwaha** [comment]
@misaochan @madhurgupta10 @ashishkumar468 can you confirm that issue and assigned me

**Comment by misaochan** [comment]
@Prince-kushwaha Could you do me a favour and test the `3.0-release branch` to see if this problem still occurs for you?

**Comment by Prince-kushwaha** [comment]
@misaochan this issue is still occur in 3.0-release branch

**Comment by nicolas-raoul** [comment]
Does it still happen after resetting the app's storage and cache?

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul app not crash after resetting the app storage and cache

**Comment by Prince-kushwaha** [comment]
@nicolas-raoul this issue some time occur and some time not occur

**Comment by misaochan** [comment]
@Prince-kushwaha you are welcome to take a look at this issue in that case. Please let us know what you find.

**Comment by Prince-kushwaha** [comment]
@misaochan this issue not present in latest master
so i close this issue
