### ISSUE TITLE
App crashes on setting avatar when not logged in

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4254]
**Summary:** 

When tapping **Set as Avatar** from menu of **MediaDetailFragment** the app crashes if the user is not logged in.

**Steps to reproduce:** 

How can we reproduce the issue? 
• Logout from your account. 
• Go to explore tab. 
• Open any image. 
• Then tap _set as avatar_ from menu. 

What did you expect the app to do, and what did you see instead?
Either the app must not show the option of setting avatar for the users not logged in.
**OR**
A dialog box must be opened on clicking it asking the user for logging in to set that image as their avatar.

**System logs:**

```
2021-02-20 00:24:20.123 17742-17742/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 17742
    java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.setAvatar(MediaDetailPagerFragment.java:234)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onOptionsItemSelected(MediaDetailPagerFragment.java:204)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2830)
        at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:2709)

```

**Device and Android version:** 
Redmi Note 7S and Android 10.
 
**Commons app version:** 
3.0.0-debug-master~b8cdc5a53

**Would you like to work on the issue?**
**Yes**.

**Comment by mrudultora** [comment]
@nicolas-raoul Your suggestions on this ?

> What did you expect the app to do, and what did you see instead?
Either the app must not show the option of setting avatar for the users not logged in.
OR
A dialog box must be opened on clicking it asking the user for logging in to set that image as their avatar.

**Comment by nicolas-raoul** [comment]
> not show the option of setting avatar for the users not logged in

This sounds like the best option to me :-)
