### ISSUE TITLE
App Crashes on changing system wide theme in WikidataItemDetailsActivity

### ISSUE THREAD

**Issue by mrudultora** [commons-app/apps-android-commons#4276]
**Summary:** 

On changing system wide theme in **WikidataItemDetailsActivity** / **CategoryDetailsActivity** and then clicking any image causes crash.

**Steps to reproduce:** 

• Open **WikidataItemDetailsActivity** / **CategoryDetailsActivity**.
• Change your system theme (Light -> Dark / Dark -> Light).
• Click any image and the app will crash.

**System logs:**

```
2021-02-24 17:15:00.439 9821-9821/fr.free.nrw.commons.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons.beta, PID: 9821
    kotlin.KotlinNullPointerException
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2.invoke(PageableMediaFragment.kt:17)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2.invoke(PageableMediaFragment.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getPagedListAdapter(Unknown Source:2)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getTotalMediaCount(PageableMediaFragment.kt:59)
        at fr.free.nrw.commons.explore.depictions.WikidataItemDetailsActivity.getTotalMediaCount(WikidataItemDetailsActivity.java:171)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter.getCount(MediaDetailPagerFragment.java:415)
        at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:532)
        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateView(MediaDetailPagerFragment.java:125)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
        at fr.free.nrw.commons.explore.depictions.WikidataItemDetailsActivity.onMediaClicked(WikidataItemDetailsActivity.java:133)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2$1.invoke(PageableMediaFragment.kt:17)
        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2$1.invoke(PageableMediaFragment.kt:14)
        at fr.free.nrw.commons.explore.media.SearchImagesViewHolder$bind$1.onClick(PagedMediaAdapter.kt:37)
        at android.view.View.performClick(View.java:7185)
        at android.view.View.performClickInternal(View.java:7162)
        at android.view.View.access$3500(View.java:819)
        at android.view.View$PerformClick.run(View.java:27684)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Device and Android version:** 
Redmi Note 7S and Android 10.

**Commons app version:** 
3.0.0-debug-master~d6dcd4390.

**Would you like to work on the issue?**
yes

**Comment by misaochan** [comment]
@mrudultora It is yours. :)

**Comment by mrudultora** [comment]
@misaochan As stated in exception, the variable declared as **lateinit** is never initialised. So, I want to ask you that can I change the lateinit variable to nullable variable. I mean will it be a good practice.

**Comment by nicolas-raoul** [comment]
@mrudultora Are you still working on this? :-)
