### ISSUE TITLE
Fragment transaction state loss: IllegalStateException error

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#435]
This is a very interesting issue that is frequently occurring in our app. Here's a [blog post](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html) explaining why this happens. 

```
USER_COMMENT=I logged in?
ANDROID_VERSION=5.1.1
APP_VERSION_NAME=1.42
BRAND=TCL
PHONE_MODEL=Alcatel_4060A
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1538)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1556)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
at fr.free.nrw.commons.upload.ShareActivity.onAuthCookieAcquired(ShareActivity.java:206)
at fr.free.nrw.commons.auth.AuthenticatedActivity$GetAuthCookieTask.onPostExecute(AuthenticatedActivity.java:41)
at fr.free.nrw.commons.auth.AuthenticatedActivity$GetAuthCookieTask.onPostExecute(AuthenticatedActivity.java:28)
at android.os.AsyncTask.finish(AsyncTask.java:636)
at android.os.AsyncTask.access$500(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5333)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:735)
```

**Comment by misaochan** [comment]
Good link, thanks!

**Comment by misaochan** [comment]
Been getting quite a few of these recently. Might want to give it higher priority.
