### ISSUE TITLE
Crash at login (pre-release)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#443]
Logging in to the pre-release (current master) version crashes on all APIs that I've tried (23 and 25 so far). Trying to figure out what changes we made that broke it.

```
03-20 18:13:03.129: E/ACRA(8560): ACRA caught a RuntimeException for fr.free.nrw.commons
03-20 18:13:03.129: E/ACRA(8560): java.lang.RuntimeException: An error occurred while executing doInBackground()
03-20 18:13:03.129: E/ACRA(8560): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
03-20 18:13:03.129: E/ACRA(8560): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-20 18:13:03.129: E/ACRA(8560): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-20 18:13:03.129: E/ACRA(8560): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-20 18:13:03.129: E/ACRA(8560): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-20 18:13:03.129: E/ACRA(8560): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-20 18:13:03.129: E/ACRA(8560): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-20 18:13:03.129: E/ACRA(8560): 	at java.lang.Thread.run(Thread.java:818)
03-20 18:13:03.129: E/ACRA(8560): Caused by: java.lang.IllegalArgumentException: account is null
03-20 18:13:03.129: E/ACRA(8560): 	at android.accounts.AccountManager.blockingGetAuthToken(AccountManager.java:1189)
03-20 18:13:03.129: E/ACRA(8560): 	at fr.free.nrw.commons.auth.AuthenticatedActivity$GetAuthCookieTask.doInBackground(AuthenticatedActivity.java:55)
03-20 18:13:03.129: E/ACRA(8560): 	at fr.free.nrw.commons.auth.AuthenticatedActivity$GetAuthCookieTask.doInBackground(AuthenticatedActivity.java:32)
03-20 18:13:03.129: E/ACRA(8560): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-20 18:13:03.129: E/ACRA(8560): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-20 18:13:03.129: E/ACRA(8560): 	... 4 more
03-20 18:13:03.166: E/ACRA(8560): fr.free.nrw.commons fatal error : An error occurred while executing doInBackground()
03-20 18:13:03.166: E/ACRA(8560): java.lang.RuntimeException: An error occurred while executing doInBackground()
03-20 18:13:03.166: E/ACRA(8560): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
03-20 18:13:03.166: E/ACRA(8560): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-20 18:13:03.166: E/ACRA(8560): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-20 18:13:03.166: E/ACRA(8560): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-20 18:13:03.166: E/ACRA(8560): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-20 18:13:03.166: E/ACRA(8560): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-20 18:13:03.166: E/ACRA(8560): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-20 18:13:03.166: E/ACRA(8560): 	at java.lang.Thread.run(Thread.java:818)
03-20 18:13:03.166: E/ACRA(8560): Caused by: java.lang.IllegalArgumentException: account is null
03-20 18:13:03.166: E/ACRA(8560): 	at android.accounts.AccountManager.blockingGetAuthToken(AccountManager.java:1189)
03-20 18:13:03.166: E/ACRA(8560): 	at fr.free.nrw.commons.auth.AuthenticatedActivity$GetAuthCookieTask.doInBackground(AuthenticatedActivity.java:55)
03-20 18:13:03.166: E/ACRA(8560): 	at fr.free.nrw.commons.auth.AuthenticatedActivity$GetAuthCookieTask.doInBackground(AuthenticatedActivity.java:32)
03-20 18:13:03.166: E/ACRA(8560): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-20 18:13:03.166: E/ACRA(8560): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-20 18:13:03.166: E/ACRA(8560): 	... 4 more

```

**Comment by misaochan** [comment]
Reverting the faulty commit seems to fix that crash, but another one occurs shortly after successful login and the contributions have been loaded.

```
03-20 18:51:24.433: E/ACRA(11980): ACRA caught a IllegalArgumentException for fr.free.nrw.commons
03-20 18:51:24.433: E/ACRA(11980): java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{5969fb9 V.E...... R......D 0,0-456,242} not attached to window manager
03-20 18:51:24.433: E/ACRA(11980): 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
03-20 18:51:24.433: E/ACRA(11980): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
03-20 18:51:24.433: E/ACRA(11980): 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
03-20 18:51:24.433: E/ACRA(11980): 	at android.app.Dialog.dismissDialog(Dialog.java:362)
03-20 18:51:24.433: E/ACRA(11980): 	at android.app.Dialog.dismiss(Dialog.java:345)
03-20 18:51:24.433: E/ACRA(11980): 	at fr.free.nrw.commons.auth.LoginActivity$LoginTask.onPostExecute(LoginActivity.java:72)
03-20 18:51:24.433: E/ACRA(11980): 	at fr.free.nrw.commons.auth.LoginActivity$LoginTask.onPostExecute(LoginActivity.java:54)
03-20 18:51:24.433: E/ACRA(11980): 	at android.os.AsyncTask.finish(AsyncTask.java:651)
03-20 18:51:24.433: E/ACRA(11980): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
03-20 18:51:24.433: E/ACRA(11980): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
03-20 18:51:24.433: E/ACRA(11980): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-20 18:51:24.433: E/ACRA(11980): 	at android.os.Looper.loop(Looper.java:148)
03-20 18:51:24.433: E/ACRA(11980): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-20 18:51:24.433: E/ACRA(11980): 	at java.lang.reflect.Method.invoke(Native Method)
03-20 18:51:24.433: E/ACRA(11980): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-20 18:51:24.433: E/ACRA(11980): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-20 18:51:24.471: E/EGL_emulation(1254): tid 1254: eglCreateSyncKHR(1660): error 0x3004 (EGL_BAD_ATTRIBUTE)
03-20 18:51:24.504: E/ACRA(11980): fr.free.nrw.commons fatal error : View=com.android.internal.policy.PhoneWindow$DecorView{5969fb9 V.E...... R......D 0,0-456,242} not attached to window manager
03-20 18:51:24.504: E/ACRA(11980): java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{5969fb9 V.E...... R......D 0,0-456,242} not attached to window manager
03-20 18:51:24.504: E/ACRA(11980): 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
03-20 18:51:24.504: E/ACRA(11980): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
03-20 18:51:24.504: E/ACRA(11980): 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
03-20 18:51:24.504: E/ACRA(11980): 	at android.app.Dialog.dismissDialog(Dialog.java:362)
03-20 18:51:24.504: E/ACRA(11980): 	at android.app.Dialog.dismiss(Dialog.java:345)
03-20 18:51:24.504: E/ACRA(11980): 	at fr.free.nrw.commons.auth.LoginActivity$LoginTask.onPostExecute(LoginActivity.java:72)
03-20 18:51:24.504: E/ACRA(11980): 	at fr.free.nrw.commons.auth.LoginActivity$LoginTask.onPostExecute(LoginActivity.java:54)
03-20 18:51:24.504: E/ACRA(11980): 	at android.os.AsyncTask.finish(AsyncTask.java:651)
03-20 18:51:24.504: E/ACRA(11980): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
03-20 18:51:24.504: E/ACRA(11980): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
03-20 18:51:24.504: E/ACRA(11980): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-20 18:51:24.504: E/ACRA(11980): 	at android.os.Looper.loop(Looper.java:148)
03-20 18:51:24.504: E/ACRA(11980): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-20 18:51:24.504: E/ACRA(11980): 	at java.lang.reflect.Method.invoke(Native Method)
03-20 18:51:24.504: E/ACRA(11980): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-20 18:51:24.504: E/ACRA(11980): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by misaochan** [comment]
#444 now fixes the second crash, too. Would appreciate if a reviewer could review and merge. :)

@maskaravivek , sorry for the revert of your commit, but I couldn't figure out how to fix that particular lint issue while keeping login intact. Please feel free to try again with fixing that lint issue.

**Comment by maskaravivek** [comment]
@misaochan Have merged your PR. Will check if we can fix the lint issue or we want to suppress that warning.

**Comment by misaochan** [comment]
Great, thanks @maskaravivek !
