### ISSUE TITLE
Handle migration to prevent crash on start

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4435]
Version 1007, yes  email sent.

**Comment by misaochan** [comment]
Stack trace is:

```
APP_VERSION_NAME=3.0.0.1007
ANDROID_VERSION=8.0.0
STACK_TRACE=java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:195)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:310)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:352)
	at androidx.room.paging.LimitOffsetDataSource.loadInitial(LimitOffsetDataSource.java:117)
	at androidx.paging.PositionalDataSource.dispatchLoadInitial(PositionalDataSource.java:286)
	at androidx.paging.TiledPagedList.<init>(TiledPagedList.java:107)
	at androidx.paging.PagedList.create(PagedList.java:229)
	at androidx.paging.PagedList$Builder.build(PagedList.java:388)
	at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
	at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
	at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by misaochan** [comment]
@jidanni Just to be clear, you are in alpha testing, right?

Pinging @ashishkumar468 , it is perplexing that this error would occur for an end user.

**Comment by jidanni** [comment]
> @jidanni Just to be clear, you are in alpha testing, right?
Correct.

**Comment by jidanni** [comment]
1008 too. Mail sent.

**Comment by misaochan** [comment]
Okay, it seems that a migration was missed, see https://github.com/commons-app/apps-android-commons/issues/3607#issuecomment-613016124 . We should update the DB version number soon (definitely prior to an actual release), but you may want to fall back to beta in the meantime @jidanni , otherwise the app will be unusable for you. I will ping you when we've fixed the issue and then you can sign up for alpha again if you want.

**Comment by jidanni** [comment]
Not so fast! Alpha's fine with me. I'll just hold my pictures and simply not upload them until the bug is fixed.

**Comment by jidanni** [comment]
Please add a simple https://en.m.wikipedia.org/wiki/Smoke_testing_(software)
To be sure the app actually launches, before releasing it. I just downloaded a fresh version and it crashed again. I sent another email.

**Comment by misaochan** [comment]
@jidanni , as I mentioned to you before alpha was never meant to be used for actual end user purposes, it is used for debugging. There are processes that we use to prevent this prior to actual releases, your app is crashing because we are in the middle of development. This will be fixed before our next release, in the meantime you can fall back to beta if you need to.
