### ISSUE TITLE
Submit button stuck

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4443]
The submit button does not work.
![Screenshot_20210607-114116.jpg](https://user-images.githubusercontent.com/1230959/120956165-88861b00-c785-11eb-9b06-ac8a55a03636.jpg)

**Comment by jidanni** [comment]
Then I crashed when I tried to open it again. I just sent you the crash mail and mentioned the submit button inside that mail.

**Comment by neslihanturan** [comment]
Thanks a lot for bug report @jidanni , let me add logs here too so that everyone has access to them:
```
USER_COMMENT= The submit button doesn't work and then it crashed when I try to open it again.
APP_VERSION_CODE=1011
APP_VERSION_NAME=3.0.0.1011
ANDROID_VERSION=8.0.0
STACK_TRACE=java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:154)
	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:195)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:310)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:352)
	at androidx.room.paging.LimitOffsetDataSource.loadInitial(LimitOffsetDataSource.java:117)
	at androidx.paging.PositionalDataSource.dispatchLoadInitial(PositionalDataSource.java:286)
	at androidx.paging.TiledPagedList.<init>(TiledPagedList.java:107)
	at androidx.paging.PagedList.create(PagedList.java:229)
	at androidx.paging.PagedList$Builder.build(PagedList.java:388)
	at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
	at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
	at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

IS_SILENT=false
USER_EMAIL=
USER_CRASH_DATE=2021-06-07T11:43:56.865+08:00
REPORT_ID=5ba83582-dace-4678-8d84-2a7bf5942ac8
```

**Comment by misaochan** [comment]
Looks related to #4435

**Comment by Rishavgupta12345** [comment]
nearby works perfectly now. It's an old issue and may be solved by any other issue. Please review and close this issue @nicolas-raoul

**Comment by nicolas-raoul** [comment]
Indeed. If anyone still experiences this, please reopen, thanks!
