### ISSUE TITLE
Splitting screens on some pages will cause the app to crash

### ISSUE THREAD

**Issue by sjl872964789** [commons-app/apps-android-commons#4498]
**Summary:** 
Splitting screens on some pages will cause the app to crash

**Steps to reproduce:** 
1. Install and open commons
2. Skip the tutorial
3. Click the "search" icon in the top right corner
4. Enter any character, such as "y"
5. Click any picture
6. Split screen
7. Crash

**System logs:**

```
07-06 21:13:41.241 11797 11797 E AndroidRuntime: FATAL EXCEPTION: main
07-06 21:13:41.241 11797 11797 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 11797
07-06 21:13:41.241 11797 11797 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property categoryImagesCallback has not been 
initialized
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getCategoryImagesCallback(PageableMediaFragment.kt:24)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2.invoke(PageableMediaFragment.kt:17)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at fr.free.nrw.commons.explore.media.PageableMediaFragment$pagedListAdapter$2.invoke(PageableMediaFragment.kt:14)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getPagedListAdapter(Unknown Source:2)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at fr.free.nrw.commons.explore.media.PageableMediaFragment.getTotalMediaCount(PageableMediaFragment.kt:55)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at fr.free.nrw.commons.explore.SearchActivity.getTotalMediaCount(SearchActivity.java:177)   
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailPagerFragment$MediaDetailAdapter.getCount(MediaDetailPagerFragment.java:404)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:532)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at fr.free.nrw.commons.media.MediaDetailPagerFragment.onCreateView(MediaDetailPagerFragment.java:105)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)     
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)     
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569) 
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7252)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)   
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:201)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6815)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)        
07-06 21:13:41.241 11797 11797 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Device and Android version:** 

Device1: [MI CC 9]
OS version1: [MIUI 11.3.3]
Device2: [PIXEL XL]
OS version2: [Android 8.0]
 
**Commons app version:** 
App version: [3.0.2]

**Screen-shots:** 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/15941953/124721001-4d6d3800-df3b-11eb-83c3-9dd14c76a011.gif)

**Comment by misaochan** [comment]
Thanks for letting us know @sjl872964789 !

**Comment by Rishavgupta12345** [comment]
APP has many changes now, and this issue is pretty old moreover, it's not an issue anymore. ITS ALREADY SOLVED

**Comment by neslihanturan** [comment]
Thanks for letting us know @Rishavgupta12345 :)
