### ISSUE TITLE
App crashed while deleting recent searches

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4507]
**Summary:** 

Every time the app is crashing while deleting recent searches. And also is delete the search item one by one. But In my emulator which is Pixel 4 API 30, the app is working as expected (not crashing and deleting the whole search). The crash is saying that we are releasing an already released resource.

**Steps to reproduce:** 

Explore -> search icon -> Delete recent searches.

**System logs:**

```
    java.lang.IllegalStateException: Already released
        at android.content.ContentProviderClient.release(ContentProviderClient.java:456)
        at fr.free.nrw.commons.explore.recentsearches.RecentSearchesDao.deleteAll(RecentSearchesDao.java:83)
        at fr.free.nrw.commons.explore.recentsearches.RecentSearchesFragment.lambda$null$0$RecentSearchesFragment(RecentSearchesFragment.java:58)
        at fr.free.nrw.commons.explore.recentsearches.-$$Lambda$RecentSearchesFragment$Ug_BF47xEbqSyqu8SnL2pEeYom0.onClick(lambda)
        at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5730)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
07-16 01:31:07.518 3182-3195/? E/ANDR-PERF-MPCTL: invalid request, no optimizations performed
```

**Device and Android version:** 

OPPO A57 API 23
 
**Commons app version:** 

latest master

**Screen-shots:** 
https://drive.google.com/file/d/1Isk-ePqpQM-Myf6JklolHODR1OXPClZa/view?usp=sharing

**Comment by misaochan** [comment]
Hi @Ayan-10 , thanks for reporting this! Are you interested in working on it?

**Comment by Ayan-10** [comment]
@misaochan Yes

**Comment by misaochan** [comment]
It is yours. :)

**Comment by rohit9625** [comment]
It's been a while since this issue is created. Has anyone encountered the same problem as I did not yet?

**Comment by nicolas-raoul** [comment]
@rohit9625 Indeed I can not reproduce either, thanks! 🙂
