### ISSUE TITLE
Crash when selecting camera

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#457]
This happens 100% of the time when I select the camera in my real device (Samsung Galaxy S7, API 24). Not sure when this crash was introduced, as I haven't tested the camera function for the past 3 months.

```
03-22 17:07:31.466: E/ACRA(740): ACRA caught a FileUriExposedException for fr.free.nrw.commons
03-22 17:07:31.466: E/ACRA(740): 	at fr.free.nrw.commons.contributions.ContributionController.startCameraCapture(ContributionController.java:60)
03-22 17:07:31.466: E/ACRA(740): 	at fr.free.nrw.commons.contributions.ContributionsListFragment.onOptionsItemSelected(ContributionsListFragment.java:133)
03-22 17:07:31.535: E/ACRA(740): fr.free.nrw.commons fatal error : file:///storage/emulated/0/Commons/images/1490166451455.jpg exposed beyond app through ClipData.Item.getUri()
03-22 17:07:31.535: E/ACRA(740): 	at fr.free.nrw.commons.contributions.ContributionController.startCameraCapture(ContributionController.java:60)
03-22 17:07:31.535: E/ACRA(740): 	at fr.free.nrw.commons.contributions.ContributionsListFragment.onOptionsItemSelected(ContributionsListFragment.java:133)

```

**Comment by misaochan** [comment]
Seems to be relevant to http://stackoverflow.com/questions/39242026/fileuriexposedexception-in-android-n-with-camera

**Comment by misaochan** [comment]
Oh, this only happened after we changed the targetsdk to 25. So the current production version is fine, this just applies to the pre-release version on master.

**Comment by misaochan** [comment]
I'm working on this at https://github.com/misaochan/apps-android-commons/tree/fix-camera-crash . Just tidying loose ends, will submit PR soon.

**Comment by misaochan** [comment]
The above branch now gets us past the initial camera selection, but after taking the picture we get this error:

`03-22 22:24:16.344: E/ACRA(6220): java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.upload.ShareActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
03-22 22:24:16.344: E/ACRA(6220): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
03-22 22:24:16.344: E/ACRA(6220): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
03-22 22:24:16.344: E/ACRA(6220): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
03-22 22:24:16.344: E/ACRA(6220): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
03-22 22:24:16.344: E/ACRA(6220): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-22 22:24:16.344: E/ACRA(6220): 	at android.os.Looper.loop(Looper.java:154)
03-22 22:24:16.344: E/ACRA(6220): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-22 22:24:16.344: E/ACRA(6220): 	at java.lang.reflect.Method.invoke(Native Method)
03-22 22:24:16.344: E/ACRA(6220): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-22 22:24:16.344: E/ACRA(6220): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-22 22:24:16.344: E/ACRA(6220): Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
03-22 22:24:16.344: E/ACRA(6220): 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
03-22 22:24:16.344: E/ACRA(6220): 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
03-22 22:24:16.344: E/ACRA(6220): 	at fr.free.nrw.commons.upload.FileUtils.getDataColumn(FileUtils.java:105)
03-22 22:24:16.344: E/ACRA(6220): 	at fr.free.nrw.commons.upload.FileUtils.getPath(FileUtils.java:73)
03-22 22:24:16.344: E/ACRA(6220): 	at fr.free.nrw.commons.upload.ShareActivity.getFileMetadata(ShareActivity.java:380)
03-22 22:24:16.344: E/ACRA(6220): 	at fr.free.nrw.commons.upload.ShareActivity.onCreate(ShareActivity.java:320)
03-22 22:24:16.344: E/ACRA(6220): 	at android.app.Activity.performCreate(Activity.java:6679)
03-22 22:24:16.344: E/ACRA(6220): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
03-22 22:24:16.344: E/ACRA(6220): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
03-22 22:24:16.344: E/ACRA(6220): 	... 9 more
03-22 22:24:16.375: E/ACRA(6220): fr.free.nrw.commons fatal error : Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.upload.ShareActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
03-22 22:24:16.375: E/ACRA(6220): java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.upload.ShareActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
03-22 22:24:16.375: E/ACRA(6220): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
03-22 22:24:16.375: E/ACRA(6220): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
03-22 22:24:16.375: E/ACRA(6220): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
03-22 22:24:16.375: E/ACRA(6220): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
03-22 22:24:16.375: E/ACRA(6220): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-22 22:24:16.375: E/ACRA(6220): 	at android.os.Looper.loop(Looper.java:154)
03-22 22:24:16.375: E/ACRA(6220): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-22 22:24:16.375: E/ACRA(6220): 	at java.lang.reflect.Method.invoke(Native Method)
03-22 22:24:16.375: E/ACRA(6220): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-22 22:24:16.375: E/ACRA(6220): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-22 22:24:16.375: E/ACRA(6220): Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
03-22 22:24:16.375: E/ACRA(6220): 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
03-22 22:24:16.375: E/ACRA(6220): 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
03-22 22:24:16.375: E/ACRA(6220): 	at fr.free.nrw.commons.upload.FileUtils.getDataColumn(FileUtils.java:105)
03-22 22:24:16.375: E/ACRA(6220): 	at fr.free.nrw.commons.upload.FileUtils.getPath(FileUtils.java:73)
03-22 22:24:16.375: E/ACRA(6220): 	at fr.free.nrw.commons.upload.ShareActivity.getFileMetadata(ShareActivity.java:380)
03-22 22:24:16.375: E/ACRA(6220): 	at fr.free.nrw.commons.upload.ShareActivity.onCreate(ShareActivity.java:320)
03-22 22:24:16.375: E/ACRA(6220): 	at android.app.Activity.performCreate(Activity.java:6679)
03-22 22:24:16.375: E/ACRA(6220): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
03-22 22:24:16.375: E/ACRA(6220): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
03-22 22:24:16.375: E/ACRA(6220): 	... 9 more
`

**Comment by misaochan** [comment]
I think `mediaUri` in ShareActivity.java is being passed the wrong Uri, as evidenced by the debug output:

`03-22 22:34:01.454: D/fr.free.nrw.commons.upload.ShareActivity(7275): Input stream created from content://fr.free.nrw.commons.provider/external_files/Commons/images/1490186009534.jpg`

Going to have to head off soon - if anyone would like to pick this up, feel free to add to my branch instead of starting from scratch. Don't think we can release with the current camera crashing, but in the worst case scenario, if we can't fix it soon we can just change the target SDK back to 23 for the time being I guess.

**Comment by misaochan** [comment]
Can't figure out a proper fix in a short period of time. Reverting the target SDK to 23 fixes the problem temporarily, so I am going to do that for the current release. Will leave this issue and https://github.com/misaochan/apps-android-commons/tree/fix-camera-crash open for future fix.

**Comment by misaochan** [comment]
The camera crash has returned with targeting API 25 (app version 2.4.2):

```
05-31 16:44:34.334 3240-3240/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: fr.free.nrw.commons, PID: 3240
                                                 android.os.FileUriExposedException: file:///storage/emulated/0/Commons/images/1496213074333.jpg exposed beyond app through ClipData.Item.getUri()
                                                     at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                     at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                     at android.content.ClipData.prepareToLeaveProcess(ClipData.java:845)
                                                     at android.content.Intent.prepareToLeaveProcess(Intent.java:8941)
                                                     at android.content.Intent.prepareToLeaveProcess(Intent.java:8926)
                                                     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
                                                     at android.app.Activity.startActivityForResult(Activity.java:4225)
                                                     at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                     at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
                                                     at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
                                                     at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:937)
                                                     at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
                                                     at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:959)
                                                     at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:948)
                                                     at fr.free.nrw.commons.contributions.ContributionController.startCameraCapture(ContributionController.java:60)
                                                     at fr.free.nrw.commons.contributions.ContributionsListFragment.onOptionsItemSelected(ContributionsListFragment.java:123)
                                                     at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2314)
                                                     at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3029)
                                                     at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
                                                     at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:414)
                                                     at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                     at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                     at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                     at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
                                                     at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
                                                     at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
                                                     at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                     at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
                                                     at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                                                     at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
                                                     at android.view.View.performClick(View.java:5637)
                                                     at android.view.View$PerformClick.run(View.java:22429)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by misaochan** [comment]
Hmm. We might have a bit of a problem. Changing the target version to 23 does not solve the problem this time. Perhaps because of `compileSdkVersion = android-25` ? But our current theme is reliant on that, switching to android-23 causes the error `Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'..`

Nobody on Nougat can use the in-app camera without crashing until we fix this. :/

**Comment by misaochan** [comment]
Interestingly, hardcoding `targetSdkVersion 23` instead of using `targetSdkVersion project.targetSdkVersion` solves the problem, so there seems to be an issue with how the Gradle constants are passed in.

**Comment by whym** [comment]
This may be the issue discussed at https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed - the best answer suggests using FileProvider.

**Comment by misaochan** [comment]
@whym I attempted that fix some time ago at https://github.com/misaochan/apps-android-commons/commits/fix-camera-crash but encountered issues with handling the URI after that. My difficulties and the error logs are documented above.

**Comment by whym** [comment]
It seems that the way to write and read the file also needs to be updated. Did you try https://developer.android.com/reference/android/support/v4/content/FileProvider.html#Permissions ?

**Comment by misaochan** [comment]
This has been fixed I think?

**Comment by tised** [comment]
Seems this is fixed, because FIleProvider implementation exist in project.

Also i switched targetSdkVersion to 25 and install app for 7.1.2, 6.0.1, 4.4 android devices, no crashes at all when select camera/from gallery

@misaochan i think you can switch 25 targetSdk on master too

**Comment by misaochan** [comment]
Strange, I thought the target SDK had been increased to 25 before this! Yeah, will do, thanks for the reminder @tised .
