### ISSUE TITLE
If you click "deny and don't ask again", the app will crash

### ISSUE THREAD

**Issue by sjl872964789** [commons-app/apps-android-commons#4594]
**Summary:** 

If you click "deny and don't ask again", the app will crash or flash all the time

**Steps to reproduce:** 

1. Install and open commons
2. Skip the tutorial and log in
3. Click "nearby"
4. Click "DENY"
5. Click "YES"
6. Click "DENY AND DON'T ASK AGAIN"
7. Crash

**System logs:**

```
08-30 21:11:10.908  8891  8891 E AndroidRuntime: FATAL EXCEPTION: main
08-30 21:11:10.908  8891  8891 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 8891
08-30 21:11:10.908  8891  8891 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {fr.free.nrw.commons/com.karumi.dexter.DexterActivity}: android.content.res.Resources$NotFoundException: String resource ID #0xffffffff
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5598)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5639)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8393)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
08-30 21:11:10.908  8891  8891 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: String resource ID #0xffffffff
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.content.res.Resources.getText(Resources.java:413)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.content.res.Resources.getString(Resources.java:509)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.content.Context.getString(Context.java:639)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at fr.free.nrw.commons.utils.PermissionUtils$1.onPermissionDenied(PermissionUtils.java:119)        
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.MultiplePermissionsListenerToPermissionListenerAdapter.onPermissionsChecked(Unknown Source:23)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.MultiplePermissionListenerThreadDecorator$1.run(Unknown Source:8)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.MainThread.execute(Unknown Source:6)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.MultiplePermissionListenerThreadDecorator.onPermissionsChecked(Unknown Source:7)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.DexterInstance.onPermissionsChecked(Unknown Source:57)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.DexterInstance.updatePermissionsAsDenied(Unknown Source:36)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.DexterInstance.onPermissionRequestDenied(Unknown Source:0)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.Dexter.onPermissionsRequested(Unknown Source:9)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at com.karumi.dexter.DexterActivity.onRequestPermissionsResult(Unknown Source:51)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8602)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:8452)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5591)
08-30 21:11:10.908  8891  8891 E AndroidRuntime:        ... 11 more
08-30 21:11:10.913 23075 23148 E AndroidRuntime: FATAL EXCEPTION: FlpThread
08-30 21:11:10.913 23075 23148 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 23075
08-30 21:11:10.913 23075 23148 E AndroidRuntime: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.        
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2071)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2039)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1987)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1151) 
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1038)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:955)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bgqs.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):14)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfjh.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):10)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfjg.f(Unknown Source:7)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfjg.c(:com.google.android.gms@19275039@19.2.75 (100408-269183835):2)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at com.google.android.location.fused.FusionEngine.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):106)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfgi.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):21)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at com.google.android.location.fused.StationaryThrottlingEngine.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):12)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfdg.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):5)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfgl.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):3)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at com.google.android.location.fused.StationaryThrottlingEngine.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):12)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfhr.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):4)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfdi.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):2)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfgv.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):1)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bfhf.handleMessage(:com.google.android.gms@19275039@19.2.75 (100408-269183835):20)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at aelo.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):3)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at aelo.dispatchMessage(:com.google.android.gms@19275039@19.2.75 (100408-269183835):4)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at bgre.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):5)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at aelo.dispatchMessage(:com.google.android.gms@19275039@19.2.75 (100408-269183835):4)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        Suppressed: java.lang.RuntimeException: Active trace: location_base-GoogleLocationManagerChimeraService_onCreate
08-30 21:11:10.913 23075 23148 E AndroidRuntime:                at sii.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):15)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:                at sjr.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):41)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:                at aelo.dispatchMessage(:com.google.android.gms@19275039@19.2.75 (100408-269183835):7)     
08-30 21:11:10.913 23075 23148 E AndroidRuntime:                ... 4 more
08-30 21:11:10.913 23075 23148 E AndroidRuntime:        Suppressed: java.lang.RuntimeException: Active trace: location_base-GoogleLocationManagerChimeraService_onCreate
08-30 21:11:10.913 23075 23148 E AndroidRuntime:                at sii.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):15)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:                at sjr.a(:com.google.android.gms@19275039@19.2.75 (100408-269183835):41)
08-30 21:11:10.913 23075 23148 E AndroidRuntime:                at aelo.dispatchMessage(:com.google.android.gms@19275039@19.2.75 (100408-269183835):7)     
08-30 21:11:10.913 23075 23148 E AndroidRuntime:                ... 2 more
```

**Device and Android version:** 

Device: [Huawei nova 5 Pro]
Android version: [Android 10.0]
EMUI version: [11.0.0]

**Commons app version:** 

App version: [3.0.3]

**Screen-shots:** 

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/15941953/131344956-cc539181-464c-4638-b85f-9b94873d1ac5.gif)

**Comment by Rishavgupta12345** [comment]
I am un able to replicate this issue . when I am clicking "DENY" app is not crashing . It just nor using the location service but working perfectly in all other ways . MAYBE THIS ISSUE IS ALREADY solved by another issue . PLEASE  VERIFY

**Comment by nicolas-raoul** [comment]
If anyone can reproduce this issue, please reopen, thanks! :-)
