### ISSUE TITLE
Upload progress bar loads forever, does not eventually upload

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4601]
**Summary:** 

I was testing the 3.1-release branch and my first upload got stuck at the progress bar (the initial part where the bar constantly moves). It doesn't ever upload.

**Steps to reproduce:** 

Not sure if this is foolproof, but I did a lot of in-app activity before going to check on my upload in Contributions. I browsed Nearby, went to About to check the version, etc. I also did not select a "depicts".

The upload was via Nearby > WLM point > Gallery.

**System logs:**

```
2021-09-01 17:41:41.176 29761-15969/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: java.io.IOException: {"error":{"code":"badinteger","info":"Invalid value \"M109373739\" for integer parameter \"pageids\".","docref":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw2288"}
        at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:90)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleAmb.subscribeActual(SingleAmb.java:84)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-09-01 17:41:41.183 29761-17864/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: java.io.IOException: {"error":{"code":"missingtitle","info":"The page you specified doesn't exist.","*":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw2352"}
        at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:90)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-09-01 17:41:41.185 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: java.io.IOException: {"error":{"code":"badinteger","info":"Invalid value \"M2f306959-3cc0-4e3f-a0db-ab71d19d7682\" for integer parameter \"pageids\".","docref":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw2253"}
        at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:90)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleAmb.subscribeActual(SingleAmb.java:84)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-09-01 17:41:41.191 29761-17865/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: java.io.IOException: {"error":{"code":"missingtitle","info":"The page you specified doesn't exist.","*":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw2403"}
        at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:90)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: java.io.IOException: {"error":{"code":"no-such-entity","info":"Could not find an entity with the ID \"M0\".","id":"M0","messages":[{"name":"wikibase-api-no-such-entity","parameters":["M0"],"html":{"*":"Could not find an entity with the ID \"M0\"."}}],"*":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."},"servedby":"mw2366"}
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:90)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at okhttp3.RealCall.execute(RealCall.java:92)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Single.subscribe(Single.java:3603)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Single.subscribe(Single.java:3603)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Single.subscribe(Single.java:3603)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Single.subscribe(Single.java:3603)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Single.subscribe(Single.java:3603)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Single.subscribe(Single.java:3603)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Single.subscribe(Single.java:3603)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleAmb.subscribeActual(SingleAmb.java:84)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Single.subscribe(Single.java:3603)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2021-09-01 17:41:42.226 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2021-09-01 17:41:42.227 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2021-09-01 17:41:42.227 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2021-09-01 17:41:42.227 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-09-01 17:41:42.227 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021-09-01 17:41:42.227 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-09-01 17:41:42.227 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-09-01 17:41:42.227 29761-17907/fr.free.nrw.commons E/OkHttpConnectionFactory$UnsuccessfulResponseInterceptor:     at java.lang.Thread.run(Thread.java:923)
2021-09-01 17:42:00.619 29761-15967/fr.free.nrw.commons E/UploadWorker$doWork: Queued Contributions: 0
2021-09-01 17:42:01.455 29761-16631/fr.free.nrw.commons E/UploadWorker$doWork: Queued Contributions: 1
2021-09-01 17:42:05.032 29761-16631/fr.free.nrw.commons E/UploadWorker: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wikipedia.dataclient.mwapi.MwServiceError.getDetails()' on a null object reference
        at java.lang.String.valueOf(String.java:2924)
        at java.io.PrintWriter.println(PrintWriter.java:754)
        at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:778)
        at java.lang.Throwable.printStackTrace(Throwable.java:667)
        at java.lang.Throwable.printStackTrace(Throwable.java:735)
        at timber.log.Timber$Tree.getStackTraceString(Timber.java:547)
        at timber.log.Timber$Tree.prepareLog(Timber.java:528)
        at timber.log.Timber$Tree.e(Timber.java:455)
        at timber.log.Timber$1.e(Timber.java:313)
        at timber.log.Timber.e(Timber.java:88)
        at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileFromStash$3$UploadClient(UploadClient.java:226)
        at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$-xVSLroq3t059tyyfYuDUQukbVk.apply(Unknown Source:4)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
        at io.reactivex.Observable.blockingSingle(Observable.java:5381)
        at fr.free.nrw.commons.upload.worker.UploadWorker.uploadContribution(UploadWorker.kt:290)
        at fr.free.nrw.commons.upload.worker.UploadWorker.access$uploadContribution(UploadWorker.kt:40)
        at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:146)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
        at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__CollectKt.collect(Collect.kt:30)
        at kotlinx.coroutines.flow.FlowKt.collect(Unknown Source:1)
        at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2.invokeSuspend(UploadWorker.kt:203)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-09-01 17:42:05.033 29761-16631/fr.free.nrw.commons E/UploadWorker: Upload from stash failed for contribution : Lifeguard flag .jpg
```

**Device and Android version:** 

Samsung Galaxy S20FE, Android 11
 
**Commons app version:** 

3.1-release

**Comment by misaochan** [comment]
Happened again yesterday for me, however this time it was with a non-Nearby upload (from Contributions).

@nicolas-raoul has this issue ever happened for you with 3.1 onwards?

**Comment by nicolas-raoul** [comment]
I haven't observed it recently on the 3.1 branch... I have not uploaded many files recently, though, maybe like 10 in total.
