### ISSUE TITLE
[Linked to custom selector] App shows an upload failed notification even after upload succeeds

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#4630]
**Summary:** 

Even though upload successfully happens, the app shows an upload failed notification because the saveIntoUploadedStatus() method throws an exception

**Steps to reproduce:** 

Not reproducible easily, but resuming a failed upload should do it.

**System logs:**

```
2021-09-16 17:21:53.831 27216-27550/fr.free.nrw.commons.beta E/UploadWorker: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{4997307 27216:fr.free.nrw.commons.beta/u0a375} (pid=27216, uid=10375) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5728)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6820)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2935)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1967)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1475)
        at fr.free.nrw.commons.upload.worker.UploadWorker.saveIntoUploadedStatus(UploadWorker.kt:418)
        at fr.free.nrw.commons.upload.worker.UploadWorker.saveCompletedContribution(UploadWorker.kt:410)
        at fr.free.nrw.commons.upload.worker.UploadWorker.uploadContribution(UploadWorker.kt:310)
        at fr.free.nrw.commons.upload.worker.UploadWorker.access$uploadContribution(UploadWorker.kt:46)
        at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:146)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
        at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__CollectKt.collect(Collect.kt:30)
        at kotlinx.coroutines.flow.FlowKt.collect(Unknown Source:1)
        at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2.invokeSuspend(UploadWorker.kt:215)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7148)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7588)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2397)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2875)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
2021-09-16 17:21:53.834 27216-27550/fr.free.nrw.commons.beta E/UploadWorker: Upload from stash failed for contribution : test master 131.jpg
2021-09-16 17:22:00.555 27216-27246/fr.free.nrw.commons.beta I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=9dcf58df-a9c6-4656-8ab5-c304caaefa20, tags={ fr.free.nrw.commons.upload.worker.UploadWorker } ]

```

**Device and Android version:** 

Android 9 Pixel 4

**Commons app version:** 

Current master

**Would you like to work on the issue?**

Preferrably not

**Comment by pratik2315** [comment]
Hey @ashishkumar468 ! can I work on this Issue if its still available?

**Comment by ashishkumar468** [comment]
Hi @pratik2315, this does not seem like a good first issue, please feel free to choose from one of the good first issue. @4D17Y4, do you want to take a look into this one?
