### ISSUE TITLE
Crash on upload wizard's depictions screen (and depiction not selected)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4642]
1. Open app (latest master)
2. Upload this picture: https://drive.google.com/file/d/1-vuOYjSqn6dTMVbgAvjBOIfoeaK0kqGm/view?usp=sharing
3. App asks "Is this a picture of XYZ?", tap Yes
4. In the depictions screen, XYZ is not selected as a depiction (problem 1)
5. Tap "Next", acknowledge the warning.
6. Crash (problem 2):

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 24 path $.commonsCategories[0]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
at org.wikipedia.json.PostProcessingTypeAdapter$1.read(PostProcessingTypeAdapter.java:26)
at com.google.gson.Gson.fromJson(Gson.java:932)
at com.google.gson.Gson.fromJson(Gson.java:897)
at com.google.gson.Gson.fromJson(Gson.java:846)
at fr.free.nrw.commons.db.Converters.readObjectWithTypeToken(Converters.java:136)
at fr.free.nrw.commons.db.Converters.stringToDepicts(Converters.java:43)
at fr.free.nrw.commons.upload.depicts.DepictsDao_Impl$5.call(DepictsDao_Impl.java:139)
at fr.free.nrw.commons.upload.depicts.DepictsDao_Impl$5.call(DepictsDao_Impl.java:122)
at androidx.room.CoroutinesRoom$Companion$execute$$inlined$suspendCancellableCoroutine$lambda$1.invokeSuspend(CoroutinesRoom.kt:83)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 24 path $.commonsCategories[0]
at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
at org.wikipedia.json.PostProcessingTypeAdapter$1.read(PostProcessingTypeAdapter.java:26)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
at org.wikipedia.json.PostProcessingTypeAdapter$1.read(PostProcessingTypeAdapter.java:26)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
... 14 more
```

Same problems when uploading any picture from Nearby.
No crash if the picture has no depiction meant for pre-selection.

**Comment by sanedroid6006** [comment]
Hello @nicolas-raoul  can you upload video for the same ,I 'm not getting this crash

**Comment by nicolas-raoul** [comment]
@sanedroid6006 You can easily reproduce the crash by following these steps:

1. Start app
2. Tap "Nearby"
3. Select any blue pin
4. Press the +
5. Tap the gallery button
6. Select any picture
7. Press Next
8. Press Next

Thanks! :-)

**Comment by sanedroid6006** [comment]
> @nicolas-raoul  in my device crash is not occuring,
By seeing your logs it's seems like invalid json response type error .
When API response is like html and not the json this error comes...
I will try this to handle on application side
But it's better to have error response like status something in api.

**Comment by nicolas-raoul** [comment]
@sanedroid6006 Thanks for investigating! Your remark hinted me that I should reset the app's data, and indeed that worked! I am quite sure it was a side-effect from working on [another branch ](https://github.com/commons-app/apps-android-commons/pull/4531) then coming back to master.

Sorry for the noise, and thanks for your help @sanedroid6006!
