### ISSUE TITLE
Failed uploads and crash from Google Photos multiple upload

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4644]
**Summary:** 

Report from user on Google groups forum.

"I was uploading a set of 7 images. Four  failed. I reset the upload. Two do complete but the other two stay in the queue. Try to upload the same file again. I think this was the point where it crashed. 

I used the share function from Google Photos. "

**Steps to reproduce:** 

Google photos > share > pick several images

**System logs:**

```
USER_COMMENT=
APP_VERSION_CODE=1025
APP_VERSION_NAME=3.1.1
ANDROID_VERSION=11
PHONE_MODEL=Mi 9 SE
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'int fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment$UploadMediaDetailFragmentCallback.getIndexInViewFlipper(fr.free.nrw.commons.upload.UploadBaseFragment)' on a null object reference
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.init(UploadMediaDetailFragment.java:136)
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.onViewCreated(UploadMediaDetailFragment.java:132)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:322)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
at android.app.Activity.performStart(Activity.java:8174)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3566)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:236)
at android.app.ActivityThread.main(ActivityThread.java:8061)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by misaochan** [comment]
Pinging @madhurgupta10 :)
