### ISSUE TITLE
NPE when uploading photos from Nearby map

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4648]
From Google groups forum:

USER_COMMENT=Adding photos of Khejarli Massacre Memorial Site.
APP_VERSION_CODE=1025
APP_VERSION_NAME=3.1.1
ANDROID_VERSION=11
PHONE_MODEL=RMX3085
```
STACK_TRACE=java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=197609, result=-1, data=Intent { (has extras) }} to activity {fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.NullPointerException: The mapper function returned a null value.
at android.app.ActivityThread.deliverResults(ActivityThread.java:5373)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5414)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2323)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:255)
at android.app.ActivityThread.main(ActivityThread.java:8194)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.NullPointerException: The mapper function returned a null value.
at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
at io.reactivex.Observable.subscribe(Observable.java:12267)
at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
at io.reactivex.Observable.subscribe(Observable.java:12267)
at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
at io.reactivex.Single.subscribe(Single.java:3603)
at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
at io.reactivex.Single.subscribe(Single.java:3603)
at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
```

USER_CRASH_DATE=2021-09-24T10:07:23.105+05:30
IS_SILENT=false
REPORT_ID=4ffdc93b-af47-416b-9c1f-713666449543
USER_EMAIL=

**Comment by ashishkumar468** [comment]
Hi @misaochan, can you attach the full stack trace for this one?

**Comment by misaochan** [comment]
It's not mine. :( This is all we have from the Google groups forum.

**Comment by ashishkumar468** [comment]
Hmm, unfortunately, these logs would not lead us to find the root cause. Have you been able to reproduce this, also would be great to have the exact steps.

**Comment by misaochan** [comment]
Contacted user, let's see if they respond.

**Comment by nicolas-raoul** [comment]
Probably fixed, I haven't heard of such issue for years.
