### ISSUE TITLE
SQLiteException: no such table: worktag

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4651]
From google groups forum (I think the user's email client removes newlines...). It was sent twice on 2 separate days

```
USER_COMMENT= APP_VERSION_CODE=1025 APP_VERSION_NAME=3.1.1 ANDROID_VERSION=10 PHONE_MODEL=VOG-L29

STACK_TRACE=android.database.sqlite.SQLiteException: no such table: worktag (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT DISTINCT tag FROM worktag WHERE work_spec_id=?, (OS error - 2:No such file or directory) at 

android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method) at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1030) at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:637) at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:610) at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:66) at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37) at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46) at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1482) at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1452) at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:161) at androidx.room.RoomDatabase.query(RoomDatabase.java:446) at androidx.room.util.DBUtil.query(DBUtil.java:83) at androidx.work.impl.model.WorkTagDao_Impl.getTagsForWorkSpecId(WorkTagDao_Impl.java:94) at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:134) at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:929) IS_SILENT=false REPORT_ID=6e3d8a31-288c-4a8f-81e7-4de889a3269b USER_CRASH_DATE=2021-09-22T13:00:17.146+02:00 USER_EMAIL= -- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.
```

Contacted user for more information

**Comment by misaochan** [comment]
@ashishkumar468 , it seems that @CordylusLizard experienced the same crash, as per #4658 . 

> I relogged and tried to upload image. After filling the category form and taping the upload button, app crashed.

Is this information sufficient for you to carry on working on this crash? If not, please ping them for more information.

**Comment by misaochan** [comment]
@ashishkumar468 thanks for the investigation! Makes sense, please submit the PR to 3.1-release
