### ISSUE TITLE
UnknownFormatConversionException: Conversion

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4653]
From google groups forum

```
USER_COMMENT=
APP_VERSION_CODE=1025
APP_VERSION_NAME=3.1.1
ANDROID_VERSION=11
PHONE_MODEL=vivo 1906
STACK_TRACE=java.util.UnknownFormatConversionException: Conversion = 'အ'
at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2782)
at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2812)
at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2625)
at java.util.Formatter.parse(Formatter.java:2558)
at java.util.Formatter.format(Formatter.java:2505)
at java.util.Formatter.format(Formatter.java:2459)
at java.lang.String.format(String.java:2911)
at android.content.res.Resources.getQuantityString(Resources.java:646)
at fr.free.nrw.commons.upload.license.MediaLicenseFragment.updateLicenseSummary(MediaLicenseFragment.java:169)
at fr.free.nrw.commons.upload.license.MediaLicensePresenter.selectLicense(MediaLicensePresenter.java:75)
at fr.free.nrw.commons.upload.license.MediaLicenseFragment$2.onItemSelected(MediaLicenseFragment.java:132)
at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
at android.widget.AdapterView.access$300(AdapterView.java:55)
at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:257)
at android.app.ActivityThread.main(ActivityThread.java:8218)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
```

**Comment by madhurgupta10** [comment]
Hi @misaochan could you please share the steps to reproduce this issue? It seems like a language-specific issue.

**Comment by misaochan** [comment]
I will ask the user what language he is using, if that will help?

**Comment by madhurgupta10** [comment]
@misaochan Thanks, that would be a great help, also if the user could provide exact steps to reproduce this issue then it would accelerate things :)

**Comment by misaochan** [comment]
He hasn't responded. :( We can leave this for the time being.
