### ISSUE TITLE
Error when uploading 2nd and 3rd picture in 3-pictures upload: "MwException: ⧼titleblacklist-custom-space⧽"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4676]
Latest master
```
10-17 13:00:44.385 11678 11739 D OkHttp  : --> GET https://commons.wikimedia.org/w/api.php?format=json&action=wbgetentities&props=labels&languagefallback=1&ids=M108674793%7CM108674873%7CM108674961%7CM108675055%7CM108675155%7CM108675246%7CM108675329%7CM108675404%7CM108675496%7CM108675583
10-17 13:00:44.388 11678 11739 D CookieManager: Domain:commons.wikimedia.org
10-17 13:00:44.476 11678 11904 D OkHttp  : <-- 200 https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&ignorewarnings=1 (3378ms, 533-byte body)
10-17 13:00:44.482 11678 11904 E UploadClient: Error in uploading file from stash
10-17 13:00:44.482 11678 11904 E UploadClient: org.wikipedia.dataclient.mwapi.MwException: ⧼titleblacklist-custom-space⧽
10-17 13:00:44.485 11678 11904 E UploadWorker: java.lang.NullPointerException: The supplied value is null
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableOnErrorReturn$OnErrorReturnObserver.onError(ObservableOnErrorReturn.java:80)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableOnErrorReturn.subscribeActual(ObservableOnErrorReturn.java:31)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker.uploadContribution(UploadWorker.kt:297)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker.access$uploadContribution(UploadWorker.kt:46)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:146)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt__CollectKt.collect(Collect.kt:30)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt.collect(Unknown Source:1)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2.invokeSuspend(UploadWorker.kt:215)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
10-17 13:00:44.485 11678 11904 E UploadWorker: Caused by: java.lang.Exception: titleblacklist-custom-space
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileFromStash$3$UploadClient(UploadClient.java:227)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$-xVSLroq3t059tyyfYuDUQukbVk.apply(Unknown Source:4)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
10-17 13:00:44.485 11678 11904 E UploadWorker: 	... 28 more
10-17 13:00:44.485 11678 11904 E UploadWorker: Upload from stash failed for contribution : Brosse en forme d'anneau - usée .jpg
10-17 13:00:44.505 11678 11703 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=b0f85ca0-660c-404a-92f8-0350ef75ce05, tags={ fr.free.nrw.commons.upload.worker.UploadWorker } ]
```

**Comment by nicolas-raoul** [comment]
Trying to upload 30 pictures as a set, all failed.
When I retry a picture, I get the same kind of error:
```
12-24 20:41:10.993 14845 15674 E UploadWorker: java.lang.NullPointerException: The supplied value is null
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableOnErrorReturn$OnErrorReturnObserver.onError(ObservableOnErrorReturn.java:80)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableOnErrorReturn.subscribeActual(ObservableOnErrorReturn.java:31)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker.uploadContribution(UploadWorker.kt:300)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker.access$uploadContribution(UploadWorker.kt:48)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:148)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt__CollectKt.collect(Collect.kt:30)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt.collect(Unknown Source:1)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2.invokeSuspend(UploadWorker.kt:218)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
12-24 20:41:10.993 14845 15674 E UploadWorker: Caused by: java.lang.Exception: titleblacklist-custom-space
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileFromStash$3$UploadClient(UploadClient.java:227)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$-xVSLroq3t059tyyfYuDUQukbVk.apply(Unknown Source:4)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
12-24 20:41:10.993 14845 15674 E UploadWorker: 	... 28 more
12-24 20:41:10.993 14845 15674 E UploadWorker: Upload from stash failed for contribution : Nature near Banfora .jpg
```

Maybe the trailing space in the filename is the problem, I might have mistakenly typed it.

**Comment by nicolas-raoul** [comment]
Only the second of a 2-pics upload failed:
```
12-31 23:06:32.026 19149 19371 D OkHttp  : <-- 200 https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=upload&ignorewarnings=1 (1798ms, 533-byte body)
12-31 23:06:32.031 19149 19371 E UploadClient: Error in uploading file from stash
12-31 23:06:32.031 19149 19371 E UploadClient: org.wikipedia.dataclient.mwapi.MwException: ⧼titleblacklist-custom-space⧽
12-31 23:06:32.034 19149 19371 E UploadWorker: java.lang.NullPointerException: The supplied value is null
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableOnErrorReturn$OnErrorReturnObserver.onError(ObservableOnErrorReturn.java:80)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableOnErrorReturn.subscribeActual(ObservableOnErrorReturn.java:31)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker.uploadContribution(UploadWorker.kt:300)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker.access$uploadContribution(UploadWorker.kt:48)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:148)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt__CollectKt.collect(Collect.kt:30)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlinx.coroutines.flow.FlowKt.collect(Unknown Source:1)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at fr.free.nrw.commons.upload.worker.UploadWorker$doWork$2.invokeSuspend(UploadWorker.kt:218)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
12-31 23:06:32.034 19149 19371 E UploadWorker: Caused by: java.lang.Exception: titleblacklist-custom-space
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at fr.free.nrw.commons.upload.UploadClient.lambda$uploadFileFromStash$3$UploadClient(UploadClient.java:227)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at fr.free.nrw.commons.upload.-$$Lambda$UploadClient$-xVSLroq3t059tyyfYuDUQukbVk.apply(Unknown Source:4)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
12-31 23:06:32.034 19149 19371 E UploadWorker: 	... 28 more
12-31 23:06:32.035 19149 19371 E UploadWorker: Upload from stash failed for contribution : December 31 in Japan, shiruko and zenzai at a supermarket .jpg
```

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul an you explain a bit more about this issue ?

**Comment by nicolas-raoul** [comment]
Sorry I haven't seen this in a while, I should have closed it.
Thanks Rishav for the hint!
