### ISSUE TITLE
Crash while clicking on hamburger icon on the bottom sheet

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4749]
**Summary:** 

Crash while clicking on hamburger icon in bottom sheet

**Steps to reproduce:** 

1. Open commons
2. click the hamburger icon on the bottom sheet

**System logs:**

```
2022-01-02 11:10:41.215 11491-11491/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 11491
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
        at android.os.Parcel.createException(Parcel.java:2373)
        at android.os.Parcel.readException(Parcel.java:2356)
        at android.os.Parcel.readException(Parcel.java:2298)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3034)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2998)
        at fr.free.nrw.commons.utils.NetworkUtils.getNetworkType(NetworkUtils.java:52)
        at fr.free.nrw.commons.utils.DeviceInfoUtil.getConnectionType(DeviceInfoUtil.java:47)
        at fr.free.nrw.commons.logging.CommonsLogSender.getExtraInfo(CommonsLogSender.java:78)
        at fr.free.nrw.commons.logging.CommonsLogSender.<init>(CommonsLogSender.java:39)
        at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:22)
        at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:9)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.injectMoreBottomSheetFragment(DaggerCommonsApplicationComponent.java:1314)
        at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.inject(DaggerCommonsApplicationComponent.java:1246)
        at fr.free.nrw.commons.navtab.MoreBottomSheetFragment.onAttach(MoreBottomSheetFragment.java:70)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:253)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1168)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:260)
        at android.app.ActivityThread.main(ActivityThread.java:8265)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
2022-01-02 11:10:41.215 11491-11491/fr.free.nrw.commons E/ACRA: ACRA caught a SecurityException for fr.free.nrw.commons
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
        at android.os.Parcel.createException(Parcel.java:2373)
        at android.os.Parcel.readException(Parcel.java:2356)
        at android.os.Parcel.readException(Parcel.java:2298)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3034)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2998)
        at fr.free.nrw.commons.utils.NetworkUtils.getNetworkType(NetworkUtils.java:52)
        at fr.free.nrw.commons.utils.DeviceInfoUtil.getConnectionType(DeviceInfoUtil.java:47)
        at fr.free.nrw.commons.logging.CommonsLogSender.getExtraInfo(CommonsLogSender.java:78)
        at fr.free.nrw.commons.logging.CommonsLogSender.<init>(CommonsLogSender.java:39)
        at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:22)
        at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:9)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.injectMoreBottomSheetFragment(DaggerCommonsApplicationComponent.java:1314)
        at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.inject(DaggerCommonsApplicationComponent.java:1246)
        at fr.free.nrw.commons.navtab.MoreBottomSheetFragment.onAttach(MoreBottomSheetFragment.java:70)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:253)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1168)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:260)
        at android.app.ActivityThread.main(ActivityThread.java:8265)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Device and Android version:** 

Realme GT master API 30
 
**Commons app version:** 

latest prodDebug

**Would you like to work on the issue?**

No

**Comment by neslihanturan** [comment]
Hey @Ayan-10 can you reproduce this reliably?

**Comment by Ayan-10** [comment]
@neslihanturan Yes, It was occurring on the latest prod master. Even I have an older version (2-3 commits older than the latest) installed on my device. It's still occurring on it. But now I can't reproduce it in the latest master anymore.

**Comment by neslihanturan** [comment]
So closing it for now, feel free to reopen :)
