### ISSUE TITLE
Leaderboard: Taping on my avatar should open tip popup explaining how to change it

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4774]
When tapping the round shown by the red arrow:
![Screenshot_20220131-120111_Commons](https://user-images.githubusercontent.com/99590/151733378-e19d1c6c-90c9-4622-b405-f5a3a961b0a0.jpg)

... show this tooltip:

> To set up your leaderboard avatar, tap "Set as avatar" in the three-dots menu of any image."

**Comment by ratneshnavlakhe** [comment]
Hi, @nicolas-raoul I would like to look into this. Can you assign me?

**Comment by nicolas-raoul** [comment]
@ratneshnavlakhe It is yours, thanks! :-)

**Comment by ratneshnavlakhe** [comment]
Hi @nicolas-raoul there seems to be some issue with loading leader board, getting this stack trace on logcat.

`2022-02-01 23:49:51.214 8161-8161/fr.free.nrw.commons.beta E/AchievementsFragment: Fetching achievements statistics failed
    java.lang.StringIndexOutOfBoundsException: length=31; index=-1
        at java.lang.String.substring(String.java:1935)
        at fr.free.nrw.commons.mwapi.OkHttpJsonApiClient.lambda$getAchievements$4$OkHttpJsonApiClient(OkHttpJsonApiClient.java:259)
        at fr.free.nrw.commons.mwapi.-$$Lambda$OkHttpJsonApiClient$-O4cqgnxRevLtbK8AVZXcOmTWMo.call(Unknown Source:6)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2022-02-01 23:49:51.256 8161-8161/fr.free.nrw.commons.beta E/RecyclerView: No adapter attached; skipping layout
`

**Comment by nicolas-raoul** [comment]
@ratneshnavlakhe Can you reproduce this problem on the master branch? If yes, please create a new GitHub issue, thanks for finding this! :-)

**Comment by misaochan** [comment]
@ratneshnavlakhe are you running betaDebug build variant (as it seems from the logs)? Please test the leaderboard with prodDebug instead, thanks. :)

**Comment by madhurgupta10** [comment]
> @ratneshnavlakhe are you running betaDebug build variant (as it seems from the logs)? Please test the leaderboard with prodDebug instead, thanks. :)

Maybe also adding a toast message saying "Leaderboard is only available on prod version" could be another good first issue.

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Great idea, issue created: #4784

**Comment by ratneshnavlakhe** [comment]
Yeah makes @madhurgupta10 to add a toast if the feature is unavailable for other variants.
Thanks, @misaochan will try it out with prodDebug build.

**Comment by SamarthAsthan** [comment]
@nicolas-raoul can i add this feature ?

**Comment by madhurgupta10** [comment]
@SamarthAsthan Sure, feel free to make a PR.

**Comment by SamarthAsthan** [comment]
@madhurgupta10 it will be great if it will open that persons profile picture on taping on avatar ?

**Comment by nicolas-raoul** [comment]
@SamarthAsthan Sorry it was ambiguous, I rewrote the issue title and description to detail exactly what must be done. Thanks! :-)

**Comment by SamarthAsthan** [comment]
@nicolas-raoul you wanna say like like instagram?

https://user-images.githubusercontent.com/97031010/187924514-dcb976be-3086-4d02-81b1-ba9a8ad7267d.MP4

**Comment by nicolas-raoul** [comment]
@SamarthAsthan Yes except it should show an explanation popup rather than a menu.

**Comment by bhavanagarlapati** [comment]
Hi @nicolas-raoul , Is anyone working on this issue? Can I take this up?

**Comment by nicolas-raoul** [comment]
@SamarthAsthan Any progress on this? :-)

@bhavanagarlapati Please take one issue at a time. Do not hesitate to come back to this one after sending a pull request for your currently assigned one. :-)

**Comment by nicolas-raoul** [comment]
@SamarthAsthan Sorry I realize I did not respond. A simple toast or snackbar is enough. No buttons needed, just a label.

**Comment by ArmanNavodia** [comment]
@nicolas-raoul can you please assign me this issue.

**Comment by nicolas-raoul** [comment]
@ArmanNavodia It is yours, thanks! 🙂
