### ISSUE TITLE
[Bug]: UnknownFormatConversionException: Conversion = 'এ'

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4877]
### Summary

UnknownFormatConversionException

### Steps to reproduce

1. Open app
2. In Settings, change "app user interface language" to বাংলা [bn]
3. Start uploading a picture (for instance via the + gallery button)

### Expected behaviour

Can upload

### Actual behaviour

Crash:

java.util.UnknownFormatConversionException: Conversion = 'এ'
at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2781)
at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2811)
at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
at java.util.Formatter.parse(Formatter.java:2557)
at java.util.Formatter.format(Formatter.java:2504)
at java.util.Formatter.format(Formatter.java:2458)
at java.lang.String.format(String.java:2883)
at android.content.res.Resources.getQuantityString(Resources.java:514)
at fr.free.nrw.commons.upload.license.MediaLicenseFragment.updateLicenseSummary(MediaLicenseFragment.java:169)
at fr.free.nrw.commons.upload.license.MediaLicensePresenter.selectLicense(MediaLicensePresenter.java:75)
at fr.free.nrw.commons.upload.license.MediaLicenseFragment$2.onItemSelected(MediaLicenseFragment.java:132)
at android.widget.AdapterView.fireOnSelected(AdapterView.java:1366)
at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1355)
at android.widget.AdapterView.access$300(AdapterView.java:59)
at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1314)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7032)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

### Android version

Any

### Commons app version

3.1.1, master

### Would you like to work on the issue?

Prefer not

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul @4D17Y4 solved this bug and created a pull request #4890 

sorry for not assigned and still solved , but this was really a simple bug and an urgent one

**Comment by 4D17Y4** [comment]
### **Please do not start working on an unassigned issue.**

Ping us to get assigned and then notify with the proposed solution.
If accepted, start working. 

Closing this as it is solved.

**Comment by nicolas-raoul** [comment]
For long-term resolution, the change should be performed in Translatewiki.
`app/src/main/res/values-bn/strings.xml` get overwritten regularly by content from Translatewiki.
https://github.com/commons-app/commons-app-documentation/blob/master/android/Translating-the-app.md

**Comment by sivaraam** [comment]
> For long-term resolution, the change should be performed in Translatewiki. 

This appears to be available in Translatewiki already. Curiously, it looks like a bot imported the changes done in the repository into translatewiki 🤔 

Related change link in Translatewiki: https://translatewiki.net/w/i.php?title=Wikimedia:Commons-android-strings-share_license_summary/bn&diff=10602509&oldid=9550296

Anyways, I suppose there's nothing left to do here. Hence closing this.
