### ISSUE TITLE
Depiction not found despite Wikidata item with that exact name

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4913]
Steps to reproduce:
1. Start an upload
2. At the depictions selection step, type `ouagadougou`

Expected: [The Ouagadougou item](https://www.wikidata.org/wiki/Q3777) is suggested
Actually: Nothing is suggested

```
03-21 16:06:06.573  5160  5160 I SurfaceFlinger:      Device | 0x733584a260 | 0002 | RGBx_8888 |   0.0    0.0 1080.0 2280.0 |    0    0 1080 2280 | fr.free.nrw.commons/fr.free.nrw.commons.upload.UploadActivity[30362]#0
03-21 16:06:06.885 30362 25922 D OkHttp  : --> GET https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json&type=item&uselang=en&search=ouagadougou&limit=25&language=en&uselang=en&continue=0
03-21 16:06:06.887 30362 25922 D CookieManager: Domain:www.wikidata.org
03-21 16:06:06.887 30362 25922 D CookieManager: Adding centralauth cookies
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: java.io.InterruptedIOException
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:642)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:394)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okio.RealBufferedSource.read(RealBufferedSource.kt:41)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okio.RealBufferedSource.exhausted(RealBufferedSource.kt:51)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okio.InflaterSource.refill(InflaterSource.kt:94)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okio.InflaterSource.read(InflaterSource.kt:54)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okio.GzipSource.read(GzipSource.kt:69)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okio.RealBufferedSource.request(RealBufferedSource.kt:62)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.Response.peekBody(Response.java:152)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:87)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at okhttp3.RealCall.execute(RealCall.java:92)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-21 16:06:06.888 30362 25931 E OkHttpConnectionFactory$UnsuccessfulResponseInterceptor: 	at java.lang.Thread.run(Thread.java:764)
03-21 16:06:06.888 30362 25931 D OkHttp  : <-- 200 https://www.wikidata.org/w/api.php?format=json&action=wbgetentities&ids=Q3777%7CQ773547%7CQ1736205%7CQ3357901%7CQ17523739%7CQ2419759%7CQ2518888%7CQ36953322%7CQ17049945%7CQ100340129%7CQ23652369%7CQ3357894%7CQ21774254%7CQ22145991%7CQ3357897%7CQ43936324%7CQ1365200 (1086ms, unknown-length body)
03-21 16:06:07.459 30362 25922 D OkHttp  : <-- 200 https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json&type=item&uselang=en&search=ouagadougou&limit=25&language=en&uselang=en&continue=0 (574ms, unknown-length body)
03-21 16:06:07.461 30362 25922 D OkHttp  : --> GET https://www.wikidata.org/w/api.php?format=json&action=wbgetentities&ids=Q3777%7CQ22145991%7CQ773547%7CQ1736205%7CQ3357901%7CQ17523739%7CQ2518888%7CQ36953322%7CQ17049945%7CQ100340129%7CQ23652369%7CQ21774254%7CQ3357897%7CQ43936324%7CQ1365200
03-21 16:06:07.463 30362 25922 D CookieManager: Domain:www.wikidata.org
03-21 16:06:07.463 30362 25922 D CookieManager: Adding centralauth cookies
03-21 16:06:08.981 30362 25922 D OkHttp  : <-- 200 https://www.wikidata.org/w/api.php?format=json&action=wbgetentities&ids=Q3777%7CQ22145991%7CQ773547%7CQ1736205%7CQ3357901%7CQ17523739%7CQ2518888%7CQ36953322%7CQ17049945%7CQ100340129%7CQ23652369%7CQ21774254%7CQ3357897%7CQ43936324%7CQ1365200 (1519ms, unknown-length body)
03-21 16:06:09.079 30362 25922 E DepictModelKt: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at kotlin.collections.EmptyList.get(Collections.kt:36)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at kotlin.collections.EmptyList.get(Collections.kt:24)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at fr.free.nrw.commons.explore.depictions.DepictsClient.mapToDepictions$lambda-3(DepictsClient.kt:55)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at fr.free.nrw.commons.explore.depictions.DepictsClient.lambda$41-KRxUt0_Z7DoN1XUSLQv2eLuU(Unknown Source:0)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at fr.free.nrw.commons.explore.depictions.-$$Lambda$DepictsClient$41-KRxUt0_Z7DoN1XUSLQv2eLuU.apply(Unknown Source:4)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Single.subscribe(Single.java:3603)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-21 16:06:09.079 30362 25922 E DepictModelKt: 	at java.lang.Thread.run(Thread.java:764)
```

As you can see, the app calls [the correct URL](https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json&type=item&uselang=en&search=ouagadougou&limit=25&language=en&uselang=en&continue=0) (which contains the correct item) but it fails.

Strangely, erasing the search field and typing `wagadugu` (the name of the same city in a different language) makes the item appear correctly.

I can reproduce all the time for `ouagadougou`, and also with many other popular Wikidata items. For instance `food truck` suggests nothing but `foodtruck` does, `takoyaki` suggests nothing but `たこ焼き` does, `Roppongi` suggests nothing, etc.

App version: git master

**Comment by Ayan-10** [comment]
I have diagnosed the issue and it came out that some of the entity response does not have either description or P31 property that's the reason for not showing any responses. I think we can show no description for the entities which neither have a description nor a P31 property (Instance of). I would like to work on this.

**Comment by nicolas-raoul** [comment]
Thanks for the investigation!

In the [API query for Ouagadougou](https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json&type=item&uselang=en&search=ouagadougou&limit=25&language=en&uselang=en&continue=0) all results have a label, but not all results have a description nor P31 (for instance [Q2518888](https://www.wikidata.org/wiki/Q2518888) does not have description nor P31).

We should display all results, even results that do not have a description or a P31 (just like we display also results that do not have a thumbnail).
