### ISSUE TITLE
[Bug]: Crash on image upload.

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4919]
### Summary

Uploading in current master crashes the app with following log :

> android.database.sqlite.SQLiteException: no such table: recent_languages (code 1 SQLITE_ERROR): , while compiling: SELECT language_name, language_code FROM recent_languages
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)

### Steps to reproduce

Try uploading a pic in current master. 

### Expected behaviour

Upload should proceed.

### Actual behaviour

App crashes

### Android version

10

### Commons app version

3.1.1

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment]
Does this happen even after removing the app's data?

**Comment by misaochan** [comment]
Hi @4D17Y4 , could you list the steps to reproduce in a more detailed manner please? For instance, are you uploading through Contributions > Gallery, or Nearby? At what step does the upload crash?
