### ISSUE TITLE
Crash when trying to edit description (in Media details)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4922]
### Summary

```
android.database.sqlite.SQLiteException: no such table: recent_languages (code 1 SQLITE_ERROR[1]): , while compiling: SELECT language_name, language_code FROM recent_languages
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1229)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:703)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1865)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:419)
at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:296)
at fr.free.nrw.commons.recentlanguages.RecentLanguagesContentProvider.query(RecentLanguagesContentProvider.java:59)
at android.content.ContentProvider.query(ContentProvider.java:1078)
at android.content.ContentProvider.query(ContentProvider.java:1170)
at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
at android.content.ContentProviderClient.query(ContentProviderClient.java:163)
at android.content.ContentProviderClient.query(ContentProviderClient.java:146)
at android.content.ContentProviderClient.query(ContentProviderClient.java:136)
at fr.free.nrw.commons.recentlanguages.RecentLanguagesDao.getRecentLanguages(RecentLanguagesDao.java:37)
at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.initLanguage(UploadMediaDetailAdapter.java:200)
at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.bind(UploadMediaDetailAdapter.java:183)
at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.onBindViewHolder(UploadMediaDetailAdapter.java:94)
at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.onBindViewHolder(UploadMediaDetailAdapter.java:39)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7093)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7172)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6037)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6304)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6143)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6139)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4141)
at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3542)
at fr.free.nrw.commons.widget.HeightLimitedRecyclerView.onMeasure(HeightLimitedRecyclerView.java:46)
at android.view.View.measure(View.java:24967)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
at android.view.View.measure(View.java:24967)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
at android.view.View.measure(View.java:24967)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
at android.view.View.measure(View.java:24967)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
at android.view.View.measure(View.java:24967)
at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
at android.view.View.measure(View.java:24967)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
at android.view.View.measure(View.java:24967)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
at android.view.View.measure(View.java:24967)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
at android.view.View.measure(View.java:24967)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:24967)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
at android.view.View.measure(View.java:24967)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7134)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:992)
at android.view.View.measure(View.java:24967)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3266)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1993)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2295)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1853)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8476)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
at android.view.Choreographer.doCallbacks(Choreographer.java:761)
at android.view.Choreographer.doFrame(Choreographer.java:696)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7032)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
Same stack trace as #4919 so it might be the same issue. I create a new issue since it happens in a different place.

### Steps to reproduce

1. Open app
2. Upload pictures with captions in several languages (might be optional)
3. In your contributions or in Explore, tap on any picture (this opens media details)
4. Tap on the pen circled in red:
![adb](https://user-images.githubusercontent.com/99590/160240295-fc195ac7-b38b-4f78-9b78-da2110c0d16c.png)

### Expected behaviour

Description edition dialog opens

### Actual behaviour

Crash

### Android version

8

### Commons app version

master

### Would you like to work on the issue?

Prefer not

**Comment by nicolas-raoul** [comment]
Probably linked to this recently merged pull request: https://github.com/commons-app/apps-android-commons/pull/4880

**Comment by Ayan-10** [comment]
@nicolas-raoul I tried to reproduce the error but got a different stack trace. Actually, in the [issue](https://github.com/commons-app/apps-android-commons/pull/4880) two places  (settings and upload) were mentioned where I have to implement the language selection history and also I forget that the description editor also uses the language selection. Sorry about that. So, language selection history is not implemented in `DescriptionEditActivity` this is the reason for the below error.


```
2022-03-26 19:31:26.853 5176-5176/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 5176
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List fr.free.nrw.commons.recentlanguages.RecentLanguagesDao.getRecentLanguages()' on a null object reference
        at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.initLanguage(UploadMediaDetailAdapter.java:200)
        at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.bind(UploadMediaDetailAdapter.java:183)
        at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.onBindViewHolder(UploadMediaDetailAdapter.java:94)
        at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.onBindViewHolder(UploadMediaDetailAdapter.java:39)
```

I can work on it but right now I'm working on another issue. So if anyone can work on it right now, please take it. The implementation should be the same as in the Settings and Upload Wizard.

Thanks.

**Comment by nicolas-raoul** [comment]
@Ayan-10 Yes I had also forgotten about this place, sorry! Sure no worries :-)

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on it?

**Comment by nicolas-raoul** [comment]
@Ayan-10 Yes thanks! :-)
