### ISSUE TITLE
[Bug]: App crashed after add new category to a picture without category 

### ISSUE THREAD

**Issue by Compiledebuger** [commons-app/apps-android-commons#4942]
### Summary

App crashed after add new category to a picture without category 

### Steps to reproduce

1.update a new picture without selecting category 
2.add a new category to the picture, then the app crashed

### Expected behaviour

The app will add a new category 

### Actual behaviour

The app crashed immediately

### Device name

No response

### Android version

9

### Commons app version

master

### Screen-shots

picture without category:
![1BD736BBA7349A8B59C54856C618DFCA](https://user-images.githubusercontent.com/57441189/164887637-9907604f-8ac0-40d4-af2e-806484bafec4.jpg)  
add new category:  
![25B027322A0A3BF6F9C7E7BE37831F93](https://user-images.githubusercontent.com/57441189/164887666-bb92661d-5490-42af-b4a0-22074391892a.jpg)    
app crashed:  
![724016E6DC4A94920519992F2308DFDB](https://user-images.githubusercontent.com/57441189/164887683-b2738254-5688-49c5-86c3-0bb041af936c.jpg)

### Would you like to work on the issue?

Yes

**Comment by Compiledebuger** [comment]
@nicolas-raoul

**Comment by nicolas-raoul** [comment]
I was not able to reproduce, strangely.
Would you mind posting a stack trace? You can easily get it by tapping 確定 on the bug report popup then checking the content of the prepared email.
Thanks for your report!

**Comment by Compiledebuger** [comment]
@nicolas-raoul The bug report is as follows:
```  
USER_COMMENT=
APP_VERSION_CODE=1025
APP_VERSION_NAME=3.1.1-debug-master
ANDROID_VERSION=9
PHONE_MODEL=AOSP on IA Emulator
STACK_TRACE=java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:2036)
at fr.free.nrw.commons.category.CategoryEditHelper.addCategory(CategoryEditHelper.java:69)
at fr.free.nrw.commons.category.CategoryEditHelper.makeCategoryEdit(CategoryEditHelper.java:49)
at fr.free.nrw.commons.upload.categories.CategoriesPresenter.updateCategories(CategoriesPresenter.kt:206)
at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment.onNextButtonClicked(UploadCategoriesFragment.java:279)
at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment_ViewBinding$1.doClick(UploadCategoriesFragment_ViewBinding.java:46)
at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
at android.view.View.performClick(View.java:6597)
at android.view.View.performClickInternal(View.java:6574)
at android.view.View.access$3100(View.java:778)
at android.view.View$PerformClick.run(View.java:25885)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

USER_CRASH_DATE=2022-04-25T09:05:53.463+00:00
IS_SILENT=false
REPORT_ID=c7185ad0-8ca8-4b8a-ba25-3b3661f4f9e6
USER_EMAIL=
```

**Comment by nicolas-raoul** [comment]
Great find! Looking forward to your pull request :-)

**Comment by Compiledebuger** [comment]
Thanks, I already make one pull request https://github.com/commons-app/apps-android-commons/pull/4943
