### ISSUE TITLE
[Bug]: Crash on clicking edit button on description

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#4959]
### Summary

Crash on clicking the edit button in the descriptions.

This caused due to incorrect previous db version in https://github.com/commons-app/apps-android-commons/pull/4880

### Steps to reproduce

Go to an Upload Media.
Click on Pencil Icon next to - In all languages in the description
App crashes

### Expected behaviour

Should not crash

### Actual behaviour

Crash on button click

### Device name

Mi A2

### Android version

API 29

### Commons app version

4.0-release

### Device logs

```
2022-05-19 14:15:26.902 3720-3720/fr.free.nrw.commons.beta E/ACRA: ACRA caught a SQLiteException for fr.free.nrw.commons.beta
    android.database.sqlite.SQLiteException: no such table: recent_languages (code 1 SQLITE_ERROR): , while compiling: SELECT language_name, language_code FROM recent_languages
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:604)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:475)
        at fr.free.nrw.commons.recentlanguages.RecentLanguagesContentProvider.query(RecentLanguagesContentProvider.java:59)
        at android.content.ContentProvider.query(ContentProvider.java:1214)
        at android.content.ContentProvider.query(ContentProvider.java:1307)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:267)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:195)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:177)
        at android.content.ContentProviderClient.query(ContentProviderClient.java:167)
        at fr.free.nrw.commons.recentlanguages.RecentLanguagesDao.getRecentLanguages(RecentLanguagesDao.java:37)
        at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.initLanguage(UploadMediaDetailAdapter.java:201)
        at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.bind(UploadMediaDetailAdapter.java:184)
        at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.onBindViewHolder(UploadMediaDetailAdapter.java:95)
        at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.onBindViewHolder(UploadMediaDetailAdapter.java:39)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7093)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7172)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6037)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6304)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6143)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6139)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4141)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3542)
        at android.view.View.measure(View.java:24549)
        at androidx.constraintlayout.widget.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:24549)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
```

### Would you like to work on the issue?

Yes

**Comment by madhurgupta10** [comment]
Fixed in #4960
