### ISSUE TITLE
[Bug]: App crashed after after edit multiple caption several time

### ISSUE THREAD

**Issue by Compiledebuger** [commons-app/apps-android-commons#4978]
### Summary

I try to add multiple caption and description of different language to a picture. First, I add some caption and description to it. And delete some of them, then the app crashed.

### Steps to reproduce

1.choose one picture and open it.  
2.push edit button near the caption.  
![image](https://user-images.githubusercontent.com/57441189/170704116-78aca595-5a35-47f3-8a62-d0c220d09bd9.png)
3.add three new caption and description
![image](https://user-images.githubusercontent.com/57441189/170704397-77778be3-b30d-4da4-a91e-44f8144c4b20.png)
4.Delete them from top to bottom.
5.And add two new caption and description, then the app crashed.
![CAE4C17DC648EEA07FE27093F9D59FA4](https://user-images.githubusercontent.com/57441189/170704988-62fc4a59-6c4b-480d-97f6-be49879fe73c.jpg)

### Expected behaviour

New title and description added

### Actual behaviour

The app crashed. The error code is 
```
USER_COMMENT=
APP_VERSION_CODE=1025
APP_VERSION_NAME=3.1.1-debug-master
ANDROID_VERSION=11
PHONE_MODEL=Nokia 8.3 5G
STACK_TRACE=java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
at java.util.ArrayList.get(ArrayList.java:437)
at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.lambda$bind$4$UploadMediaDetailAdapter$ViewHolder(UploadMediaDetailAdapter.java:183)
at fr.free.nrw.commons.upload.-$$Lambda$UploadMediaDetailAdapter$ViewHolder$1zvdxPzcb5GVb51Y8BuAMwqXxy4.onTextChanged(Unknown Source:4)
at fr.free.nrw.commons.utils.AbstractTextWatcher.onTextChanged(AbstractTextWatcher.java:21)
at android.widget.TextView.sendOnTextChanged(TextView.java:10665)
at android.widget.TextView.setText(TextView.java:6331)
at android.widget.TextView.setText(TextView.java:6156)
at android.widget.EditText.setText(EditText.java:121)
at android.widget.TextView.setText(TextView.java:6108)
at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.bind(UploadMediaDetailAdapter.java:159)
at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.onBindViewHolder(UploadMediaDetailAdapter.java:95)
at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.onBindViewHolder(UploadMediaDetailAdapter.java:39)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7093)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7172)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6037)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6304)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6143)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6139)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2314)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4141)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3853)
at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1899)
at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5270)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
at android.view.Choreographer.doCallbacks(Choreographer.java:878)
at android.view.Choreographer.doFrame(Choreographer.java:807)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7697)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

IS_SILENT=false
REPORT_ID=d6b6d4d3-2edb-4036-baa2-274427f75493
USER_CRASH_DATE=2022-05-27T20:33:02.991+08:00
USER_EMAIL=
```

### Device name

Nokia 8.3 5G

### Android version

9

### Commons app version

master

### Would you like to work on the issue?

Yes

**Comment by Compiledebuger** [comment]
@nicolas-raoul

**Comment by nicolas-raoul** [comment]
I can reproduce the crash, thanks for finding this and reporting!
