### ISSUE TITLE
v4.0 crash report - java.lang.SecurityException: getDataNetworkTypeForSubscriber

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4988]
From our google group crash report forum:

```
USER_COMMENT=
APP_VERSION_CODE=1026
APP_VERSION_NAME=4.0.0
ANDROID_VERSION=11
PHONE_MODEL=DN2103
STACK_TRACE=java.lang.SecurityException: getDataNetworkTypeForSubscriber
at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
at android.os.Parcel.createException(Parcel.java:2373)
at android.os.Parcel.readException(Parcel.java:2356)
at android.os.Parcel.readException(Parcel.java:2298)
at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3051)
at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3015)
at fr.free.nrw.commons.utils.NetworkUtils.getNetworkType(NetworkUtils.java:52)
at fr.free.nrw.commons.utils.DeviceInfoUtil.getConnectionType(DeviceInfoUtil.java:47)
at fr.free.nrw.commons.logging.CommonsLogSender.getExtraInfo(CommonsLogSender.java:78)
at fr.free.nrw.commons.logging.CommonsLogSender.<init>(CommonsLogSender.java:39)
at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:22)
at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:9)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.injectMoreBottomSheetFragment(DaggerCommonsApplicationComponent.java:1401)
at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.inject(DaggerCommonsApplicationComponent.java:1332)
at fr.free.nrw.commons.navtab.MoreBottomSheetFragment.onAttach(MoreBottomSheetFragment.java:84)
at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:253)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1168)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:265)
at android.app.ActivityThread.main(ActivityThread.java:8360)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

**Comment by misaochan** [comment]
Another similar report from a different user which might help:

```
USER_COMMENT=Burger menu clicked, app is crashed
APP_VERSION_CODE=1026
APP_VERSION_NAME=4.0.0-debug-HEAD
ANDROID_VERSION=11
PHONE_MODEL=Mi 9T
STACK_TRACE=java.lang.SecurityException: getDataNetworkTypeForSubscriber
at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8768)
at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3031)
at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2995)
at fr.free.nrw.commons.utils.NetworkUtils.getNetworkType(NetworkUtils.java:52)
at fr.free.nrw.commons.utils.DeviceInfoUtil.getConnectionType(DeviceInfoUtil.java:47)
at fr.free.nrw.commons.logging.CommonsLogSender.getExtraInfo(CommonsLogSender.java:78)
at fr.free.nrw.commons.logging.CommonsLogSender.<init>(CommonsLogSender.java:39)
at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:22)
at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:9)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.injectMoreBottomSheetFragment(DaggerCommonsApplicationComponent.java:1401)
at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.inject(DaggerCommonsApplicationComponent.java:1332)
at fr.free.nrw.commons.navtab.MoreBottomSheetFragment.onAttach(MoreBottomSheetFragment.java:84)
at [androidx.fragment.app](http://androidx.fragment.app/).Fragment.performAttach(Fragment.java:2672)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentStateManager.attach(FragmentStateManager.java:253)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.moveToState(FragmentManager.java:1168)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.moveToState(FragmentManager.java:1354)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.moveToState(FragmentManager.java:1495)
at [androidx.fragment.app](http://androidx.fragment.app/).BackStackRecord.executeOps(BackStackRecord.java:447)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.executeOps(FragmentManager.java:2167)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.executeOpsTogether(FragmentManager.java:1990)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.execPendingActions(FragmentManager.java:1847)
at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager$4.run(FragmentManager.java:413)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7666)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by madhurgupta10** [comment]
@misaochan These crashes are caused by the changes done in https://github.com/commons-app/apps-android-commons/pull/4723 

Mapbox needs this permission - https://stackoverflow.com/questions/70803660/mapbox-oncreate-instance-crashed-onstart-android-java

I am not sure what should I do here?

**Comment by madhurgupta10** [comment]
@misaochan I could not reproduce the crash on my end, I tested with AVD 10, 11 and 12 so I am not 100% sure if the crash is caused by Mapbox or not, we could try updating the Mapbox SDKs to latest. Still, without reproducing it locally, we need to wait for the original reporter to confirm if it is fixed or not.

**Comment by misaochan** [comment]
Yes, please do so and I'll release the next beta version, then we will see if the crash reports still come in for this one.

**Comment by misaochan** [comment]
@madhurgupta10 seems like it didn't work. :/

```
USER_COMMENT=внизу справа нажал три полоски и программа закрылась
APP_VERSION_CODE=1027
APP_VERSION_NAME=4.0.1
ANDROID_VERSION=12
PHONE_MODEL=M2101K6G
STACK_TRACE=java.lang.SecurityException: getDataNetworkTypeForSubscriber
at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
at android.os.Parcel.createException(Parcel.java:2409)
at android.os.Parcel.readException(Parcel.java:2392)
at android.os.Parcel.readException(Parcel.java:2334)
at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:9300)
at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2964)
at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2928)
at fr.free.nrw.commons.utils.NetworkUtils.getNetworkType(NetworkUtils.java:52)
at fr.free.nrw.commons.utils.DeviceInfoUtil.getConnectionType(DeviceInfoUtil.java:47)
at fr.free.nrw.commons.logging.CommonsLogSender.getExtraInfo(CommonsLogSender.java:78)
at fr.free.nrw.commons.logging.CommonsLogSender.<init>(CommonsLogSender.java:39)
at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:22)
at fr.free.nrw.commons.logging.CommonsLogSender_Factory.get(CommonsLogSender_Factory.java:9)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.injectMoreBottomSheetFragment(DaggerCommonsApplicationComponent.java:1401)
at fr.free.nrw.commons.di.DaggerCommonsApplicationComponent.inject(DaggerCommonsApplicationComponent.java:1332)
at fr.free.nrw.commons.navtab.MoreBottomSheetFragment.onAttach(MoreBottomSheetFragment.java:84)
at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:253)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1168)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8168)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```
