### ISSUE TITLE
NullPointerException: Attempt to invoke interface method UploadMediaDetailFragmentCallback.getIndexInViewFlipper

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4990]
```
APP_VERSION_CODE=1025
APP_VERSION_NAME=3.1.1-debug-master
ANDROID_VERSION=9
PHONE_MODEL=SM-G970F
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'int fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment$UploadMediaDetailFragmentCallback.getIndexInViewFlipper(fr.free.nrw.commons.upload.UploadBaseFragment)' on a null object reference
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.init(UploadMediaDetailFragment.java:155)
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.onViewCreated(UploadMediaDetailFragment.java:151)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:322)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
at android.app.Activity.performStart(Activity.java:7348)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3131)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7032)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

Happening on latest master.

This started happening rather recently.

I only got it a few times, but reproduction seems to be like this:
1. Prepare an upload by selecting a few pictures.
2. Without actually uploading, leave the app for hours, doing other things.
3. Crash when opening the app.

**Comment by SamarthAsthan** [comment]
@misaochan can i work on it ?

**Comment by nicolas-raoul** [comment]
@SamarthAsthan Yes thanks!

**Comment by ev-rymko** [comment]
Hello! Is this issue open now? If yes, can I try to fix it?

**Comment by nicolas-raoul** [comment]
No recent news from SamarthAsthan so you can take it, thanks!

But I haven't seen this issue in months actually, so better close it actually.
If you manage to reproduce it, you are more than welcome to fix it, though :-)
