### ISSUE TITLE
v4.0 crash report - NPE at UploadMediaDetailFragment.java:155

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#5001]
From google groups forum:

```
USER_COMMENT=I switched apps, then switched back again, and this error popped up
APP_VERSION_CODE=1027
APP_VERSION_NAME=4.0.1
ANDROID_VERSION=11
PHONE_MODEL=moto g(9) plus
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'int fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment$UploadMediaDetailFragmentCallback.getIndexInViewFlipper(fr.free.nrw.commons.upload.UploadBaseFragment)' on a null object reference
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.init(UploadMediaDetailFragment.java:155)
at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.onViewCreated(UploadMediaDetailFragment.java:151)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:322)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
at android.app.Activity.performStart(Activity.java:8134)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3534)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:250)
at android.app.ActivityThread.main(ActivityThread.java:7848)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by misaochan** [comment]
Perhaps related - there is another crash report with the exact same user comment (in German) but a different stack trace.

```
USER_COMMENT=Hochladen funktioniert schon wieder nicht.
APP_VERSION_CODE=1025
APP_VERSION_NAME=3.1.1
ANDROID_VERSION=12
PHONE_MODEL=SM-G998B
STACK_TRACE=[java.lang.RuntimeException](http://java.lang.runtimeexception/): Failure delivering result ResultInfo{who=null, request=66537, result=-1, data=Intent { (has extras) }} to activity {[fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity](http://fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity)}: [java.lang.NullPointerException](http://java.lang.nullpointerexception/): The mapper function returned a null value.
at [android.app.ActivityThread.deliverResults](http://android.app.activitythread.deliverresults/)(ActivityThread.java:5864)
at [android.app.ActivityThread.handleSendResult](http://android.app.activitythread.handlesendresult/)(ActivityThread.java:5903)
at [android.app.servertransaction.ActivityResultItem.execute](http://android.app.servertransaction.activityresultitem.execute/)(ActivityResultItem.java:54)
at [android.app.servertransaction.ActivityTransactionItem.execute](http://android.app.servertransaction.activitytransactionitem.execute/)(ActivityTransactionItem.java:45)
at [android.app.servertransaction.TransactionExecutor.executeCallbacks](http://android.app.servertransaction.transactionexecutor.executecallbacks/)(TransactionExecutor.java:135)
at [android.app.servertransaction.TransactionExecutor.execute](http://android.app.servertransaction.transactionexecutor.execute/)(TransactionExecutor.java:95)
at [android.app.ActivityThread](http://android.app.activitythread/)$[H.handleMessage](http://h.handlemessage/)(ActivityThread.java:2438)
at [android.os.Handler.dispatchMessage](http://android.os.handler.dispatchmessage/)(Handler.java:106)
at [android.os.Looper.loopOnce](http://android.os.looper.looponce/)(Looper.java:226)
at [android.os.Looper.loop](http://android.os.looper.loop/)(Looper.java:313)
at [android.app.ActivityThread.main](http://android.app.activitythread.main/)(ActivityThread.java:8669)
at [java.lang.reflect.Method.invoke](http://java.lang.reflect.method.invoke/)(Native Method)
at [com.android.internal.os.RuntimeInit](http://com.android.internal.os.runtimeinit/)$[MethodAndArgsCaller.run](http://methodandargscaller.run/)(RuntimeInit.java:571)
at [com.android.internal.os.ZygoteInit.main](http://com.android.internal.os.zygoteinit.main/)(ZygoteInit.java:1135)
Caused by: [java.lang.NullPointerException](http://java.lang.nullpointerexception/): The mapper function returned a null value.
at [io.reactivex.internal.functions.ObjectHelper.requireNonNull](http://io.reactivex.internal.functions.objecthelper.requirenonnull/)(ObjectHelper.java:39)
at [io.reactivex.internal.operators.single.SingleMap](http://io.reactivex.internal.operators.single.singlemap/)$[MapSingleObserver.onSuccess](http://mapsingleobserver.onsuccess/)(SingleMap.java:57)
at [io.reactivex.internal.operators.observable.ObservableSingleSingle](http://io.reactivex.internal.operators.observable.observablesinglesingle/)$[SingleElementObserver.onComplete](http://singleelementobserver.oncomplete/)(ObservableSingleSingle.java:109)
at [retrofit2.adapter.rxjava2.BodyObservable](http://retrofit2.adapter.rxjava2.bodyobservable/)$[BodyObserver.onComplete](http://bodyobserver.oncomplete/)(BodyObservable.java:66)
at [retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual](http://retrofit2.adapter.rxjava2.callexecuteobservable.subscribeactual/)(CallExecuteObservable.java:48)
at [io.reactivex.Observable.subscribe](http://io.reactivex.observable.subscribe/)(Observable.java:12267)
at [retrofit2.adapter.rxjava2.BodyObservable.subscribeActual](http://retrofit2.adapter.rxjava2.bodyobservable.subscribeactual/)(BodyObservable.java:34)
at [io.reactivex.Observable.subscribe](http://io.reactivex.observable.subscribe/)(Observable.java:12267)
at [io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual](http://io.reactivex.internal.operators.observable.observablesinglesingle.subscribeactual/)(ObservableSingleSingle.java:35)
at [io.reactivex.Single.subscribe](http://io.reactivex.single.subscribe/)(Single.java:3603)
at [io.reactivex.internal.operators.single.SingleMap.subscribeActual](http://io.reactivex.internal.operators.single.singlemap.subscribeactual/)(SingleMap.java:34)
at [io.reactivex.Single.subscribe](http://io.reactivex.single.subscribe/)(Single.java:3603)
at [io.reactivex.internal.operators.single.SingleSubscribeOn](http://io.reactivex.internal.operators.single.singlesubscribeon/)$[SubscribeOnObserver.run](http://subscribeonobserver.run/)(SingleSubscribeOn.java:89)
at [io.reactivex.Scheduler](http://io.reactivex.scheduler/)$[DisposeTask.run](http://disposetask.run/)(Scheduler.java:578)
at [io.reactivex.internal.schedulers.ScheduledRunnable.run](http://io.reactivex.internal.schedulers.scheduledrunnable.run/)(ScheduledRunnable.java:66)
at [io.reactivex.internal.schedulers.ScheduledRunnable.call](http://io.reactivex.internal.schedulers.scheduledrunnable.call/)(ScheduledRunnable.java:57)
at [java.util.concurrent.FutureTask.run](http://java.util.concurrent.futuretask.run/)(FutureTask.java:266)
at [java.util.concurrent.ScheduledThreadPoolExecutor](http://java.util.concurrent.scheduledthreadpoolexecutor/)$[ScheduledFutureTask.run](http://scheduledfuturetask.run/)(ScheduledThreadPoolExecutor.java:301)
at [java.util.concurrent.ThreadPoolExecutor.runWorker](http://java.util.concurrent.threadpoolexecutor.runworker/)(ThreadPoolExecutor.java:1167)
at [java.util.concurrent.ThreadPoolExecutor](http://java.util.concurrent.threadpoolexecutor/)$[Worker.run](http://worker.run/)(ThreadPoolExecutor.java:641)
at [java.lang.Thread.run](http://java.lang.thread.run/)(Thread.java:920)
```
