### ISSUE TITLE
v4.0 crash report - SQLiteException: no such table: contribution (code 1 SQLITE_ERROR)

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#5006]
From google groups forum:

```
USER_COMMENT=
APP_VERSION_CODE=1027
APP_VERSION_NAME=4.0.1
ANDROID_VERSION=11
PHONE_MODEL=motorola one 5G UW
STACK_TRACE=android.database.sqlite.SQLiteException: no such table: contribution (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM ( SELECT * FROM contribution order by media_dateUploaded DESC ) LIMIT ? OFFSET ?
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1545)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1520)
at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:161)
at androidx.room.RoomDatabase.query(RoomDatabase.java:446)
at androidx.room.RoomDatabase.query(RoomDatabase.java:429)
at androidx.room.paging.LimitOffsetDataSource.loadRange(LimitOffsetDataSource.java:220)
at androidx.room.paging.LimitOffsetDataSource.loadRange(LimitOffsetDataSource.java:191)
at androidx.paging.PositionalDataSource.dispatchLoadRange(PositionalDataSource.java:302)
at androidx.paging.TiledPagedList$2.run(TiledPagedList.java:209)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
```

**Comment by misaochan** [comment]
From the user: "I think all I did was go back to the app after having it in the
background, when the crash notice appeared. I was doing some Wikidata
uploads from the map, but I think this happened between uploads just
as I brought the app back to the foreground (possibly from the task
switcher)."
