### ISSUE TITLE
[Bug]: App won't launch after signing in for first time

### ISSUE THREAD

**Issue by endim8** [commons-app/apps-android-commons#5021]
### Summary

Launching the app for the first time, it was able to open the login screen. After I logged in, the app crashed and now refuses to open.

### Steps to reproduce

1. attempt to open the app

### Expected behaviour

the app should launch

### Actual behaviour

The app refuses to launch

### Device name

Oneplus 8 Pro

### Android version

Android 12

### Commons app version

2.6.0 (fdroid)

### Device logs

```bash
08-01 16:34:15.013  1300  7894 I ActivityTaskManager: START u0 {flg=0x4000000 cmp=fr.free.nrw.commons/.contributions.ContributionsActivity} from uid 10336
08-01 16:34:15.015   999   999 I android.hardware.power-service-qti: Power setMode: 5 to: 1
08-01 16:34:15.021  1300  2524 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (38481976)
08-01 16:34:15.032 16896 16896 D AndroidRuntime: Shutting down VM
08-01 16:34:15.033 16896 16896 E AndroidRuntime: FATAL EXCEPTION: main
08-01 16:34:15.033 16896 16896 E AndroidRuntime: Process: fr.free.nrw.commons, PID: 16896
08-01 16:34:15.033 16896 16896 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.ContributionsActivity}: java.lang.NullPointerException: fr.free.nrw.commons.CommonsApplication.activityInjector() returned null
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3662)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3819)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7833)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: Caused by: java.lang.NullPointerException: fr.free.nrw.commons.CommonsApplication.activityInjector() returned null
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at dagger.internal.Preconditions.checkNotNull(Preconditions.java:79)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at dagger.android.AndroidInjection.inject(AndroidInjection.java:56)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at fr.free.nrw.commons.contributions.ContributionsActivity.onCreate(ContributionsActivity.java:142)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8057)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8037)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3643)
08-01 16:34:15.033 16896 16896 E AndroidRuntime: 	... 12 more
08-01 16:34:15.035  1300 28683 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
08-01 16:34:15.035  1300  7894 W ActivityTaskManager:   Force finishing activity fr.free.nrw.commons/.contributions.ContributionsActivity
08-01 16:34:15.040 16896 16896 I Process : Sending signal. PID: 16896 SIG: 9
08-01 16:34:15.071  1300  9833 I ActivityManager: Process fr.free.nrw.commons (pid 16896) has died: fg  TOP 

```

### Would you like to work on the issue?

Prefer not

**Comment by endim8** [comment]
ah ok, the f-droid version is just insanely out of date... it's working with 3.1.1 downloaded from google play
