### ISSUE TITLE
Beta version crashes: Unrecognized license value

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#506]
After upgrading to the beta version, the Settings screen immediately crashes for me.

1. Delete the app's local storage.
2. Uninstall the app.
3. Install the normal (non-beta) app and launch it. (EDIT: or build and install v.2.1.)
4. Enroll to the beta testing. (EDIT: or build and install v.2.2.)
5. Install it and open Settings.

ANDROID_VERSION=6.0.1
APP_VERSION_NAME=2.2
BRAND=google
PHONE_MODEL=Nexus 5
CUSTOM_DATA=
STACK_TRACE=
java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.settings.SettingsActivity}: java.lang.RuntimeException: Unrecognized license value
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: Unrecognized license value
at fr.free.nrw.commons.Utils.licenseNameFor(Utils.java:233)
at fr.free.nrw.commons.settings.SettingsFragment.onCreate(SettingsFragment.java:22)
at android.app.Fragment.performCreate(Fragment.java:2198)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
at android.app.BackStackRecord.run(BackStackRecord.java:793)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
at android.app.FragmentController.execPendingActions(FragmentController.java:325)
at android.app.Activity.performStart(Activity.java:6267)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
... 9 more
java.lang.RuntimeException: Unrecognized license value
at fr.free.nrw.commons.Utils.licenseNameFor(Utils.java:233)
at fr.free.nrw.commons.settings.SettingsFragment.onCreate(SettingsFragment.java:22)
at android.app.Fragment.performCreate(Fragment.java:2198)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
at android.app.BackStackRecord.run(BackStackRecord.java:793)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
at android.app.FragmentController.execPendingActions(FragmentController.java:325)
at android.app.Activity.performStart(Activity.java:6267)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by misaochan** [comment]
Does it crash again the second time you try?

**Comment by whym** [comment]
Yes. A workaround was to clear the app's data. Restarting it didn't help.

**Comment by VojtechDostal** [comment]
Probably same here. Enabled beta, updated the app, got these error messages when trying to open Settings (Yay! I learned how to use Android Studio :-) ) : 


04-15 17:27:33.138 172-172/? E/BufferQueueCore: [PopupWindow:369cc7c5] setDefaultMaxBufferCount: setting count to 3, previous is 2 
04-15 17:27:34.029 11413-11413/? E/ViewRootImpl: sendUserActionEvent() mView == null
04-15 17:27:34.049 11413-11413/? E/MotionRecognitionManager: mSContextService = null
04-15 17:27:34.049 11413-11413/? E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@44128ca
04-15 17:27:34.079 11413-11413/? E/ACRA: ACRA caught a RuntimeException for fr.free.nrw.commons
                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.settings.SettingsActivity}: java.lang.RuntimeException: Unrecognized license value
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3160)
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3275)
                                             at android.app.ActivityThread.access$1000(ActivityThread.java:218)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:145)
                                             at android.app.ActivityThread.main(ActivityThread.java:7007)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                          Caused by: java.lang.RuntimeException: Unrecognized license value
                                             at fr.free.nrw.commons.Utils.licenseNameFor(Utils.java:233)
                                             at fr.free.nrw.commons.settings.SettingsFragment.onCreate(SettingsFragment.java:22)
                                             at android.app.Fragment.performCreate(Fragment.java:2075)
                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:869)
                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
                                             at android.app.BackStackRecord.run(BackStackRecord.java:834)
                                             at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1470)
                                             at android.app.Activity.performStart(Activity.java:6646)
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3275) 
                                             at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744) 
                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                             at android.os.Looper.loop(Looper.java:145) 
                                             at android.app.ActivityThread.main(ActivityThread.java:7007) 
                                             at java.lang.reflect.Method.invoke(Native Method) 
                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
04-15 17:27:34.440 11413-11500/? E/ACRA: fr.free.nrw.commons fatal error : Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.settings.SettingsActivity}: java.lang.RuntimeException: Unrecognized license value
                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.settings.SettingsActivity}: java.lang.RuntimeException: Unrecognized license value
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3160)
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3275)
                                             at android.app.ActivityThread.access$1000(ActivityThread.java:218)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:145)
                                             at android.app.ActivityThread.main(ActivityThread.java:7007)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                          Caused by: java.lang.RuntimeException: Unrecognized license value
                                             at fr.free.nrw.commons.Utils.licenseNameFor(Utils.java:233)
                                             at fr.free.nrw.commons.settings.SettingsFragment.onCreate(SettingsFragment.java:22)
                                             at android.app.Fragment.performCreate(Fragment.java:2075)
                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:869)
                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
                                             at android.app.BackStackRecord.run(BackStackRecord.java:834)
                                             at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1470)
                                             at android.app.Activity.performStart(Activity.java:6646)
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3275) 
                                             at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744) 
                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                             at android.os.Looper.loop(Looper.java:145) 
                                             at android.app.ActivityThread.main(ActivityThread.java:7007) 
                                             at java.lang.reflect.Method.invoke(Native Method) 
                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
04-15 17:27:34.530 11501-11501/? E/Zygote: MountEmulatedStorage()
04-15 17:27:34.530 11501-11501/? E/Zygote: v2
04-15 17:27:34.560 11501-11501/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-15 17:27:34.620 172-172/? E/BufferQueueCore: [com.sec.android.app.launcher/com.android.launcher2.Launcher] setDefaultMaxBufferCount: setting count to 3, previous is 2 
04-15 17:27:34.720 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.740 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.750 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.770 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.780 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.800 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.820 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.830 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.850 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.870 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.880 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.900 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.920 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.930 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.950 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.970 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:34.980 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.000 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.010 172-172/? E/BufferQueueCore: [fr.free.nrw.commons/org.acra.CrashReportDialog] setDefaultMaxBufferCount: setting count to 3, previous is 2 
04-15 17:27:35.030 749-1710/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.040 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.050 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.060 172-172/? E/BufferQueueCore: [fr.free.nrw.commons/org.acra.CrashReportDialog] setDefaultMaxBufferCount: setting count to 3, previous is 2 
04-15 17:27:35.080 749-1400/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.090 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.110 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.120 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.130 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping
04-15 17:27:35.150 749-779/? E/WindowManager: Performed 6 layouts in a row. Skipping

And it crashed.

I also tried to load "Nearby" items, but they don't seem to load at all. The window remains blank.

**Comment by misaochan** [comment]
Pinging @maskaravivek re: the recent work on licenses, do you think there is a way to prevent this?

**Comment by whym** [comment]
It looks like this crash does not happen when I set system language to English.

**Comment by VojtechDostal** [comment]
I tried switching to US English and it crashed again.

**Comment by misaochan** [comment]
I'll push @whym 's PR as a hotfix once one of the others who wrote the relevant code (@domdomegg or @maskaravivek ) comments on the PR.

**Comment by misaochan** [comment]
Hotfix has been pushed to beta in v2.2.1, should be downloadable in a couple hours. Hopefully this solves the problem. :)

**Comment by VojtechDostal** [comment]
Just confirming that this has been solved apparently. At least in my case.
