### ISSUE TITLE
Upgrade Kotlin Version from 1.5.10 to 1.7.20

### ISSUE THREAD

**Issue by kartikaykaushik14** [commons-app/apps-android-commons#5158]
### What is the user problem or growth opportunity you want to see solved?

As part of [this issue](https://github.com/commons-app/apps-android-commons/issues/5154) and based on [this comment](https://github.com/commons-app/apps-android-commons/issues/4994#issuecomment-1442125601), before migrating from Mapbox to MapLibre, we require certain upgrades in dependencies in our application. This enhancement is to upgrade the Kotlin version from 1.5.10 to 1.7.20. 

Apart from satisfying the requirements of MapLibre, the upgrade in Kotlin has several advantages -

- Bug fixes: Each new version of Kotlin includes bug fixes and stability improvements, which can make your code more reliable and prevent unexpected issues.
- Performance improvements: New versions of Kotlin often include optimizations that can make your code run faster and use fewer resources.
- New language features: Kotlin is a rapidly evolving language, and new versions often include new language features that can improve the expressiveness and readability of your code.
- Security updates: As with any software, new versions of Kotlin may include important security updates that can help protect your application from vulnerabilities and attacks.

**Comment by kartikaykaushik14** [comment]
@nicolas-raoul Could you please assign this issue to me?

**Comment by nicolas-raoul** [comment]
@kartikaykaushik14 Done, thanks!

**Comment by kartikaykaushik14** [comment]
I have been incrementally updating the Kotlin version of the app, and I was able to successfully upgrade the Kotlin version from 1.5.10 to 1.6.10. 

However, during the process of incrementing from 1.6.10 to 1.6.20, I encountered some errors in the tests that need to be addressed. Specifically in org.wikipedia.dataclient.mwapi.page.MwMobileViewPageLeadTest and org.wikipedia.dataclient.mwapi.page.MwPageClientTest.

        
        java.lang.AssertionError: Not completed (latch = 0, values = 0, errors = 1, completions = 0)
        at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:189)
        at io.reactivex.observers.BaseTestConsumer.assertComplete(BaseTestConsumer.java:242)
        at org.wikipedia.dataclient.page.BasePageClientTest.testLeadTitle(BasePageClientTest.java:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)


        Caused by:
        org.wikipedia.dataclient.mwapi.MwException: Unrecognized value for parameter "action": mobileview.
            at org.wikipedia.dataclient.mwapi.MwResponse.postProcess(MwResponse.java:20)
            at org.wikipedia.json.PostProcessingTypeAdapter$1.read(PostProcessingTypeAdapter.java:28)
            at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
            at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
            at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:227)
            at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
            at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
            at io.reactivex.Observable.subscribe(Observable.java:12267)
            at org.wikipedia.dataclient.page.BasePageClientTest.testLeadTitle(BasePageClientTest.java:46)
            ... 18 more

I investigated the issue in MediaWiki and checked the exact URL we were passing as part of the test. I received the following output on running [this URL](https://en.wikipedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=mobileview&prop=text|sections|languagecount|thumb|image|id|namespace|revision|description|lastmodified|normalizedtitle|displaytitle|protection|editable|pageprops&pageprops=wikibase_item&sections=0&sectionprop=toclevel|line|anchor&noheadings=) manually - 

    {"errors":[{"code":"badvalue","text":"Unrecognized value for parameter \"action\": mobileview.","module":"main"}],"docref":"See https://en.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.","servedby":"mw2292"}

Also, on checking [this link](https://en.wikipedia.org/w/api.php?errorformat=plaintext&action=help), I found out that there is indeed no action for "mobileview". Please advise on how to proceed from here.

**Comment by nicolas-raoul** [comment]
Interesting, do you have any idea why the same test was not failing with Kotlin 1.6.10?

If no immediate fix is found, disabling these unit tests temporarily might also be considered. In such a case, please let us know about how many unit tests would be impacted.

Thanks a lot!

**Comment by kartikaykaushik14** [comment]
I found 11 test cases that would be impacted if we plan to disable them temporarily. 

The build on my local is quite unstable. It sometimes fails even for the latest changes on the Master branch. Is there a way I could run the CI pipeline on my own for my branch to test changes?

**Comment by nicolas-raoul** [comment]
Thanks a lot! I think it is OK to disable 6 test cases temporarily if that helps get us on F-Droid.

Very interesting, would you mind creating a new issue ("bug" type) about Mobile Content Service? Thanks!

**Comment by nicolas-raoul** [comment]
> Is there a way I could run the CI pipeline on my own for my branch to test changes?

CI unit tests run every time you push, right?

If you want to re-run for any reason, feel free to push a dummy commit. :-)
