### ISSUE TITLE
[Bug]: some images visible in the list disappear when clicked on details

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5234]
### Summary

When I click on some images that I've taken and uploaded for commons, on their detail page image starts to show, but then disappears. For some images it works normally, showing full picture taken.

### Steps to reproduce

1. take some pictures with Commons app and upload them
2. go in area without internet
3. try to click on "thumbnail" in the list of pictures in app in main view (in order to see picture metadata and full-sized picture)
4. notice that picture is shown for some images, but not others

### Expected behaviour

in step `3.`, I'd expect that I could see all pictures normally when I click on them

### Actual behaviour

some images are not visible after clicking on them.

When clicked in images list, the image is initially shown for a split second, but it then fades-out to gray "mountain & sun" placeholder.

### Device name

Huawei P30Pro

### Android version

Android 10 (EMUI 12)

### Commons app version

4.0.3~cf35307d9 (latest f-droid)

### Device logs

```
2023-06-08 18:49:20,172     [DEBUG] [file-logging-thread-1] [LocationServiceManager] : on location changed
2023-06-08 18:49:21,908     [DEBUG] [file-logging-thread-1] [MediaDetailFragment] : Media license is: CC BY 4.0
2023-06-08 18:49:21,912     [DEBUG] [file-logging-thread-1] [MediaDetailFragment] : Media license is: CC BY-SA 4.0
2023-06-08 18:49:21,913     [DEBUG] [file-logging-thread-1] [MediaDetailFragment] : Media license is: CC BY 4.0
2023-06-08 18:49:21,915     [DEBUG] [file-logging-thread-1] [MediaDataExtractor] : Error occurred while fetching discussion
2023-06-08 18:49:21,920     [DEBUG] [file-logging-thread-1] [MediaDataExtractor] : Error occurred while fetching discussion
2023-06-08 18:49:21,922     [DEBUG] [file-logging-thread-1] [MediaDataExtractor] : Error occurred while fetching discussion
2023-06-08 18:49:21,928     [ERROR] [file-logging-thread-1] [-$$Lambda$mvgeVM6S-0Wc8Z2hreSxmgnMF1Y] : java.net.UnknownHostException: Unable to resolve host "commons.wikimedia.org": No address
 associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at fr.free.nrw.commons.OkHttpConnectionFactory$CommonHeaderRequestInterceptor.intercept(OkHttpConnectionFactory.java:67)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:80)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Linux.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
        ... 44 more

2023-06-08 18:49:21,928     [ERROR] [file-logging-thread-1] [-$$Lambda$mvgeVM6S-0Wc8Z2hreSxmgnMF1Y] : java.net.UnknownHostException: Unable to resolve host "commons.wikimedia.org": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at fr.free.nrw.commons.OkHttpConnectionFactory$CommonHeaderRequestInterceptor.intercept(OkHttpConnectionFactory.java:67)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:80)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:190)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
        at libcore.io.Linux.android_getaddrinfo(Native Method)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
        at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
        ... 44 more

```

### Screen-shots

Here is video of it happening:

https://github.com/commons-app/apps-android-commons/assets/156656/c08314c2-2614-4a64-a77f-215c835cc4df

You'll notice that image is normally displayed only for "fig leaves" picture (_"smokva sa nezrelim plodom"_), but it fails to display on other two images. 

If you watch carefully (or step frame-by-frame) you'll also notice that **all the images do actually get shown**, but after being show for a fraction of second they are **removed and replaced by gray placeholder**. 

### Would you like to work on the issue?

None

**Comment by mnalis** [comment]
I can confirm that this bug is still present in latest f-droid release (4.1.0~1649d1e2c) on Android 10 (EMUI 12), Huawei P30 Pro.

**Comment by sivaraam** [comment]
@mnalis From the log the image load failure seems to be due to a failure to connect with commons.wikimedia.org. 

Could you check if you're able to load the corresponding file page on the browser reliably? You could go to the file page by clicking on the overflow menu in top right in the details view and use the "View file page" option.

**Comment by mnalis** [comment]
@sivaraam see `step 2.` above; the problem only happens when there is no Internet (in which case I cannot open web browser to see file page either, of course). When Internet is present, pictures shows normally (both in the app, and on the webpage).

What is interesting is that:
- the image seems to be cached locally in the app - e.g. it is still visible in main view of the app (multi-picture display)
- when clicking on image to see its details, it shows the picture normally for split second (indicating that it is indeed cached), but it still tries to go online - and then un-displays the picture when that fails (because there is no Internet)
- it happens on some, but not all images. For some images displaying their details still works even when offline.

See e.g. this video below:
- image is visible in main view (0:01)
- upon clicking for details, image is visible for a split second (0:03)
- however a second later on that same details page, image becomes hidden (0:04)
- enabling Internet (0:06) makes the problem go away (0:08) (also note that display _probably_ happens too fast for actual image download if it were actually missing)
- disabling Internet again (0:11) makes the problem appear again (0:13) (so even if it were downloading the image, it did not cache it?)

https://github.com/commons-app/apps-android-commons/assets/156656/834c150a-9c4e-4131-9c48-08ae0efb8b03

So I would guess there are probably two issues:
- app needlessly tries to  download image even when that image is already cached
- if that download then fails, the image is removed from display (instead of reusing existing previously cached copy)

**Comment by nicolas-raoul** [comment]
Thanks @mnalis for the great bug report and @srishti-R for the nice fix!
