### ISSUE TITLE
[Bug]: Crash in MediaDetailPagerFragment due to lack of no-arg constructor

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5240]
### Summary

We've got a whole bunch of crash reports with a cause that seems to surround with instantiating the MediaDetailPagerFragment. One some exploration the cause seems to be due to the lack of a public default constructor in MediaDetailPagerFragment. There's a private no-arg constructor but Android needs a public no-arg contructor to instantiate fragments [[ref](https://stackoverflow.com/a/16977633/5614968)].

### Steps to reproduce

I don't have specific steps. @nicolas-raoul could you share a set of steps if possible ?

### Expected behaviour

The MediaDetailPagerFragment has  a public no-arg constructor for Android to use.

### Actual behaviour

Instantiating the MediaDetailPagerFragment fails when Android is trying to restore it. We need to introduce a public no-arg constructor and possibly avoid the parameterized constructors for the fragment by receive the corresponding parameters via Bundle arguments as suggested in [this Q&A](https://stackoverflow.com/a/16977633/5614968)

### Android version

13

### Commons app version

4.1.0

**Note**

This does not seem specific to 4.1.0 or Android 13. There are crash reports from other versions like 4.0.3 and Android versions like 10.

### Device logs

 The trace of one such crash looks as follows:

<details><summary>Stack trace of MediaDetailPagerFragment crash</summary>
<p>

```stacktrace
java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.free.nrw.commons.media.MediaDetailPagerFragment: could not find Fragment constructor
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5782)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5673)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5741)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2316)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7918)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment fr.free.nrw.commons.media.MediaDetailPagerFragment: could not find Fragment constructor
at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1890)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:479)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
at fr.free.nrw.commons.di.CommonsDaggerAppCompatActivity.onCreate(CommonsDaggerAppCompatActivity.java:24)
at fr.free.nrw.commons.theme.BaseActivity.onCreate(BaseActivity.java:28)
at fr.free.nrw.commons.contributions.MainActivity.onCreate(MainActivity.java:119)
at android.app.Activity.performCreate(Activity.java:8342)
at android.app.Activity.performCreate(Activity.java:8321)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
... 17 more
Caused by: java.lang.NoSuchMethodException: fr.free.nrw.commons.media.MediaDetailPagerFragment.<init> []
at java.lang.Class.getConstructor0(Class.java:2363)
at java.lang.Class.getConstructor(Class.java:1759)
at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
... 38 more
```

</p>
</details> 

### Would you like to work on the issue?

None

**Comment by sivaraam** [comment]
Tagging this as high-priority since this seems to be the cause for a major chunk of our crash reports as of now.

**Comment by shakivhussain** [comment]
@sivaraam I want to work on this issue 
Can you please assign it to me?



I'm unable to build this project, I have attached the error screenshot please check.

![Screenshot 2023-06-20 at 12 35 50 PM](https://github.com/commons-app/apps-android-commons/assets/51313301/bca5ccbe-669f-4382-9d40-5c298ff59fa6)

**Comment by sivaraam** [comment]
@shakivhussain Some errors don't seem specific to the app. Could you kindly search for checkout the solution to this? For instance you could checkout the answer in [this Q&A](https://stackoverflow.com/a/60413117/5614968).

**Comment by sivaraam** [comment]
@shakivhussain Were you able to make any progress on this? This issue seems to constitute a significant proportion of the crash logs for the app. So, it would be ideal to fix this soon 🙂 

Let us know if you're stuck somewhere with identifying a fix for this.

**Comment by nicolas-raoul** [comment]
@alamzeeshan It is yours, thanks! 🙂

**Comment by alamzeeshan** [comment]
> @alamzeeshan It is yours, thanks! 🙂

Thanks. I will start working on it.

**Comment by sivaraam** [comment]
@alamzeeshan Just wanted to check in to know if you were able to make progress on this issue ? 🙂

**Comment by alamzeeshan** [comment]
> @alamzeeshan Just wanted to check in to know if you were able to make progress on this issue 🙂

I have made the code changes and everything looks good. I am traveling right now so I will open a PR on Thursday

**Comment by nicolas-raoul** [comment]
@alamzeeshan Any progress on this? We are aiming for a release soon. :-) Thanks!

**Comment by alamzeeshan** [comment]
> @alamzeeshan Any progress on this? We are aiming for a release soon. :-) Thanks!

Sorry for the delay. I will open a PR tomorrow.

**Comment by alamzeeshan** [comment]
@nicolas-raoul @sivaraam Opened a PR
