### ISSUE TITLE
Achievements: level not loading

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5287]
![Screenshot_20230908-182245.png](https://github.com/commons-app/apps-android-commons/assets/99590/f6176829-4dcc-420f-bec4-fe98e2757c01)

**Comment by whym** [comment]
Just to eliminate the possibility of it being caused by some bad cache, does it still happen today?

Also, it might depend on user accounts. Do you have another user account you can test with?

**Comment by nicolas-raoul** [comment]
Yes it depends on the account:
- It still happens now for user `Syced` (13k uploads).
- It does NOT happen for another account with 130 uploads.

**Comment by RitikaPahwa4444** [comment]
This used to work back then, but now it's not working for me as well. 

Account: RitikaPahwa4444
Upload count: 1803

**Comment by whym** [comment]
The newer issue seems to be a separate one, affecting everyone. My current guess is that there is a syntax error in /data/project/urbanecmbot/.lighttpd.conf in Toolforge. (I emailed urbanecm about it.)

**Comment by ShashwatKedia** [comment]
Yaa, it's not working for me as well, though it used to a couple of days back. Also, the HTTP request is returning 503 (Service unavailable error), with this error in logcat: 

Fetching achievements statistics failed
                                                                                                    java.lang.NullPointerException: The callable returned a null value
                                                                                                    	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                                                                    	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
                                                                                                    	at io.reactivex.Single.subscribe(Single.java:3603)
                                                                                                    	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                                    	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                                                    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by neeldoshii** [comment]
I'll try to take a deep look on this. For me with 3 uploads also its taking more than a minute. My guess is from logs it's fetching leaderboard too despite being at the achievement screen.

**Comment by neeldoshii** [comment]
Seems like I found the root cause.

**Before:**

```
curl --location 'https://tools.wmflabs.org/commons-android-app/tool-commons-android-app/leaderboard.py?user=Syced&duration=weekly&category=upload&limit=100&offset=100'
```
**Response:**
<details>
 <summary>Response</summary>
<pre>
<codeclass="language-json">

```json
{
    "status": 200,
    "username": "Syced",
    "avatar": "https://upload.wikimedia.org/wikipedia/commons/7/77/Rainbow_Bridge_by_night_seen_from_Odaiba_side.jpg",
    "rank": 68,
    "category_count": 91,
    "category": "upload",
    "duration": "weekly",
    "limit": 100,
    "offset": 100,
    "leaderboard_list": [
        {
            "username": "Ridamtosh",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 101,
            "category_count": 54
        },
        {
            "username": "Francoerbi",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 102,
            "category_count": 50
        },
        {
            "username": "RaffiKojian",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 103,
            "category_count": 50
        },
        {
            "username": "Rigorius",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 104,
            "category_count": 50
        },
        {
            "username": "Awinkler3",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 105,
            "category_count": 50
        },
        {
            "username": "Sneeuwvlakte",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 106,
            "category_count": 50
        },
        {
            "username": "ThePhilosopherAccount",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 107,
            "category_count": 50
        },
        {
            "username": "Tad001",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 108,
            "category_count": 50
        },
        {
            "username": "Noël Danjou",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 109,
            "category_count": 49
        },
        {
            "username": "Tagooty",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 110,
            "category_count": 47
        },
        {
            "username": "MPF",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 111,
            "category_count": 47
        },
        {
            "username": "Kurmanbek",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 112,
            "category_count": 44
        },
        {
            "username": "Charlesjsharp",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 113,
            "category_count": 43
        },
        {
            "username": "Granpar",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 114,
            "category_count": 43
        },
        {
            "username": "Drkirstyross",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 115,
            "category_count": 43
        },
        {
            "username": "Mentxuwiki",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 116,
            "category_count": 42
        },
        {
            "username": "Elgaard",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 117,
            "category_count": 42
        },
        {
            "username": "Jörg Blobelt",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 118,
            "category_count": 41
        },
        {
            "username": "Christojobyantony",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 119,
            "category_count": 41
        },
        {
            "username": "Habst",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 120,
            "category_count": 40
        },
        {
            "username": "Rohit14400",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 121,
            "category_count": 40
        },
        {
            "username": "Oxyman",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 122,
            "category_count": 39
        },
        {
            "username": "Strakhov",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 123,
            "category_count": 39
        },
        {
            "username": "Meqqal",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 124,
            "category_count": 39
        },
        {
            "username": "Iwaqarhashmi",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 125,
            "category_count": 39
        },
        {
            "username": "Nakonana",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 126,
            "category_count": 38
        },
        {
            "username": "Kognos",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 127,
            "category_count": 37
        },
        {
            "username": "БРИАН.Ю.М",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 128,
            "category_count": 37
        },
        {
            "username": "ReneeWrites",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 129,
            "category_count": 37
        },
        {
            "username": "Johann Jaritz",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 130,
            "category_count": 36
        },
        {
            "username": "Dalbergiaada",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 131,
            "category_count": 36
        },
        {
            "username": "Mkkagain",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 132,
            "category_count": 36
        },
        {
            "username": "Exec8",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 133,
            "category_count": 36
        },
        {
            "username": "Adam Cuerden",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 134,
            "category_count": 35
        },
        {
            "username": "Vyacheslav Bukharov",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 135,
            "category_count": 35
        },
        {
            "username": "A.-K. D.",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 136,
            "category_count": 34
        },
        {
            "username": "Gerd Fahrenhorst",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 137,
            "category_count": 34
        },
        {
            "username": "Harald Hetzner",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 138,
            "category_count": 34
        },
        {
            "username": "Renardo la vulpo",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 139,
            "category_count": 33
        },
        {
            "username": "A.Savin",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 140,
            "category_count": 32
        },
        {
            "username": "Teseo",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 141,
            "category_count": 32
        },
        {
            "username": "ExpressaoSAMPA",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 142,
            "category_count": 32
        },
        {
            "username": "Yu tptw",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 143,
            "category_count": 30
        },
        {
            "username": "Packa",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 144,
            "category_count": 30
        },
        {
            "username": "Richardnsfg",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 145,
            "category_count": 30
        },
        {
            "username": "Collectie Scherft",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 146,
            "category_count": 30
        },
        {
            "username": "Avelludo",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 147,
            "category_count": 30
        },
        {
            "username": "Ganesh Mohan T",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 148,
            "category_count": 29
        },
        {
            "username": "RevengerTime",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 149,
            "category_count": 29
        },
        {
            "username": "Suyash.dwivedi",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 150,
            "category_count": 29
        },
        {
            "username": "Nandhinirajappa",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 151,
            "category_count": 29
        },
        {
            "username": "Wadaihangit",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 152,
            "category_count": 28
        },
        {
            "username": "Atanu Bose Photography",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 153,
            "category_count": 28
        },
        {
            "username": "Vijayanrajapuram",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 154,
            "category_count": 27
        },
        {
            "username": "N9713",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 155,
            "category_count": 27
        },
        {
            "username": "Medusalabar",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 156,
            "category_count": 27
        },
        {
            "username": "Tokumeigakarinoaoshima",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 157,
            "category_count": 27
        },
        {
            "username": "Екатерина Борисова",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 158,
            "category_count": 26
        },
        {
            "username": "円周率３パーセント",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 159,
            "category_count": 25
        },
        {
            "username": "Bernd Schwabe in Hannover",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 160,
            "category_count": 25
        },
        {
            "username": "MaedaAkihiko",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 161,
            "category_count": 25
        },
        {
            "username": "Kawaart",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 162,
            "category_count": 25
        },
        {
            "username": "Bekbal",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 163,
            "category_count": 25
        },
        {
            "username": "SMA",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 164,
            "category_count": 25
        },
        {
            "username": "Duschgeldrache2",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 165,
            "category_count": 24
        },
        {
            "username": "Clic",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 166,
            "category_count": 24
        },
        {
            "username": "Ermell",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 167,
            "category_count": 24
        },
        {
            "username": "Patafisik",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 168,
            "category_count": 24
        },
        {
            "username": "Al*from*Lig",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 169,
            "category_count": 24
        },
        {
            "username": "Karthoo",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 170,
            "category_count": 24
        },
        {
            "username": "Frank Schulenburg",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 171,
            "category_count": 24
        },
        {
            "username": "Enperfectify World",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 172,
            "category_count": 24
        },
        {
            "username": "Fernando Archuby",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 173,
            "category_count": 24
        },
        {
            "username": "Bemule",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 174,
            "category_count": 24
        },
        {
            "username": "999real",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 175,
            "category_count": 24
        },
        {
            "username": "Strubbl",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 176,
            "category_count": 23
        },
        {
            "username": "Meow",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 177,
            "category_count": 23
        },
        {
            "username": "TanvirSdq",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Chandra_Mahal.jpg",
            "rank": 178,
            "category_count": 23
        },
        {
            "username": "Tsopbeng djinon",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 179,
            "category_count": 23
        },
        {
            "username": "Victor Fortunato",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 180,
            "category_count": 23
        },
        {
            "username": "Coen",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 181,
            "category_count": 22
        },
        {
            "username": "Llann Wé²",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 182,
            "category_count": 22
        },
        {
            "username": "Shonagon",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 183,
            "category_count": 22
        },
        {
            "username": "Francisco Peralta Torrejón",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 184,
            "category_count": 22
        },
        {
            "username": "Handelsgeselschaft",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 185,
            "category_count": 22
        },
        {
            "username": "Nennokkk",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 186,
            "category_count": 22
        },
        {
            "username": "David Osipov",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 187,
            "category_count": 22
        },
        {
            "username": "Saosukgam",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 188,
            "category_count": 22
        },
        {
            "username": "Tournasol7",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 189,
            "category_count": 21
        },
        {
            "username": "JustAnotherCarDesigner",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 190,
            "category_count": 21
        },
        {
            "username": "Ludvig14",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 191,
            "category_count": 21
        },
        {
            "username": "Sm faysal",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 192,
            "category_count": 21
        },
        {
            "username": "Zolfeqar Fatihzadeh",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 193,
            "category_count": 21
        },
        {
            "username": "Jeromi Mikhael",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 194,
            "category_count": 21
        },
        {
            "username": "Rodelar",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 195,
            "category_count": 20
        },
        {
            "username": "Komoro no kaze",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 196,
            "category_count": 20
        },
        {
            "username": "Athulvis",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 197,
            "category_count": 20
        },
        {
            "username": "1970gemini",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 198,
            "category_count": 20
        },
        {
            "username": "OttavianoUrsu",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 199,
            "category_count": 20
        },
        {
            "username": "Harriet Rodriguez Rivera",
            "avatar": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gnome-stock_person.svg/200px-Gnome-stock_person.svg.png",
            "rank": 200,
            "category_count": 20
        }
    ]
}
```
</code>
</pre>
</details>

From log it seems, we are calling this in Achievement screen. As you can see the above response is providing us the leaderboard array which is redundant as someone who has 13k uploads this will consume so much memory which we don't even need. The question here really arises is why are we having limit 100, offset 100. 

**After**
```
curl --location 'https://commons-android-app.toolforge.org/tool-commons-android-app/leaderboard.py?user=Syced&duration=weekly&category=upload&limit=0&offset=0'
```
**Response**
<details>
 <summary>Response</summary>
<pre>
<codeclass="language-json">

```json
{
    "status": 200,
    "username": "Syced",
    "avatar": "https://upload.wikimedia.org/wikipedia/commons/7/77/Rainbow_Bridge_by_night_seen_from_Odaiba_side.jpg",
    "rank": 68,
    "category_count": 91,
    "category": "upload",
    "duration": "weekly",
    "l>mit": 0,
    "offset": 0,
    "leaderboard_list": []
}
```
</code>
</pre>
</details>

**Comment by nicolas-raoul** [comment]
@neeldoshii I believe the relevant script for achievements is `feedback.py`: https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/java/fr/free/nrw/commons/mwapi/OkHttpJsonApiClient.kt#L257

The leaderboard works fine. :-)

**Comment by neeldoshii** [comment]
> @neeldoshii I believe the relevant script for achievements is `feedback.py`: https://github.com/commons-app/apps-android-commons/blob/main/app/src/main/java/fr/free/nrw/commons/mwapi/OkHttpJsonApiClient.kt#L257
> 
> The leaderboard works fine. :-)

Makes sense! I guess I overlooked.

**Comment by ChinchuC** [comment]
<img width="812" height="1478" alt="Image" src="https://github.com/user-attachments/assets/4394ffda-e8cd-47d9-bd0b-aae320656131" />

Similar issue. Achievements tab loads as empty and Level is shown as "%1$D"

Tried uninstalling and then downloading the app again. Same result.

**Comment by gangaasoonu** [comment]
<img width="720" height="1092" alt="Image" src="https://github.com/user-attachments/assets/6b66963b-4b08-4ec9-ae9c-0dd794d61ea0" />

Never shows data
