### ISSUE TITLE
Crash when tapping in custom picker while processing

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5289]
Steps to reproduce the crash:

1. In the app's main activity, tap the + then the bottom button ("custom picker")
2. Choose your camera folder.
3. Select about 20 pictures.
4. Tap "Mark as not for upload", then immediately tap another picture.
5. Crash: 

APP_VERSION_CODE=1034
APP_VERSION_NAME=4.1.0-debug-master
ANDROID_VERSION=14
PHONE_MODEL=Pixel 7 Pro
STACK_TRACE=java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
at java.util.ArrayList$Itr.next(ArrayList.java:982)
at fr.free.nrw.commons.customselector.ui.selector.CustomSelectorActivity$insertIntoNotForUpload$1.invokeSuspend(CustomSelectorActivity.kt:432)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a4967a, Dispatchers.Main]

IS_SILENT=false
REPORT_ID=8d9e911e-6935-46fb-b084-9cf292fde687
USER_CRASH_DATE=2023-09-11T21:56:40.639+09:00

Maybe show a wait dialog and stop listening to taps while processing?

**Comment by Abdullahkhanspn** [comment]
I am a beginner so can you please tell me hoe to reproduce this crash in the app the upper steps i see but not understand please tell me and i recently setup the app .
@nicolas-raoul

**Comment by nicolas-raoul** [comment]
@Abdullahkhanspn Could you first try to upload a set of pictures using the custom selector? It will help you understand the steps above.

**Comment by Abdullahkhanspn** [comment]
ok I will do that, thanks.

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by nicolas-raoul** [comment]
@vimalJD Yes this project is alive and ongoing. :-) Please first read the documentation: https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md It includes how to find a good first issue.

**Comment by aryanA101a** [comment]
@nicolas-raoul This seems interesting, can you assign this issue to me?

**Comment by nicolas-raoul** [comment]
@aryanA101a Did you manage to reproduce the issue? :-)

**Comment by aryanA101a** [comment]
@nicolas-raoul Yes it is even happening on selecting 5 photos.

**Comment by nicolas-raoul** [comment]
Thanks, it is yours! Please let us know about your progress at least every week or so. :-)
