### ISSUE TITLE
Suggest depicted country based on EXIF latitude/longitude

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#53]
Would need to embed a rough database of countries/areas borders, or [a specialized library if that exists](http://softwarerecs.stackexchange.com/questions/28378/tiny-java-library-to-guess-country-from-latitude-longitude).

**Comment by Pratham2305** [comment]
Hey, @nicolas-raoul I would like to work on this.

**Comment by nicolas-raoul** [comment]
@Pratham2305 Thanks! If you have any question or suggestion about the library and its integration please let me know :-)

**Comment by nicolas-raoul** [comment]
To import the library you will have to use method 2 described here: https://stackoverflow.com/a/34329145/226958

**Comment by nicolas-raoul** [comment]
Example usage:

`Coordinates2Country.countryQID(-23.7, 39.8)` returns 142, the [Wikidata QID number of France](https://www.wikidata.org/wiki/Q142).

**Comment by nicolas-raoul** [comment]
Update: Importing the library just become much easier!  
Just add `implementation("io.github.coordinates2country:coordinates2country:1.2")` to the app's `build.gradle`.

Details at https://github.com/coordinates2country/coordinates2country/blob/main/README.md#use

**Comment by Pratham2305** [comment]
On using it, I am getting this error

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.free.nrw.commons, PID: 29045
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
        at io.github.coordinates2country.Coordinates2Country.country(Coordinates2Country.java:62)
        at io.github.coordinates2country.Coordinates2Country.countryQID(Coordinates2Country.java:31)
        at fr.free.nrw.commons.repository.UploadRepository.getCountryDepictions(UploadRepository.java:283)
        at fr.free.nrw.commons.upload.depicts.DepictsPresenter.selectPlaceDepictions(DepictsPresenter.kt:97)
        at fr.free.nrw.commons.upload.depicts.DepictsFragment.onBecameVisible(DepictsFragment.java:121)
        at fr.free.nrw.commons.upload.UploadActivity.onPreviousButtonClicked(UploadActivity.java:492)
        at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment.onPreviousButtonClicked(UploadCategoriesFragment.java:180)
        at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment_ViewBinding$2.doClick(UploadCategoriesFragment_ViewBinding.java:52)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:7161)
        at android.view.View.performClickInternal(View.java:7133)
        at android.view.View.access$3500(View.java:804)
        at android.view.View$PerformClick.run(View.java:27416)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.imageio.ImageIO" on path: DexPathList[[zip file "/data/app/fr.free.nrw.commons-9JSpJEveQGUVDzRbot0I-Q==/base.apk"],nativeLibraryDirectories=[/data/app/fr.free.nrw.commons-9JSpJEveQGUVDzRbot0I-Q==/lib/arm64, /data/app/fr.free.nrw.commons-9JSpJEveQGUVDzRbot0I-Q==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.github.coordinates2country.Coordinates2Country.country(Coordinates2Country.java:62) 
        at io.github.coordinates2country.Coordinates2Country.countryQID(Coordinates2Country.java:31) 
        at fr.free.nrw.commons.repository.UploadRepository.getCountryDepictions(UploadRepository.java:283) 
        at fr.free.nrw.commons.upload.depicts.DepictsPresenter.selectPlaceDepictions(DepictsPresenter.kt:97) 
        at fr.free.nrw.commons.upload.depicts.DepictsFragment.onBecameVisible(DepictsFragment.java:121) 
        at fr.free.nrw.commons.upload.UploadActivity.onPreviousButtonClicked(UploadActivity.java:492) 
        at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment.onPreviousButtonClicked(UploadCategoriesFragment.java:180) 
        at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment_ViewBinding$2.doClick(UploadCategoriesFragment_ViewBinding.java:52) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18) 
        at android.view.View.performClick(View.java:7161) 
        at android.view.View.performClickInternal(View.java:7133) 
        at android.view.View.access$3500(View.java:804) 
        at android.view.View$PerformClick.run(View.java:27416) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:241) 
        at android.app.ActivityThread.main(ActivityThread.java:7582) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941) 

```
Maybe the `java.awt` and `javax.imageio` isn't supported on Android

**Comment by nicolas-raoul** [comment]
Thank you for noticing this! I will try to fix it, feel free to do other things meanwhile.

**Comment by nicolas-raoul** [comment]
Could you please try again with `implementation("io.github.coordinates2country:coordinates2country-android:1.2")`?
Thanks!

**Comment by Pratham2305** [comment]
After adding it, the Gradle build is failing. I have not made any changes in the gradle related files just added the dependency. 

![Screenshot (273)](https://user-images.githubusercontent.com/54663429/148391269-8fee41f8-281e-4dfc-b0a4-4b7d75d60f29.png)

I have tried a few things but none of them helped.
Simply fixing each error could be a solution but I am not sure what is causing it, as after removing the dependency Gradle build is working fine as usual.

**Comment by Pratham2305** [comment]
@nicolas-raoul Sorry for the Delay, I have resolved the issue and created the PR now. Please Review!
