### ISSUE TITLE
[Bug]: crash after writing description

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5314]
### Summary

App crashes occasionally.

### Steps to reproduce

not sure. Happens relatively rarely, and I didn't manage to catch exact sequence for reproducing it. Last time it happened when I finished writing description of a picture, after I was viewing picture several times, and switched in/out other apps like gallery etc.

### Expected behaviour

picture submission continues normally

### Actual behaviour

app crashes

### Device name

Huawei P30Pro

### Android version

Android 10 (EMUI 12)

### Commons app version

4.1.0~1649d1e2c (latest f-droid)

### Device logs

```
APP_VERSION_CODE=1034
APP_VERSION_NAME=4.1.0
ANDROID_VERSION=10
PHONE_MODEL=VOG-L29
STACK_TRACE=java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at fr.free.nrw.commons.upload.mediaDetails.UploadMediaPresenter.verifyImageQuality(UploadMediaPresenter.java:181)
        at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment.onNextButtonClicked(UploadMediaDetailFragment.java:225)
        at fr.free.nrw.commons.upload.mediaDetails.UploadMediaDetailFragment_ViewBinding$2.doClick(UploadMediaDetailFragment_ViewBinding.java:62)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:7317)
        at android.view.View.performClickInternal(View.java:7291)
        at android.view.View.access$3600(View.java:838)
        at android.view.View$PerformClick.run(View.java:28247)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

IS_SILENT=false
REPORT_ID=b545072d-8746-4ef4-ae16-ba43c8c1d453
USER_CRASH_DATE=2023-08-14T19:06:40.450+02:00
USER_EMAIL=
```

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
Does it happen only after starting a multi-files upload? Or on single picture uploads only? Or both?
Perhaps after cancelling one picture among a multi-pictures upload, maybe?

**Comment by Shin0017** [comment]
Hi @nicolas-raoul, may I take this issue?

**Comment by Shin0017** [comment]
if (items.contains(uploadItem)) {
            return items.get(items.indexOf(uploadItem));
        }

        if (place != null) {
            uploadItem.getUploadMediaDetails().set(0, new UploadMediaDetail(place));
        }
        if (!items.contains(uploadItem)) {
            items.add(uploadItem);
        }
I am not been able to reproduce this bug until now. In my opinion, this bug may caused by abnormally calling the onError(), onComplete() or onDetachView(). And then calling cleanup(). Otherwise, the length of the items can not be 0.

**Comment by Shin0017** [comment]
This may caused by the OS releasing some resources when you switch in/out of other apps. How about we check the length of the items before executing the verifyImageQuality() method? And if the items is empty, this app goes to the main activity.

**Comment by nicolas-raoul** [comment]
Thanks for testing @Shin0017 ! It is possible that the issue does not exist anymore, as the code has changed a lot since 4.1.0

@mnalis If you can reproduce with 4.2.x+ please be sure to let us know, thanks! :-)
