### ISSUE TITLE
Fix prodRelease flavor build, probably by updating Proguard

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5323]
When building the `prodRelease` flavor, I get this error:

```
Execution failed for task ':app:minifyProdReleaseWithProguard'.
> java.io.IOException: Can't read [/Users/nicolasraoul/Library/Android/sdk/platforms/android-33/optional/android.car.jar] (Can't process class [android/car/Car$CarServiceLifecycleListener.class] (Unsupported version number [55.0] (maximum 54.0, Java 10)))
```

That's probably because we use an old version of Proguard. Latest version is 7.3.2.

**Comment by sivaraam** [comment]
Yeah. For this I was looking into integrating the changes in #5220 since it bumps the gradle plugin to 8.0. I was indeed able to generate the release variant of the JAR. Unfortunately, the app fails to even start on my devices. I observed two issues:

```stacktrace
java.lang.RuntimeException: Unable to resume activity {fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.IllegalArgumentException: Unable to create call adapter for class io.reactivex.Observable for method Service.getAllNotifications
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4035) 
```
I'm looking into fixing the above. So far I found that [this QA](https://stackoverflow.com/q/43434073/5614968) is relevant. Yet to understand it fully.

The other one issue is:

```stacktrace
java.lang.RuntimeException: Missing type parameter.
  at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(SourceFile:84)
  at com.google.gson.reflect.TypeToken.(SourceFile:62)
```

For the above, I think the solution mentioned [here works](https://stackoverflow.com/a/72520577/5614968). I'm yet to fully confirm this.

**Comment by nicolas-raoul** [comment]
I just built and tried `prodRelease` flavor for pull request #5220:
- The first activity (log in screen) appears and looks fine.
- If I tap `Skip`, I get the app's normal UI, it works normally but all network calls fail (except the maps which are showing fine including for remote places I am sure I don't have in any cache).
- When I try to log in, after tapping `log in` the app immediately crashes, with this stacktrace:
```
java.lang.IllegalArgumentException: Unable to create call adapter for interface retrofit2.Call
    for method Service.getLoginToken
at retrofit2.Utils.methodError(SourceFile:53)
at retrofit2.HttpServiceMethod.createCallAdapter(SourceFile:105)
at retrofit2.HttpServiceMethod.parseAnnotations(SourceFile:66)
at retrofit2.ServiceMethod.parseAnnotations(SourceFile:37)
at retrofit2.Retrofit.loadServiceMethod(SourceFile:192)
at retrofit2.Retrofit$1.invoke(SourceFile:149)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy6.getLoginToken(Unknown Source)
at fr.free.nrw.commons.auth.LoginActivity.doLogin(SourceFile:263)
at fr.free.nrw.commons.auth.LoginActivity.performLogin(SourceFile:258)
at fr.free.nrw.commons.auth.LoginActivity_ViewBinding$1.doClick(SourceFile:51)
at butterknife.internal.DebouncingOnClickListener.onClick(SourceFile:18)
at android.view.View.performClick(View.java:7659)
at android.view.View.performClickInternal(View.java:7636)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30156)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>
at retrofit2.DefaultCallAdapterFactory.get(SourceFile:41)
at retrofit2.Retrofit.nextCallAdapter(SourceFile:243)
at retrofit2.Retrofit.callAdapter(SourceFile:227)
at retrofit2.HttpServiceMethod.createCallAdapter(SourceFile:103)
```

**Comment by sivaraam** [comment]
Ok. So, you're facing the same issue as I do. I did some digging and came as far as to realize that the problem is with R8 full mode being enabled via that MR [[ref](https://github.com/commons-app/apps-android-commons/pull/5220/files#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19L36)]

I got around that retrofit2 issue with the following proguard rules:

```
# START of R8 full mode retrofit2
-keep class retrofit2.*
```

I'm still facing issues with other classes going missing. I believe at this point we should either find the complete proguard conf that works for us (or) find a way to reduce the proguard optimization being done.

**Comment by sivaraam** [comment]
> ... to reduce the ~~proguard~~~ R8 optimization being done.

Adding the following to `gradle.properties` seems like a good place to start [[ref](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes)] :

```properties
android.enableR8.fullMode=false
```

I now get the following exception when trying to login. This happens for the release flavour but not for the debug flavour. I'm yet to figure out the cause.

```stacktrace
java.io.IOException: {"errors":[{"code":"missingparam","text":"The \"logintoken\" parameter must be set.","module":"clientlogin"}],"docref":"See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes.","servedby":"mw2356"}
                                                                                                    	at fr.free.nrw.commons.OkHttpConnectionFactory$UnsuccessfulResponseInterceptor.intercept(OkHttpConnectionFactory.java:90)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-10-09 11:17:55.317  7782-8208  okhttp.OkHttpClient     fr.free.nrw.commons                  I  <-- 200 https://commons.wikimedia.org/w/api.php?format=json&formatversion=2&errorformat=plaintext&action=clientlogin&rememberMe= (461ms, 405-byte body)
2023-10-09 11:17:55.320  7782-7782  LoginActivity           fr.free.nrw.commons                  E  java.lang.IllegalStateException: closed
                                                                                                    	at okio.RealBufferedSource.read(RealBufferedSource.kt:36)
```

**Comment by sivaraam** [comment]
> I now get the following exception when trying to login. This happens for the release flavour but not for the debug flavour. I'm yet to figure out the cause.

I digged into this and identified the root cause of the issue as Proguard's obfuscation of the Model classes [ [ref](https://stackoverflow.com/a/46862419/5614968) ]. Using the [@Keep annotation](https://developer.android.com/reference/kotlin/androidx/annotation/Keep) on specific classes seems to work but that would be too much manual works since there are so many model classes. The simpler way would be to use a proguard rule to disable the obfuscation.

I'm facing some challenges with disabling it via a Proguard rule since the classes are in the data-client library. There's some progress but I haven't got a complete solution yet. Just wanted to keep this issue updated about the progress.

**Comment by sivaraam** [comment]
Ok. So, I managed to figure out that the adding the following to our app's proguard-rules.txt (apart from disabling R8 full mode as mentioned above) does the trick: 

```
-keepclasseswithmembers class org.wikipedia.** { *; }
```

I've pushed the change to the MR #5220. I'm now able to successfully get the release APK for v4.2.0 and ensure the app works basically ☺️ 

@nicolas-raoul Would you be able to cross-check that the fix works for you too ?

**Comment by nicolas-raoul** [comment]
Wonderful! We indeed do not need any obfuscation. I am walking now but will try in a few hours.

**Comment by nicolas-raoul** [comment]
Thanks @sivaraam for fixing the prod build!
I created #5339 about the unit tests.
