### ISSUE TITLE
IndexOutOfBoundsException when using both custom picker and gallery

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5336]
1. Using custom picker, open an album, disable `Show already actioned pictures`.
2. With gallery, open the same album, select a few pictures, then upload them, taking a few minutes.
3. Go back to the app from launcher icon, for me it opened the screen from step 1.
4. Scroll a bit up and down.
5. A few pictures disappear as they got uploaded.
6. Crash:

APP_VERSION_CODE=1035
APP_VERSION_NAME=4.2.0-debug-shankarpriyank-rotate_feature
ANDROID_VERSION=14
PHONE_MODEL=Pixel 7 Pro
STACK_TRACE=java.lang.IndexOutOfBoundsException: Index 18 out of bounds for length 18
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.util.Objects.checkIndex(Objects.java:359)
at java.util.ArrayList.get(ArrayList.java:434)
at fr.free.nrw.commons.customselector.ui.adapter.ImageAdapter.onBindViewHolder(ImageAdapter.kt:122)
at fr.free.nrw.commons.customselector.ui.adapter.ImageAdapter.onBindViewHolder(ImageAdapter.kt:29)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7093)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7172)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6037)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6304)
at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by u7452206** [comment]
hi, does anyone work on this task? if not, can I take it ?

**Comment by nicolas-raoul** [comment]
@u7452206 It is yours, thanks! :-)

**Comment by 1162706031** [comment]
I also found this problem, not only when using both custom picker and gallery, but also when using camera to take pictures and upload them

**Comment by nicolas-raoul** [comment]
@1162706031 Very interesting! Would you mind posting a video screencast if you can? Thanks  a lot! :-)

**Comment by 1162706031** [comment]
This is the video

**Comment by 1162706031** [comment]
I think I found the problem
![image](https://github.com/commons-app/apps-android-commons/assets/59361311/df37f8a4-914d-472b-922c-5d9e291dda44)
It will return -1 as an index when the user language is Chinese

**Comment by nicolas-raoul** [comment]
@1162706031 
Cool! Would you mind creating the issue? Then you can start working on it immediately if you want. Thanks! :-)
I unfortunately get `there was a problem loading the video`, would you mind uploading each screencast to GitHub itself by using the `Attach files` grey area at the bottom of the text area when creating the new issue? You may need to recompress the video if GitHub says it is too big.

**Comment by 1162706031** [comment]
> @1162706031 Cool! Would you mind creating the issue? Then you can start working on it immediately if you want. Thanks! :-) I unfortunately get `there was a problem loading the video`, would you mind uploading each screencast to GitHub itself by using the `Attach files` grey area at the bottom of the text area when creating the new issue? You may need to recompress the video if GitHub says it is too big.

You can try download that, because webm file is not supported for onedrive watching online Thank you!

**Comment by 1162706031** [comment]
I am not so sure that the bug appears in another Android device because I don't have an Android phone, I ran it using the emulator in Android Studio.

**Comment by u7452206** [comment]
Hi @nicolas-raoul,  I currently work on the issue. I try to upload photos from album and custom picker. But  either gallery saying failed to upload photos. Does this situation happen before? Or how do I able to solve this problem?

**Comment by 1162706031** [comment]
> Hi @nicolas-raoul, I currently work on the issue. I try to upload photos from album and custom picker. But either gallery saying failed to upload photos. Does this situation happen before? Or how do I able to solve this problem?

I also encountered this problem.
![image](https://github.com/commons-app/apps-android-commons/assets/59361311/fa933ff1-e00a-4476-868a-0e58dea6b14d)

**Comment by nicolas-raoul** [comment]
Could you please build the `prodDebug` flavor and try again?

**Comment by 1162706031** [comment]
This is very strange. When running in the prodDebug flavour, there is no problem uploading images.

**Comment by nicolas-raoul** [comment]
The test server is unfortunately quite different from the production server.

> However, IndexOutOfBoundsException when using both custom picker and gallery still appear in both the prodDebug flavor and betaDebug flavor.

Interesting! If you find a way to fix that, it would be very welcome. :-)

**Comment by srishti-R** [comment]
is this issue in some other branch "shankarpriyank-rotate_feature"? I couldn't replicate on main, it wrongly showed me uploaded pictures as well when I came back to custom picker after uploading but no crashes.

**Comment by nicolas-raoul** [comment]
@srishti-R I added a precision to step 1, that might be the reason.

I believe it happens on main too, I will try.

**Comment by nicolas-raoul** [comment]
I was not able to reproduce the issue, let's close it for now.
