### ISSUE TITLE
[Bug]: Crash when opening Nearby when location permission hasn't been granted yet

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5413]
### Summary

The app crashes when trying to open the Nearby screen. I observe this on a fresh installation when the app doesn't have the location permission.

### Steps to reproduce

1. Install the app afresh
2. Login to the app
3. Click on Nearby
4. Observe the app crashing (likely due to lack of location permission)

### Expected behaviour

The app should open the Nearby screen properly requesting for the location permission.

### Actual behaviour

The app crashes with the exception trace found below. The location permission request is shown after the app screen goes away.

### Device name

OnePlus Nord

### Android version

12

### Commons app version

Should be reproducible on master

### Device logs

```stacktrace
java.lang.RuntimeException: Unable to resume activity {fr.free.nrw.commons/fr.free.nrw.commons.contributions.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'double org.osmdroid.util.GeoPoint.getLatitude()' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4935)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4974)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8212)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Would you like to work on the issue?

None

**Comment by ShashwatKedia** [comment]
@nicolas-raoul @sivaraam I would like to work on this issue, if no one else is on it.

**Comment by ShashwatKedia** [comment]
I tried to reproduce this issue on some physical devices (Android 13, 12 and 8), but the app behaved correctly, asking for permission first and thus did not crash. Interestingly, it did crash on both the emulators I tested upon, with the same device logs as given above.

**Comment by rohit9625** [comment]
I faced the same issue on my device that has android 14.

**Comment by ShashwatKedia** [comment]
@sivaraam @nicolas-raoul Kindly review the above PR :]

**Comment by abhineshchandra1234** [comment]
Hi @sivaraam @nicolas-raoul ,

- I am an Android developer with 4 yrs exp working for Infosys.
- I would like to contribute to this repository, If you have any task for me. Please let me know.

**Comment by nicolas-raoul** [comment]
@abhineshchandra1234 Please follow the instructions at https://github.com/commons-app/apps-android-commons/issues/5427 thanks! :-)

**Comment by bhoomigadhiya** [comment]
Does this issue still persist?

**Comment by nicolas-raoul** [comment]
@bhoomigadhiya Sorry we will test @ShashwatKedia 's pull request soon.
