### ISSUE TITLE
[Bug]: No response when search in area is used at some places

### ISSUE THREAD

**Issue by rohit9625** [commons-app/apps-android-commons#5487]
### Summary

When going to another location where no images may be available, then no response is shown when clicking `SEARCH THIS AREA`. 

### Steps to reproduce

1. Open Explore Fragment
2. Go to Map 
3. Explore any location like mountains, sea, etc., where no images are available
4. Click on `SEARCH THIS AREA`

### Expected behaviour

A response should be shown to the user just like before.

### Actual behaviour

No response is shown.

### Device name

SAMSUNG A14

### Android version

ANDROID 14

### Commons app version

Latest Updated

### Device logs

When sending a request to the Wikimedia server from the map fragment, this is the response that is received:-
`{
    "error": {
        "code": "invalid-coord",
        "info": "Invalid coordinate provided",
        "docref": "See https://commons.wikimedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."
    },
    "servedby": "mw2286"
}`

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/101377978/728c4bbf-13d4-4874-bc69-69a1fc63dbc7

### Would you like to work on the issue?

None

**Comment by rohit9625** [comment]
Feel free to work on this issue : )

**Comment by kanahia1** [comment]
@rohit9625 I am looking into it !

**Comment by sivaraam** [comment]
@kanahia1 I think this issue is actually a duplicate of #5461 on which @ShashwatKedia is already working. I suppose you both would need to cross-check that you're not working on the same issue.

**Comment by rohit9625** [comment]
That is a different issue. The issue I opened is happening after migration to `OsmDroid` in **Maps** of `Explore Fragment`.

**Comment by sivaraam** [comment]
Though that issue mentions an issue with the Nearby screen. It also mentions a problem with the "Search this area" button. So, they're certainly related 🙂

**Comment by rohit9625** [comment]
Yeah maybe related but I didn't face that issue before.

**Comment by sivaraam** [comment]
In retrospect, #5490 also seems closely related.

**Comment by ShashwatKedia** [comment]
@sivaraam I think that #5490 and #5461 are related, as both the Nearby and the Explore fragments don't work correctly when location access is not there. But this issue seems to be when we Search at a particular location where images are not there, so I think it's a bit different.

**Comment by sivaraam** [comment]
Ah ok. On reading [this comment](https://github.com/commons-app/apps-android-commons/issues/5461#issuecomment-1913054830), I was of the opinion that you were also handling the issue where the "Search this are" button doesn't work as intended.

**Comment by ShashwatKedia** [comment]
Oh, my apologies for that. @kanahia1 seems to be working on this.

**Comment by kanahia1** [comment]
Hello @rohit9625, I tried going to same place. Here are my logs in `prodDebug`


```
2024-01-29 13:27:20.456 18801-28388 okhttp.OkHttpClient     fr.free.nrw.commons                  I  <-- 200 https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=geosearch&ggsnamespace=6&prop=imageinfo|coordinates&iiprop=url|extmetadata|user&&iiurlwidth=640&iiextmetadatafilter=DateTime|Categories|GPSLatitude|GPSLongitude|ImageDescription|DateTimeOriginal|Artist|LicenseShortName|LicenseUrl&ggscoord=62.36604211252142%7C111.95062541627323&ggslimit=30&ggsradius=10000 (1491ms, 22-byte body)
2024-01-29 13:27:20.465 18801-28388 System.err              fr.free.nrw.commons                  W  java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
2024-01-29 13:27:20.465 18801-28388 System.err              fr.free.nrw.commons                  W      at kotlin.collections.EmptyList.get(Collections.kt:36)
2024-01-29 13:27:20.465 18801-28388 System.err              fr.free.nrw.commons                  W      at kotlin.collections.EmptyList.get(Collections.kt:24)
2024-01-29 13:27:20.465 18801-28388 System.err              fr.free.nrw.commons                  W      at fr.free.nrw.commons.explore.map.ExploreMapController.loadAttractionsFromLocation(ExploreMapController.java:74)
2024-01-29 13:27:20.465 18801-28388 System.err              fr.free.nrw.commons                  W      at fr.free.nrw.commons.explore.map.ExploreMapPresenter.lambda$loadAttractionsFromLocation$2$fr-free-nrw-commons-explore-map-ExploreMapPresenter(ExploreMapPresenter.java:156)
2024-01-29 13:27:20.465 18801-28388 System.err              fr.free.nrw.commons                  W      at fr.free.nrw.commons.explore.map.ExploreMapPresenter$$ExternalSyntheticLambda3.call(Unknown Source:8)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at io.reactivex.Observable.subscribe(Observable.java:12267)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024-01-29 13:27:20.466 18801-28388 System.err              fr.free.nrw.commons                  W      at java.lang.Thread.run(Thread.java:1012)
2024-01-29 13:27:20.467 18801-18801 AnimatorSet             fr.free.nrw.commons                  D  mReversing is false. Don't call initChildren.

```
Can you please check again :)

Error here is when there are no images at/near coordinate which is the point of https://github.com/commons-app/apps-android-commons/issues/5457

**Comment by rohit9625** [comment]
The exact logs appeared when I tried.
The issue #5457 was about about showing more descriptive response. But here no response seen at all even in the form a Toast.

**Comment by rohit9625** [comment]
However, both are related :)
Can you please guide me to the code where response is received?
@kanahia1

**Comment by rohit9625** [comment]
Let me check first.

**Comment by rohit9625** [comment]
You are right **Kanhia**, this is the duplicate of #5457.
