### ISSUE TITLE
Move the API call out of the LoginActivity

### ISSUE THREAD

**Issue by psh** [commons-app/apps-android-commons#5533]
### What is the user problem or growth opportunity you want to see solved?

Architecturally speaking, the `LoginActivity` is not the place to make API calls.  This is the job of our `LoginClient`.  The API calls of the `doLogin()` method in the Activity should therefore move to the login client so work is happening in the correct places.

The goal will be to get to where the `LoginClient` is doing the work and the `LoginActivity` has no more references to "import retrofit2" and handles just user interface related tasks.

### Why is this important?

This is code cleanup moving toward better code health.

### Who will benefit from it?

At the end of the day, if this is done correctly, it should be transparent to the end-users and only the developers will see the benefit of better code quality.

### Any other thoughts
 
* `LoginActivity` is written in Java, the `LoginClient` is kotlin so you'll be making a gentle language translation as you work this issue
* The `LoginActivity` was the only outside caller of `getLoginToken()` in the login client, so you'll be able to make that private by the time you're done

**Comment by shashankiitbhu** [comment]
I would like to work on this , can you assign this to me @psh

**Comment by rohit9625** [comment]
Let's leave this issue for newcomers at least for some days.

**Comment by geektan123** [comment]
YES PLEASE ASSIGN IT TO I WANT TO MARK MY FIRST CONTRIBUTION  @psh  assign #5533

**Comment by geektan123** [comment]
Hello, @nicolas-raoul,

I have made every effort to solve the task, and I have moved all the API calls to the LoginClient.kt file. However, since the doLogin() function has been relocated to LoginClient, the login process works smoothly. Nonetheless, upon successful login, the function fails to access the functions and variables within the LoginActivity, despite importing the LoginActivity in the LoginClient. Consequently, this leads to a crash. Could anyone kindly provide hints so that I may resolve this issue independently? Your assistance would be greatly appreciated.

**Comment by shashankiitbhu** [comment]
@geektan123 can you provide logs after the crash ?

**Comment by geektan123** [comment]
Sure,
2024-02-19 23:06:20.273 21617-21617 LoginActivity           fr.free.nrw.commons.beta             D  Login to start!
2024-02-19 23:06:20.377  4603-7496  WindowManager           system_server                        V  Changing focus from Window{2b82f4a u0 fr.free.nrw.commons.beta/fr.free.nrw.commons.auth.LoginActivity} to Window{865b316 u0 Logging in} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:567 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6316 com.android.server.wm.WindowManagerService.addWindow:1965 com.android.server.wm.Session.addToDisplayAsUser:182 
--------- beginning of crash
2024-02-19 23:06:20.392 21617-21617 AndroidRuntime          fr.free.nrw.commons.beta             E  FATAL EXCEPTION: main
                                                                                                    Process: fr.free.nrw.commons.beta, PID: 21617
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ProgressDialog.show()' on a null object reference
                                                                                                    	at fr.free.nrw.commons.auth.login.LoginClient.doLogin(LoginClient.kt:63)
                                                                                                    	at fr.free.nrw.commons.auth.LoginActivity.performLogin(LoginActivity.java:217)
                                                                                                    	at fr.free.nrw.commons.auth.LoginActivity.lambda$onCreate$4$fr-free-nrw-commons-auth-LoginActivity(LoginActivity.java:104)
                                                                                                    	at fr.free.nrw.commons.auth.LoginActivity$$ExternalSyntheticLambda4.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:8160)
                                                                                                    	at android.widget.TextView.performClick(TextView.java:16222)
                                                                                                    	at android.view.View.performClickInternal(View.java:8137)
                                                                                                    	at android.view.View.access$3700(View.java:888)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30236)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2024-02-19 23:06:20.394 21617-21617 ACRA                    fr.free.nrw.commons.beta             E  ACRA caught a NullPointerException for fr.free.nrw.commons.beta
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ProgressDialog.show()' on a null object reference
                                                                                                    	at fr.free.nrw.commons.auth.login.LoginClient.doLogin(LoginClient.kt:63)
                                                                                                    	at fr.free.nrw.commons.auth.LoginActivity.performLogin(LoginActivity.java:217)
                                                                                                    	at fr.free.nrw.commons.auth.LoginActivity.lambda$onCreate$4$fr-free-nrw-commons-auth-LoginActivity(LoginActivity.java:104)
                                                                                                    	at fr.free.nrw.commons.auth.LoginActivity$$ExternalSyntheticLambda4.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:8160)
                                                                                                    	at android.widget.TextView.performClick(TextView.java:16222)
                                                                                                    	at android.view.View.performClickInternal(View.java:8137)
                                                                                                    	at android.view.View.access$3700(View.java:888)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30236)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by shashankiitbhu** [comment]
@geektan123 it seems that you are calling show() on a null object there,check code in loginClient.kt , must be some uninitialised object.

**Comment by psh** [comment]
Since you'll be calling the login client from the Activity, it might simply be easier to call the "show()" method before calling the client and have that in the Activity, since that's where all the other user-interface stuff should happen anyhow.

**Comment by psh** [comment]
Hi there.  Just a friendly check-in to see how things are going with this issue.  Is there anything I can do to help?

**Comment by neeldoshii** [comment]
Are you still working on this @geektan123?

**Comment by geektan123** [comment]
Sorry to say but  I did gave my level best to solve issue @psh but not able to solve the issue.I request you to please assign someone better than me..

**Comment by neeldoshii** [comment]
I would like to take it up.

**Comment by rohit9625** [comment]
> Sorry to say but  I did gave my level best to solve issue @psh but not able to solve the issue.I request you to please assign someone better than me..

Don't be sorry. It's a good first issue. We will help you solving this issue if you want. So just ask. Don't think like you can't make it 🙂

**Comment by ShashwatKedia** [comment]
Yeah, you can always retry this or try your hand at another "Good first issue" such as #5565 or some other simpler issue if you want :)

**Comment by neeldoshii** [comment]
@psh I have fixed the issue on #5599.

**Comment by neeldoshii** [comment]
> Sorry to say but I did gave my level best to solve issue @psh but not able to solve the issue.I request you to please assign someone better than me.

@geektan123 whenever you get stuck feel free to ask it in the community. Don't be sadthis is a part of learning phase. ;)
