### ISSUE TITLE
Edit categories of already uploaded pic: can't find category, crash whe pressing "back"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5540]
![Screenshot_20240211-221102.png](https://github.com/commons-app/apps-android-commons/assets/99590/a2fac377-16d8-4f24-980b-0f5c9afa168c)

on branch. should test on main too.

```
APP_VERSION_CODE=1036
APP_VERSION_NAME=4.2.1-debug-ShashwatKedia-issue5511ShashwatKedia
ANDROID_VERSION=14
PHONE_MODEL=Pixel 7 Pro
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment.onDestroyView(UploadCategoriesFragment.java:179)
at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3200)
at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:742)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:745)
at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:672)
at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:776)
at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:147)
at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:120)
at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:297)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2202)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by kanahia1** [comment]
Hello @nicolas-raoul, Can I work on this issue.

**Comment by kanahia1** [comment]
I am also getting similar error. Looking into it ;-)


```APP_VERSION_CODE=1036
APP_VERSION_NAME=4.2.1-debug-issue5502
ANDROID_VERSION=14
PHONE_MODEL=SM-G990E
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
at fr.free.nrw.commons.upload.categories.UploadCategoriesFragment.onDestroyView(UploadCategoriesFragment.java:179)
at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3200)
at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:742)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:745)
at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:672)
at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:776)
at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:147)
at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:120)
at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:297)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2202)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8893)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

**Comment by ShashwatKedia** [comment]
@kanahia1 I am getting this issue while changing depictions as well. Also, while pressing the next button the app crashes

**Comment by kanahia1** [comment]
@ShashwatKedia, Thanks for reporting 🙌

**Comment by rohit9625** [comment]
The activity shown in the screen shot should not be created with a next button.
It should be created with the save button like before.

It must be happening due to any check(null check or something) that was implemented to survive configuration changes during **upload activity **.

**Comment by shashankiitbhu** [comment]
@nicolas-raoul I already reported this issue #5505 and it is already Fixed by the PR I made that is linked with it, Please Review and merge it, thanks :)

**Comment by nicolas-raoul** [comment]
Ah sorry for missing this, thanks all and sorry for the backlog! 🙂
