### ISSUE TITLE
Crash when opening Explore

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5548]
Tasks:
1. Reproduce the issue on main branch.
2. Find the commit that introduced the error.
3. Revert or even fix it.

https://github.com/commons-app/apps-android-commons/assets/99590/375238e3-f416-4b24-b1c5-2cc61fef9dfa

```
java.lang.NullPointerException
at fr.free.nrw.commons.explore.paging.BasePagingFragment.getBinding(BasePagingFragment.kt:33)
at fr.free.nrw.commons.explore.paging.BasePagingFragment.onViewCreated(BasePagingFragment.kt:46)
at fr.free.nrw.commons.explore.media.PageableMediaFragment.onViewCreated(PageableMediaFragment.kt:55)
at fr.free.nrw.commons.explore.categories.media.CategoriesMediaFragment.onViewCreated(CategoriesMediaFragment.kt:19)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
at android.view.View.measure(View.java:27133)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27133)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
at android.view.View.measure(View.java:27133)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2944)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
at android.view.Choreographer.doCallbacks(Choreographer.java:952)
at android.view.Choreographer.doFrame(Choreographer.java:882)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by kanahia1** [comment]
Hey @nicolas-raoul, Can I look into it 😀

**Comment by shashankiitbhu** [comment]
Hey @nicolas-raoul , already opened the issue #5547 and working on it, the issue started after a recent PR #5547

**Comment by nicolas-raoul** [comment]
Sorry, duplicate of #5547
