### ISSUE TITLE
Crash when marking multiple pictures as not for upload ("Show already actioned pictures" enabled)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5629]
Introduced by pull request #5576

https://github.com/commons-app/apps-android-commons/assets/99590/660de479-199d-4332-b3ee-c08e2e752415

```
STACK_TRACE=java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
at java.util.ArrayList$Itr.next(ArrayList.java:982)
at fr.free.nrw.commons.customselector.ui.selector.CustomSelectorActivity$insertIntoNotForUpload$1.invokeSuspend(CustomSelectorActivity.kt:506)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7166044, Dispatchers.Main]
```

**Comment by shashankiitbhu** [comment]
Isn't this a duplicate of Issue #5628?

**Comment by shashankiitbhu** [comment]
@nicolas-raoul I think this one is Fixed with #5628 by #5639

**Comment by Kota-Jagadeesh** [comment]
> [@nicolas-raoul](https://github.com/nicolas-raoul) I think this one is Fixed with [#5628](https://github.com/commons-app/apps-android-commons/issues/5628) by [#5639](https://github.com/commons-app/apps-android-commons/pull/5639)

Yeah, i was not able to reproduce this issue in the current version of the app.
