### ISSUE TITLE
Reproducible crash when marking last pictures as "not for upload"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5634]
https://github.com/commons-app/apps-android-commons/assets/99590/65ebb611-f9fc-4588-af32-333ececbf04f

Possibly caused by recent PR

```
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
at java.util.ArrayList$Itr.next(ArrayList.java:982)
at fr.free.nrw.commons.customselector.ui.selector.CustomSelectorActivity$insertIntoNotForUpload$1.invokeSuspend(CustomSelectorActivity.kt:506)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@37a8630, Dispatchers.Main]
```

**Comment by rohit9625** [comment]
I tried it multiple times with beta and prod Debug build but still can't see the crash. Can you please provide some extra point or something like a condition in which you reproduced this issue?

**Comment by kanahia1** [comment]
@rohit9625 It happens every time. Looking into it ;-)

https://github.com/commons-app/apps-android-commons/assets/114223204/2a1a4125-2c3e-4d17-8793-5884906d66c1

**Comment by rohit9625** [comment]
Wait when I tried it doesn't happen. I just pulled from main branch. Why it doesn't occur in my case?

**Comment by kanahia1** [comment]
@rohit9625 It happens in the case of multiple selection
