### ISSUE TITLE
[Bug]: Crash when adding and then removing media details

### ISSUE THREAD

**Issue by mnalis** [commons-app/apps-android-commons#5721]
### Summary

App crashes when I attempt to remove (after first adding) several instances of Caption/Description fields.

### Steps to reproduce

1. choose image to upload in Commons app
2. on step `1 of 4: Media Details` click in `+` button several times to add more Caption/Description fields
3. click on `X` button several times to remove Captions/Descriptions added in previous step

### Expected behaviour

extra Captions/Descriptions fields should be removed all the way until we're back on only one instance Caption/Description field.

### Actual behaviour

app crashes

### Device name

Samsung Galaxy S23+

### Android version

Android 14 (OneUI 6.1)

### Commons app version

5.0.1~af028cbdd (latest F-droid)

### Device logs

```
FATAL EXCEPTION: main
Process: fr.free.nrw.commons, PID: 15984
java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 5
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at fr.free.nrw.commons.upload.UploadMediaDetailAdapter.removeDescription(UploadMediaDetailAdapter.java:195)
	at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.lambda$bind$5(UploadMediaDetailAdapter.java:300)
	at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder.$r8$lambda$icSYp6LLQKJERqNSGIAA-LSzeUk(UploadMediaDetailAdapter.java:0)
	at fr.free.nrw.commons.upload.UploadMediaDetailAdapter$ViewHolder$$ExternalSyntheticLambda5.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:8047)
	at android.view.View.performClickInternal(View.java:8024)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31890)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Screen-shots

https://github.com/commons-app/apps-android-commons/assets/156656/93a7b27d-af8d-4ed8-a17c-b49a0d6e7d43

### Would you like to work on the issue?

None

**Comment by pacha0** [comment]
@mnalis @nicolas-raoul can I take a look at this one? Looks like a counter is going out of bounds in UploadMediaDetailAdapter.removeDescription

**Comment by nicolas-raoul** [comment]
@pacha0 It is yours, thanks! 🙂
