### ISSUE TITLE
[Bug]: Don't show nominate for deletion / edit category and edit depicts for logged out users

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#5726]
### Summary

It seems like we're showing the "Nominate for deletion" button and edit category and edit depicts buttons to the logged out users.

### Steps to reproduce

1. Open the app using the "Skip login" option
2. Open an image from the "Explore" screen
3. Observe the "Nominate for deletion" button, edit category and edit depicts buttons shown for the image.

### Expected behaviour

It should not be possible for users who are not logged in to "Nominate for deletion" button, edit category and edit depicts buttons shown for the image.

### Actual behaviour

We show the option to "Nominate for deletion" button, edit category and edit depcits buttons but it won't work. Nominate for deletion results in an app crash. Trying to edit the image results in a indefinite spinning loader that then goes away.

### Device name

OnePlus Nord

### Android version

12

### Commons app version

5.0.1

### Device logs

<details><summary>Crash log when "Nominate for deletion" is hit</summary>
<p>

```stacktrace
Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:1082)
at android.app.ContextImpl.startActivity(ContextImpl.java:1058)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:421)
at fr.free.nrw.commons.auth.LoginActivity.startYourself(LoginActivity.java:418)
at fr.free.nrw.commons.auth.SessionManager.forceLogin(SessionManager.java:120)
at fr.free.nrw.commons.delete.ReasonBuilder.checkAccount(ReasonBuilder.java:96)
at fr.free.nrw.commons.delete.ReasonBuilder.fetchArticleNumber(ReasonBuilder.java:66)
at fr.free.nrw.commons.delete.ReasonBuilder.getReason(ReasonBuilder.java:51)
at fr.free.nrw.commons.media.MediaDetailFragment.onDeleteClickeddialogtext(MediaDetailFragment.java:1242)
at fr.free.nrw.commons.media.MediaDetailFragment.lambda$onDeleteButtonClicked$22(MediaDetailFragment.java:1187)
at fr.free.nrw.commons.media.MediaDetailFragment.$r8$lambda$xhyCexNuF3zrc2K-l2yuaiumOfQ(MediaDetailFragment.java:0)
at fr.free.nrw.commons.media.MediaDetailFragment$$ExternalSyntheticLambda25.run(R8$$SyntheticClass:0)
at fr.free.nrw.commons.utils.DialogUtil.createAndShowDialogSafely$lambda$6$lambda$3$lambda$2(DialogUtil.kt:179)
at fr.free.nrw.commons.utils.DialogUtil.$r8$lambda$ECLVYheIYrcn9r0orhEVOej1iq8(DialogUtil.kt:0)
at fr.free.nrw.commons.utils.DialogUtil$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:191)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8212)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

</p>
</details> 

### Would you like to work on the issue?

None

**Comment by djbloop** [comment]
Hey there @sivaraam wanted to take this on as my first contribution. Can I take this up?

**Comment by nicolas-raoul** [comment]
@djbloop It is yours, thanks!

**Comment by djbloop** [comment]
Hi @nicolas-raoul , I wanted to clarify the expected behaviour of the delete button. Should the button be disabled if the user skips the login, or should it disappear entirely? I wanted to ask as I've disabled the function but I wanted to get some clarification.

**Comment by djbloop** [comment]
I'm also unaware of the wording of "edit the image" as I'm unable to reproduce it. I can see that the metadata is editable but not the image itself.

**Comment by sivaraam** [comment]
> Should the button be disabled if the user skips the login, or should it disappear entirely? 

We're accustomed to hiding the buttons that are not relevant to the logged out user in other places. So, doing the same here would be ideal.

> I'm also unaware of the wording of "edit the image" as I'm unable to reproduce it. I can see that the metadata is editable but not the image itself.

Sorry about that. There isn't any edit image button. The description was just trying to refer to the edit category and edit depcits buttons shown for the image. I've updated the description accordingly to avoid confusion.

**Comment by djbloop** [comment]
I'm wondering how I'm supposed to run a unit test. But I can't find any documentation on it in "commons-app-documentation".

**Comment by djbloop** [comment]
> I'm wondering how I'm supposed to run a unit test. But I can't find any documentation on it in "commons-app-documentation".

Figured it out.
