### ISSUE TITLE
CustomSelectorActivity kotlin.UninitializedPropertyAccessException: lateinit property imageAdapter has not been initialized

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5867]
https://github.com/user-attachments/assets/bd55c85b-5c82-4e20-a4a9-a0ea9407ae67

```
java.lang.RuntimeException: Unable to destroy activity {fr.free.nrw.commons/fr.free.nrw.commons.customselector.ui.selector.CustomSelectorActivity}: kotlin.UninitializedPropertyAccessException: lateinit property imageAdapter has not been initialized
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6044)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6076)
at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:52)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)
at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:169)
at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:101)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)
at android.os.Handler.dispatchMessage(Handler.java:109)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8787)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property imageAdapter has not been initialized
at fr.free.nrw.commons.customselector.ui.selector.ImageFragment.onDestroy(ImageFragment.kt:331)
at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3219)
at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:774)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:350)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:120)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:334)
at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:330)
at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:280)
at fr.free.nrw.commons.theme.BaseActivity.onDestroy(BaseActivity.java:50)
at fr.free.nrw.commons.customselector.ui.selector.CustomSelectorActivity.onDestroy(CustomSelectorActivity.kt:599)
at android.app.Activity.performDestroy(Activity.java:9310)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1563)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6031)
... 14 more
```

**Comment by rohit9625** [comment]
Don't worry most of the code will be replaced soon.
The UI and it's features are almost complete but I am having trouble with the zoom and horizontal pager functionality to view all images.

I was thinking to link a PR but that functionality having conflicts dealing with the gestures.
What do you think?

**Comment by nicolas-raoul** [comment]
OK I will mark this as low priority, looking forward to  the replacement! 🙂

Swipes are really useful when going through many pictures.

**Comment by RitikaPahwa4444** [comment]
#6429 has a check on this lateinit property. Are we still facing this issue?

**Comment by nicolas-raoul** [comment]
I haven't faced this recently. 🙂
