### ISSUE TITLE
Category search results not appearing

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5910]
On rc 5.1.0 but also seen in main.

https://github.com/user-attachments/assets/6ebc7ba5-8ae3-485e-8d34-3ba2d004005c

**Comment by sivaraam** [comment]
That's weird. Do you observe any relevant logs related to this in logcat that may indicate a potential cause ?

**Comment by nicolas-raoul** [comment]
I just reproduced the issue (maybe that happens after I uploaded something?), and this is the last thing I see this in logcat:
```
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean fr.free.nrw.commons.wikidata.mwapi.MwQueryPage$CategoryInfo.isHidden()' on a null object reference
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at fr.free.nrw.commons.category.CategoryClient$responseMapper$2.invoke(CategoryClient.kt:127)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at fr.free.nrw.commons.category.CategoryClient$responseMapper$2.invoke(CategoryClient.kt:124)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at fr.free.nrw.commons.category.CategoryClient.responseMapper$lambda$1(CategoryClient.kt:124)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at fr.free.nrw.commons.category.CategoryClient.$r8$lambda$PpmPhtqaRvMwswU5RXlbuTpQAbg(Unknown Source:0)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at fr.free.nrw.commons.category.CategoryClient$$ExternalSyntheticLambda2.apply(D8$$SyntheticClass:0)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Single.subscribe(Single.java:3603)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Single.subscribe(Single.java:3603)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Single.subscribe(Single.java:3603)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.subscribe(ObservableCombineLatest.java:117)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.observable.ObservableCombineLatest.subscribeActual(ObservableCombineLatest.java:71)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.subscribe(ObservableCombineLatest.java:117)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.observable.ObservableCombineLatest.subscribeActual(ObservableCombineLatest.java:71)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-30 22:54:29.819 16101 16101 E CategoriesPresenter$onAttachView: 	at java.lang.Thread.run(Thread.java:1012)
```

When I type something in the category search bar, I see nothing appear in logcat.
A few minutes ago when uploading a previous picture I was seeing a line like this for each category search:
```
okhttp.OkHttpClient: --> GET https://commons.wikimedia.org/w/api.php?action=query&format=json&formatversion=2&generator=allcategories&prop=categoryinfo|description|pageimages&piprop=thumbnail&pithumbsize=70&gacprefix=nutella&gaclimit=25&gacoffset=0
```

**Comment by nicolas-raoul** [comment]
I can still reproduce these symptoms on main, still some of the time only (I didn't check logcat though).

#5884 fixes the issue but introduces other problems.

**Comment by OpenGreenStreet** [comment]
I only know the problem in the current version and the strange thing is that the problem does not always occur. After "closing" and restarting the app, it works at least once.

I have observed the following variants:

* No selection possible at all
* Selection is only possible after closing and restarting the app
* the category of the “searched image” is stored, but no additional category can be selected
* sometimes everything is as usual/as expected

See: https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_Molgreen_for_version_5.1.0~707997bd1_on_2024/11/14_16:51:33

 #5929

**Comment by sivaraam** [comment]
> I only know the problem in the current version and the strange thing is that the problem does not always occur

I agree with this. To be honest, I have unfortunately not been able to reproduce this issue. How often does it occur? Is there a particular search phrase for which this occurs reliably? This would help us narrow down the issue.

**Comment by OpenGreenStreet** [comment]
@sivaraam
I have no idea why, but since a few days the problem does not occur anymore. (I have uploaded a few pictures in the meantime without any problems.) Is it possibly because the system requested for the categories did not work as expected?

**Comment by sivaraam** [comment]
> Is it possibly because the system requested for the categories did not work as expected?

If you're suspecting that this may be a problem on the server side. I'm kind of unsure. There is a possibility for that to be true if the response was not received properly and has been corrected now. It's hard to say for certain, though.

Feel free to post here any specific details if you come across this issue again.

**Comment by OpenGreenStreet** [comment]
@sivaraam 
Yes, I will do that. As I said, I haven't had the problem for at least 14 days.

**Comment by nicolas-raoul** [comment]
I am recently getting this issue very frequently:
https://github.com/user-attachments/assets/cb409692-4588-45f7-b1a8-f784268999f1

**Comment by sivaraam** [comment]
Indeed. Even I just observed this in the app now. 🤔

**Comment by OpenGreenStreet** [comment]
It is very strange: I know the problem, but it hasn't happened to me for weeks (just tried it).

**Comment by nicolas-raoul** [comment]
Yesterday it happened to me once, while 5 other uploads had no issue.

Anyone investigating this, I would recommend watching category-related API network calls while trying to reproduce, it may take like 10 trials.

**Comment by parneet-guraya** [comment]
Check #6093 this should be fixed now, same exception occurs when we search something in the `explore` screen and categories list is empty due to this, this happens 100% of the time in this case. The solution pretty much sums up what was the issue.

**Comment by sivaraam** [comment]
Closing this as PR #6093 has been merged (as noted in [this comment](https://github.com/commons-app/apps-android-commons/issues/6043#issuecomment-2585398622))
