### ISSUE TITLE
App crashes while trying to submit feedback when you don't have access to internet

### ISSUE THREAD

**Issue by neeldoshii** [commons-app/apps-android-commons#6003]
Reproduce Video

https://github.com/user-attachments/assets/af8957b6-9ac5-466d-a28b-4190dcfe6a01

Seems Like similar to #5962

```
HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "query.wikidata.org": No address associated with hostname

FATAL EXCEPTION: main
Process: fr.free.nrw.commons.beta, PID: 16365
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 
Caused by: fr.free.nrw.commons.auth.csrf.InvalidLoginTokenException: App believes we're logged in, but got anonymous token.
	at fr.free.nrw.commons.auth.csrf.CsrfTokenClient.getTokenBlocking(CsrfTokenClient.kt:69)
	at fr.free.nrw.commons.actions.PageEditClient.createNewSection(PageEditClient.kt:145)
	at fr.free.nrw.commons.navtab.MoreBottomSheetFragment.uploadFeedback(MoreBottomSheetFragment.kt:173)
	at fr.free.nrw.commons.navtab.MoreBottomSheetFragment$showFeedbackDialog$1.onFeedbackSubmit(MoreBottomSheetFragment.kt:161)
	at fr.free.nrw.commons.feedback.FeedbackDialog.submitFeedback(FeedbackDialog.kt:74)
	at fr.free.nrw.commons.feedback.FeedbackDialog.onCreate$lambda$0(FeedbackDialog.kt:44)
	at fr.free.nrw.commons.feedback.FeedbackDialog.$r8$lambda$HTtDYbvegYNGtZntfhXIXLSkmWA(Unknown Source:0)
	at fr.free.nrw.commons.feedback.FeedbackDialog$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:6733)
	at android.view.View.performClickInternal(View.java:6691)
	at android.view.View.access$3400(View.java:802)
	at android.view.View$PerformClick.run(View.java:26499)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7178)
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 
ACRA caught a RuntimeException for fr.free.nrw.commons.beta
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 
Caused by: fr.free.nrw.commons.auth.csrf.InvalidLoginTokenException: App believes we're logged in, but got anonymous token.
	at fr.free.nrw.commons.auth.csrf.CsrfTokenClient.getTokenBlocking(CsrfTokenClient.kt:69)
	at fr.free.nrw.commons.actions.PageEditClient.createNewSection(PageEditClient.kt:145)
	at fr.free.nrw.commons.navtab.MoreBottomSheetFragment.uploadFeedback(MoreBottomSheetFragment.kt:173)
	at fr.free.nrw.commons.navtab.MoreBottomSheetFragment$showFeedbackDialog$1.onFeedbackSubmit(MoreBottomSheetFragment.kt:161)
	at fr.free.nrw.commons.feedback.FeedbackDialog.submitFeedback(FeedbackDialog.kt:74)
	at fr.free.nrw.commons.feedback.FeedbackDialog.onCreate$lambda$0(FeedbackDialog.kt:44)
	at fr.free.nrw.commons.feedback.FeedbackDialog.$r8$lambda$HTtDYbvegYNGtZntfhXIXLSkmWA(Unknown Source:0)
	at fr.free.nrw.commons.feedback.FeedbackDialog$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:6733)
	at android.view.View.performClickInternal(View.java:6691)
	at android.view.View.access$3400(View.java:802)
	at android.view.View$PerformClick.run(View.java:26499)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7178)
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942) 
Sending signal. PID: 16365 SIG: 9
channel '86f5e3 fr.free.nrw.commons.beta/fr.free.nrw.commons.contributions.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
channel 'edaf929 fr.free.nrw.commons.beta/fr.free.nrw.commons.contributions.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
channel 'c9f613d fr.free.nrw.commons.beta/fr.free.nrw.commons.contributions.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
type=1400 audit(0.0:20637): avc: denied { search } for name="/" dev="mmcblk0p40" ino=2 scontext=u:r:zygote:s0 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=0
Late-enabling -Xcheck:jni
type=1400 audit(0.0:20638): avc: denied { read } for name="u:object_r:mtk_amslog_prop:s0" dev="tmpfs" ino=8454 scontext=u:r:untrusted_app:s0:c207,c256,c512,c768 tcontext=u:object_r:mtk_amslog_prop:s0 tclass=file permissive=0
Access denied finding property "persist.vendor.sys.activitylog"
The ClassLoaderContext is a special shared library.
The ClassLoaderContext is a special shared library.
Unable to instantiate appComponentFactory
java.lang.ClassNotFoundException: Didn't find class "fr.free.nrw.commons.beta.commons" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/base.apk", zip file "/data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/split_config.arm64_v8a.apk", zip file "/data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/split_config.en.apk", zip file "/data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/lib/arm64, /data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/base.apk!/lib/arm64-v8a, /data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/split_config.en.apk!/lib/arm64-v8a, /data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.LoadedApk.createAppFactory(LoadedApk.java:238)
	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:778)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:857)
	at android.app.LoadedApk.getResources(LoadedApk.java:1092)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2469)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6162)
	at android.app.ActivityThread.access$1300(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/split_config.arm64_v8a.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:354)
		at dalvik.system.DexFile.<init>(DexFile.java:101)
		at dalvik.system.DexFile.<init>(DexFile.java:75)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
		at dalvik.system.DexPathList.<init>(DexPathList.java:164)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:774)
		... 12 more
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/fr.free.nrw.commons.beta-CX5Dz3f-o9_o8euoJ1y0jg==/split_config.en.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:354)
		at dalvik.system.DexFile.<init>(DexFile.java:101)
		at dalvik.system.DexFile.<init>(DexFile.java:75)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
		at dalvik.system.DexPathList.<init>(DexPathList.java:164)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.ja
```

**Comment by angrezichatterbox** [comment]
I will like to work on this issue. Could this be assigned to me

**Comment by angrezichatterbox** [comment]
Hi @nicolas-raoul I have made a PR for this issue. Happy to make changes as required to make the PR perfect.
