### ISSUE TITLE
Nearby activity feels slow, performance issues

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#6038]
- UI slowdowns in areas with many points
- slow loading of pins even cached ones
- memory leaks

Some issues have been identified, feel free to report others:

- https://github.com/commons-app/apps-android-commons/issues/6037
- https://github.com/commons-app/apps-android-commons/issues/4465
- https://github.com/commons-app/apps-android-commons/issues/5529

**Comment by savsch** [comment]
Throughout this comment, I will use the terms _"pins: initial loading"_ and _"pins: details loading"_ to refer to the two stages in which pins are loaded in nearby.

Spent the greater part of my day trying to fix UI slowdowns (caused mostly by flawed _"pins: details loading"_ implementation).
[This is the branch I have been working on](https://github.com/savsch/apps-android-commons/tree/nearby/performance-experiments). (didn't create a draft PR as it started out as an experiment and rewriting some of the marker overlay management is still left.)

Rewrote most of the _"pins: details loading"_ logic, the existing implementation of which was computationally inefficient in part and also prone to race conditions.
This should hopefully have fixed most UI slowdowns.

@nicolas-raoul can you try out the branch and confirm whether the UI slowdowns have lessened?

---

Stuff that's still left to account for:
 - Map tiles loading slowly.
 - Issue tracking the current location.
 - Flawed _"pins: initial loading"_.

I'd like to expound upon the last point above, and also suggest fixes. Creating a new issue for the same...

**Comment by nicolas-raoul** [comment]
@savsch I just tested your repo, it seems so much faster! 🎉

**Comment by nicolas-raoul** [comment]
With your branch:
- Initial loading:Zooming out then in does not trigger slowdowns anymore. 🎉
- Details loading: Cached pins load very fast. 🎉

**Comment by nicolas-raoul** [comment]
I spotted another improvement opportunity.
After initial loading, the current algorithm for loading details of pins seems to be:

1. Start from the centermost pin.
2. If it is cached, then show it, else make the query and show it.
3. Move on to the next pin, going away from the center little by little.

Instead, I would suggest this algorithm:
1. For each pin, check whether it is cached or not. Show all cached pins.
2. Now we only have uncached pins left. Similarly to the algorithm above, perform queries starting from the center.

**Comment by nicolas-raoul** [comment]
Still on your repo, I sometimes see the loading icon forever:

https://github.com/user-attachments/assets/fa54993f-cdb1-452f-b8f2-9bf5ba858bfe

**Comment by nicolas-raoul** [comment]
Still on your repo, after leaving Nearby open for 10 minutes, it suddenly crashed:
```
APP_VERSION_NAME=5.0.2-debug-nearby/performance-experiments
ANDROID_VERSION=15
PHONE_MODEL=Pixel 9 Pro
STACK_TRACE=java.lang.RuntimeException: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1516256 free bytes and 1480KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
at fr.free.nrw.commons.concurrency.BackgroundPoolExceptionHandler.lambda$onException$0(BackgroundPoolExceptionHandler.java:18)
at fr.free.nrw.commons.concurrency.BackgroundPoolExceptionHandler$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1516256 free bytes and 1480KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
at fr.free.nrw.commons.logging.FileLoggingTree.logMessage(FileLoggingTree.kt:66)
at fr.free.nrw.commons.logging.FileLoggingTree.log$lambda$0(FileLoggingTree.kt:55)
at fr.free.nrw.commons.logging.FileLoggingTree.$r8$lambda$XsoUiE8XuqISALIIa-wwDdY9dms(Unknown Source:0)
at fr.free.nrw.commons.logging.FileLoggingTree$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
... 1 more
```

**Comment by savsch** [comment]
> Still on your repo, I sometimes see the loading icon forever

With the current HEAD, it should not happen any more frequently than it does on the current main. Even if it does happen, I am likely to replace the existing loading icon implementation, as it's a bit hacky in my opinion (relies on Handler.postDelayed and static variables), when working on #6044.

**Comment by nicolas-raoul** [comment]
Nearby does not feel slow anymore, great work all! :-)
