### ISSUE TITLE
Crash upon uploading a picture

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#6053]
```
STACK_TRACE=java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 359904 free bytes and 351KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
at java.lang.Integer.valueOf(Integer.java:1208)
at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:1040)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:387)
at android.os.Looper.loopOnce(Looper.java:189)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8934)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by sonalyadav1** [comment]
@nicolas-raoul I think this error is thrown by Java Virtual Machine (JVM) when an object cannot be allocated due to lack of memory space and also, the garbage collector cannot free some space.
