### ISSUE TITLE
[Bug]: App crashes when clicking on a bookmarked location 

### ISSUE THREAD

**Issue by sonalyadav1** [commons-app/apps-android-commons#6077]
### Summary

The crash occurred due to a ClassCastException where a FrameLayout was being cast to a RelativeLayout.

### Steps to reproduce

1. Navigate to the Bookmark section.
2. Click on a bookmarked location.
3. The app crashes.

https://github.com/user-attachments/assets/35051527-7472-46bb-a6ab-3369eb217201

### Expected behaviour

Clicking on a bookmarked location should not crash the app. The PlaceAdapterDelegate should function correctly without any errors.

### Actual behaviour

The app crashes with a NullPointerException when clicking on a bookmarked location, due to accessing an uninitialized focusChangeListener property

### Device name

Vivo V25

### Android version

Android 14

### Commons app version

5.0.2

### Would you like to work on the issue?

Yes

**Comment by sonalyadav1** [comment]
@nicolas-raoul  Are you able to reproduce?

**Comment by nicolas-raoul** [comment]
Great catch!

I am also getting a crash, but with a different exception haha:
```
java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.RelativeLayout
at fr.free.nrw.commons.nearby.PlaceAdapterDelegateKt$placeAdapterDelegate$2.invoke$lambda$12$lambda$1(PlaceAdapterDelegate.kt:48)
at fr.free.nrw.commons.nearby.PlaceAdapterDelegateKt$placeAdapterDelegate$2.$r8$lambda$P-sx_9zMDaDAyiTKiF7QraPxt3s(Unknown Source:0)
at fr.free.nrw.commons.nearby.PlaceAdapterDelegateKt$placeAdapterDelegate$2$$ExternalSyntheticLambda7.onFocusChange(D8$$SyntheticClass:0)
at android.view.View.onFocusChanged(View.java:8769)
at android.view.View.handleFocusGainInternal(View.java:8425)
at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:855)
at android.view.View.requestFocusNoSearch(View.java:15395)
at android.view.View.requestFocus(View.java:15369)
at android.view.ViewGroup.requestFocus(ViewGroup.java:3350)
at android.view.View.requestFocus(View.java:15336)
at android.view.View.requestFocus(View.java:15278)
at android.view.View.onTouchEvent(View.java:18106)
at android.view.View.performOnTouchCallback(View.java:16621)
at android.view.View.dispatchTouchEvent(View.java:16574)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3138)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2814)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3144)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2829)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:474)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1981)
at android.app.Activity.dispatchTouchEvent(Activity.java:4599)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:432)
at android.view.View.dispatchPointerEvent(View.java:16904)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8118)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7877)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7259)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7316)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7282)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7448)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7290)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7505)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7263)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7316)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7282)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7290)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7263)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10404)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10355)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10323)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10546)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:387)
at android.os.Looper.loopOnce(Looper.java:189)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8934)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```
When reporting an exception would you mind pasting the full stack? Or at least the first 10 lines. It makes it more searchable, and sometimes contains hints. Thanks for your report! 🙂

**Comment by sonalyadav1** [comment]
The crash occurred due to a ClassCastException where a FrameLayout was being cast to a RelativeLayout. 
Thank you for pointing out the importance of attaching the full stack trace! 
I've resolved the issue by adjusting the logic in PlaceAdapterDelegate.kt to handle the layout type properly. The crash no longer occurs.
