### ISSUE TITLE
Crash on rotate

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#631]
App crashes when rotating device inside MediaDetailsFragment activity.

```
05-19 15:45:34.151 11819-11819/fr.free.nrw.commons E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: fr.free.nrw.commons, PID: 11819
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.ContributionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
                                                                         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4974)
                                                                         at android.app.ActivityThread.-wrap21(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                                                         at fr.free.nrw.commons.contributions.ContributionsActivity.onCreate(ContributionsActivity.java:139)
                                                                         at android.app.Activity.performCreate(Activity.java:6912)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008) 
                                                                         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4974) 
                                                                         at android.app.ActivityThread.-wrap21(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6688) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 

```

**Comment by misaochan** [comment]
This has been fixed
