### ISSUE TITLE
Crash: Unable to start app when commons access is blocked

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#708]
Maybe we can add a sign as "Sorry, it is not possible to connect from your country" etc. Here is the log:

```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NullPointerException: key == null || value == null
at android.support.v4.util.LruCache.put(LruCache.java:133)
at fr.free.nrw.commons.MediaWikiImageView$ThumbnailFetchTask.onPostExecute(MediaWikiImageView.java:84)
at fr.free.nrw.commons.MediaWikiImageView$ThumbnailFetchTask.onPostExecute(MediaWikiImageView.java:70)
at android.os.AsyncTask.finish(AsyncTask.java:631)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by misaochan** [comment]
I'm not sure this is always country-related (could someone face the same issue if they were just, say, experiencing internet problems?), but we should definitely display a message instead of crash.

**Comment by neslihanturan** [comment]
Should I close this issue manually?

**Comment by misaochan** [comment]
Yes, please feel free to close any issues that you think should be closed @neslihanturan . :) If you make a mistake it can always be reopened, so no big deal.
