### ISSUE TITLE
Crash: java.lang.NoSuchFieldError on Android 4.4.2 on MediaDetailFragment

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#711]
To reproduce please click one of your uploaded photo to see details.

```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: fr.free.nrw.commons, PID: 11110
java.lang.NoSuchFieldError: android.support.v7.appcompat.R$id.image
at android.support.v7.widget.ActivityChooserView.<init>(ActivityChooserView.java:241)
at android.support.v7.widget.ActivityChooserView.<init>(ActivityChooserView.java:205)
at android.support.v7.widget.ActivityChooserView.<init>(ActivityChooserView.java:195)
at android.support.v7.widget.ShareActionProvider.onCreateActionView(ShareActionProvider.java:221)
at android.support.v4.view.ActionProvider.onCreateActionView(ActionProvider.java:169)
at android.support.v7.view.menu.MenuItemImpl.getActionView(MenuItemImpl.java:633)
at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:195)
at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:508)
at android.support.v7.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1160)
at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:95)
at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:234)
at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1047)
at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1074)
at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:460)
at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
at android.view.Choreographer.doCallbacks(Choreographer.java:591)
at android.view.Choreographer.doFrame(Choreographer.java:559)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by misaochan** [comment]
Does this still happen?

**Comment by neslihanturan** [comment]
Unfortunately, yes.

**Comment by mwoguri** [comment]
@neslihanturan I was unable to reproduce this crash on an Xperia Z1 Compact running 4.4.2.  Could you give any further details?  Here's what I did:

1. Install app
2. Go through tutorial and log in
3. Upload photo, adding a title and category
4. On "My Recent Uploads" page, tap the photo
(No crash observed)

**Comment by neslihanturan** [comment]
Hey, no error occurs on my case either, any more. Thanks for reminding this! This issue can be closed, I guess.
