### ISSUE TITLE
NullPointerException at NavigationBaseFragment

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#728]
@neslihanturan @maskaravivek We are getting a new crash (in the production version of the app) from the hamburger menu. :(

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
  at android.app.ActivityThread.-wrap12(ActivityThread.java:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6186)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: 
  at fr.free.nrw.commons.hamburger.NavigationBaseFragment.setUsername(NavigationBaseFragment.java:95)
  at fr.free.nrw.commons.hamburger.NavigationBaseFragment.onCreateView(NavigationBaseFragment.java:72)
  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
  at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2888)
  at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
  at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
  at android.app.Activity.performStart(Activity.java:6701)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
```

**Comment by neslihanturan** [comment]
How can we reproduce it?
On Jun 8, 2017 4:48 PM, "Josephine Lim" <notifications@github.com> wrote:
>
> @neslihanturan @maskaravivek We are getting a new crash (in the
production version of the app) from the hamburger menu. :(
>
> java.lang.RuntimeException:
>   at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
>   at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
>   at android.app.ActivityThread.-wrap12(ActivityThread.java:0)
>   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
>   at android.os.Handler.dispatchMessage(Handler.java:102)
>   at android.os.Looper.loop(Looper.java:154)
>   at android.app.ActivityThread.main(ActivityThread.java:6186)
>   at java.lang.reflect.Method.invoke(Native Method:0)
>   at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
> Caused by: java.lang.NullPointerException:
>   at
fr.free.nrw.commons.hamburger.NavigationBaseFragment.setUsername(NavigationBaseFragment.java:95)
>   at
fr.free.nrw.commons.hamburger.NavigationBaseFragment.onCreateView(NavigationBaseFragment.java:72)
>   at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
>   at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
>   at
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
>   at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
>   at
android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2888)
>   at
android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
>   at
android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
>   at
android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
>   at
android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
>   at android.app.Activity.performStart(Activity.java:6701)
>   at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)

**Comment by misaochan** [comment]
Unfortunately, I have no idea lol. I got that crash report from the Google Developer ANRs/crashes page, that I think only @nicolas-raoul and myself were granted access to by WMF (as we are published via their account). The only further information I have is

> Report timestamp
> Today, 07:41
> Application version
> 73
> Android version
> Android 7.1
> Device
> Nexus 5 (hammerhead)
> Manufacturer Google RAM (MB) 2048 Screen size 1080 × 1920 Screen density (dpi) 480 Native platform armeabi-v7a OpenGL ES version 3.0 CPU make Qualcomm CPU model MSM8974

**Comment by maskaravivek** [comment]
@misaochan Am not able to find the line of code thats mentioned in the error log in our codebase. It seems to crashing because of a NPE in `setUsername` in `NavigationBaseFragment` but this line doesn't exist in the latest code that i pulled. :/

**Comment by misaochan** [comment]
Yeah, that's really strange, I can't find it either. :/ The application version was 73, which was only set at https://github.com/commons-app/apps-android-commons/commit/d5c4e59db5df44dbabb95eee329da73d337db93a . Even by browsing the repo at that point in history, line 95 at NavigationBaseFragment onwards is:

```
    @OnClick(R.id.settings_item)
    protected void onSettingsItemClicked() {
        closeDrawer();
        SettingsActivity.startYourself(getActivity());
    }
```

Not sure what's going on, lol. Fortunately only 1 user seems to be impacted by this.

**Comment by veyndan** [comment]
Can this be closed since `NavigationBaseFragment` was removed in #752?

**Comment by misaochan** [comment]
Yeah, good point. This issue does not seem to have recurred yet anyway.
