### ISSUE TITLE
java.lang.OutOfMemoryError at NavigationBaseFragment.showPictureOfTheDay

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#731]
Also from Google Developer crash reports:

```
java.lang.OutOfMemoryError: 
  at dalvik.system.VMRuntime.newNonMovableArray(Native Method:0)
  at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method:0)
  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
  at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
  at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1155)
  at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:720)
  at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
  at android.content.res.Resources.getDrawable(Resources.java:771)
  at android.content.res.Resources.getDrawable(Resources.java:742)
  at fr.free.nrw.commons.hamburger.NavigationBaseFragment.showPictureOfTheDay(NavigationBaseFragment.java:77)
  at fr.free.nrw.commons.hamburger.NavigationBaseFragment.onCreateView(NavigationBaseFragment.java:70)
  at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
  at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2888)
  at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
  at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
  at android.app.Activity.performStart(Activity.java:6701)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
  at android.app.ActivityThread.-wrap12(ActivityThread.java:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6186)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

> Report timestamp
> Yesterday, 04:20
> Application version
> 73
> Android version
> Android 7.1
> Device
> Nexus 5 (hammerhead)
> Manufacturer Google RAM (MB) 2048 Screen size 1080 × 1920 Screen density (dpi) 480 Native platform armeabi-v7a OpenGL ES version 3.0 CPU make Qualcomm CPU model MSM8974

This might be worth looking at, as 2GB of RAM is a pretty standard amount.

**Comment by tised** [comment]
I cannot find such package "hamburger" on main branch, and NavigationBaseFragment are not exist too

**Comment by misaochan** [comment]
I think this issue might have been deprecated by the recent changes. I'll close it for now, we can reopen if it persists.
