### ISSUE TITLE
java.lang.NullPointerException at ContributionsContentProvider.update

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#732]
11 reports by 6 impacted users - pretty high priority IMO.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3335)
  at android.app.ActivityThread.-wrap21(ActivityThread.java:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.NullPointerException: 
  at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
  at fr.free.nrw.commons.contributions.ContributionsContentProvider.update(ContributionsContentProvider.java:151)
  at android.content.ContentProvider$Transport.update(ContentProvider.java:356)
  at android.content.ContentResolver.update(ContentResolver.java:1407)
  at fr.free.nrw.commons.upload.UploadService.onStartCommand(UploadService.java:166)
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3318)
```

> By app version
> 73	4
> 72	4
> 71	3
> 73	4	36.4%
> 72	4	36.4%
> 71	3	27.3%
> By Android version
> Android 7.1	6
> Android 7.0	5
> Android 7.1	6	54.5%
> Android 7.0	5	45.5%
> By device
> OnePlus3T (OnePlus3T)
> 2 (18.2%)
> Nexus 5X (bullhead)	3
> Moto G(4) (athene)	3
> Moto G Plus (5th Gen) (potter_n)	2
> OnePlus3T (OnePlus3T)	2
> Others	1
> Nexus 5X (bullhead)	3	27.3%
> Moto G(4) (athene)	3	27.3%
> Moto G Plus (5th Gen) (potter_n)	2	18.2%
> OnePlus3T (OnePlus3T)	2	18.2%
> Others	1	9.1%

**Comment by neslihanturan** [comment]
I think this has the same reason with #733 and might be solved by adding one line, but do we have more information about re-producing them? Or does this bug occur on every app launch on specified devices?

**Comment by misaochan** [comment]
Unfortunately the information that I posted above is all we have. It would be easier for you guys to be able to log in to the developer console and see the charts for easier visualization, but I have requested access for you guys a couple of weeks ago and WMF hasn't gotten back to me about that.

At any rate, I don't think anything in the console says whether it occurs on every app launch on specific devices, but it does give a breakdown of devices for each week. The current week is:

> By device
> Galaxy S7 (herolte)	6
> Galaxy S7 Edge (hero2lte)	5
> P9 (HWEVA)	4
> Galaxy S8+ (dream2qltesq)	2
> Others	2
> Galaxy S7 (herolte)	6	31.6%
> Galaxy S7 Edge (hero2lte)	5	26.3%
> P9 (HWEVA)	4	21.1%
> Galaxy S8+ (dream2qltesq)	2	10.5%
> Galaxy Note5 (noblelte)	1	5.3%
> Galaxy S7 (heroqltevzw)	1	5.3%
> 
> 

So given the numbers above it does not appear to be the case - the Galaxy S7 for instance is quite a popular phone, so if it happened to ALL Galaxy S7 devices ALL the time, chances are the numbers would be higher than just 3 crashes. Also they fluctuate by time and seem to be quite spread out among various devices each week.

**Comment by neslihanturan** [comment]
It seems like this happens on Android 7 or higher versions. But I couldn't understand what does this percentages mean?

**Comment by misaochan** [comment]
The percentages all just add up to 100%. Perhaps this screenshot will help:

![crash_charts](https://user-images.githubusercontent.com/3611199/27735587-bfb9b7a4-5de3-11e7-9d66-43abde0c9c77.png)

You are correct that it only happens in Android 7.0 and above.

Bear in mind that this chart only represents the current week. I'm not sure how to aggregate all the weeks' data yet.

**Comment by misaochan** [comment]
Should have been fixed, will reopen if not.
