### ISSUE TITLE
java.lang.NullPointerException at ModificationsContentProvider.query

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#733]
```
java.lang.NullPointerException: 
  at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
  at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
  at fr.free.nrw.commons.modifications.ModificationsContentProvider.query(ModificationsContentProvider.java:57)
  at android.content.ContentProvider.query(ContentProvider.java:1020)
  at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
  at android.content.ContentProviderClient.query(ContentProviderClient.java:145)
  at android.content.ContentProviderClient.query(ContentProviderClient.java:127)
  at fr.free.nrw.commons.modifications.ModificationsSyncAdapter.onPerformSync(ModificationsSyncAdapter.java:38)
  at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```

6 reports by 4 impacted users:

> By app version
> 71	4
> 73	2
> 71	4
> 73	2
> 71	4	66.7%
> 73	2	33.3%
> By Android version
> Android 7.1
> 6 (100%)
> Android 7.1	6
> Android 7.1	6	100.0%
> By device
> OnePlus3T (OnePlus3T)	3
> Xperia XZ (F8331)	2
> Pixel (sailfish)	1
> OnePlus3T (OnePlus3T)	3	50.0%
> Xperia XZ (F8331)	2	33.3%
> Pixel (sailfish)	1	16.7%

**Comment by misaochan** [comment]
Should be fixed, will reopen if not.
