### ISSUE TITLE
java.lang.IllegalStateException at NearbyActivity.setMapFragment

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#739]
USER_COMMENT=i clicked on automatic location setting
ANDROID_VERSION=7.1.1
APP_VERSION_NAME=2.4.2
BRAND=OnePlus
PHONE_MODEL=ONEPLUS A3003
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:649)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
at fr.free.nrw.commons.nearby.NearbyActivity.setMapFragment(NearbyActivity.java:295)
at fr.free.nrw.commons.nearby.NearbyActivity$NearbyAsyncTask.onPostExecute(NearbyActivity.java:276)
at fr.free.nrw.commons.nearby.NearbyActivity$NearbyAsyncTask.onPostExecute(NearbyActivity.java:225)
at android.os.AsyncTask.finish(AsyncTask.java:667)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6290)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by eoinzy** [comment]
FYI, I think you can just change:
`fragmentTransaction.commit();`

to
`fragmentTransaction. commitAllowingStateLoss();`

**Comment by misaochan** [comment]
Hi @tised ,

Thanks for all the great patches, they've been very helpful to us. :) A little note: If you put the issue number (say, "fix #739") in the pull request comment/description, it will automatically close the issue when I merge it. Putting it in a commit or the title of the PR does help, but I don't think it automatically closes issues (this one is still open).

**Comment by neslihanturan** [comment]
Should I close this issue manually?
