### ISSUE TITLE
Constant crashes in Release build (current beta in Google Play Store) 

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#986]
When generating a signed APK with the ProdRelease build, I get these errors:

```
C:\Code\GitHub\apps-android-commons\app\build.gradle
Error:Error: commons-logging defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
Error:Error: httpclient defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
```

I was able to carry on and generate the APK regardless, but we should still probably look into them so that we don't keep getting errors in future versions.

Update: Currently, it seems that in order to release any of the new features post-2.5.0, we will need to:

- [ ] Fix issue with commons-logging and httpclient
- [ ] Fix error with kaptProdReleaseKotlin
- [ ] Re-test ProdRelease build (I am hoping we can find a way for other devs to test release builds as well, see #988

**Comment by misaochan** [comment]
Wow. So it said APK build successful and I was able to upload to Google Play beta - but the app crashes for me on the Google Play version. I sent logs, but can't access them until they go through to the server.

**Comment by misaochan** [comment]
Will try to deploy the fixes mentioned at https://stackoverflow.com/questions/46989310/commons-logging-defines-classes-that-conflict-with-classes-now-provided-by-andro

**Comment by misaochan** [comment]
Huh. Well, that didn't solve the problem for me. :/

**Comment by misaochan** [comment]
Ran logcat:

```
11-27 22:31:35.631 25616-25616/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: fr.free.nrw.commons, PID: 25616
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.ContributionsActivity}: java.lang.NullPointerException: fr.free.nrw.commons.CommonsApplication.activityInjector() returned null
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                    Caused by: java.lang.NullPointerException: fr.free.nrw.commons.CommonsApplication.activityInjector() returned null
                                                       at dagger.internal.Preconditions.checkNotNull(Preconditions.java:79)
                                                       at dagger.android.AndroidInjection.inject(AndroidInjection.java:56)
                                                       at fr.free.nrw.commons.contributions.ContributionsActivity.onCreate(ContributionsActivity.java:142)
                                                       at android.app.Activity.performCreate(Activity.java:6912)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 

11-27 22:31:40.509 25646-25646/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: fr.free.nrw.commons, PID: 25646
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.ContributionsActivity}: java.lang.NullPointerException: fr.free.nrw.commons.CommonsApplication.activityInjector() returned null
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                    Caused by: java.lang.NullPointerException: fr.free.nrw.commons.CommonsApplication.activityInjector() returned null
                                                       at dagger.internal.Preconditions.checkNotNull(Preconditions.java:79)
                                                       at dagger.android.AndroidInjection.inject(AndroidInjection.java:56)
                                                       at fr.free.nrw.commons.contributions.ContributionsActivity.onCreate(ContributionsActivity.java:142)
                                                       at android.app.Activity.performCreate(Activity.java:6912)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
11-27 22:31:41.343 3698-4045/? E/OpenGLRenderer: Error:glDeleteShader::<shader> is not a value generated by OpenGL
11-27 22:31:41.343 3698-4045/? E/OpenGLRenderer: Error:glDeleteShader::<shader> is not a value generated by OpenGL
11-27 22:31:41.343 3698-4045/? E/OpenGLRenderer: Error:glDeleteShader::<shader> is not a value generated by OpenGL
11-27 22:31:41.343 3698-4045/? E/OpenGLRenderer: Error:glDeleteShader::<shader> is not a value generated by OpenGL
11-27 22:31:41.343 3698-4045/? E/OpenGLRenderer: Error:glDeleteShader::<shader> is not a value generated by OpenGL
11-27 22:31:41.343 3698-4045/? E/OpenGLRenderer: Error:glDeleteShader::<shader> is not a value generated by OpenGL
11-27 22:31:41.356 3698-3786/? E/ViewRootImpl: sendUserActionEvent() mView == null
11-27 22:31:41.390 25666-25666/? E/Zygote: v2
11-27 22:31:41.391 25666-25666/? E/Zygote: accessInfo : 0
11-27 22:31:41.943 8461-8461/? E/SKBD KeyboardInfoUtils: getInstance start
11-27 22:31:41.944 8461-8461/? E/SKBD KeyboardInfoUtils: sendSIPInformation state:6  isAbstractKeyboardView : true
11-27 22:31:41.946 8461-25714/? E/SKBD KeyboardInfoUtils: sending null keyboardInfo as SIP is closed
11-27 22:31:41.982 8461-8461/? E/SamsungIME: <AbstractKeyboardView> - onDraw() called
11-27 22:31:42.629 8461-8461/? E/SKBD KeyboardInfoUtils: getInstance start
11-27 22:31:42.629 8461-8461/? E/SKBD KeyboardInfoUtils: sendSIPInformation state:6  isAbstractKeyboardView : true
11-27 22:31:42.630 8461-25715/? E/SKBD KeyboardInfoUtils: sending null keyboardInfo as SIP is closed
11-27 22:31:42.800 8461-25717/? E/SamsungIME: updateShiftState() : 2
11-27 22:31:42.907 8461-8461/? E/SamsungIME: <AbstractKeyboardView> - onDraw() called
11-27 22:31:42.997 8461-8461/? E/SamsungIME: <AbstractKeyboardView> - onDraw() called
11-27 22:31:44.239 3698-3794/? E/BatteryStatsService: no controller energy info supplied
11-27 22:31:44.257 3698-3794/? E/BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}

```

**Comment by whym** [comment]
From the result of 'gradle app:dependencies', it looks like the old dependencies are via in.yuvi:http.fluent (which is unmaintained). Not sure if we have to remove (replace) it or there are easier workarounds.

prodReleaseCompileClasspath - Resolved configuration for compilation for variant: prodRelease
+--- com.github.nicolas-raoul:Quadtree:ac16ea8035bf07
+--- fr.avianey.com.viewpagerindicator:library:2.4.1.1
+--- in.yuvi:http.fluent:1.3
|    +--- org.apache.httpcomponents:httpclient:4.2.2
|    |    +--- org.apache.httpcomponents:httpcore:4.2.2
|    |    +--- commons-logging:commons-logging:1.1.1
|    |    \--- commons-codec:commons-codec:1.6 -> 1.10
|    \--- org.apache.httpcomponents:httpmime:4.2.2
|         \--- org.apache.httpcomponents:httpcore:4.2.2
+--- com.android.volley:volley:1.0.0
+--- ch.acra:acra:4.7.0
|    \--- com.android.support:support-v4:23.0.1 -> 26.1.0
|         +--- com.android.support:support-compat:26.1.0
|         |    +--- com.android.support:support-annotations:26.1.0 -> 25.2.0
|         |    \--- android.arch.lifecycle:runtime:1.0.0
|         |         +--- android.arch.lifecycle:common:1.0.0
|         |         \--- android.arch.core:common:1.0.0
|         +--- com.android.support:support-media-compat:26.1.0
|         |    +--- com.android.support:support-annotations:26.1.0 -> 25.2.0
|         |    \--- com.android.support:support-compat:26.1.0 (*)
|         +--- com.android.support:support-core-utils:26.1.0
|         |    +--- com.android.support:support-annotations:26.1.0 -> 25.2.0
|         |    \--- com.android.support:support-compat:26.1.0 (*)
|         +--- com.android.support:support-core-ui:26.1.0
|         |    +--- com.android.support:support-annotations:26.1.0 -> 25.2.0
|         |    \--- com.android.support:support-compat:26.1.0 (*)
|         \--- com.android.support:support-fragment:26.1.0
|              +--- com.android.support:support-compat:26.1.0 (*)
|              +--- com.android.support:support-core-ui:26.1.0 (*)
|              \--- com.android.support:support-core-utils:26.1.0 (*)
+--- org.mediawiki:api:1.3
|    \--- in.yuvi:http.fluent:1.3 (*)
+--- commons-codec:commons-codec:1.10
+--- com.github.pedrovgs:renderers:3.3.3
|    \--- com.android.support:recyclerview-v7:25.3.1 -> 26.1.0
|         +--- com.android.support:support-annotations:26.1.0 -> 25.2.0
|         +--- com.android.support:support-compat:26.1.0 (*)
|         \--- com.android.support:support-core-ui:26.1.0 (*)
+--- com.google.code.gson:gson:2.8.1
+--- com.jakewharton.timber:timber:4.5.1
+--- info.debatty:java-string-similarity:0.24
|    \--- net.jcip:jcip-annotations:1.0
+--- com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0
|    +--- com.android.support:support-annotations:25.3.1 -> 25.2.0
|    +--- com.android.support:support-v4:25.3.1 -> 26.1.0 (*)
|    +--- com.android.support:design:25.3.1 -> 26.1.0
|    |    +--- com.android.support:support-v4:26.1.0 (*)
|    |    +--- com.android.support:appcompat-v7:26.1.0
|    |    |    +--- com.android.support:support-annotations:26.1.0 -> 25.2.0
|    |    |    +--- com.android.support:support-v4:26.1.0 (*)
|    |    |    +--- com.android.support:support-vector-drawable:26.1.0
|    |    |    |    +--- com.android.support:support-annotations:26.1.0 -> 25.2.0
|    |    |    |    \--- com.android.support:support-compat:26.1.0 (*)
|    |    |    \--- com.android.support:animated-vector-drawable:26.1.0
|    |    |         +--- com.android.support:support-vector-drawable:26.1.0 (*)
|    |    |         \--- com.android.support:support-core-ui:26.1.0 (*)
|    |    +--- com.android.support:recyclerview-v7:26.1.0 (*)
|    |    \--- com.android.support:transition:26.1.0
|    |         +--- com.android.support:support-annotations:26.1.0 -> 25.2.0
|    |         \--- com.android.support:support-v4:26.1.0 (*)
|    +--- com.jakewharton.timber:timber:4.5.1
|    +--- com.squareup.okhttp3:okhttp:3.7.0 -> 3.8.1
|    |    \--- com.squareup.okio:okio:1.13.0
|    +--- com.mapzen.android:lost:1.1.1
|    |    +--- com.android.support:appcompat-v7:22.2.0 -> 26.1.0 (*)
|    |    \--- com.android.support:support-v4:22.2.0 -> 26.1.0 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-java-geojson:2.1.3
|    |    +--- com.mapbox.mapboxsdk:mapbox-java-core:2.1.3
|    |    \--- com.google.code.gson:gson:2.8.0 -> 2.8.1
|    \--- com.mapbox.mapboxsdk:mapbox-android-telemetry:2.1.3
|         +--- com.android.support:appcompat-v7:25.1.0 -> 26.1.0 (*)
|         \--- com.squareup.okhttp3:okhttp:3.6.0 -> 3.8.1 (*)
+--- com.android.support:support-v4:26.1.0 (*)
+--- com.android.support:appcompat-v7:26.1.0 (*)
+--- com.android.support:design:26.1.0 (*)
+--- com.android.support:cardview-v7:26.1.0
|    \--- com.android.support:support-annotations:26.1.0 -> 25.2.0
+--- com.jakewharton:butterknife:8.6.0
|    +--- com.jakewharton:butterknife-annotations:8.6.0
|    |    \--- com.android.support:support-annotations:25.1.0 -> 25.2.0
|    +--- com.android.support:support-annotations:25.1.0 -> 25.2.0
|    \--- com.android.support:support-compat:25.1.0 -> 26.1.0 (*)
+--- com.squareup.okhttp3:okhttp:3.8.1 (*)
+--- com.squareup.okio:okio:1.13.0
+--- io.reactivex.rxjava2:rxandroid:2.0.1
|    \--- io.reactivex.rxjava2:rxjava:2.0.1 -> 2.1.2
|         \--- org.reactivestreams:reactive-streams:1.0.0
+--- io.reactivex.rxjava2:rxjava:2.1.2 (*)
+--- com.jakewharton.rxbinding2:rxbinding:2.0.0
|    +--- io.reactivex.rxjava2:rxjava:2.0.2 -> 2.1.2 (*)
|    +--- io.reactivex.rxjava2:rxandroid:2.0.0 -> 2.0.1 (*)
|    \--- com.android.support:support-annotations:25.1.1 -> 25.2.0
+--- com.jakewharton.rxbinding2:rxbinding-support-v4:2.0.0
|    +--- com.jakewharton.rxbinding2:rxbinding:2.0.0 (*)
|    \--- com.android.support:support-core-ui:25.1.1 -> 26.1.0 (*)
+--- com.jakewharton.rxbinding2:rxbinding-appcompat-v7:2.0.0
|    +--- com.jakewharton.rxbinding2:rxbinding:2.0.0 (*)
|    \--- com.android.support:appcompat-v7:25.1.1 -> 26.1.0 (*)
+--- com.jakewharton.rxbinding2:rxbinding-design:2.0.0
|    +--- com.jakewharton.rxbinding2:rxbinding:2.0.0 (*)
|    \--- com.android.support:design:25.1.1 -> 26.1.0 (*)
+--- com.facebook.fresco:fresco:1.3.0
|    +--- com.facebook.fresco:drawee:1.3.0
|    |    \--- com.facebook.fresco:fbcore:1.3.0
|    +--- com.facebook.fresco:fbcore:1.3.0
|    \--- com.facebook.fresco:imagepipeline:1.3.0
|         +--- com.parse.bolts:bolts-tasks:1.4.0
|         +--- com.facebook.fresco:fbcore:1.3.0
|         \--- com.facebook.fresco:imagepipeline-base:1.3.0
|              +--- com.parse.bolts:bolts-tasks:1.4.0
|              \--- com.facebook.fresco:fbcore:1.3.0
+--- com.facebook.stetho:stetho:1.5.0
|    +--- commons-cli:commons-cli:1.2
|    \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.1
+--- com.google.dagger:dagger:2.11
|    \--- javax.inject:javax.inject:1
+--- com.google.dagger:dagger-android-support:2.11
|    +--- com.google.dagger:dagger:2.11 (*)
|    +--- com.google.dagger:dagger-android:2.11
|    |    +--- com.google.dagger:dagger:2.11 (*)
|    |    +--- com.android.support:support-annotations:25.0.0 -> 25.2.0
|    |    +--- com.google.code.findbugs:jsr305:3.0.1
|    |    \--- javax.inject:javax.inject:1
|    +--- com.android.support:appcompat-v7:25.0.0 -> 26.1.0 (*)
|    +--- com.android.support:support-annotations:25.0.0 -> 25.2.0
|    +--- com.android.support:support-v4:25.0.0 -> 26.1.0 (*)
|    +--- com.google.code.findbugs:jsr305:3.0.1
|    \--- javax.inject:javax.inject:1
\--- com.squareup.leakcanary:leakcanary-android-no-op:1.5.1

**Comment by misaochan** [comment]
Possibly worth noting that even with Dagger reverted (on my fork), the ProdRelease build fails with 

```
Error:Execution failed for task ':app:kaptProdReleaseKotlin'.
> Internal compiler error. See log for more details
```

**Comment by misaochan** [comment]
I reverted the beta: https://github.com/misaochan/apps-android-commons/tree/D-commit

Currently, it seems that in order to release any of the new features post-2.5.0, we will need to:

-  Fix conflicts between Dagger and commons-logging and httpclient, or else not use Dagger
-  Fix error with kaptProdReleaseKotlin
-  Re-test ProdRelease build (I am hoping we can find a way for other devs to test release builds as well)

**Comment by nicolas-raoul** [comment]
Did you post any question on StackOverflow about this? If yes, please post the URL here so that I can bounty it :-)

**Comment by misaochan** [comment]
@nicolas-raoul Do you know if it's OK for us to link to our GitHub repo on StackOverflow? The issue is quite specific and there's too much relevant code for me to copy to StackOverflow.

**Comment by psh** [comment]
The *kapt* failure looks like the `build.gradle` dependency was removed but there are other commits that needed to come out as well.

One of the changes back in **Android 6.0** was to [remove the Apache HTTP Client API](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client)

> Android 6.0 release removes support for the Apache HTTP client. If your app is using this client and targets Android 2.3 (API level 9) or higher, use the HttpURLConnection class instead. This API is more efficient because it reduces network use through transparent compression and response caching, and minimizes power consumption. To continue using the Apache HTTP APIs, you must first declare the following compile-time dependency in your build.gradle file:
> 
> android {
>     useLibrary 'org.apache.http.legacy'
> }

Is this what we're seeing?

**Comment by misaochan** [comment]
@psh Thanks for the suggestion. We already do have `useLibrary 'org.apache.http.legacy'` in our current build.gradle file, though... or do you mean we should find a way to remove dependency on it?

**Comment by nicolas-raoul** [comment]
@misaochan Yes the question should include all relevant elements, answerers should not have to click any link. It can be a good opportunity to check everything and make clear what the problem is with all of the minimum conditions.

**Comment by misaochan** [comment]
Checking out with detached HEAD at https://github.com/commons-app/apps-android-commons/commit/75496388ce96eb532334f5f7efe59fb3a3d05e20 yields no such issues when tested. So the issue would lie with commits made after that point, most likely #932 is my guess. @maskaravivek , could you please take a look at this, as you made most of the recent changes to Gradle?

Interestingly, checking out the detached HEAD at https://github.com/commons-app/apps-android-commons/commit/061bb75ab835b7178aa1359589cbffa8f83b7efa still causes the errors with commons-logging and httpclient (described in my first post)... so it seems Dagger might not be at fault after all. However we cannot discount the possibility of **both** being at fault. 

@nicolas-raoul I am trying to think of how to describe this in SO, but I think it is really difficult to explain to someone who has no familiarity with our repo. Hopefully after we do further investigation we can write a better summary if still needed.

**Comment by misaochan** [comment]
I can confirm that #932 is a contributing factor. Checking out the merge of #929 (the PR merged directly before 932) produces no errors, but checking out the merge of #932 does.

**Comment by maskaravivek** [comment]
The source of crash is definitely dagger but am not sure why it is happening just on release builds. I tried disabling prodguard and minification on release build(just for finding the root cause) but that too didnt help. 

This is the stacktrace. 

```
FATAL EXCEPTION: main
Process: fr.free.nrw.commons, PID: 5632
java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.ContributionsActivity}: java.lang.NullPointerException: fr.free.nrw.commons.CommonsApplication.activityInjector() returned null
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3160)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3275)
at android.app.ActivityThread.access$1000(ActivityThread.java:218)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:7007)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.NullPointerException: fr.free.nrw.commons.CommonsApplication.activityInjector() returned null
at dagger.internal.Preconditions.checkNotNull(Preconditions.java:79)
at dagger.android.AndroidInjection.inject(AndroidInjection.java:56)
at fr.free.nrw.commons.contributions.ContributionsActivity.onCreate(ContributionsActivity.java:142)
at android.app.Activity.performCreate(Activity.java:6609)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3113)
```

@whym @psh Do you guys have any insights on it?

**Comment by misaochan** [comment]
To recap my conversation with Vivek, it seems that there are two separate issues here:

1. Dagger causing crashes in release build. We are trying to find a solution for this (because ideally we would like to keep using Dagger instead of wasting time reverting many scattered commits), but if we are unable to find one within the week, we may have to revert in order to get the release out to users.

2. The errors with httpclient and commons-logging that existed after merging #932 but prior to Dagger implementation. Hopefully the `exclude` solution mentioned above will suffice for fixing those.

**Comment by maskaravivek** [comment]
After investigating a bit, i found that there seems to be some issue with fresco initialisations that is causing the crashes. 
```
FATAL EXCEPTION: main
                                                 Process: fr.free.nrw.commons, PID: 3772
                                                 android.view.InflateException: Binary XML file line #21: Error inflating class fr.free.nrw.commons.MediaWikiImageView
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                     at fr.free.nrw.commons.contributions.ContributionsListAdapter.newView(ContributionsListAdapter.java:21)
                                                     at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:269)
                                                     at android.widget.AbsListView.obtainView(AbsListView.java:2828)
                                                     at android.widget.GridView.onMeasure(GridView.java:1064)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1060)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5908)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3076)
                                                     at android.view.View.measure(View.java:18926)
                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2411)
                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1429)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1677)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:606)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:576)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:145)
                                                     at android.app.ActivityThread.main(ActivityThread.java:7007)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                 	at com.android.internal.os.ZygoteInit.
```

- Fixing the fresco init issue on master wasn't helping as master still has a public constructor in `CommonsApplication` that provides an instance of application. 
- I observed that this approach was now giving trouble with a mix of dagger and non dagger usage of `CommonApplication`. 
- So I tried working upon @psh's PR. Running a release version of his PR was also giving the same error. But putting my fix over his PR apparently solves the issue. 

Here's a [reference](https://github.com/facebook/fresco/issues/74) to the `Fresco` init issue.

So to fix the issue, am doing two things,
- Merging @psh's PR
- Submitting my PR for the release fix.
