### ISSUE TITLE
Nearby crashes when switching views before GPS is found

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#998]
While the GPS is searching switching between map and list view can crash the app. Easily reproducible when having no location and just hitting the list/map button a few times.

Version: 2.6.4
Android 7.0

**Comment by misaochan** [comment]
Thanks for reporting this @tobias47n9e . Just to clarify, this did not happen in the previous versions?

**Comment by tobias47n9e** [comment]
@misaochan Don't really know when this was introduced. Does anyone get a crash report window? In my case the app just closes and nothing else happens.

**Comment by psh** [comment]
I managed to generate *two* different crashes while testing current _master_ on my Pixel XL running the beta of Android 8.1.0.

### AFTER SCREEN WAS ALLOWED TO LOAD COMPLETELY, THEN SWITCHING MANY TIMES (QUICKLY)
```
12-06 21:19:04.551  8572  8572 E NativeMapView: You're calling `getTopOffsetPixelsForAnnotationSymbol` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?
12-06 21:19:04.551  8572  8572 E NativeMapView: You're calling `addMarkers` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?
12-06 21:19:04.557  8572  8572 D AndroidRuntime: Shutting down VM
12-06 21:19:04.559  8572  8572 E AndroidRuntime: FATAL EXCEPTION: main
12-06 21:19:04.559  8572  8572 E AndroidRuntime: Process: fr.free.nrw.commons.debug, PID: 8572
12-06 21:19:04.559  8572  8572 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.AnnotationManager.addMarkers(AnnotationManager.java:206)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapboxMap.addMarkers(MapboxMap.java:1228)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyMapFragment.lambda$setupMapView$1$NearbyMapFragment(NearbyMapFragment.java:89)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyMapFragment$$Lambda$0.onMapReady(Unknown Source:2)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:946)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.access$1000(MapView.java:911)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.MapView$MapCallback$1.run(MapView.java:929)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-06 21:19:04.559  8572  8572 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-06 21:19:04.562   914  5460 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.nearby.NearbyActivity
```

### COUPLE OF QUICK MAP/LIST TAPS AS ITS LOADING
```
12-06 21:21:49.804  9797  9797 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyController.loadAttractionsFromLocationToPlaces(NearbyController.java:80)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at fr.free.nrw.commons.nearby.NearbyListFragment.onViewCreated(NearbyListFragment.java:69)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-06 21:21:49.804  9797  9797 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-06 21:21:49.808   914  3036 W ActivityManager:   Force finishing activity fr.free.nrw.commons.debug/fr.free.nrw.commons.nearby.NearbyActivity
```

**Comment by maskaravivek** [comment]
Created #1006 and #1007 for the issues reported by @psh

**Comment by misaochan** [comment]
I think the 2nd crash report is similar to this issue (couple of quick map/list taps as loading)?
